### ISSUE TITLE
Define Comparative Side Length Parameters for Dynamic Details

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#101]
Related to #78, here is best guess at the starting region ranges for the Comparative Side Length parameter used in the Details and in the dynamic state description used in the PDOM's scene summary.

At this time, it is only required to implement the scale for Voicing, but the design goal is for these descriptions to remain in synch.

Here's a link to the [Comparative Side Length Parameters](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.surzggpll38r)

Here's screen shot for documentation:
![image](https://user-images.githubusercontent.com/1902116/158471813-640329e2-4e64-4bfa-9ebd-2c8018e4880b.png)

**Comment by terracoda** [comment]
The priority is for Voicing implementation, implement dynamic state description, if it makes sense to do so and saves time.

**Comment by jessegreenberg** [comment]
This is getting folded into #78 as it is needed to produce the descriptions designed there. I think this can be closed but assigning back to @terracoda to confirm.

**Comment by terracoda** [comment]
The comparative side length descriptions seem to work.
