### ISSUE TITLE
Make model consistent for parallel determination for both trapezoids and parallelograms

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#109]
In bringing the model in line with our long discussed shape hierarchy and recent decisions on what we mean by "parallel" in our scheme, we'd like to use the complementary angle viewpoint for determining parallel lines.

![image](https://user-images.githubusercontent.com/47331395/161614555-385475d6-34ff-4cb7-a400-cc1eb14c653d.png)

To be a quadrilateral, all angles but add up to 2*pi radians (360 degrees)

For 1 set of parallel lines (trapezoids):
- Only 2 distinct angles must have **one** adjacent angle that sums to 180 degrees (pi radians)

For 2 sets of parallel lines (parallelograms):
- All angles must have **two** adjacent angles that sum up to 180 degrees (pi radians)

In this model, yes, a parallelogram is a trapezoid. The parallelogram label overrides the trapezoid level when true.

**Comment by jessegreenberg** [comment]
@BLFiedler we decided that say that two sides are parallel when the vertices that connect the two sides add up to Math.PI
```
    // vertex1---------------vertex2
    //    |                   |
    //    |                   |
    //    |                   |
    //    |-------------------|
    // vertex2   side2       vertex1
    return this.isAngleEqualToOther( side1.vertex1.angleProperty!.value + side2.vertex2.angleProperty!.value, Math.PI );
```

Can we trust this now and say that we have a parallelogram when we have two pairs of sides that are parallel with this calculation?

**Comment by jessegreenberg** [comment]
OK, this change was made in the above commit. Here is how it works now:

1) Find the pairs of opposite sides that are parallel. Opposite sides are parallel according to the diagram and calculation above.
2) The shape is a parallelogram if we have 2 pairs of parallel sides from step 1.

@BLFiedler is this what you had in mind and can you please review?

**Comment by BLFiedler** [comment]
This seems to be working well! And by that I mean I cannot tell there is anything different when making a parallelogram and I can successfully make a trapezoid and maintain it when dragging a parallel side. So. Closing.
