### ISSUE TITLE
Implement Responses for checkboxes

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#119]
The responses for the checkboxes are in the Interactive description design document. Copying the responses here to be implemented for Voicing's virtual experience.

**Corner Labels, checkbox**
- Name Response: Corner Labels
- No object response
- Context responses: 
    - When checked: Letters A through D added to corners.
   - When checked: Names hidden.

**Corner Guides, checkbox**
- Accessible Name: Corner Guides
- No object response
- Context responses: 
    - When checked: Angle guides added to corners.
    - When checked: Guides hidden.

@jessegreenberg, is this enough information for implementation?

**Comment by jessegreenberg** [comment]
Definitely! Context responses added, back to @terracoda to verify or close.

**Comment by terracoda** [comment]
Verified. Thanks @jessegreenberg.
