### ISSUE TITLE
Add a visual grid to support shape creation by means of symmetry

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#121]
We discussed the difficulty in creating particular shapes, including parallelograms when beginning from irregular shapes.

Strategies have included lining up the shape with the play area boundary or the showModelValues box.

We decided that adding an optional reference would aid in shape exploration. Possibilities included a draggable ruler, a static line, a cartesian graph, and a grid.

We decided that a de-emphasized grid, aligned with the input grid but at a large scale would work best.

- [x] Let's create this as a Checkbox named 'Symmetry Grid' 
- [x] with a small line width (smaller than the play area boundary) and a light grey color.
- [x] and spacing of 4 major steps (requiring 4 key presses to move from one edge to the other)

**Comment by jessegreenberg** [comment]
The symmetry grid checkbox has been added. @BLFiedler can you please review?

Also @terracoda can you please recommend context responses for this new checkbox?

**Comment by terracoda** [comment]
@jessegreenberg, I put all checkbox context responses in the design document here:
https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.mdwog6bsxanh

**The Symmetry Grid ones (only new ones) are:**
Name Response
- Symmetry Grid

No Object Response

Context Responses
- Grid lines added.
- Lines hidden.

I also created a hint response, only for the focus event:
- Explore shapes with or without visual grid.

Don't think we have hints yet for the checkboxes, so I will open a separate issue for all 3, so @BLFiedler can way in.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, these context and hint responses have been added.

**Comment by terracoda** [comment]
@jessegreenberg, responses sound good. The new checkbox is not resetting with the Reset All button.

**Comment by jessegreenberg** [comment]
Ah thanks for catching @terracoda, fixed above.

**Comment by BLFiedler** [comment]
Awesome! I think we will want to adjust the grid size or positioning slightly to align better with the starting shapes initial corner positions - either changing the starting shape size or the grid itself. Let's plan to discuss.

**Comment by BLFiedler** [comment]
We decided to go with 5 major key presses as our units (go metric!), thus 20 minor keypresses. The starting shape magically aligns perfectly!

**Comment by jessegreenberg** [comment]
During the meeting we agreed that https://github.com/phetsims/quadrilateral/commit/6389e78819a4a7cbeb20d53599beb765a578c963 looked OK, closing.
