### ISSUE TITLE
Does it still make sense to have vertex labels be optional?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#126]
If the toolbar buttons are pressed before the "Corner Labels" checkbox the responses can be difficult to follow. There is no introduction to vertices or sides labelled by letter. Would it make sense to always display vertex labels?

**Comment by BLFiedler** [comment]
I think we want to continue to support the ability to manipulate the shape without explicit reference. I can verify with interested parties.

However, I see the issue when Voicing is enabled. Does it make sense to auto-enable Corner Labels and provide a context response when Voicing is turned on (if it is not already on)?

I imagine then that when the Voicing toggle is enabled you'd hear: "Voicing on. Corner labels visible".

I don't think we need to also automatically toggle them off when turning off Voicing.

**Comment by terracoda** [comment]
Interesting question.

I think there may be an issue with the suggested approach as the Preferences Menu is not part of the sim.

I wonder if it might make better sense to start with Corner Labels on by default and then a leaner or teacher has the option to hide (uncheck) the visual labels as needed or as preferred.

That would avoid a special sim-specific response when turning on Voicing from with the Preferences menu.

**Comment by terracoda** [comment]
As an example, GFLB starts with the Distance Arrows checked, but a leaner/teacher can uncheck it for a more qualitative experience with or without Voicing.

**Comment by BLFiedler** [comment]
Makes sense. Let's go ahead with that approach for now.

@jessegreenberg Let's make the default state for the Corner Labels checkbox checked.

**Comment by jessegreenberg** [comment]
Corner labels are visible by default. @BLFiedler is there anything else for this issue?

**Comment by BLFiedler** [comment]
Looks good to me!
