### ISSUE TITLE
Pickup sounds that are different for vertex and side

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#128]
To differentiate component pickup, we'd like two different sounds for picking up a vertex vs. a side

We could start by choosing a pickup/drop set of sounds for vertex similar to Faraday's law. 

Perhaps the side length sound could just be a lower set of tones? Can discuss at sound meeting.

**Comment by BLFiedler** [comment]
Note by @jessegreenberg during Sound design today:

> A pickup sound could be disabled if Voicing is enabled.
> Or it might sound nice when we have volume ducking with sound + voicing (issue #185)

**Comment by terracoda** [comment]
Like Voicing, I think the pick-up sound might be really helpful for people who have trouble seeing the screen or can't see the screen, so I don't think it needs to be disabled when Voicing is enabled.

**Comment by BLFiedler** [comment]
We liked the Ratio and Proportion sounds as a more "general" sound than Faraday's Law pick up sounds. They are a little too subtle though.

@Ashton-Morris, could you modify the pickup sounds from Ratio and Proportion to differentiate them further? Perhaps the lower tone goes lower still?

**Comment by BLFiedler** [comment]
From @terracoda's recent interview:
![image](https://user-images.githubusercontent.com/47331395/207655013-29a918d8-0c3b-4c26-ad7f-5151f70a1e82.png)

While tabbing through quickly, it was difficult to tell the difference. It won't need much, but a small tweak is fine to quickly address even based on one interview.

@Ashton-Morris , Could you raise the pitch of grab.mp3 from Ratio and Proportion just a bit to differentiate it from the lower pitched release.mp3 that is used for a side right now? I defer to your judgment on what is a small but meaningful pitch change here.

- [ ] Raise the pitch of grab.mp3 just a bit to differentiate from release.mp3

**Comment by Ashton-Morris** [comment]
I have added theses sounds in [this folder.](https://drive.google.com/drive/folders/1sTyhfR9EZVJWl7GTfi3COXGHK9yCqoa8?usp=share_link)


Some I have added a slight click to them to differentiate them a bit more. Choose your favorite one.

- grab-v5.mp3
- grab-v4.mp3
- grab-v3.mp3
- grab-v2.mp3

**Comment by BLFiedler** [comment]
@jessegreenberg,

- [ ] Let's replace the vertex pickup sound with grab-v2.mp3 in the folder Ashton linked.

**Comment by jessegreenberg** [comment]
OK, new sound for grabbing Vertices was added to the sim (grab-v2.mp3). @Ashton-Morris @BLFiedler can you please review?

**Comment by BLFiedler** [comment]
Sounds good to me. Definitely a clear difference, but they share enough quality to be the same interaction.

We discussed changing the sounds levels a bit for these and the boundary sounds. I gave that a try in the commit above.

**Comment by Ashton-Morris** [comment]
Sounds good to me as well. @jessegreenberg I would lower the corner sound down about 10% though since it is higher in pitch. Can you do that?

**Comment by BLFiedler** [comment]
Done! To make any real effectual change I went a bit further (0.8 -> 0.6). Did you want to review, @Ashton-Morris?

**Comment by Ashton-Morris** [comment]
Just checked and the changes sound good.
