### ISSUE TITLE
Hide non-parallelogram feedback in Sim-specific preferences menu

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#129]
We would like the ability to hide the visual and auditory feedback about non-parallelogram shapes for interviews/codesign.

Let's put both the visual and sound for non-parallelogram shape detection in the Sim-specific preferences menu as a checkbox and disable is by default (so no feedback is provided).

Let's also create a query parameter to enable it on load for interviews.

**Comment by terracoda** [comment]
@BLFiedler, just to be totally clear, this will not affect the language we have in the read-me buttons (State Descriptions), right.

**Comment by BLFiedler** [comment]
Right. This is only intended to hide the visual cue and the sounds.

**Comment by jessegreenberg** [comment]
OK, done in the above commit. A checkbox has been added in the Preferences dialog to turn it back on. A query parameter was added called `?shapeIdentificationFeedback=true` to set the initial state of the checkbox.

Over to @BLFiedler to verify.

**Comment by BLFiedler** [comment]
No feedback, but shape detection using `?showModelValues`. Seems correct to me!
