### ISSUE TITLE
Safari issue with haptics - Mouse input no longer works

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#131]
I was just using Quad in Safari and mouse input no longer works anywhere.

@jessegreenberg thought this might be related to recent haptics implementation which does work on Safari.

Alt Input with keyboard seems to work fine.

**Comment by jessegreenberg** [comment]
Thanks for reporting @terracoda. We started using tappi in #104 which uses `navigator.vibrate` to trigger vibrations. `navigator.vibrate` is not available on safari so when it starts to request vibrations the sim will crash on that platform. We need to do something like prevent its usage on safari or conditionally use tappi in quad or improve tappi to no-op on Safari.

@jbphet do you have a preference for how we continue with tappi work with this issue?

**Comment by jbphet** [comment]
@terracoda - I've pushed some changes that should prevent this issue on Safari.  However, I don't have a good way to test it.  Please try it out and let us know if the problem with mouse input is resolved.

**Comment by terracoda** [comment]
Thanks @jbphet!
