### ISSUE TITLE
Can we get visual access to the Voiced text?

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#132]
In RaP, we have a query parameter &printVoicingResponses

Is it feasible to have that fro Quad, too?

The reason the text would be handy is that, I would be able to separate actual Web Speech pronunciation issues from  non-optimal capitalization, punctuation or spacing in the Voiced strings. Text-to-Speech software can be quite finicky about these things.

**Comment by jessegreenberg** [comment]
Indeed! This is a query parameter in common code so `?printVoicingResponses` should be usable for all sims that support Voicing.

**Comment by terracoda** [comment]
I can use the parameter. It's working and the punctuation and spacing all look fine. Closing.
