### ISSUE TITLE
Sides and Angles when using  &showModelValues

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#133]
Is it possible to make the displayed labels for the values match the sims labels?

Side AB:
Side BC:
Side CD:
Side DA:

Corner A:
Corner B:
Corner C:
Corner D:

**Comment by jessegreenberg** [comment]
Thanks @terracoda that is a good idea. Updated in the above commit, over to you to confirm.

**Comment by terracoda** [comment]
Beautiful. Thanks @jessegreenberg. That will greatly reduce my cognitive load when reviewing.
