### ISSUE TITLE
Hint Responses for checkboxes

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#137]
I generally design hint responses based on the PDOM help text as the help text is more critical for non-visual access. 

Here are my suggested hint responses for the the three checkboxes in Quadrilateral.

For checkboxes, the hint responses only fire on keyboard focus and when helpful hints are checked in the Preferences menu.
- Explore shapes with or without visual labels.
- Explore shapes with or without visual angle guides.
- Explore shapes with or without visual grid.

See [Confirmatory Context Responses](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.mdwog6bsxanh) in the Voicing design document.

Note: Hint Responses are State Descriptions from a description design framework perspective, but from a Voicing design doc perspective they get put with the interaction.

**Comment by terracoda** [comment]
@BLFiedler, shall we have @jessegreenberg put on these Hint Responses, so we can hear how they sound?

**Comment by terracoda** [comment]
The Corner Labels checkbox has the incorrect hint. It should be:
    - Explore shapes with or without visual labels.

The Corner Guides checkbox has not hint. It should be:
    - Explore shapes with or without visual angle guides.

The Symmetry Grid checkbox's hint is correct.

The Context Responses are implemented as designed.

**Comment by jessegreenberg** [comment]
Sorry, looks like I accidentally moved the corner labels hint over the corner guides hint. Fixed in the above commit.

**Comment by terracoda** [comment]
All good now! Thanks @jessegreenberg. Closing.
