### ISSUE TITLE
Update Overview to include new check box

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#138]
@jessegreenberg, please update teh Overview Button text to reflect the addition of the Symmetry Grid checkbox.

**Change third paragraph from:**
In addition, checkboxes add labels, guides to support your exploration, and a button resets the sim.

**To:**
In addition, checkboxes add or remove labels, guides, and grid lines to support your exploration. A button resets the sim.

I updated the PDOM design as well, but that' not the focus right now. All details are here:
https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.pf5fb8apgrt4

**Comment by jessegreenberg** [comment]
OK, updated in https://github.com/phetsims/quadrilateral/commit/06b1e1a9cd911078a4f0745621c7c12626ed6c77
