### ISSUE TITLE
Map vertex identity to OpenCV markers

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#141]
As noted in #20: "Lack of marker-to-vertex identity adds some funny behavior when rotating."

We want to add marker to vertex identity and we'll try something like modulating the width of each marker so we can later do some perspective adjustment (e.g., for tilt) (not priority for this issue).

**Comment by jessegreenberg** [comment]
A first pass of this was done in the above commit, simply using marker area to label the vertex. The smallest to largest markers are labelled as vertex A through D. With this in place the shape can rotate without rearanging the vertices:

<details>

![image](https://user-images.githubusercontent.com/6396244/166584030-641d5a9e-ca4f-4471-b39f-2bb576882555.png)

</details>


This is working well when the camera and TMQ are fixed in space. This should be enough to play with a tangible and test Voicing/sounds but we can do something more sophisticated like @BLFiedler mentioned to try to account for perspective later.

**Comment by jessegreenberg** [comment]
Ready for review. By default the prototype is NOT doing this, but there is a checkbox to enable detection.

**Comment by BLFiedler** [comment]
I believe what we settled on in the meeting was:

- [ ] Investigate maintaining marker identity when one or more markers are partially or fully obscured

with the following additional desired behaviors:
1. Covering one or two markers should allow the remaining detected to keep moving, only freezing the missing markers
1A. Only allowing the above behavior for one obscured marker and otherwise freezing all markers is acceptable behavior.
2. Partially obscuring a larger marker should not result in reassigning vertices.

One strategy mentioned may include assessing marker size during calibration to assist in tracking even when losing other markers.

Let me know if this feels like two separate issues @jessegreenberg

**Comment by jessegreenberg** [comment]
While working on this I noticed that the contours are susceptible to motion blurring like we had with the mechamarker input before. While stationary marker sizes are relatively free of noise but while the shape is moving there is huge variability in the size of each marker.

**Comment by BLFiedler** [comment]
I'm alright with trying colors, especially since it seems like we can do a pretty good job isolating those colors with the filters. I agree any spatial identification (shape, size, etc) is going to introduce this problem. Letting up size might let us later correct for perspective too, yeah?

**Comment by jessegreenberg** [comment]
> Letting up size might let us later correct for perspective too, yeah?

Yes, good point! Could definitely make that easier.

**Comment by jessegreenberg** [comment]
I tried this today by getting some new duct tape colors using red, green, blue, white. I am running into some more challenges
1) The auto-detect approach that worked well for green isn't working well for red and white. For example, this is the filter I found I need for white

![image](https://user-images.githubusercontent.com/6396244/168398349-aef4d2d8-bbb9-45d6-80a2-65c9ada76adf.png)

the hue range is way larger than 20.

2) Red and white overlap with my skin and so when I interact with the tangible it interferes with the markers.

This is why we decided to use green in the first place. Maybe we can use shades of green instead? Maybe I can print some green rectangles and tape them to the tangible.

**Comment by BLFiedler** [comment]
Just to note - I played around with the existing OpenCV test (5/24) and was able to isolate these colors pretty well. Might be able to standardize 1 light green, 1 dark green, 1 light blue, 1 dark blue (both are colors used in "green screen technology")

![image](https://user-images.githubusercontent.com/47331395/170092958-1aeed868-620d-4281-b47d-cd02ca1ebb55.png)

**Comment by jessegreenberg** [comment]
I got this working well enough to make a commit point:

<details>

![image](https://user-images.githubusercontent.com/6396244/170380942-48a98d19-b0f0-405a-ac32-41cdf6df7d89.png)

</details>

Its working OK but increased number of filtering operations has a negative impact on performance and the framerate is pretty slow. There may be ways to make it faster.

**Comment by jessegreenberg** [comment]
Using ?profiler for the sim, I am seeing ~40 fps when tracking a single color and ~15 fps when tracking 4 colors.

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/170720745-e5aaabec-9d14-46de-a340-0fa2d473b746.png)

![image](https://user-images.githubusercontent.com/47331395/170720797-b0fa39e0-679e-4071-806a-1abec48313ac.png)

Noting here that detection seems cleaner against a white background than a black background.

**Comment by jessegreenberg** [comment]
Meeting with @BLFiedler - we noticed that performance is acceptable in the OpenCV video and canvas output but is terrible in the simulation. The next thing we should look into is why it gets so slow for the sim.

**Comment by BLFiedler** [comment]
Current implementation is fine for our purposes - will open up new issues for optimizations when and if needed.
