### ISSUE TITLE
Implement basic Context Responses for finding and losing a parallelogram

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#143]
We know we need at least two general context responses to indicate finding or losing a parallelogram.

For a while now, we have been quite happy with these two context responses:
- "You made a parallelogram!"
- "You lost your parallelogram!"

However, I can make them slightly shorter and maybe more flexible (if we add more shapes) by using verbs only, no subject.

@jessegreenberg, can you implement these two phrases **with the current tolerances for being in a parallelogram**?
- "Found a parallelogram!"
- "Lost your parallelogram!"

That will give me something to play with, and I will be able to see how the object responses sound with that, too.

Down the road (but not now), we might want context responses like:
- "Found a trapezoid!"
- "Found an isosceles trapezoid!"
- "Found a kite!"

**Comment by jessegreenberg** [comment]
OK sounds good, added in the above commit for parallelogram. I also removed the context responses that were added to the sim in December, we can restore them from history if we need.

**Comment by terracoda** [comment]
Thanks for removing the older context responses.
 "Found a parallelogram!" and "Lost your parallelogram!" sound really good.

I just realized - while working on the more general context responses - that it is likely a good idea to incorporate some parameters into "Found a parallelogram!" The details about all equal corners and sides. I think these fit nicely in the basic context response.

@jessegreenberg, in addition to "Found a parallelogram!" can you add in the following parameters:

- Found a parallelogram {{with all {{right angles}}}}!
- Found a parallelogram {{with all {{sides equal}}}}!
- Found a parallelogram {{with all {{sides equal and all right angles}}}}!

Moving into a parallelogram (in the virtual space) can only happen when when moving a vertex. I'll use the same "right angles", "sides equal", when maintaining a parallelogram while moving  a side, but since the strings are in a different context, they may need to be "All {{right angles}}" and "All {{sides equal}}" I will make a related issue for that.

**Comment by terracoda** [comment]
Maybe "Found a {{parallelogram}} {{with all {{right angles and all sides equal}}}}!" sounds better?

I'll reverse the order.

**Comment by jessegreenberg** [comment]
This was done with #144, ready for review again @terracoda.

**Comment by terracoda** [comment]
These responses sound really good.

I did notice some inconsistency with the "all right angles" property. Sometimes I can pass through a mirrored parallelogram and not get it (no visual and no description). I'll mention this at design meeting.
