### ISSUE TITLE
Context responses that call out equality when maintaining a parallelogram

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#144]
To follow-up from #143 , I listed out the scenarios for calling out equality when maintaining a parallelogram in the design document in this [Table: Maintaining a parallelogram & calling out equality in corners and sides](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.wg0ek35rj5z2)

Here a copy of the visual table that I mapped out:
![image](https://user-images.githubusercontent.com/1902116/167210582-074f7362-02b7-46dd-bae8-d7b4739096da.png)

**Comment by jessegreenberg** [comment]
OK, these have been added with the above commit. The implementation also includes #143. @terracoda just so you know it was far easier in this case to not use string patterns so a unique string was added for each case like

```json
      "foundAParallelogram": {
        "value": "Found a parallelogram!"
      },
      "lostYourParallelogram": {
        "value": "Lost your parallelogram!"
      },
      "foundAParallelogramWithAllRightAngles": {
        "value": "Found a parallelogram with all right angles!"
      },
      "foundAParallelogramWithAllSidesEqual": {
        "value": "Found a parallelogram with all right angles!"
      },
      "foundParallelogramWithAnglesAndSidesEqual": {
        "value": "Found a parallelogram with all right angles and all sides equal!"
      },
      "allRightAnglesAndSidesEqual": {
        "value": "All right angles and all sides equal!"
      },
      "allSidesEqual": {
        "value": "All sides equal."
      },
      "allRightAngles": {
        "value": "All right angles."
      },
```

Ready for review.

**Comment by jessegreenberg** [comment]
Sorry, forgot to assign you @terracoda.
