### ISSUE TITLE
All right angles property, sometimes doesn't fire

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#146]
While testing #143 , I noticed in some cases (hard to reproduce, but have done so) the all right angles property does not fire when moving a side and passing through a mirrored parallelogram.

I am using latest version on PhET Test. Apologies this example is not a video.
![image](https://user-images.githubusercontent.com/1902116/167656364-f051d3ad-b4ce-4227-91f2-c1ebf7f5b6e9.png)

**Comment by jessegreenberg** [comment]
I tried for a few minutes to reproduce but couldn't find the case. @terracoda can you please reproduce this with the "symmetry grid" enabled and when it happens take a screenshot with ?showModelValues disaplayed so we can see the angles and the current tolerance interval values?

**Comment by terracoda** [comment]
Yes, will try with model values. It popped up a couple of times, but I could easily reproduce.

**Comment by terracoda** [comment]
@jessegreenberg, It turns out that this is NOT a bug. 

It just so happens that when the shape gets a little askew of the grid (mixed use of shift key), it is possible that when returning to maintaining a parallelogram while using the keyboard and the default step size, you can jump over or not actually hit the "all right angles" spot when all corners are 1.57.

However, switching back to shift key, you will hit it.

We may want to revisit and make sure that that step (all corners 1.57) can't be skipped.

If that is super trivial to do, let's go ahead and do it. 

It will mean a learner can easily without intention get back on the default grid. 

If not trivial, let's mark for design meeting and discuss with @BLFiedler

**Comment by jessegreenberg** [comment]
OK sounds good, lets discuss tomorrow. It looks potentially complicated to change input behavior around this case so it would be good to discuss briefly.

**Comment by BLFiedler** [comment]
This is analagous to the efforts in RaP to bias user intention to find the Target Proportion when using the shift key for small steps. In that case, it was possible to skip over the target proportion even when using small steps, so the step size "adjusted" to find the proportion.

Presently, this case is different, focusing on the large step. If we find that we can readily skip over the parallelogram state (or all right angles, etc) with a small step, we'll first re-assess tolerance intervals, then possibly revisit biasing the step size toward target feedback.

**Comment by BLFiedler** [comment]
Noting that right now it is very difficult to find cases (I haven't isolated anything except a rare rotated shape while finding parallelograms) where the small step skips target feedback with the current tolerance values.

Over to @terracoda to assess and close for now until we see a prominent problem with small steps.

**Comment by terracoda** [comment]
I can now easily reproduce by using the shift key for one small step and then going back to using the plain arrow key to take big steps.
![image](https://user-images.githubusercontent.com/1902116/171006581-d03a4fcb-5c8b-4133-8030-053adfe23707.png)
![image](https://user-images.githubusercontent.com/1902116/171006640-140f7bf3-19f8-460a-95b6-1fe588169778.png)
![image](https://user-images.githubusercontent.com/1902116/171006692-ef195b6b-4de2-4dc2-8765-2c40faf745b7.png)


I am not sure this is a bug. It is keyboard input specific, and it may just be a fact of keyboard navigation. 

I think the only way to resolve it is to snap back to the large steps that fit on the grid when using large steps. But honestly, for this sim, that solution might cause more problems for the model.

Perhaps a good approach is to leave it to the learner, and making sure they know that when using the keyboard they have small and large steps with which to refine their shapes.

**Comment by terracoda** [comment]
@BLFiedler, do you think a snapping solution is feasible? I am not sure I have a full grasp of what unintended consequences we might introduce with keyboard snapping behaviour.

**Comment by BLFiedler** [comment]
> Perhaps a good approach is to leave it to the learner, and making sure they know that when using the keyboard they have small and large steps with which to refine their shapes.

I would air on this side until we find it untenable. We'd possibly need to do this for all form of feedback we're hoping to provide (parallel, all right angles, all sides equal, etc).

Closing for now.

**Comment by zepumph** [comment]
I see this is closed, I just wanted to note that in Ratio and Proportion, we spend a lot of effort "conserving" key presses and making sure that we could get to the in-proportion state. If you ever re-open this issue, and need to implement, I'd recommend looking at `getKeyboardInputSnappingMapper`. It is a bit gross, but it made this possible.

**Comment by terracoda** [comment]
I can easily slip off the input grid by using the shift once and then moving a side AB back and forth. When I do that I will jump over a square. I think it would be awesome to have a snap back to the grid in key places, like passing over 90 degrees.

I think it would be difficult to define something for each shape, could we have a snap-to for a few specific properties like
- 90 degrees
- parallelism
- equal side length?

**Comment by terracoda** [comment]
@BLFiedler, I tested with the latest on PhET Test today. I am not sure yet to be input tolerances and new step sizes will prevent these "jump-overs".

**Comment by terracoda** [comment]
Maybe this issue is related to #197

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/207665801-da9bab0d-b228-4f4f-bab3-5949dfe4c73d.png)

**Comment by BLFiedler** [comment]
See #292 for proposed solution. Closing.
