### ISSUE TITLE
Replace vertex bounds constraints with a constraint that you cannot create a concave shape

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#15]
We talked about how to do this. One way would be to limit the angles so that each cannot be greater than 180 degrees. Another approach would be to limit such that a vertex cannot cross a line.

**Comment by BLFiedler** [comment]
Copying from the meeting notes/Zoom chat for log purposes: 

BF: Just as a note - none of our parallelism focused sonifications will give you much of anything in the concave shape world. So, it'll come down to: Do (we) think that is a case worth exploring for a user to figure out or prove their theories on the model? Can ask Sofia and Dor.

EM: I think we should note any decision with respect to the design of the model that precludes the concave shapes, and proceed with excluding these shapes. That way, in the future if we want a version that allows this, it’s clear to all what’s needed (in the model) to do it, but I do not think we want to support the creation of these concave shapes. I think it’s a non-trivial, but challengingly subtle, kind of geometry and we want to keep things as simple as possible for as long as possible.

Another thought to log: 
- Worth considering how the tangible/sim coupling responds to either of these constraints. Degrees of freedom for the CHROME Lab 3D printed quad are less than say a decoupled 4 sensor tangible (e.g., rings or tabletop markers), so while the angle restriction will likely not intrude on the former, it might be more evident in the latter.

**Comment by BLFiedler** [comment]
For simplicity, let's just go with the angle restriction for now. Especially after the discussion during the sound design meeting.

Perhaps some give as well (178/2 degrees? Vs. 180/0 degrees)

**Comment by BLFiedler** [comment]
Possible solution of irregular boundaries that is easier to develop than angle restriction:
![image](https://user-images.githubusercontent.com/47331395/137980568-62d1c32d-ac70-46f6-832b-20fa740a3ee7.png)

**Comment by jessegreenberg** [comment]
I got this working well enough to see a potential issue when vertices change to create a concave shape. For example, we have this area for vertex2:

![image](https://user-images.githubusercontent.com/6396244/140142669-3712ee16-28ae-4179-82eb-b23d68c1963a.png)


But when vertex2 is dragged down so that it becomes concave the bounds for vertex1 change:
![image](https://user-images.githubusercontent.com/6396244/140144948-370ffbd8-718b-4b16-afbe-110ae45868bb.png)

So I think this algorithm will effectively disallow concave shapes.

**Comment by jessegreenberg** [comment]
@BLFiedler this can be tested at https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.7/phet/quadrilateral_en_phet.html?showVertices&showPointerAreas&showDragAreas. Do you have any thoughts about how to handle this?

**Comment by jessegreenberg** [comment]
Perhaps one way would be to disallow concave shapes by creating a shape between connected vertices like this:
![image](https://user-images.githubusercontent.com/6396244/140162259-129dd23c-9d45-485f-b236-775c60797c5e.png)

I think this has similar behavior as https://github.com/phetsims/quadrilateral/issues/15#issuecomment-947719793 but it does prevent concave shapes.

**Comment by BLFiedler** [comment]
Will need to flesh this out later - but let's discuss your last comment and this idea. Effectively adding the bisector of the adjacent vertices as an allowable area. Opens up some weirder "irregular quadrilaterals".  The possible uncomfortable zone I've darkened where you can make overlapping lines.

![image](https://user-images.githubusercontent.com/47331395/140180317-42c05e60-cca7-4f23-9252-985d97a38b6e.png)

**Comment by BLFiedler** [comment]
JG and I met to discuss. The following, after verifying a few cases, appears to be a proper solution for all convex and concave quadrilaterals.

On the side of the vertex of control, the allowable regions are bounded by:
    - The lines formed by the opposite vertex and adjacent vertices (i.e., the sides not connected to the vertex of control)
    - Lines radially outward from the adjacent vertices to the play area along the line formed by the adjacent vertices.

1. Example for a convex quadrilateral for the red vertex:
![image](https://user-images.githubusercontent.com/47331395/140374181-d17a8602-53fd-44b9-a72d-aae125781e7c.png)
2. Example for a concave quadrilateral for the red vertex:
![image](https://user-images.githubusercontent.com/47331395/140374701-7adddb7e-794f-4850-aec2-0a710ea06d6c.png)
3. Example for the same concave quadrilateral for the green vertex:
![image](https://user-images.githubusercontent.com/47331395/140374311-ebd7e719-c24b-48fd-b5bf-cc8ccd0d74f5.png)
4. Example 1 with previous bound overlayed to highlight new allowable areas:
![image](https://user-images.githubusercontent.com/47331395/140374593-d28c0ca9-59dd-4b19-9d2e-718aebc6d1a9.png)

**Comment by jessegreenberg** [comment]
The above commit implements what is described in https://github.com/phetsims/quadrilateral/issues/15#issuecomment-961184570. It works pretty well, but there is a breaking case when there is a concave shape:
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/6396244/140970114-4446a893-da17-49a5-aec3-faa482761296.gif)

**Comment by jessegreenberg** [comment]
During meeting today we discussed a solution to this where if the angle of the opposite vertex is greater than 180 degrees, we need to constrain the drag area to something that will not allow twisted quadrilaterals. For example, when concave, the drag area for vertex1 will look like this:

![image](https://user-images.githubusercontent.com/6396244/141002525-a217b039-642b-4e93-a3ad-95c2f63b7911.png)

IN this case, a ray is formed from vertex2 to vertex3 and a ray is formed between vertex4 and vertex3 which intersect with the model boundaries and create a shape that will prevent twisting.

When convex, the area is quite a bit larger as described in https://github.com/phetsims/quadrilateral/issues/15#issuecomment-961184570.

@BLFiedler can you please review this in https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.9/phet/quadrilateral_en_phet.html?showDragAreas&showPointerAreas You can drag a side to see the drag areas of both connected vertices change at the same time

**Comment by BLFiedler** [comment]
This is beautiful and makes for a very trippy experience. Tested via cursor, keyboard, and iPad touchscreen (2 & 4 fingers). I was not able to break it myself. It did not interrupt any of the parallel maintenance movements. The only time it is obvious is during single vertex manipulation and especially when trying to rotate the entire shape using only single vertices (this is not a problem, only a note).

Keeping issue open to discuss @ Thursday meeting & virtual model meeting. Specifically, I would like to know thoughts on allowing a vertex to make a line with another vertex.

**Comment by BLFiedler** [comment]
Let's make a pass on giving the lines a defined width in model space and preventing overlap of vertices and lines.

**Comment by jessegreenberg** [comment]
I have an initial pass at changing the Sides so that they have model bounds and adding their intersection to the calculation of allowable shapes. But somehow it is is possible now to get crossed shapes:
![image](https://user-images.githubusercontent.com/6396244/148139389-04b87bf2-7d93-4f2a-8701-be2b220683f7.png)


Ill return to this part next time.

**Comment by jessegreenberg** [comment]
This bug is unrelated to these changes. Here it is again where the bottom right vertex crosses. It seems to be that a position perfectly vertically aligned with another vertex.
![image](https://user-images.githubusercontent.com/6396244/148460300-790de135-e4df-493c-93f1-5549f56a365b.png)

**Comment by jessegreenberg** [comment]
I started https://github.com/phetsims/quadrilateral/issues/39 this bug is unrelated to the changes here.

**Comment by jessegreenberg** [comment]
I have a workaround in place for #39, and opened an issue in kite to investigate the identified problem in that repo.

Back to https://github.com/phetsims/quadrilateral/issues/15#issuecomment-970580310...

This should be done, can you please verify @BLFiedler? IS there anything else you would like for this issue?

**Comment by BLFiedler** [comment]
A couple of points to bring up at our meeting today:
- "Stickiness" of vertex when it meets a boundary during drag
- Side overlap with adjacent vertex 
![image](https://user-images.githubusercontent.com/47331395/148954484-7eb2b1be-e8fc-4b4d-ad6e-0740d976c2a9.png)

**Comment by BLFiedler** [comment]
Oops - also found a crash. Placing in this issue for now. Happens whenever a vertex means the leftmost play area boundary (by keyboard, touch, and cursor) - (on Chrome & Edge (Win10) and Chrome (iPad))

![image](https://user-images.githubusercontent.com/47331395/148956015-d7ec7cf5-4830-4a87-ab15-525a56e092fb.png)

**Comment by jessegreenberg** [comment]
I believe the crashing is fixed with the above commit.

**Comment by BLFiedler** [comment]
We concluded in the meeting that there should not be overlap with sides and vertices, even for those not currently being dragged to avoid the situation pictured in https://github.com/phetsims/quadrilateral/issues/15#issuecomment-1009981737

However, side overlap that occurs when a concave shape is alright.
![image](https://user-images.githubusercontent.com/47331395/149007084-a6cfcbd1-c35a-4e3d-81c4-5e26c01b80ab.png)

After this addition, this issue can be closed.

**Comment by jessegreenberg** [comment]
I spent a few hours on this issue this morning, I ran into the issue again where the entire shape instead of just the proposed position for the vertex (https://github.com/phetsims/quadrilateral/issues/33) - I replaced the function with `isQuadrilateralShapeAllowed` so we can verify all of the requirements of the shape when we change it instead of just verifying the position of a vertex.

It is working pretty well but for some reason vertex 3 cannot move beyond this position vertically:
![image](https://user-images.githubusercontent.com/6396244/149971744-eb106af0-cdd7-4b10-8bc2-753da7935845.png)

**Comment by jessegreenberg** [comment]
Ah, I think this is the same issue as https://github.com/phetsims/quadrilateral/issues/39. That explains why it is only an issue for the third vertex.

**Comment by BLFiedler** [comment]
I think this is instantiated for the purpose of this issue. The stickiness issue can continue over in #41
