### ISSUE TITLE
When should we hear parallel in object responses?

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#150]
In #130 we implemented and tested object responses for corners and sides.

Just now in dev version https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.31/phet/quadrilateral_en_phet.html?showModelValues

I heard a case where the shape was named a trapezoid, but the parallel sides were not described as "parallel"

**Comment by terracoda** [comment]
When clicking on a non-parallel side, I think the adjacent sides need to be described as parallel. 

I am checking the design document. I might have missed this detail as we iterated.

**Comment by terracoda** [comment]
Could be tolerance issue? Not sure. I have haven't tested deeply.

**Comment by jessegreenberg** [comment]
@terracoda do you know what the values of `angleToleranceInterval` are? They are covered up by that side. I suspect that the `shapeAngleToleranceInterval` indicates this is a trapezoid, but the `angleToleranceInterval` is negative infinity because a side was dragged while it is not a parallelogram.

**Comment by terracoda** [comment]
Sorry
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1902116/168122658-eabcac68-e067-4be7-bdb0-0a4c82f781dd.png">

**Comment by jessegreenberg** [comment]
Excellent, thank you @terracoda! That means it probably isn't a model problem, Ill take a look.

**Comment by jessegreenberg** [comment]
Turns out it was just a wrong string in the file...oops...fixed in the above commit.

However it did identify a parallel case that is currently not described. When only one adjacent side is equal to the object side the parallel state is not described and we hear 

"equal to one adjacent side", as in the "Sides of a Kite" example:

![image](https://user-images.githubusercontent.com/6396244/168128067-7c47786d-b36f-49b4-a815-d8cd192c4b90.png)

Does the parallel state in this case need to be called out or should we be hearing something different in this case?

**Comment by terracoda** [comment]
I hear parallel adjacent sides in object responses for trapezoids now.
All good, now closing.

**Comment by jessegreenberg** [comment]
Sorry, the question was not just about trapezoids but about  a trapezoid where an adjacent side has equal length like in https://github.com/phetsims/quadrilateral/issues/150#issuecomment-1125218885. In that example side DA is equal in length to side CD so all we hear is "equal to one adjacent side". Is that OK?

**Comment by terracoda** [comment]
Oh right, good catch! I'll look more carefully.

**Comment by terracoda** [comment]
The implementation is correct. 

It would potentially confusing to add {{parallel}} for the case of "one adajcent side" see https://github.com/phetsims/quadrilateral/issues/150#issuecomment-1125218885 because with the current phrasing we need to talk about "opposite" sides as being parallel.

Comparing the strings:
1. "Side AB, {{comparable to}} opposite side, {{equal to one}} adjacent side"
2. "Side AB, {{comparable to}} opposite side, {{equal to one}} {{parallel}} adjacent side"

I find "{{equal to one}} {{parallel}} adjacent side" confusing and awkward. With the current phrase pattern, we would need something very complex like:
- "Side AB, {{comparable to}} opposite side, {{equal to one}} adjacent side that is parallel to its opposite".

I chose to keep it simple. It is likely better to just click on an equal adjacent side to find out that it is indeed parallel to its opposite.
