### ISSUE TITLE
Not always hearing actual shape name

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#152]
Some times I hear "You have a shapeName, not a parallelogram. Explore what makes parallelograms."

Trying to track down examples with &showModelValues... just noticed an example where parallelogram is voiced and displayed correctly, though the model says "general_quadrilateral"

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1902116/168621373-2f3fc9a9-6639-4cdc-8611-94e766bd1cc5.png">

**Comment by terracoda** [comment]
Here's an example where I hear "shapeName" instead of "general quadrilateral". I think it is only the gen quad shapes that are the issue.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/1902116/168623101-27fd43d6-11f5-4f20-8b40-f2fe3e010921.png">

**Comment by terracoda** [comment]
Over to you @jessegreenberg

**Comment by jessegreenberg** [comment]
Fixed in the above commit, thanks @terracoda
