### ISSUE TITLE
Add some buffer area around the edge of the screen and ResetAllButton

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#16]
After #11, it was working well but maybe a bit to far. It felt like vertices could escape off screen and could overlap the ResetAllButton. We want to make sure that vertices cannot overalp with UI components in the sim and have a bit more buffer so they don't get quite so close to the edge. It isn't clear what the UI will look like, so for now we want to prevent overlap and make it easy to change "play area" bounds in the future.

**Comment by jessegreenberg** [comment]
I changed model space so that it does not overlap with the ResetAllButton and there is some space between the edges of the screen. @BLFiedler can you please review the latest on phettest and let me know if this is working as intended? For now we just have a ResetAllButton but we are set up now to add more space if we add additional UI components.

**Comment by BLFiedler** [comment]
To the letter of this issue, I think this is all good. Thanks, Jesse!
