### ISSUE TITLE
Retain last used HSV values for OpenCV

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#160]
Since folks tend to use the same (or will use) the same markers, retaining the last "good" values set in their browser for markers would be a helpful feature.

**Comment by jessegreenberg** [comment]
This would be really nice, especially now that there are 5 filters to re-find every refresh. Would probably speed up iterative development a lot to have this so Im going to work on this next.

**Comment by jessegreenberg** [comment]
This is done @BLFiedler and will be usable in the next build.
