### ISSUE TITLE
Make it easier to find the "angle change" responses with the TMQ

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#164]
We are at a point where we can test the context responses with a tangible! One thing I noticed is that the length change almost always triggers before the angle change still. I almost always hear "shape gets bigger/smaller" and never "as opposite corners tilt equally/unequally". @terracoda would you be OK if we reduced the threshold of the angle response so that we hear it more often and hopefully before we hear the length change?

**Comment by jessegreenberg** [comment]
I ended up leaving the angle change trigger the same, but reducing the angle change required to prefer describing the change in angle over the change in length. It sounds OK to me but I think all of these variables will continue to be modified over the next week. Closing.

**Comment by terracoda** [comment]
@jessegreenberg, I think it sounds pretty good!
