### ISSUE TITLE
Can/should we reduce intensity of the "success" sounds?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#165]
I am finding the "all sides equal" sound to be a bit distorted and base heavy. And I find the "all right angles" sound a little too sharp. They don't sound as pleasant as the other sounds in this sim to me. Just making an issue in case it is something we want to return to at some point, probably after June studies.

@BLFiedler assigning to you to triage or feel free to just close if you disagree.

**Comment by BLFiedler** [comment]
Yes, I agree that there is some iteration to be done. Like much of the visual design, I thought it important to put "something" there that captures the functionality we want. We'll bring these back to Ashton and co if it seems like they "get the job done" so to speak!

**Comment by BLFiedler** [comment]
Just to update this issue - we are likely to remove these sounds in the coming sound design. This is not a concrete decision at this point, but I will close if so. If not, we should revisit the sound quality of these reference sounds.

**Comment by BLFiedler** [comment]
We are continuing with the continuous, musical sound design and this issue is no longer relevant.
