### ISSUE TITLE
What should the defaults be for the June 11 study

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#167]
We are currently using a URL with a long string of queries like
`?deviceShapeAngleToleranceInterval=0.05&deviceShapeLengthToleranceInterval=0.03&toleranceIntervalScaleFactor=10&dataCollection`

Should these be made defaults? Should Voicing/Context Responses be enabled by default?

Lets check in during design meeting this week.

**Comment by jessegreenberg** [comment]
Discussed today that @BLFiedler will try out the sim to try out tolerance interval defaults.

We discussed that we do NOT want to enable voicing/context responses by default because there will be a test with just sound first, then voicing will be layered in.

**Comment by BLFiedler** [comment]
For the record, this is what I settled on the day before the study with the setup I had: ?dataCollection&deviceAngleTolerance=0.03&deviceShapeAngleToleranceInterval=0.05&deviceShapeLengthToleranceInterval=0.03&toleranceIntervalScaleFactor=5&deviceGridSpacing=0.0375&smoothingLength=3
