### ISSUE TITLE
Add a control in OpenCV to adjust grid size

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#170]
Discusssed in 6/7/2022 meeting - Let's adjust from (same as keyboard/mouse input) up to 5 times in increments of 1

**Comment by jessegreenberg** [comment]
This has been added @BLFiedler. It seems very effective for me in reducing noise, though of course it also makes motion feel less smooth in the sim.
![image](https://user-images.githubusercontent.com/6396244/172471727-5e9eb8ca-eb47-4aee-81d6-4b97947cb97e.png)

Min slider value is grid size for mouse. Max is 5x that. But that range could be adjusted. Over to you to confirm and try it out.
