### ISSUE TITLE
Proximity to Parallel revisited

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#171]
I'd like to try a brief foray into revisiting the Parallel Volume sound set (before attempting any new sounds for a similar purpose).

![image](https://user-images.githubusercontent.com/47331395/174390587-c926f298-945c-4f04-a0b2-f95111e1e135.png)

- [x] Could we (with Sound One as default for that set) try turning off the sound once parallel has been achieved for either set of sides?
- [x] Play the "tick" sound (currently used for non-parallelogram Shape Identification) when one set of sides is parallel (either side).
- [x] Play the current Parallelogram Success sound when both sets of sides are parallel (aka we have a parallelogram). Keep the breaking out of parallel sound for now too. Leave out the parallelogram maintenance sound.

Sounds are stand-ins just to try out the general interaction experience.

**Comment by jessegreenberg** [comment]
The "base sound" is shared between "Parallels Volume" and "Quartet". Just noting that updating the initial value changed the default for both.

I think I have this in, @BLFiedler would you like to try?

**Comment by BLFiedler** [comment]
We will continue with the continuous soundscape instead of mapping any properties to sounds.
