### ISSUE TITLE
Update shape detection with new names and one new shape

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#176]
As we move to a more general framework for the simulation that will expose the names of the various four-sided plane figures within the quadrilateral shape, we will want to clarify the names. 

- [x] Let's update the names accordingly:
  - [x] Convex Quadrilateral (new name from General Quadrilateral)
  - [x] Concave Quadrilateral (new name from Concave)
  - [x] Parallelogram (currently not named, needs to be named)
(the remaining which do not need to be changed are: Trapezoid, Isosceles Trapezoid, Kite, Rhombus, Rectangle, Square)

- [x] Let's also add the only commonly named shape we are missing that is a member of the Kite family - the Dart ![image](https://user-images.githubusercontent.com/47331395/178542692-3c415705-c601-4cf6-94f5-7e95834805a1.png)
- Dart (i.e., concave kite) - Kite with an interior angle greater than or equal to 180 degrees (!!! This overrides the current Kite detection. Might need to adjust the Kite detection to exclude the 180 degree case: 
![image](https://user-images.githubusercontent.com/47331395/178543570-7f4ccb92-a81c-484c-8c59-a21ce94605e4.png)

(BF: I am making the call that the 180 degree case is a concave kite. It's a funny triangle is what it is. We'll see if we get any feedback from math folk).

**Comment by jessegreenberg** [comment]
> Concave Quadrilateral (new name from Concave)

Just confirming, the Voicing strings have always called this "concave quadrilateral". But I changed the constant name in the code to "CONCAVE_QUADRILATERAL".

**Comment by jessegreenberg** [comment]
OK, dart has been added and the above changes were made. @BLFiedler over to you to close or review if you wish.

**Comment by BLFiedler** [comment]
All above comes through on phettest! Fantastique. Closing.
