### ISSUE TITLE
Add Diagonal Guides

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#179]
The grid and corner guides are particularly helpful frames of reference for most of the shapes we are able to detect. Kites and Darts could benefit from a different guide to assist with symmetry visualization with a line drawn through the diagonals of the shape (one line connecting A & C, one line connecting B & D).

- [x] Let's add a new checkbox, above Grid (renamed in #178) and below Corner Guides, named Diagonal Guides.
- [x] Add dashed lines (width ~ play area boundary line width) that connect the diagonals (A to C and B to D) and continue in either direction to the play area boundaries. Let's go with something like RGB 155 110 110 for now.
- [x] Draw the diagonals under the Shape (both vertices and side) and under Corner Guides for now.

Rough mockups below (does not reflect the checkbox control order stated above or updated naming):

![image](https://user-images.githubusercontent.com/47331395/180506869-d5d8faaa-c191-4469-9384-84d62e2973a6.png)
![image](https://user-images.githubusercontent.com/47331395/180506987-065e75d2-d5d9-4114-9869-db93249d8a86.png)

**Comment by jessegreenberg** [comment]
Added in the above commits. I noticed that the color values 
>RGB 155 110 110
Are a bit more red than what is shown in these mockups. Let me know which one you prefer.

Here is a dev version with this added since phettest is not predictable: 
https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.42/phet/quadrilateral_en_phet.html

**Comment by jessegreenberg** [comment]
In a meeting @BLFiedler said that the R channel was supposed to be 115, that explains the redness. Fixed in the above commit.

**Comment by BLFiedler** [comment]
Oops - that was 115 110 110 on the RGB value. Typo!

The spacing relative to the width on the dashed line feels like it can cause some issues trying to estimate when they are perpendicular. Can we reduce the "transparent" portion a bit to be around the width of the line?

**Comment by jessegreenberg** [comment]
OK! Yes, reduced the off length in the above commit. Can you review again? Let me know if you would like a dev version.

**Comment by BLFiedler** [comment]
Looks great! Closing for now. Additional adjustments based on other feedback for other issues.
