### ISSUE TITLE
Side or Corner can get stuck sometimes when - not just Kite to Dart

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#180]
Using Safari on MacOS Monterey 12.2.1
MacBook Pro

With keyboard I can't move Corner A below this angle with the Down Arrow key presses.
![image](https://user-images.githubusercontent.com/1902116/181291656-4a008cd8-7746-43fb-9522-cfc0fa733bc4.png)

Strangely if I start my key presses after already in a Dart shape, I can move up and down with Arrow keys without getting stuck. 

![image](https://user-images.githubusercontent.com/1902116/181292248-df7a616b-f285-481a-a31d-f9ca8e0efb4a.png)
Moving up with Up Arrow key
![image](https://user-images.githubusercontent.com/1902116/181292340-073b7f6b-9438-4979-b849-f56f30a164bb.png)
Moving down again with Down Arrow key
![image](https://user-images.githubusercontent.com/1902116/181292517-62b438c4-c7e7-46ed-aa1e-97aab9b599dd.png)

**Comment by terracoda** [comment]
After a reset, I easily made this Dart from the starting Square.
![image](https://user-images.githubusercontent.com/1902116/181293321-3c869308-f876-4e46-9ba9-8cffd014ad03.png)

**Comment by terracoda** [comment]
After a page reload. I tried just using the keyboard. I was able to make this Dart
![image](https://user-images.githubusercontent.com/1902116/181294921-a29d8fcd-85c3-4670-b432-3d80aa263f62.png)

But not able to move down beyond this point with Corner A. 
![image](https://user-images.githubusercontent.com/1902116/181295171-78404a9c-6d88-4036-8f2a-aa6f1113aa8a.png)

Maybe there is something amiss with Corner A? I was able to make Darts by moving Corners B and D. Again, never used the mouse in the sim here except to take screen shots.

![image](https://user-images.githubusercontent.com/1902116/181295648-7108fab6-044f-4d15-bbac-a465bae067fb.png)

**Comment by terracoda** [comment]
This might be a more general problem. Corner B is getting stuck here:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/1902116/181307401-0c76f8bf-12ac-49ac-8deb-c3609a197c99.png">

Even though I moved it down with the keyboard, I can't move it back up.

**Comment by jessegreenberg** [comment]
I am also seeing that this is a general problem with keyboard input, for instance I can not move vertex A any higher for this shape
![image](https://user-images.githubusercontent.com/6396244/184917001-4e289785-fa66-4566-8c39-f73d7514b29d.png)

**Comment by BLFiedler** [comment]
Same. In fact, once you do that, you can get B stuck so it can go farther down, C cannot go farther up, and then if you move D up to A, it cannot go any farther down:

![image](https://user-images.githubusercontent.com/47331395/184919713-dcf7085b-5f1b-42c3-84ae-40bef75232c0.png)

**Comment by terracoda** [comment]
I also experienced this issue with 1.0.0-dev.53

**Comment by jessegreenberg** [comment]
Removing assignment, we hope this will be fixed with https://github.com/phetsims/quadrilateral/issues/41

**Comment by jessegreenberg** [comment]
Found this again for a Kite, I cannot move corner B up
![image](https://user-images.githubusercontent.com/6396244/191555790-791e60f9-1836-47fb-a672-d0356cb8d09d.png)

**Comment by terracoda** [comment]
Just found this one. I can't move Corner D up over the horizontal grid line.
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1902116/191973595-1f68b3cc-504a-455a-91fb-ea21e9ac5466.png">

After moving Corner D up above the line with the mouse, I now can't move it down across the same line.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/1902116/191974285-9837f5b9-73aa-4cdd-b75a-22d41daa569b.png">

**Comment by terracoda** [comment]
Latest code on master. Here in this shape, Corner B cannot be moved down with keyboard (fine for mouse), and corner D can't move up or down with keyboard (fine for mouse).
<img width="981" alt="image" src="https://user-images.githubusercontent.com/1902116/192289940-f32c1b15-135e-48d8-a337-4aad5683bbdb.png">

**Comment by terracoda** [comment]
Found another case - Corner C got stuck when moving down.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/1902116/192362246-2c62ac51-68ae-464a-9c76-fa1883260889.png">

**Comment by terracoda** [comment]
And Side DC is stuck here
<img width="911" alt="image" src="https://user-images.githubusercontent.com/1902116/192362628-878d6119-b2f9-4854-92f3-c3405f48fdc1.png">

**Comment by terracoda** [comment]
I can't move Side CD down in this screen shot
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1902116/194560533-54851aee-ac6f-44cd-b821-f69d3495e3aa.png">

After moving it down with the mouse, I could not move it back up over a similar location (see below - can't move up)
<img width="525" alt="image" src="https://user-images.githubusercontent.com/1902116/194560789-f8b5e60c-a818-474a-a11f-341fec9902f4.png">

**Comment by terracoda** [comment]
Today a kite got stuck here twice, once after a fresh pull.
Corner C is stuck for both keyboard and Mouse input.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/1902116/195391687-84c0a2d9-34f9-424e-8275-2942b920a8ef.png">

When I clicked on Corner B - Corner C jump 3 grid-cells down on its own
<img width="902" alt="image" src="https://user-images.githubusercontent.com/1902116/195392019-a5c5d939-c336-4169-92f3-78a21cffcfd2.png">

And sound is playing for ever - maybe the sim has crashed.

**Comment by terracoda** [comment]
Pressing the Reset Button stopped the music but did not reset the shape. Pressing Reset All reset everything.

**Comment by jessegreenberg** [comment]
Yes, I am guessing sim is crashed. Are there any errors in the dev tools?

**Comment by terracoda** [comment]
Opening a new issue as - yes  - getting a huge number of errors in Dev Tools. This could be a common code problem unrelated to previous sticky corner and sides.

**Comment by BLFiedler** [comment]
Collision detection as a new model for shape restriction is being abandoned. We guessed it would be a fix for this issue, but we will have to open up an investigation using the current shape restriction model.

Assigning to @jessegreenberg to fix.

**Comment by jessegreenberg** [comment]
OK, I think this is fixed with https://github.com/phetsims/quadrilateral/commit/2c7f7d3981f83239bd9eab2e24a4cc78d287c400. I believe that issue explains every screenshot posted in this issue, thanks @terracoda for collecting them all! Closing this one.
