### ISSUE TITLE
Potentially duck Sound when Voicing is active

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#185]
[creating issues from the new project boards automatically makes a blank initial comment which I have realized since making this issue...]

**Comment by BLFiedler** [comment]
In case we want to reduce the really cool music while Voicing is actively speaking or provide an option to duck the sound, there may be possibilities built into Voicing.

During monthly check-in:

> From Me to Everyone 12:28 PM
> Random thought - do we have a way to lower sonification levels when voicing is active? Either a live ducking or just a toggle in the Audio tab to reduce Sounds under the Voicing tab?
> 
> From Michael Kauzmann to Everyone 12:29 PM
> We know when the browser is actually speaking, so potentially sound could listen to that, though it isn't currently set up to notify on speaking quite like that (I think)
> 
> From Emily Moore to Everyone 12:29 PM
> I'm not sure, Jesse would know. We can't do that with Interactive Description, but Voicing I would guess we could do that if we wanted.
> 
> From Taliesin Smith to Everyone 12:29 PM
> I have a feeling that WebSpeech might do this automatically, but not sure.
> 
> From Michael Kauzmann to Everyone 12:34 PM
> Ahh nice! https://github.com/phetsims/utterance-queue/blob/03e6296bb7dbe1e0f738d8a81ff30e982343bc2c/js/SpeechSynthesisAnnouncer.ts#L129-L132
>
```
voicingManager.startSpeakingEmitter.addListener( () => { soundManager.duckVolume(); } );
voicingManager.endSpeakingEmitter.addListener( () => { soundManager.unduckVolume(); } );
```

No assignment, but leaving it here in case it proves helpful in the current sound design being explored in #175. Can close prior to publication if it doesn't prove helpful.

**Comment by BLFiedler** [comment]
From @terracoda in Slack: 

"... For mouse exploration the clicks on the side and and corner object responses really support identifying properties. There's no automatic audio ducking, so descriptions are little hard to hear..."

**Comment by terracoda** [comment]
I think this should be an option. It might best placed in the Voicing Toolbar.

**Comment by jessegreenberg** [comment]
Just wanted to note that `soundManager` currently doesn't have functions `duckVolume`/`unduckVolume` but I assume something like that could be added. We will want to consider whether this is something to build into common code or just quadrilateral.

**Comment by BLFiedler** [comment]
> Just wanted to note that `soundManager` currently doesn't have functions `duckVolume`/`unduckVolume` but I assume something like that could be added. We will want to consider whether this is something to build into common code or just quadrilateral.

I suspect as sound design in sims continue (especially with continued exploration into palatable continuous sounds), this will find more use. Tagging @jbphet to have him weigh in.

**Comment by BLFiedler** [comment]
After interviews where I was trying to speak, and after Voicing interviews by @terracoda, I think this will be very helpful (in addition to some sound mixing).

@jbphet, do you feel this is something that should stay in Quad or be expanded to common code?

**Comment by BLFiedler** [comment]
Throwing out for later decision: Would this option live in the Audio Tab or Voicing Tab?

**Comment by jessegreenberg** [comment]
I made https://github.com/phetsims/tambo/issues/167 to investigate this in tambo.

**Comment by terracoda** [comment]
I think this is an important option.

**Comment by terracoda** [comment]
But it can wait until we have object and context responses refined and implemented. I thnk we need less talking in general.

I am starting to think that the sonification can fill the silent steps between useful object and context responses.

**Comment by BLFiedler** [comment]
@terracoda, is this better with the changes to the overall volume mix in #175 ? 

Would it be helpful to say, half the volume again when we turn on Voicing for now until we investigate active ducking?

**Comment by BLFiedler** [comment]
Agreed on the 1xParallel track, which I made a comment on already (need to lower it specifically or just swap it entirely). I mostly meant that we had halved all the shape sounds, so their balance relative to Voicing should already be better. But, if it'd be helpful to halve it again with Voicing on, then we should!

**Comment by BLFiedler** [comment]
@jbphet will likely implement this in tambo.

For Quadrilateral, we'd like this to functionally lower volume of all sounds/sonifications while Voicing strings are being read out.

**Comment by jbphet** [comment]
This has been implemented and is now available on master.  I'm not sure who should review the behavior and provide feedback, so I'll start by assigning it to @BLFiedler, since he opened the issue originally.

**Comment by BLFiedler** [comment]
Tagging @terracoda into the issue. This is currently live.

**Comment by BLFiedler** [comment]
We decided in the meeting that lengthening the tracks fade out by one more second will help in most cases. Other users havethe option to enable Tracks Play Forever checkbox in the pref menu. I'll take care of this change.

**Comment by jbphet** [comment]
@Ashton-Morris and I talked about this feature in today's sound design meeting, and he'd like to review this as well.  Adding him as an assignee.

**Comment by BLFiedler** [comment]
We bumped up the shape sound play time to 5 seconds instead of 4 seconds to increase probability of hearing any sonification after Voicing string ends. Forgot to update this.

This is ready to close, but it was indicated that @Ashton-Morris might want to review this.

**Comment by Ashton-Morris** [comment]
I think it sounds good! Feel free to close.
