### ISSUE TITLE
Corners "slip" off of the input grid when using the shift modifier

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#186]
This was noted a few months back by @BLFiedler, @jessegreenberg, and @terracoda, but wasn't put into an issue. Pressing the shift key modifier for small steps using the arrow keys/WSAD can cause the vertices to come off of the input grid. 

This seems to be a bug with respect to the press and hold feature for keyboard input (and is more reliably reproduced holding the button), but can happen with single key presses where it seems to "slip" farther than intended. 

When this happens, it isn't possible to return to the input grid and consequently, you cannot line return to the same shape or back to a grid line. Aside from just being a bug, this breaks the "same keypress brings me back to the same state" philosophy we have tried to adhere to.

Note: This doesn't happen with Sides currently. There is no press-and-hold support for sides. This may change with the collision model being implemented in #41?

I made a small video illustrating the single key press slip:

https://user-images.githubusercontent.com/47331395/183090684-755e1a76-9b80-4df5-8b3f-eb0021254538.mp4

**Comment by jessegreenberg** [comment]
This has been fixed via https://github.com/phetsims/scenery/issues/1437. @BLFiedler can you please confirm?

**Comment by jessegreenberg** [comment]
Corners are constrained to the grid correctly now, but there is an issue (particularly with shift modifier) where more than one step can happen per press. We aren't exactly sure what is causing it. Back to me to investigate.

**Comment by jessegreenberg** [comment]
Pressing and holding the shift key and then pressing an arrow key causes this bug to happen consistently.

**Comment by jessegreenberg** [comment]
OK, confirmed that these timing variables that manage the delay for press and hold behavior increment if any key is down. They should probably only increment if dragging keys are down.

```js
      // dt is in seconds and we convert to ms
      this.moveOnHoldDelayCounter += ms;
      this.moveOnHoldIntervalCounter += ms;
```

**Comment by jessegreenberg** [comment]
Fix committed above. Before this fix you could reproduce by
1) Press and hold any key (shift key or any letter key, doesn't matter). Hold for a few seconds.
2) Press an arrow key or a letter key.

Draggable will move multiple steps. Should no longer happen after the above change. @BLFiedler can you please confirm?

**Comment by BLFiedler** [comment]
Haven't been able to recreate on current branch with several minutes of play. Closing.
