### ISSUE TITLE
Align model shape detection with shape hierarchy design

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#188]
### Why

We discussed changing the organization and specific shape detection code to more closely align with the shape relationship hierarchy for code clarity as well as possible insight into the parameters we can tweak or other solutions to ongoing problems with shape detection (rectangle not being detected and instead displaying a parallelogram and trapezoids becoming parallelograms during side interaction).

### Current Shape Relationship Hierarchy
![image](https://user-images.githubusercontent.com/47331395/183741722-056b401f-8f97-4d55-a2c5-1726c3e27eb5.png)

#### Current
Convex or Concave -> Parallelogram (Rectangle, Square, Rhombus),  Trapezoid (Isosceles), Kite (Dart)

or 

- Convex
  -  Kite
  - Trapezoid
       - Isoceles Trapezoid
  - Parallelogram
      - Rectangle
      - Square
      - Rhombus
- Concave
  - Dart

#### Proposed
Convex -> Kite, Trapezoid (Isoceles Trapezoid, Parallelogram (Rectangle, Square, Rhombus))
Concave -> Dart (using kite requirement)

or

- Convex
  -  Kite
  - Trapezoid
      - Isoceles Trapezoid
      - Parallelogram
        - Rectangle
        - Square
        - Rhombus
- Concave
  - Dart

#### Parallel Lines
We determine parallel line pairs separately. This is already being done in the model. Let's then use this to determine when a trapezoid or parallelogram is formed.
> 	// Determines is AB is parallel with CD or BC is parallel with DA using addition up to MATH.PI (angleToleranceInterval)

#### Trapezoid
Requirements: Only one set of parallel lines. Relies on angleToleranceInterval.
> // IF AB and CD XOR BC and DA are parallel then I am a Trapezoid

#### Parallelogram
Requirements: (Trapezoid &&) Exactly two sets of parallel lines. Relies on angleToleranceInterval.
> // IF AB and CD && BC and DA are parallel then I am a Parallelogram

#### Square, Rectangle, Rhombus
Requirements: Check for Parallelogram. Check for full requirements for each shape:
 - Rectangle - all angles = Pi/2 (shapeAngleToleranceInterval)
 - Rhombus - all sides = each other (shapeLengthToleranceInterval)
 - Square - All sides = each other && all angles = Pi/2 (shapeAngleToleranceInterval & shapeLengthToleranceInterval)

#### Kite
Requirements: Exactly one set of equal, opposite angles (shapeAngleToleranceInterval) and exactly two sets of equal adjacent sides (shapeLengthToleranceInterval).
> // IF two pairs of adjacent sides have equal length AND there is one pair of opposite angles are equal (shapeAngleToleranceInterval && shapeLengthToleranceInterval)

**Comment by jessegreenberg** [comment]
OK, this is done. Honestly the code is much cleaner, this may be easier to read than https://github.com/phetsims/quadrilateral/issues/184.  Seems good to have this aligned with shape hierarchy and hopefully it will naturally resolve some of the open bugs related to name detection.

https://github.com/phetsims/quadrilateral/blob/b4100a0ffec18f2a0c3837dff3f8e21ded854fc1/js/quadrilateral/model/QuadrilateralShapeModel.ts#L529-L589

@BLFiedler over to you to review or comment on next steps for this issue.

**Comment by BLFiedler** [comment]
Rectangle/Parallelogram detection seems fixed! 🥇 

I am currently encountering 2 tolerance-sourced detection errors (both tied to parallel determination) and 1 unknown error:
#### Tolerance-sourced errors
- It is possible to move from Convex < - > Trapezoid with side drag.
- It is possible to move from Trapezoid < - > Parallelogram with side drag.

#### Unknown shape detection error
When moving the unequal vertices parallel to one another (e.g., up and down) to maintain a kite, we pass through a convex quadrilateral before and after the parallelogram-overlapped kites. Single minor steps result in the following shape sequence:

Kite < - > Convex Quadrilateral < - > Square or Rhombus < - > Convex Quadrilateral < - > Kite

The tolerance-sourced detection errors will require their own special behavior (related to issues #108 and #156) and I think should be solved in #156.

Uncertain about the latter error. Possibly an issue with the current kite detection? Or does it enter the square/parallelogram region of code and then get spit out to the default convex case without reaching kite detection?

**Comment by jessegreenberg** [comment]
> The tolerance-sourced detection errors will require their own special behavior (related to issues https://github.com/phetsims/quadrilateral/issues/108 and https://github.com/phetsims/quadrilateral/issues/156) and I think should be solved in https://github.com/phetsims/quadrilateral/issues/156.

Totally agree, that sounds like where we last landed in https://github.com/phetsims/quadrilateral/issues/108#issuecomment-1090402804

> Unknown shape detection error

Sorry I don't understand the steps to recreate this, can you demo in meeting today?

**Comment by BLFiedler** [comment]
The kite-centric error is actually two issues. One is the definition of a Kite I provided that doesn't let a shape with all equal angles to be a kite (oops, sorry :( ). The other is the priority of a parallelogram over a kite and the overlap in angleToleranceInterval and shapeAngleToleranceInterval.

## Kite defaults to Convex Quadrilateral when two sets of equal opposite angles

Kite currently behaves this way:

> Kite
>Requirements: **Exactly one set of equal, opposite angles** (shapeAngleToleranceInterval) and exactly two sets of equal adjacent sides (shapeLengthToleranceInterval).
>
>// IF two pairs of adjacent sides have equal length AND there is one pair of opposite angles are equal (shapeAngleToleranceInterval && shapeLengthToleranceInterval)

My mistake. It should actually behave:

Kite
Requirements: _At least one_ set of equal, **opposite** angles (shapeAngleToleranceInterval) and exactly two sets of equal **adjacent** sides (shapeLengthToleranceInterval).

// IF two pairs of adjacent sides have equal length AND there is one or two pairs of _opposite angles_ are equal (shapeAngleToleranceInterval && shapeLengthToleranceInterval)

- [ ] Adjust Kite definition to include two sets of equal but opposite angles

## Parallelogram should not overwrite Kite detection if not Rhombus or Kite

This may actually not have been the exact case when we discovered it during the meeting but would have been even if we implemented the fix above, since a parallelogram would override a Kite or create inconsistent behavior depending on the last shape.

On one hand, it's possible that building in redundancies for Square and Rhombus detection as nested in the Kite Detection may improve this. 

However, I suspected one issue was in how angleToleranceInterval and shapeAngleToleranceInterval differed in their usage. We use the same values for them, but one is used in a sum to determine parallel pairs (angleToleranceInterval) and the other is used in direct comparisons against angles (shapeAngleToleranceInterval), both = 0.01. I tried cutting angleToleranceInterval in half to 0.005 and I am no longer able to replicate the Kite -> Parallelogram -> Rhombus -> Parallelogram -> Kite interaction sequence described previously.

I haven't found anything that would prevent us from making this change after several minutes of changing between shapes with sides and vertices.

- [ ] Change default angleToleranceInterval value to 0.005.

https://bayes.colorado.edu/dev/phettest/quadrilateral/quadrilateral_en.html?ea&brand=phet&showModelValues&angleToleranceInterval=0.005

**Comment by jessegreenberg** [comment]
> Found one oddity - Moving Vertex D left and right in this case transitions from Kite -> Rhombus -> Kite. 

I found the reason for this. Our kite detection checks for exactly two sets of adjacent equal sides. When a square or a rhombus there are four pairs of equal adjacent sides so the model claims it is not a kite.

Another case of this is here: 
![image](https://user-images.githubusercontent.com/6396244/185206143-d4223542-7282-4e51-a0aa-5698737cb8ce.png)

This should be a kite, but the model says that all adjacent lengths are equal within `shapeLengthToleranceInterval`.

**Comment by BLFiedler** [comment]
Let's see if we can connect over this soon - I'm a little uncertain over the interaction in https://github.com/phetsims/quadrilateral/issues/188#issuecomment-1218301103. Since Rhombus is the most specific shape (and a member of the Kite), that is what should happen I believe? Kite should be overridden by Rhombus/Square. However, I think you're correct in building in the redundancy as shown above.

Just as a note, I am also able to reach a case with widened tolerances where an isosceles trapezoid occurs with all equal angles (90 degrees). I think your suggestion above will fix that as well?

We could also restrict Isosceles Trapezoid to two pairs of equal adjacent angles, but not all equal (which goes against the shape relationships model we're trying to align with)

**Comment by jessegreenberg** [comment]
> ince Rhombus is the most specific shape (and a member of the Kite), that is what should happen I believe?

Thanks, yes that makes sense now.

**Comment by BLFiedler** [comment]
As @terracoda noted during the meeting, there do seem to be some issues that overlap with the interaction between the input grid and tolerance interval values. The interrelatedness of the input grid and tolerance (and thus shape detection) I think are inextricable for the purposes of smooth and consistent interaction.

We are also up against the fact that the code must run linearly (with exit points) while the shape relations are branched and overlapping.

And these two are butting up against each other.

I have one thought for accommodating the tension between the branched shape relationships and the shape detection algorithm that would require one more rewrite, but is more aligned with the ways I've been thinking about the shared properties of the shapes and closer to how our sound design is done. However, I'm not sure how feasible it is in terms of code structure. I'll reach out for a meeting w/ JG.

On the other, we may decide to cover up any small inconsistencies in tolerance values with adjustments to the input grid. Testing parts of this with #199.

**Comment by BLFiedler** [comment]
A quick note on what happens if we enlarge the grid spacing too large relative to the tolerances. In this case with a rotated shape, I lose the ability to locate a kite. This was already possible with only standard keypresses (no shift modifier), but I'm using a mouse here.

https://user-images.githubusercontent.com/47331395/186428099-04ef0783-c82d-460e-ad0b-d6eec9c32045.mov

**Comment by BLFiedler** [comment]
Discussed with @jessegreenberg over Zoom, but dumping this here without further context for the moment:

concaveShape
parallelOnePair
parallelTwoPair
~~equalAdjacentCornerOnePair~~
equalAdjacentCornerTwoPair
equalOppositeCornerOnePair
~~equalOppositeCornerTwoPair~~(parallelogram optional)
equalAllCorner = BOOLEAN
~~equalAdjacentSideOnePair~~
equalAdjacentSideTwoPair
equalOppositeSideOnePair
~~equalOppositeSideTwoPair~~ (parallelogram optional)
equalAllSide

shapeIdentityArray = [concaveShape, parallelOnePair, parallelTwoPair, equalAdjacentCornerTwoPair, equalOppositeCornerOnePair, equalAllCorner, equalAdjacentSideTwoPair, equalOppositeSideOnePair, equalAllSide]

shapeIsConvexQuadrilateral =  [FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE]
shapeIsConcaveQuadrilateral = [**TRUE**, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE]
shapeIsDart = [**TRUE**, FALSE, FALSE, FALSE, **TRUE**, FALSE, **TRUE**, FALSE, FALSE]
shapeIsKite = [FALSE, FALSE, FALSE, FALSE, **TRUE**, FALSE, **TRUE**, FALSE, FALSE]
shapeIsTrapezoid = [FALSE, **TRUE**, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE]
shapeIsIsoscelesTrapezoid = [FALSE, **TRUE**, FALSE, **TRUE**, FALSE, FALSE, FALSE, **TRUE**, FALSE]
shapeIsParallelogram = [FALSE, **TRUE**, **TRUE**, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE]
shapeIsRectangle = [FALSE, **TRUE**, **TRUE**, **TRUE**, FALSE, **TRUE**, FALSE, **TRUE**, FALSE]
shapeIsRhombus = [FALSE, **TRUE**, **TRUE**, FALSE, **TRUE**, FALSE, **TRUE**, FALSE, **TRUE**]
shapeIsSquare = [FALSE, **TRUE**, **TRUE**, **TRUE**, **TRUE**, **TRUE**, **TRUE**, **TRUE**, **TRUE**]


EXAMPLES:

*Check Concave/Convex*
?A || B || C || D >= 180
**concaveShape** = TRUE
else
**concaveShape** = FALSE 

*Check Parallel*
if cornerA + cornerD = 180 || cornerB + cornerC = 180
	then parallelABtoCD -> TRUE

if cornerA + cornerB = 180 || cornerC + cornerD = 180 
	then parallelBCtoDA -> TRUE

if parallelBCtoDA = TRUE & parallelABtoCD = FALSE || parallelBCtoDA = FALSE & parallelABtoCD = TRUE 
	then **parallelOnePair** = TRUE 
if parallelBCtoDA = TRUE & parallelABtoCD = TRUE
	then **parallelTwoPair** = TRUE

**Comment by BLFiedler** [comment]
The above post was regarding a change to how we do shape detection (again) that more closely mimics how we've been using the shape hierarchy. Rather than branching paths, it uses a build-up of shared properties as the basis for shape identification. This results in a unique ID for each shape based on the presence of parallel pairs, angle equivalencies, and side equivalencies.

We believe this will prevent some of the issues we anticipate hitting when transitioning between families of shapes, much like the problem described above when a shape that should be labeled a Kite is being labeled a Convex Quadrilateral.

- [ ] Implement the shape detection scheme above with unique IDs for each shape in place of branching

This will NOT fix issues of overlapping tolerance such as the "looks like a rectangle/square but registers as an isosceles trap". One issue there may be that we are still using shapeAngleToleranceInterval differently. It is being used both to measure a change in angles (e.g., between adjacent angles for an isosceles trapezoid) and as a self-comparison against a static value (right angle display against 90 degrees). angleToleranceInterval is applied to a similar case re: a change in angles, but is also changed to infinity occasionally to avoid some undesirable side-dragging induced shape changes (trap -> convex, trap -> parallelogram). For now, let's create a new tolerance interval to separate the self-comparison and angle change cases. 

- [ ] Create a new tolerance staticAngleToleranceInterval that replaces shapeAngleToleranceInterval for the case of checking 90 degrees (right angle display) or 180 degrees (convex) or anywhere else it is used to check the angle against a single value. Set the default for this to 0.01 for now. 
- [ ] Leave shapeAngleToleranceInterval anywhere it is used for comparison between angles (e.g., corner A to corner B, between adjacent/opposite angles)
- [ ] Create a query parameter to adjust the new tolerance interval.

Once this is done, we may play around with the requirements for a parallelogram to address trapezoids becoming a parallelogram by dragging a side.

**Comment by BLFiedler** [comment]
In case it's helpful, I adjusted the above lists into a table. I added in the two extra parallelogram constraints for completeness.

|  | concaveShape | parallelOnePair | parallelTwoPair | equalAdjacentCornerTwoPair | equalOppositeCornerOnePair | equalOppositeCornerTwoPair | equalAllCorner | equalAdjacentSideTwoPair | equalOppositeSideOnePair | equalOppositeSideTwoPair | equalAllSide |
|---|---|---|---|---|---|---|---|---|---|---|---|
| Concave | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Dart | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 |
| Convex | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Kite | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 |
| Trapezoid | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Isosceles Trapezoid | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 |
| Parallelogram | 0 | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 1 | 1 | 0 |
| Rectangle | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 1 | 1 | 0 |
| Rhombus | 0 | 1 | 1 | 0 | 1 | 1 | 0 | 1 | 1 | 1 | 1 |
| Square | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |

Clarifying what I mean in those labels (angles defined by middle vertex):
- concaveShape - Shape has one angle >= 180 degrees or Pi radians
- parallelOnePair - Any angle has only one adjacent angle whose sum is 180 degrees or Pi radians
- parallelTwoPair - Any angle has two adjacent angles whose sum is 180 degrees or Pi radians
- ~~equalAdjacentCornerOnePair~~There is one set of two adjacent angles in the shape that are equal (e.g., A = B =/= C =/= D)
- equalAdjacentCornerTwoPair - There are two sets of two adjacent angles in the shape that are equal (e.g., isosceles trap, A = B =/= C = D) 
- equalOppositeCornerOnePair - There is one set of two opposite angles in the shape that are equal (e.g., A = C =/= B =/= D)
- equalOppositeCornerTwoPair (parallelogram optional) - There are two sets of two opposite angles in the shape that are equal (e.g., A = C =/= B = D)
- equalAllCorner - All corners are 90 degrees or Pi/2 radians
- ~~equalAdjacentSideOnePair~~ - There is one set of two adjacent side in the shape that are equal (e.g., AB = BC =/= CD =/=DA)
- equalAdjacentSideTwoPair - There are two sets of two adjacent sides that are equal (e.g., kite, AB = BC =/= CD = DA)
- equalOppositeSideOnePair - There is one set of two opposite sides that are equal (e.g., isosceles trap, AB = CD =/= BC =/= DA)
- equalOppositeSideTwoPair (parallelogram optional) - There are two sets of two opposite sides that are equal (e.g., AB = CD =/= BC = DA)
- equalAllSide = All sides are the same length (e.g., rhombus, square, AB = BC = CD = DA)

**Comment by terracoda** [comment]
@BLFiedler, I started with a tilted a square and did not have much trouble finding a Kite with either a keyboard or a mouse. I don't think I fully understand what you mean my skipping over shapes? Wouldn't this be more of an issue for keyboard than for mouse input? 
Of course if a learner has a tilted shape, they won't be able to follow the visual grid to find a kite. They would have to rely more heavily on the visual diagonal guides, or align their shape to the visual grid.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/1902116/187238443-50d94b3d-fef4-4ba8-a1ea-97941665aa00.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/1902116/187238054-68006e12-2c62-46ce-a02a-c75ca544ef64.png">

In my case all the tolerances are equal to the default step size. Is that the case for you demo?

**Comment by jessegreenberg** [comment]
- Shouldnt a Rectangle have two `equalAdjacentSideTwoPair` true?

**Comment by jessegreenberg** [comment]
I was thinking that each row in https://github.com/phetsims/quadrilateral/issues/188#issuecomment-1228576246 was the only condition for that shape. But of course "concave" requires the `concaveShape` but could have any number of columns be true. Wondering if we need special "fallback" cases for convex and concave so that those classifications can include other conditions.

**Comment by jessegreenberg** [comment]
Over a zoom meeting, @BLFiedler and I worked on https://github.com/phetsims/quadrilateral/commit/4f321c7a7426c7fa6079310f5fffb1f66c38c990. The resultant behavior is https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.60/phet/quadrilateral_en_phet.html. It may be a good way forward but there are a couple of problems still.
1) There are some manual checks to include trapezoids with special conditions. They had to be manually added. We are worried about other cases we are missing and may have to add later.
2) One such case that we know is not implemented is
>"is not quite a parallelogram* case, or (One Parallel, two opp angle, two opposite side)

We discussed a different approach where we allow multiple shape matches and allow the most specific shape requirements to take priority. I added this in https://github.com/phetsims/quadrilateral/commit/39a9c73a478bd7ad4a73f61696e838bfafab9d42 and really like it so far!

Here is a build with that: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html

I haven't been able to break it so far, but have not tested thoroughly.

Over to @BLFiedler to review this approach and comment on how we should continue here.

**Comment by BLFiedler** [comment]
Pasting in some modified notes made to JG over Slack:

>So, I am also unable to break it for everything we were trying to achieve before. The one exception, once again, is the right angle indicators (make a long rectangle and then shift it just a tick to make a parallelogram OR shift two vertices one tick away to make an isoceles trapezoid).


Located where the right angle indicators are drawn in the View



...
`assert && assert( vertex1.angleProperty.value, 'Angle must be available to draw the indicator' );
    const angle = vertex1.angleProperty.value!;
    this.visible = this.shapeModel.isRightAngle( angle ) && this.cornerGuideVisibleProperty.value;`

...

And investigating where isRightAngle is defined in the Model and otherwise used in combination with shapeAngleToleranceInterval, led me to:

>So yeah, this is now just simply the difference between the mathematical trueness of all angles equal means 90 and the all angles equal to a tolerance derived 90.


>I am trying to determine what tolerance means in the face of the larger input grid we've discussed. It seems we've created that shape detection model that is more independent of tolerance (ignoring the right angle indicators)

Meaning, it does exactly what we expect it to within the set tolerance.


>After playing around with extremely low to zero tolerance, I've settled on the need for the intervals for sure and now have a decent understanding of their values relative to the input grid. 

Here's a link I used. You'll notice this doesn't work very well. Adding any nearly any level of angle tolerance fixes a few thing. I can't quite find a value less than 0.0125 for minorVertexInterval that works, but I suspect things would get worse with more interstitial values. (https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html?shapeAngleToleranceInterval=0&angleToleranceInterval=0&shapeLengthToleranceInterval=0.0001)

>And extremely large tolerances (https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html?shapeAngleToleranceInterval=5&angleToleranceInterval=5&shapeLengthToleranceInterval=10)

> This is so far, my foolproof link: [https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phe[…]nterval=0.002&angleToleranceInterval=0.001&showModelValues](https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html?shapeAngleToleranceInterval=0.002&angleToleranceInterval=0.001&showModelValues)



Lastly,
- [ ] Go ahead and make dev.61 the real deal. Nearly two hours of play and I haven't found an issue.

**Comment by terracoda** [comment]
> We discussed a different approach where we allow multiple shape matches and use the match with the most specific requirements to take priority. I added this in https://github.com/phetsims/quadrilateral/commit/39a9c73a478bd7ad4a73f61696e838bfafab9d42 and really like it so far!

This sounds like totally the right approach to me!

It seems like @BLFiedler tested things deeply here.

I'll try [https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phe[…]nterval=0.002&angleToleranceInterval=0.001&showModelValues](https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html?shapeAngleToleranceInterval=0.002&angleToleranceInterval=0.001&showModelValues)

with the keyboard and voicing.

**Comment by BLFiedler** [comment]
This is a WILD issue. Definitely need to bookmark it for some future publication.

On that note, here is a link I think captures a lot of the intended defaults in other issues (#197, #175): https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html?shapeAngleToleranceInterval=0.002&angleToleranceInterval=0.001&shapeLengthToleranceInterval=0.003&soundDesign=TRACKS_BUILD_UP_SIMPLE&minorVertexInterval=0.05&majorVertexInterval=0.25

**Comment by terracoda** [comment]
I seem to have lost it, but I had trouble making a kite, but the above shapeLengthTolerance provided by Brett might fix that.

**Comment by terracoda** [comment]
With the default step-size of 1 grid space, I think it it hard to find a rhombus.

**Comment by terracoda** [comment]
At least when transitioning between a square and parallelogram.

**Comment by terracoda** [comment]
I can't seem to get an incorrect shape. In certain cases I need to use the shift modifier key to not jump over certain shapes when transitioning between the different parallelograms.

Using this link: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.61/phet/quadrilateral_en_phet.html?shapeAngleToleranceInterval=0.002&angleToleranceInterval=0.001&shapeLengthToleranceInterval=0.003&showModelValues

**Comment by terracoda** [comment]
@BLFiedler and @jessegreenberg I think this works well, too.

**Comment by terracoda** [comment]
It would be good to discuss the default step-size and adjusted step size in a different issue.

**Comment by terracoda** [comment]
Maybe we can adjust the snap to, so one cannot jump over a shape. For example, one cannot jump over a rectangle when leaning a parallelogram from left to right when using the keyboard. Michael had some code for this kind of thing in RaP.

**Comment by BLFiedler** [comment]
> With the default step-size of 1 grid space, I think it it hard to find a rhombus.

Yes, I think swapping the major and minor step as default is probably the way to go.

> Maybe we can adjust the snap to, so one cannot jump over a shape. For example, one cannot jump over a rectangle when leaning a parallelogram from left to right when using the keyboard. Michael had some code for this kind of thing in RaP.

I'm less certain here. There isn't a "right way" to proceed through the shapes and it's possible we'll hit multiple points where stopping the movement early may interfere with systematic exploration. It is also likely to highlight the edges of the tolerances we're avoiding by using the input grid. What if the shape isn't on the grid at all? I want to talk about the movement from square -> rhombus -> parallelogram, as that also sits at the boundary of mathematical "trueness" and what we allow with set tolerance.

I think we should try finding the right combination of default and shift-modified spacing before any snapping behavior.

**Comment by terracoda** [comment]
Thinking about it as "stopping the movement" is the wrong way to think about what I am referring to. The steps are discrete anyways when using the keyboard, so it's just about making sure a key press lands on 90 degrees if the key press step is passing through  88 and 92 degrees. A mouse user won't ever skip 90 degrees in the same way.

**Comment by BLFiedler** [comment]
Sure, that totally makes sense. I meant to weigh that against the certainty in spacing (and therefore length or possibly angles changes) from each keypress.

Let's chat about this at the next meeting and move the discussion to #197. There are suggestions there to further align mouse/touch and keyboard input that are relevant to what angles or shapes any user can find.

**Comment by BLFiedler** [comment]
@jessegreenberg, we can close this issue when you've merged the shape detection from dev.61 and done any necessary cleanup.

Tolerance adjustments and input grid adjustments will be handled elsewhere.

**Comment by jessegreenberg** [comment]
Very good, old shape detection functions have been removed and documentation was added. I added some references back to this issue regarding decisions.

Closing.

**Comment by jessegreenberg** [comment]
Hosting latest diagram of shape families and geometric properties for documentation:
![quad-shape-heirarchy](https://user-images.githubusercontent.com/6396244/221933377-fdc7d16e-9edb-4974-bf9a-eff72ce49af0.png)
