### ISSUE TITLE
Fade in and out of Tracks sound designs

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#189]
Discussed today during design meeting, it would be nice if the sounds would fade in and out. They are a bit abrupt currently.

Also, the play time should be extended a bit, 2 seconds is too fast.

**Comment by jessegreenberg** [comment]
The fade has been implemented with the above commits. This introduced some timing variables that we can control
- Track play time is 4 seconds.
- Fade in/out time is 1 second.

@BLFiedler @Ashton-Morris over to you to review.

**Comment by jessegreenberg** [comment]
New version to avoid phettest: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.51/phet/quadrilateral_en_phet.html

**Comment by BLFiedler** [comment]
As said in Slack. Definitely a great improvement. Will let @Ashton-Morris weigh in and otherwise close.

**Comment by Ashton-Morris** [comment]
Sounds great! I think its much more pleasant to use now.
