### ISSUE TITLE
Try icons in place of, or in addition to checkbox labels

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#190]
Suggested by @emily-phet  in a separate meeting:

Similar to the grid icon, it may make for a more cohesive PhET feel and a clearer indication of purpose if we add icons for the other checkboxes.

If possible, @jessegreenberg, can we generate these in code? Otherwise, I can get something quickly made up (better than these mockups). I would assume we try an outline style of what they accomplish rather than a full color, but also have color.

- [x] For first pass, let's replace the labels (retain voicing titles as they are). 

- [x] Corner Labels - Vertex with an A
![image](https://user-images.githubusercontent.com/47331395/184161141-ccf719c5-c2fd-4cfd-82e1-b7df5d78d823.png)
or
![image](https://user-images.githubusercontent.com/47331395/184162079-fdbb9964-60b8-41ba-949e-16b00dc834b7.png)

- [x] Corner Guides - A 90-degree or 120 degree slice of the corner guides? 
![image](https://user-images.githubusercontent.com/47331395/184160698-22ef1a29-33e0-4196-ba10-b6e2d1069126.png)
or
![image](https://user-images.githubusercontent.com/47331395/184161640-cbddc024-48e3-4961-96fb-6fb30020316d.png)
or
![image](https://user-images.githubusercontent.com/47331395/184163708-cd0e5e37-92ea-449e-b0ff-461def25bc0d.png)

- [x] Diagonal Guides
![image](https://user-images.githubusercontent.com/47331395/184164056-4174cf4a-1834-4829-a13d-42b54b70b8e3.png)

- [x] Grid - Can we just change the color of this to black for better contrast?

**Comment by jessegreenberg** [comment]
@BLFiedler sounds good!  Yes I can draw these with scenery.

**Comment by emily-phet** [comment]
Suggestions: 
- Keep them all black/white/greyscale, so they don't draw additional attention to themselves.
- For Corner Guides, I'd suggest starting with @BLFiedler's second option above.
- Diagonal Guides: I'd suggest making something just like the current grid icon, but with dashed diagonal lines (making like an extended, dashed line, letter "X")

**Comment by jessegreenberg** [comment]
New icons added. They also gave us a lot more room for the model bounds. Reassigning to @BLFiedler and @emily-phet to review.

![image](https://user-images.githubusercontent.com/6396244/184249857-21cb85ba-cab0-499d-837d-ce828cf7f696.png)

**Comment by emily-phet** [comment]
Hmm - I kind of like it, and I also kind of think it looks "flat". 

@jessegreenberg Can you try another variant adding the following words sandwiched between the checkbox and the image:
- Label 
- Corner
- Diagonals
- Grid

I'd like to get a sense of whether the addition of text (and the slight offsetting of alignment of the images that will cause) helps. If that's not a winning direction, another thought is to put the whole thing in a control panel kind of thing, but I'd prefer to avoid that.

**Comment by jessegreenberg** [comment]
Sure! Here it is with those labels and the icons center aligned:
![image](https://user-images.githubusercontent.com/6396244/184464097-80583ed7-ddd4-41e9-8607-e5b62c6bf22b.png)

Without alignment
![image](https://user-images.githubusercontent.com/6396244/184464117-1910d280-5abf-444c-8922-403e930bc09c.png)

Another thought I had was to make it look like FontAwesome "solid" icons, like this. Could use more adjustment but this shows the idea: 
![image](https://user-images.githubusercontent.com/6396244/184465355-589972dc-90ef-4d7a-87fe-fb38d58d3723.png)

**Comment by BLFiedler** [comment]
Just to note from interviews that all 4 students were able to deduce the purpose of the icons (without labels). A quick confirmatory check and uncheck was all it took. For diagonals, they either referred to it as "the lines through opposite corners" or used the term diagonals unprompted. The grid was universally called a grid.

I'm not sure how this would play with elementary students, but I don't suspect going labelless will cause significant friction. That being said, I am happy to include simple labels as well.

Jesse also tested using a music note icon for the Play Music checkbox (made in #201) in issue #200. I do think this looks nice, but also a little more attractive. I'd possibly want to move that particular control somewhere where it is less likely to be pressed just out of exploration. The text in that case may result in fewer people unchecking it and not returning?

**Comment by emily-phet** [comment]
I would recommend using the musical note icon rather than providing a text label. 
There's a little nuance here...I'd like to continue talking about the non-speech auditory display for sims in the same language we've used to date (sound, including sound effects and sonification). Music is a term we can use casually, but I think it will complicate an already muddy terminology-space to introduce its use in a formal sense. If it's been decided that the description will read out "music" that's fine (no need to circle back), but if we can try to use something like "shape sound" or something like that, I think it will cause us less headaches in the future. Auditory display is a sea of confusing and non-standardized terminology and "music" carries with it some baggage.

**Comment by emily-phet** [comment]
As far as location...perhaps a crazy idea. You could add the "music" icon to the current list of checkboxes, and place the "reset shape" button just left of the reset all button. 

Or maybe, if the checkboxes are all icons, that may be unattractive overall, and you might be able to get away with placing the reset shape button just below the list of checkboxes (with empty space between it, and the reset all button). If the reset shape button is the only colorful thing (and it's the same color as the shape), it may be the most attractive thing on the right hand side. And buttons are almost always more attractive than checkboxes, so maybe you can make it feel slightly oversized so even though it's below the checkboxes it feels slightly heavier in weighting, to result in the desired visual cueing as more important for initial exploration than the checkboxes.

**Comment by BLFiedler** [comment]
Let's go ahead and put the above changes into place:

- [ ] Move Reset Shape button right aligned with the Play Area boundary. Recolor the button to match the shape color (lighter on hover, whatever is typical here (or match the shape change less saturated color)). 
- [ ] Change Play Music to the icon. Move the checkbox below the other checkboxes, closer to the reset all button than the checkbox group (to emphasize use).

**Comment by jessegreenberg** [comment]
Done, @BLFiedler can you please review.

**Comment by BLFiedler** [comment]
@emily-phet @terracoda @jessegreenberg 

Any thoughts on overall look/ordering?

**Comment by emily-phet** [comment]
@BLFiedler - I'm having trouble accessing the latest on phettest. I updated the password, so I can get to phettest, but the sims won't run (it asks for password again, but doesn't load). Looked at latest on phet dev, but changes don't seem to be there. I'll ask about issue with password and see if I can get access. If faster is better, can you upload a screenshot?

**Comment by BLFiedler** [comment]
Mobile layout but added dev bounds so hopefully that helps!

![Screenshot_20220917-151652](https://user-images.githubusercontent.com/47331395/190873111-46b00a0c-7a66-4ed6-9ecb-4ed7be736207.png)

**Comment by emily-phet** [comment]
Thanks! 
Part of me wants to recommend the sound checkbox stay up by the reset shape button. Each relates solely to the quad shape itself. 
But, after thinking through the ordering of the description in the PDOM, having focus/description of turning the sound Off so early in the sim flow seems less than ideal. Since we want users to be able to turn the quad sound off, but not necessarily emphasize that up front, the current layout looks good to me. 

One last thought comes to mind. I don't 100% love the checkbox+icon without label option in general. It's essentially two icons together visually, the checkbox square and the feature icon. Adding a short label helps break that up visually, bringing the checkbox square more easily recognizable as a checkbox (they're usually accompanied by text). If that were still an option on the table, I think added a text label to the four feature checkboxes, and leaving the musical not as a lone unlabeled option, might help distinguish it as minimally important in the exploration, and make it look a little more like it's own grouping at the bottom there rather than just an option that is offset. (I'm fine with either option on this, just wanted to share the thought for @BLFiedler consideration).

**Comment by BLFiedler** [comment]
I agree that the music checkbox would be well suited up near the shape reset. For no-vision navigation, having it before the label/guide checkboxes would be a-okay, since they are not useful if you can't see them. Though the reset all button is still helpful (and is also last). For other circumstances, I figured having it as far away from notice as possible would be best. Let's leave it for now. Perhaps when Taliesin gets into user interviews we'll have a clear answer, and I'll note it for pre-publication sighted interviews.

>  I think added a text label to the four feature checkboxes, and leaving the musical not as a lone unlabeled option, might help distinguish it as minimally important in the exploration, and make it look a little more like it's own grouping at the bottom there rather than just an option that is offset.

I agree. We will need to make some adjustments to the overall size of the sim, since the icons bought us some more space. But, let's try and we might just end up enlarging the shape visually if things seem like they're shrinking a bit too much. We just adjusted the grid and that shrunk the shape a tad. 

@jessegreenberg, let's add labels. Can we try icon, then label? Though I'm also okay with the first image [in this comment](https://github.com/phetsims/quadrilateral/issues/190#issuecomment-1213636954) if that doesn't look great.

- [ ] Add labels to the right of the icons, shrink the play area as needed.

**Comment by jessegreenberg** [comment]
How is this?
![image](https://user-images.githubusercontent.com/6396244/191082731-59daac2f-8176-4a68-ac95-0ee07f244ecb.png)

**Comment by BLFiedler** [comment]
Ah, my bad, I did not carry through Emily's idea. 

Can you remove the Music label and keep al the other labels?

**Comment by emily-phet** [comment]
I like it! I suggest putting the labels by the checkbox. 

@BLFiedler What do you think?

**Comment by BLFiedler** [comment]
@jessegreenberg, go ahead and swap the labels and icons as you have in the first image in https://github.com/phetsims/quadrilateral/issues/190#issuecomment-1213636954. 

- [ ] Swap labels and icons for the four grouped checkboxes.

We'll make adjustment to the grid, etc in #220. Feel free to close after this is done.

**Comment by jessegreenberg** [comment]
OK, here is where we landed then: 
![image](https://user-images.githubusercontent.com/6396244/192062409-ea852640-b57d-480b-ab25-19e3ae02239a.png)

Closing!
