### ISSUE TITLE
Read-me button updates for Overview and Hint Buttons

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#192]
Latest visual design
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/1902116/184953540-7b589cc5-1981-457e-bb7f-e83df416f6ba.png">

**Please change Overview button to:**
> A quadrilateral is a closed four-sided shape. This quadrilateral is an interactive sim. It changes as you play with it. 

Four grabbable corners and four grabbable sides allow you to create different shapes and explore their properties. 

To support your exploration, show or hide shape name, and use checkboxes to add or remove labels, guides, and grid lines. A button resets the sim.

**Please change Hint button to:**
> You have {{a square}}. {{Explore what shapes you can make}}.

**Comment by terracoda** [comment]
Eventually, we will want shape name as part of Details, but lets leave that for now.

**Comment by terracoda** [comment]
@jessegreenberg, since this update in text might be an pretty easy swap, please do it before #182.

**Comment by jessegreenberg** [comment]
OK, strings have been updated. Back to @terracoda to review.

**Comment by terracoda** [comment]
For the Hint button, is it easy to quickly remove, the parallelogram and not a parallelogram parameters, and just name the shape?

**Change from:**
- You have {{a parallelogram}{{, and}} {{a square}}. Explore what shapes you can make.
- You have {{an Isosceles Trapezoid}}{{, not a parallelogram}}. Explore what shapes you can make.

**To:**
- You have {{a square}}. Explore what shapes you can make.
- You have {{an Isosceles Trapezoid}}. Explore what shapes you can make.

**Comment by jessegreenberg** [comment]
Sure, parallelogram information has been removed from the hint button content. Back to you to review and verify.

**Comment by terracoda** [comment]
Sounds good, closing issue.

**Comment by terracoda** [comment]
Re-opening:
Please update Over to include all new UI controls

> A quadrilateral is a closed four-sided shape. This quadrilateral is an interactive sim. It changes as you play with it. 
Four grabbable sides and four grabbable corners allow you to create different shapes and explore their properties. 
You have options to show shape name, mute music, add visual guides and grid lines. You can reset the shape, or reset the entire sim.

**Comment by jessegreenberg** [comment]
Done above, @terracoda back to you to review or close.

**Comment by terracoda** [comment]
The new Overview is in place. Thanks @jessegreenberg . Closing.
