### ISSUE TITLE
Add visual interaction hints 

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#195]
We should add some visual indicators to highlight what is interactable in the sim. Initial interviews had early issues identifying what could be changed in the sim. Also required explicit hints about the sides being interactable. 

Something simple that doesn't bias learners to e.g., always play with vertex A first and indicates that vertices and sides are both interactable (without just highlighting the whole shape).

I thought perhaps using the same outliens but changing the representation (box vs. arrow) might work?

![image](https://user-images.githubusercontent.com/47331395/185426586-eada33d5-454b-452c-a910-47eeb9c95ea3.png)

Can also roll with something simpler, but I am not sure I personally prefer this:

![image](https://user-images.githubusercontent.com/47331395/185427675-19ca06dd-ac76-4bd4-bf1e-a0bbd88272d2.png)

**Comment by BLFiedler** [comment]
Let's go ahead with something like the first picture with boxes around the corners and arrows for the sides. The color should not be focus-highlight-pink of course. Perhaps a bright green to differentiate from anything else in the sim. And the dashed line thickness on the order of the play area boundary or slightly thicker.

A bit more like this:

![image](https://user-images.githubusercontent.com/47331395/186493924-fbb3c31a-26b8-49dd-a326-e41118cbf347.png)

This uses RGB 21 255 127 for reference.

**Comment by jessegreenberg** [comment]
This could actually be a more complicated change depending on how we interpret
> These should disappear upon interacting with the side or vertex.

If all indicators can disappear when you interact with any side or vertex, this is a quick drawing task. If only the indicator that is clicked on disappears when you interact with a side or vertex the cuing arrows will need to rotate and reposition with the side.

@BLFiedler can you please clarify which one it needs to be?

**Comment by BLFiedler** [comment]
Oops - yes I meant **everything** should disappear when _any_ side or vertex is pressed!

**Comment by jessegreenberg** [comment]
Visual interaction cues added. Back to you to review @BLFiedler.

**Comment by BLFiedler** [comment]
Great! Tossed it out on slack for any quick thoughts from folks.

**Comment by jbphet** [comment]
We have a bit of a de facto standard for what we generally call "cueing arrow" (or sometimes "cuing arrows").  I'll paste some examples below.  This style might be a bit too much for this particular sim, but I thought I'd point out some previous examples in case you want to me more consistent with previous sims, and possibly leverage their implementations.

From the Greenhouse Effect flux sensor:

![image](https://user-images.githubusercontent.com/3082831/187513344-68e76915-cfa9-4aee-a2f0-7f5d61fb1950.png)

From Blackbody Spectrum:

![image](https://user-images.githubusercontent.com/3082831/187513549-b03dca9b-51c7-4355-a251-4dda26cca6bb.png)

From Geometric Optics:

![image](https://user-images.githubusercontent.com/3082831/187513801-8dc0bb4d-c6cb-4fec-af42-ba4cb14c4253.png)

From Projectile Motion:

![image](https://user-images.githubusercontent.com/3082831/187513963-a722f705-0714-43c3-83ca-b7b577e420b6.png)

**Comment by jbphet** [comment]
Two other notes:

- I noticed that the cursor doesn't change when hovering over the draggable element in Quadrilateral.  Usually we have it change to a pointy finger in a case where it can be dragged in multiple directions.  This is another clue to the user that the element is draggable.
- If you end up just going with the single arrow as showing in the example at the top of this issue, I personally would prefer to see it point the other direction.

**Comment by BLFiedler** [comment]
Thanks, JB! I see the issue with using the arrows. I had intended to just draw notice to them and not indicate a direction of movement which the arrows typically do for the above examples. The 8 interactable sides/vertices can move in any direction. I'm not sure even a 4-way arrow would accomplish that neutral bias for selecting a side or vertex.

Perhaps something a bit simpler and just borrowing the shape of the interactable bit?:

![Image](https://user-images.githubusercontent.com/47331395/187742503-e497b3c9-9e6e-40e8-8751-82c3cd2090b6.png)

> I noticed that the cursor doesn't change when hovering over the draggable element in Quadrilateral. Usually we have it change to a pointy finger in a case where it can be dragged in multiple directions. This is another clue to the user that the element is draggable.

Also, great catch on the cursor change. Can we add that in, @jessegreenberg?

**Comment by jessegreenberg** [comment]
Yep, thanks! Cursors set.

**Comment by BLFiedler** [comment]
Cursor change definitely feels informative!

@jessegreenberg, let's go ahead and modify the visual interaction hints to reflect changes made in the comment above https://github.com/phetsims/quadrilateral/issues/195#issuecomment-1233229188. I do have reservations about the implications of using an arrow.

- [ ] Change vertex hint box to a circle, slightly larger than the vertex itself.
- [ ] Change the side "arrows" to rectangular boxes that cover "most" of the length and a width to match the vertex hint circle.

**Comment by terracoda** [comment]
I agree, I think the arrows might be problematic, as they only cue one-way. I like @BLFiedler 's change in [comment](https://github.com/phetsims/quadrilateral/issues/195#issuecomment-1233229188)

**Comment by jessegreenberg** [comment]
OK, shapes changed in the following commit. Back to @BLFiedler to review.

**Comment by BLFiedler** [comment]
Great! I think this will serve for now. We'll see how any later interviews go prior to publication.

**Comment by BLFiedler** [comment]
Quickly reopening based on what I saw from Scott's tangible use.

Can we disable these visual interaction hints when our tangible is connected? Probably when using OpenCV as well.

We could tie it to the query parameters? Camera input hands will be published with a query parameter. That is dependent on the load of a lot of extra data though, which I believe drove that decision.

Or do we still have a flag for the tangible/marker input driving connection that we can use to hide the green outlines?

**Comment by jessegreenberg** [comment]
Yes, there is a `connectedToDeviceProperty` in the model. When there is a successful device connection we can make these disappear. I just set the Property in the bluetooth connection. The Property can be set in other prototypes when we return to them but I do not have a way to test them now.

I built this change into a a new dev version (65) and shared the link with Scott.

**Comment by terracoda** [comment]
Here's latest visual interaction hints.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/1902116/195887370-1cd6523f-8e16-442e-855b-0eff57ba3bfa.png">

They disappear on focus. Is that intentional? 
In John Travoltage (and some other sims), the visual hints disappear after successful movement.

**Comment by terracoda** [comment]
And when clicking, only one of the two hints disappears. If you click on the Leg Swing, the Arm Swing hint remains until you click on the Arm Swing.

I think we could consider doing the same for the corners and sides.

**Comment by BLFiedler** [comment]
Keeping the visual interaction hints when the shape is changing requires additional code to draw,rotate, scale the hints which is more work than we currently have for publication. For now, resetting the sim to see the hints will suffice.
