### ISSUE TITLE
Consider re-ordering interactive corners and sides

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#196]
In recent session with consultant, it was suggested that the interactive shape components follow directly from Left to Right rather than be grouped as 4 corners then 4 sides.

I am suggesting we try the following Tab Order for the interactive shape components.

- Corner A
- Side AB
- Corner B
- Side BC
- Corner C
- Side CD
- Corner D
- Side DA

**Comment by jessegreenberg** [comment]
Traversal order has been updated. @terracoda back to you to review/confirm.

**Comment by terracoda** [comment]
Awesome! Closing.

**Comment by terracoda** [comment]
@jessegreenberg, re-opening as moving a corner complicates the shape early on, and @BLFiedler and I discussed that it might be nice to see what happens if a learner plays with a side before playing with corners.

Can you change the tab order again to be:

- Side AB
- Corner B
- Side BC
- Corner C
- Side CD
- Corner D
- Side DA
- Corner A

**Comment by terracoda** [comment]
Sorry, I forgot to assign you @jessegreenberg.

**Comment by jessegreenberg** [comment]
OK, changed to the above order. It feels a little strange to me to end on VertexA. @terracoda @BLFiedler over to you to review.

**Comment by terracoda** [comment]
I agree, but I thought this would be weirder:
- Side AB
- Corner A
- Corner B
- Side BC
- Corner C
- Side CD
- Corner D
- Side DA

**Comment by jessegreenberg** [comment]
Yes agreed. What do you think about having all sides first and then all vertices?

**Comment by BLFiedler** [comment]
Initially I think the alternating approach was aimed to address @terracoda's comment here: https://github.com/phetsims/quadrilateral/issues/196#issue-1343267399

Is it less strange to start on side DA and then go to A next?

**Comment by terracoda** [comment]
Yes, with consecutive ordering starting with a side is a little trickier than I first thought.

We could try @BLFiedler suggestion and  start with Side DA. 

It is the left side, and we are describing things from left to right.

@jessegreenberg, let's try that instead.

**Comment by terracoda** [comment]
And I agree, ending with A seems a bit weird.

**Comment by jessegreenberg** [comment]
OK! Ending on vertex D feels a bit better to me, @terracoda @BLFiedler this seem OK?

**Comment by BLFiedler** [comment]
If there's some orientation in the overview indicating there's a shape with corners A,B,C,D, then I think this is okay!

I think it's likely someone questions us on why it is that way or recommends it be Corner A first, but we are trying to scaffold something in particular, so we need to be careful about those kinds of suggestions. But maybe the outcome is more attention to the sides, which could be good (and very TMQ-like)

**Comment by terracoda** [comment]
I agree @BLFiedler. Alternating the corners and sides was suggested by a consultant, and then starting with a side was my idea since the Tab order should start with what we want them to start with.  

The Overview does describe four movable sides and corners without naming them. I drafted some new overviews on Monday. I'll return to that again after focusing on the object and context responses a bit more.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for changing the order again. The Tab order is as requested. Hopefully, this will hold with some good scaffolding in the overview/details of the state descriptions.

Verified and closing for now.
