### ISSUE TITLE
Add reset shape control

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#200]
After interviews, and through our own exploration, we'd like to add a button distinct from the Reset All button that only resets the shape to a square without undoing the checkboxes, turning off Voicing, or anything else.

I believe functionally this will just force move the vertices to their original position without changing anything else in the sim.

Let's go with something similar to the button that appears in Molecules and Light when a molecule goes off screen

![image](https://user-images.githubusercontent.com/47331395/186435858-0f71ccfd-e524-4a10-b4b5-77edc90054c5.png)

- [ ] Make a button, "Reset Shape", in the top right, about the height of the shape name display and top aligned with it.  Left align with checkboxes below.

Something like this:
![image](https://user-images.githubusercontent.com/47331395/186436312-62ded4f9-e86f-4c79-9f54-9e3652570640.png)

**Comment by jessegreenberg** [comment]
Happy 200 issues! 🎉 

This looks fine but PhET also has ResetButton that is sometimes used for portions of the screen, do you have  a preference between this iconic button and the text button?

![image](https://user-images.githubusercontent.com/6396244/186440877-02034fa6-6f75-4371-a527-d49075c59aa6.png)

(Proportion Playground)

**Comment by BLFiedler** [comment]
Hmmm. I see the use in Proportion Playground and I think once you play with the sim you have a pretty clear idea of what that button is intended to do. It also resets multiple components on the screen at once. 

It's a little less clear to me that folks will know that button only applies to the shape and nothing else.

I may defer to @terracoda and @emily-phet here.

**Comment by emily-phet** [comment]
It looks like Proportion Playground uses the same shape and circular arrow to cue it's behavior is similar to "Reset All". BASE takes a different approach, using the color orange to cue it's related to "Reset All", and spells out "Reset Balloon". 

If we're still able to generate all instances of a particular component in Binder, looking through all the regular push buttons (not sure what the technical name for that component is...but Jesse would know) you might find some other examples.

**Comment by jessegreenberg** [comment]
I couldn't find visual ResetButton examples in binder. I found this list but I think it is including all sims because ResetAllButton extends ResetButton https://phetsims.github.io/binder/#components (ResetButton is the second component in the list)

A search for `new ResetButton` shows
unit-rates
expression-exchange
models-of-the-hydrogen-atom
number-line-integers
proportion-playground
scenery-phet

**Comment by BLFiedler** [comment]
After perusing the different ways displays are reset (![image](https://user-images.githubusercontent.com/47331395/186688258-db6b68df-bb48-4ea6-977b-1bf483b42b49.png)), refreshed (![image](https://user-images.githubusercontent.com/47331395/186688194-84d83573-16ff-4fb6-be03-babefd9b2f54.png)), and restarted (![image](https://user-images.githubusercontent.com/47331395/186688499-e4629336-5faf-4e2a-9037-737e880ab8ff.png)), I think the clearest option is still to use a button with the label "Reset Shape". 

How those other buttons are used across other sims does not quite match what is happening here (no randomization or restarting of movement) and while I think the Reset button used in Proportion Playground could work if we were able to put it closer to the shape itself.

Another option though, since there doesn't appear to be any standards here, is to customize a bit further and continue forgoing words where possible. Mocked up a few possibilities that lean into the default square shape.

![image](https://user-images.githubusercontent.com/47331395/186700681-0ffd38dc-89e5-40a8-88c3-5a08da110402.png)

Also, again, this will need description before closing the issue.

**Comment by jessegreenberg** [comment]
Sounds good, added controls in the above commit as requested. Ready for review on phettest.

Just playing around with a slightly different layout and colors that I though also looked nice:
- Use the default "PhET blue" for the button (I find the orange harsh, especially against the red ExpandCollapseButton)
- Aligns controls along the play area
- Default sizing for the TextPushButton
- Icon for the "music" checkbox

![image](https://user-images.githubusercontent.com/6396244/186778743-c1a25f06-3047-4c9b-85f9-fc4e3fae7a14.png)

**Comment by BLFiedler** [comment]
Agreed on the harshness of the orange. I like the changes you made! I was pondering an icon for the music and really glad you tried it out.

The text button stands out a bit in this case still. Might consider going all icon or going the hybrid approach suggested in #190

**Comment by terracoda** [comment]
As for description...

**{{Reset Shape}}, button**
Accessible Name (label text): Reset Shape
Interaction Type: push button or reset button
Help Text choices: 
- Reset Shape to the starting square.
- Reset shape to starting angles and side lengths.
- Reset Shape to start again.
- Reset corners and sides to starting shape.
- Explore again, starting from a square!
- or have no help text

**Context response on reset:** 
**_If shape name shown:_** 
  - Your shape is a square.
  - Other possible ideas when shape is hidden:
      - You have a square!
      - You found a square!
      - You have a square! Explore shape again. (only if no help text)
      - Explore shape again from starting square.

**_If shape name not shown:_** 
- Your shape has all equal sides and all right angles.
- Other possible ideas when shape is hidden:
    - All right angles and all sides equal.
    - Angles and sides reset. (might be too vague for non-visual users)
 
Design Note: The special thing is we might need 2 unique context responses to account for in shape name is show or not.

**Comment by terracoda** [comment]
To Start @jessegreenberg, I would go with this:

**{{Reset Shape}}, button**
Accessible Name (label text): Reset Shape
Interaction Type: push button / reset button
Help Text: none

**Context response on reset:** 
**_If shape name shown:_** 
  - Angles and sides reset to a square.

**_If shape name not shown:_** 
- Shape has all right angles and all sides equal.

**Comment by terracoda** [comment]
@jessegreenberg, assigning description to you.

**Comment by terracoda** [comment]
The above design pattern fits more with Interactive Description. But if the name response is include
- Name Response: Reset Shape
- no Object Response
- Context Responses:
  - when shape is shown:  You have a square! (Will hear: Reset Shape, You have a square!)
  - when shape is hidden: All right angles and all sides equal. (Will hear: Reset Shape, All right angles and all sides equal.)

**Comment by terracoda** [comment]
Please ignore brainstorm and initial design in comments https://github.com/phetsims/quadrilateral/issues/200#issuecomment-1228746723 and https://github.com/phetsims/quadrilateral/issues/200#issuecomment-1228752048

**Comment by jessegreenberg** [comment]
Voicing responses for the reset shape button added. Back to @terracoda to verify.

**Comment by emily-phet** [comment]
Suggestion - make the "reset shape" button the same yellow as the quad, to tie them together and to avoid introducing a new color into the sim. (more colors = more problems :)

**Comment by terracoda** [comment]
@jessegreenberg, the Reset Shape button, does reset the name of the shape being voiced - same issue as I mentioned in #183

**Comment by terracoda** [comment]
If we were to use an iconic button, I think the square in the button would have to look similar to the starting square.
Very rough sketch: 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/1902116/187246607-3275e811-bacc-447e-9e49-3e0d5355fd20.png">

**Comment by terracoda** [comment]
A yellow button with the words "Reset Shape" works for me, though.

**Comment by terracoda** [comment]
@jessegreenberg the voiced context responses are working properly. If shape name is hidden, I hear "Reset Shape" + "All right angles and all sides equal." when shape name is not shown.

**Comment by terracoda** [comment]
The Voicing of the Reset Shape button is working fine.

@BLFiedler  do you like Emily's suggestion in https://github.com/phetsims/quadrilateral/issues/200#issuecomment-1229773115 - make the button the same color of the quad?

Maybe we need 2 colors - one for the button and then one for hover/focus?

**Comment by BLFiedler** [comment]
I think we're good here and will continue discussion about button appearance and placement as a whole in #190
