### ISSUE TITLE
Add checkbox to toggle the shape music

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#201]
From comments during the interviews and our own discussions during design meetings, we foresee the need for an on-screen toggle to disable the music that plays as a shape is transformed. Something like a "Play Music" checkbox. The intention is to retain any other sounds (UI or sounds we intend to add for play area collision/vertex-side collisions) when the music is disabled. We'll have the music enabled by default (box checked).

This will likely behave similarly to the sound checkboxes in [Waves:Intro](https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro_en.html). When the audio toggle ![image](https://user-images.githubusercontent.com/47331395/186441025-35a71d0c-2fe9-4c2e-848a-3b01bc90d7b5.png) on the navbar is pressed to mute sound, we'll need the checkbox to disable: ![image](https://user-images.githubusercontent.com/47331395/186440959-979770a4-5c2e-43ac-b28c-1e2fabd06517.png)

- [ ] Make a checkbox, "Play Music", that disables only the shape detection sound design when unchecked. Place the checkbox below and left aligned with the button being added in issue #200. Disable the checkbox when the audio toggle is muted.

**Comment by BLFiedler** [comment]
Noting that this will need description after implementation @terracoda

**Comment by jessegreenberg** [comment]
Done, functionality added (without Voicing for now). I proposed a different layout and icon though in #200, related to this issue.

**Comment by BLFiedler** [comment]
Great! I'll leave the discussion of text vs icon to issue #190
