### ISSUE TITLE
Description for Play Music Checkbox

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#203]
Coming very soon.

**Comment by terracoda** [comment]
![image](https://user-images.githubusercontent.com/1902116/186968327-c5dcac53-3f74-4e6f-a779-38677a7d83f5.png)

"Shape Music" or just "Music" might work better than "Play Music" since the checkbox is checked by default, and checkboxes with verbs are a bit difficult for Voicing since we hear the name response and the context response together.

For Voicing I propose starting with just "Music":
- Name Response: Music
- Object Response: none
- Context Respones:
    - When Unchecking: Name Response + "Off for shape changes." 
    - When checking: Name Response + "On for shape changes." 

Note that the control type and accessible name could influence the context response for this interaction.

@BLFiedler, we might also want to consider an iconic toggle button.

@jessegreenberg, I think we canroll with the above for tomorrow.

**Comment by jessegreenberg** [comment]
Voicing response for the music control added, @terracoda over to you to verify.

**Comment by terracoda** [comment]
This is implemented as I intended, and sounds good. Thanks @jessegreenberg.

@BLFiedler, since the visual plan is leaning towards using an icon, do you have a preference for the Name Response between "Music" or "Shape Music"?

Another possibility that could work is "Shape Melody". If you like this better, I would add "Music" to the context responses. For example, like this:
    
- Name Response: Shape Melody
- Object Response: none
- Context Responses:
    - When Unchecking: Name Response + "Music off for shape changes."
    - When checking: Name Response + "Music on for shape changes."

Assigning to @BLFiedler for your preference.

**Comment by BLFiedler** [comment]
@emily-phet mentioned a good point in keeping the number of words we use for auditory display to a minimum in https://github.com/phetsims/quadrilateral/issues/190#issuecomment-1229777148. 

We could keep to "Shape Sound" if that works for you @terracoda, which I believe you brought up at one point.

And then for context responses, replace Music with Sound?

**Comment by terracoda** [comment]
Yes, that should work:
- Name Response: Shape Sound
- Object Response: none
- Context Responses:
    - When Unchecking: Name Response + "Off for shape changes."
    - When checking: Name Response + "On for shape changes."

**Comment by terracoda** [comment]
Forgot to assign you @jessegreenberg.

Let me know if this is clear to implement. I am assuming you don't need this mapped out by input method.
For mouse we hear Name Response & Context Response
For Keyboard we hear Name Response on focus, the Name & Context Response on checking and unchecking the checkbox.

**Comment by terracoda** [comment]
And, the music icon implementation is happening over in #190

**Comment by jessegreenberg** [comment]
OK, name response for this control has been updated, @terracoda anything else for this issue?

**Comment by terracoda** [comment]
This sounds good now.
Thanks!
