### ISSUE TITLE
New traversal order including music and reset shape controls

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#204]
These new controls need to be placed in the traversal order. Should be
> quadrilateral shape -> shape name display -> reset shape and music checkbox -> visbiility controls -> reset all button

**Comment by jessegreenberg** [comment]
REquired for a user interview that will happen tomorrow.

**Comment by terracoda** [comment]
Yes, that order is good @jessegreenberg

**Comment by jessegreenberg** [comment]
Great, thanks @terracoda. Updated in the above commit.
