### ISSUE TITLE
Consider different region name for "comparable"

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#205]
We use comparable to describe corners and side length that are similar or almost the same. I need a different word. Or one less size/length region.

**Comment by BLFiedler** [comment]
Random off the top of the head list:

"almost equal"
"nearly equal"
"slightly different"
"close to equal"
"almost the same"
"not quite equal"

**Comment by terracoda** [comment]
@jessegreenberg , can you change "comparable to" to:
- "almost equal to"

**Comment by jessegreenberg** [comment]
Done in the above commit, @terracoda over to you to close or verify.

**Comment by terracoda** [comment]
I hear ""almost equal to"! Thanks @jessegreenberg. Closing.
