### ISSUE TITLE
Add Interactive Highlighting to this sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#207]
In design meeting today we remembered this feature and decided we want it active in this sim.

**Comment by jessegreenberg** [comment]
Added in the above commit. Almost working but I noticed that highlights surrounding sides don't update until release. Ill investigate.

**Comment by terracoda** [comment]
This is really nice to have :-)

**Comment by jessegreenberg** [comment]
There was a bug in scenery that didn't update the highlight for "Interactive Highlights" when it fell back to the default focus highlight. It should be fixed in the above commit.

@terracoda can you please review interactive highlights in this sim to confirm that feature is working OK?

**Comment by terracoda** [comment]
Interactive highlights are working well. Closing.
