### ISSUE TITLE
Consider how we could voice a grid in the absence of tangible or haptic display 

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#208]
We may need to find a way to voice the grid to support non-visual access when only the virtual experience is available.

Ideally, the Voicing feature would be paired with either a tangle device or some kind of tangible haptic display.

When those supports are not available, are there easy ways to describe the shape or grid to make it more understandable who someone who cannot see the screen?

**Comment by BLFiedler** [comment]
@terracoda and I discussed the possibility of using an ABC, 123 style grid for the major gridlines.

@terracoda, do we want to go ahead with this? Do you know where this information would live?
