### ISSUE TITLE
Enumerations with equal key names confuse PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/quadrilateral#209]
In https://github.com/phetsims/phet-core/issues/99 we saw that PhET-iO is confused because of these similarly structured Enumerations:

```
class QuartetSoundFile extends EnumerationValue {
  public static ONE = new QuartetSoundFile();
  public static TWO = new QuartetSoundFile();
  public static THREE = new QuartetSoundFile();
  public static FOUR = new QuartetSoundFile();

  // gets a list of keys, values and mapping between them for EnumerationProperty and PhET-iO
  public static enumeration = new Enumeration( QuartetSoundFile );
}

class SuccessSoundFile extends EnumerationValue {
  public static ONE = new SuccessSoundFile();
  public static TWO = new SuccessSoundFile();
  public static THREE = new SuccessSoundFile();
  public static FOUR = new SuccessSoundFile();

  // gets a list of keys, values and mapping between them for EnumerationProperty and PhET-iO
  public static enumeration = new Enumeration( SuccessSoundFile );
}
```

PhET-iO builds EnumerationIO keys based on the strings, so does not currently support these.  I wonder if this would be a good candidate for using string literal unions?

I'll commit a workaround for the moment, then reassign to @jessegreenberg for a longer term solution.

**Comment by samreid** [comment]
I added a very hackish workaround in the commit.  Would be good to discuss with @jessegreenberg.  Other possible solutions to consider:

* String literal union (my top pick, unless we are planning to need rich features)
* Different key names
* Change PhET-iO to support different enumerations with the same keys (non-trivial, but may be best if this kind of problem happens over and over.  Right now, this was one of 2 known cases.).

**Comment by jessegreenberg** [comment]
Thanks @samreid, I renamed the keys in the above commit.

> String literal union

I have been preferring `Enumeration` because I like having one pattern that works for all enumerations. I have also found IDE support for string literal unions to be worse.

> Change PhET-iO to support different enumerations with the same keys

This whole class is for development/prototyping so no need for this case to sway the decision IMO.

@samreid this look OK or would you like to discuss further?

**Comment by samreid** [comment]
Sounds good.  I think it should be developer preference to choose between string literal union vs Enumeration.  The changes look good.  Sorry about the PhET-iO constraint on key names, if it gets more severe we can work on relaxing that constraint in phet-io.  Closing.
