### ISSUE TITLE
Add back a debugging grid

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#211]
Would be nice to display a visual grid that shows the `majorVertexInterval` and `minorVerticalInterval` that constrain vertex positions when moving them. Probably available by query param.

**Comment by jessegreenberg** [comment]
Added in the above commit. Query parameter to use this is `?showVertexGrid`. It is only shown if the normal grid is enabled with the checkbox.

Of course with current defaults it is difficult to see spacings unless zoomed in.
![image](https://user-images.githubusercontent.com/6396244/188707864-0199a658-7359-4542-bf80-72ee6891a1ce.png)

But will probably be more useful as the intervals get larger.

@BLFiedler @terracoda is this what you had in mind? Any recommendations? Is the query parameter name OK or colors need changing?

**Comment by terracoda** [comment]
Thank you for this!
