### ISSUE TITLE
Concern for Rhombus and side length changes

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#212]
@BLFiedler, mentioned this issue in today's design meeting.

We have a tolerance for side length that allows a learner to go directly from a square to a rhombus by moving a side 1 step.

Currently, the object response describes and side length change that would rule out a rhombus, "Adjacent sides longer".

Changes to object responses are in the works. I'll see how to deal with this contradiction.

**Comment by BLFiedler** [comment]
This one is going to be a struggle. The magnitude of the length AND angle change actually does depend on the length of the sides (longer side length, smaller angle change with a single increment to the left/right). Quick illustration using GeoGebra:

![image](https://user-images.githubusercontent.com/47331395/189178410-70e04bd2-d22d-4589-9dfb-0b9d405c02b6.png)

Long green line with one step to the right and short red line with same single grid step to the right. You can see a significant difference in the angle and length differences in the green segments and between the red segments.

I'll have to see how small the tolerances can be or think of some scaling...

**Comment by BLFiedler** [comment]
And I know I've been a bit vocal about the need for fairly small tolerances, to the point where it may seem like we don't need them at all, but we do need them for any rotated shape. Since we're operating on a 2D grid, regardless of how fine or coarse it is, we're stuck in a place where reaching particular sets of angles/side lengths just aren't possible. Take for example, the GeoGebra environment which too has a grid, though it is much finer than ours. Created a rotated quad and try to make a rectangle (i.e., all right angles). You'll find it very difficult, as I did. It's a bit easier with larger shapes (for the reasons stated above). This was the closest I could get for a shape I was manipulating:

![image](https://user-images.githubusercontent.com/47331395/189184003-0292dc69-1828-4975-934e-c01fce429d61.png)

and a larger shape

![image](https://user-images.githubusercontent.com/47331395/189184034-5c89388f-ed70-4e6e-af14-ee847024668f.png)

**Comment by BLFiedler** [comment]
Tagging @jessegreenberg for awareness of the above limitations

**Comment by terracoda** [comment]
I agree, the shape rotation complicates things and tolerances are needed.
Today when I tested, and went from Square to Rhombus, I hear "All sides equal" with the shift-key step, and "Adjacent sides longer" with the default step size, and in both cases I have a rhombus, so I think we need to make sure the Adjacent sides longer" response is not being constrained by or not following the same tolerances as the shape-detection.

I'm sure this is fixable, and I am currently reviewing responses, so maybe some simple adjustments to when these responses fire will solve this issue.

And maybe we won't need some of the responses or at least not as often.

**Comment by BLFiedler** [comment]
The changes in #197 result in the following behavior: Default (and potentially larger) keypresses on a side transition the default shape from Square -> Parallelogram. Using the Fine Input Spacing checkbox in the Preferences menu (when implemented), will allow this. This should be fine for fine spacing. The shape change necessary to maintain a rhombus is not linear and a slight movement laterally is not an egregious misalignment with mathematical expectations.

Some doodling below to try to help with the above explanation:

![image](https://user-images.githubusercontent.com/47331395/190203581-46959dbd-5ff2-473e-847b-252c85c204d6.png)

**Comment by BLFiedler** [comment]
How does that sound @terracoda? I know we'll want to see how this sounds compared to description before closing the issue, just in case we need to intervene with what the shape says. It might be too small of a change to trigger a length change description?

**Comment by terracoda** [comment]
Here's two screen shot from the latest version. We don't have the Precision mode available yet.

Initial transitioning responses:
- Object: "Adjacent sides longer."
- Context: "Found a Parallelogram." 
Can we make the Show Values Parameter always display to the 100th decimal point?
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1902116/190430940-5aec02ac-74a8-43f4-af8a-a4a27753265f.png">

<img width="846" alt="image" src="https://user-images.githubusercontent.com/1902116/190430712-0d906073-b5c6-4bc5-833f-724cabf07db0.png">

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1902116/190431213-69dbc011-61ee-4e57-8879-02d80a07bdcc.png">

When the shape get a little bigger you can find a Rhombus.
If you move into it by tilting and not changing side-length you hear:
- Object: "right"
- Context: "Found a Rhombus." 

If you move into it by changing side length (shape was already tilted in a previous step) you hear:
- Object: "Adjacent sides longer."
- Context: "Found a Rhombus." 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/1902116/190431361-85eca677-d3b8-40bb-84b9-c7e97387a0b1.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1902116/190431700-c995af08-52bb-43f0-a43f-2fadbb54b43b.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/1902116/190430532-aa542602-4062-4b64-bae3-b40b6f68332d.png">

The voiced descriptions are voicing the same information that appears on the screen, so the visual & described information is in synch. 

My question is, what is happening in the first 3 screen shots and the one below where the side lengths look equal and appear equal in the model values, but the shape is beign defined as a Parallelogram?

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1902116/190439160-0bab047e-6b50-444a-8948-9e78b45938cd.png">

**Comment by terracoda** [comment]
I looked around for a square and then was able to make a rhombus again. Notice the same side lengths as above.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/1902116/190442558-a9a78040-11bd-4fe3-92c5-49fb776aeada.png">

**Comment by BLFiedler** [comment]
> When the shape gets a little bigger you can find a Rhombus.
If you move into it by tilting and not changing side-length you hear:

> My question is, what is happening in the first 3 screen shots and the one below where the side lengths look equal and appear equal in the model values, but the shape is being defined as a Parallelogram?

You'll want to drag the Decimal Places slider in the showModelValues panel to at least 4 decimal places to see that.

Regarding finding rhombus at larger shapes. Yup. That will happen for the reason stated in the comment above: https://github.com/phetsims/quadrilateral/issues/212#issuecomment-1240961669 . Longer sides = smaller length/angle changes for identical displacement intervals.

We can try to limit it further. We're just likely to find even fewer rhombus from the "square orientation". From our largest possible square, reducing shapeLengthToleranceInterval to 0.0005 ( 😮 ) skips the Rhombus from Square. This is likely to affect kites in some way as well.

Regardless, I am finding any "rotated shape" to be rather unpleasant for certain shapes with these tolerances. Finding a rectangle is quite difficult. when not aligned to the visual grid.

Maybe the Rhombus behavior is just best suited to exist as a note in the model assumptions. Going to chat with Jesse about some work in #210, #214, and #197 and afterward see if we can find some good compromise for the tolerance values that keeps this behavior to a minimum but helps find rotated rectangles, kites, isosceles traps, etc.

**Comment by terracoda** [comment]
I think my concerns for Rhombus have been resolved :-)

**Comment by BLFiedler** [comment]
Note to check this issue after changes to tolerance incoming in #197

**Comment by terracoda** [comment]
In current master, I can get directional object responses (i.e., no side length change) when I go from Rhombus to Parallelogram. This seems odd, and might be resolved once #197 is finalized.

**Comment by terracoda** [comment]
No, but I am now getting adjacent sides longer when I go from Square to Rhombus and Rhombus to Rhombus (sigh).
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1902116/196560696-2b3c8ce6-d4a5-43f2-97dc-a25402645ced.png">

**Comment by terracoda** [comment]
Just an FYI, for this Rhombus-Square transition on first key press I get "right, Found a Rhombus!", and 
<img width="799" alt="image" src="https://user-images.githubusercontent.com/1902116/196713897-149e82a0-6eab-42b2-99ed-4043df75833c.png">
then on the next key press I get "adjacent sides longer", with no shape transition to a parallelogram.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1902116/196714282-bf8991ce-85ab-459b-9bd9-a3c595c28864.png">
On the third key press right, I correctly get "adjacent sides longer" and correctly get a transition to a parallelogram
<img width="803" alt="image" src="https://user-images.githubusercontent.com/1902116/196714576-0ee8217e-5e79-407d-b606-779714cab349.png">

**Comment by terracoda** [comment]
The above example is from https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.67/phet/quadrilateral_en_phet.html?showModelValues with regular input steps (i.e., Fine input spacing is not checked).

**Comment by BLFiedler** [comment]
Can you try 

https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.67/phet/quadrilateral_en_phet.html?showModelValues&shapeLengthToleranceInterval=0.005

I realize that what was implemented was not what I was testing. I believe I mistyped 0.01 for 0.005 when I asked Jesse to change them. That way only 1 key press should net you a rhombus for the starting shape, which was my initial aim.

**Comment by terracoda** [comment]
I hear "adjacent sides longer" when I go from home square to rhombus.

With a bigger square (e.g. 6x6) I hear "right, Found Rhombus!" on the first step right and then "adjacent sides longer" with no voicing AND no change in shape name.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1902116/197571203-9c62676a-2ddf-406a-8889-2aeb34874b13.png">

So basically, we **still have an issue for keyboard users**, and we'll need to find some way to only hear directional object responses when the changes in side-length or angle-width do not result in visual changes in a shape.

I am not sure if a better solution would be to increase the tolerance for the when the directional responses might fire?
The shape name & shape property context responses only fire once, and the shape maintenance responses only happen occasionally.

AND, currently, this is not an issue for mouse/touch input as the moving object responses only happen with keyboard.

**Comment by terracoda** [comment]
Would it help to check the units? It the above screen shot. The sides are all still six units, so nothing actually got longer according the description of the side units.

When the shape visually becomes a Parallelogram, Side BC becomes "just over 6 units". That sounds really good.

I think the bug is with the object response. 

Perhaps the object response is not seeing/using the same length tolerance or angle tolerance as the visual display and context responses.

**Comment by terracoda** [comment]
@BLFiedler, please when you have a chance. Do you agree that this might be an object response issue?

**Comment by BLFiedler** [comment]
I do suspect this is an inconsistency between the shape detection and object response generation. The shape detection model considers all the sides to still be the same length.

Next meeting we'll need to look at where description is using its own metrics for change vs. the shape detection model.

**Comment by terracoda** [comment]
OK, sounds good. I will mark this as a meeting item.

**Comment by BLFiedler** [comment]
To address the inconsistencies here, we decided in today's design meeting:

- [ ] Update default `shapeLengthToleranceInterval` = 0.005
- [ ] Update the object response adjacent side tolerances to match `shapeLengthToleranceInterval`

There is some discussion about changing how to trigger "adjacent sides longer" when moving a side to compare to the initial side lengths and wait for them to exceed the tolerance instead of each keypress but that will happen elsewhere.
