### ISSUE TITLE
Detect a triangle when any angle is exactly equal to 180

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#215]

**Comment by terracoda** [comment]
I think is issue us related to #236 , where i suggest a special response that questions the number of sides for the shape.

**Comment by BLFiedler** [comment]
Yes, it is. I think we should go ahead with the Triangle easter egg. We should have a quick chat about any visual changes that may happen to de-emphasize the "4th point"

**Comment by BLFiedler** [comment]
- [ ] Detect triangle when any angle is equal to 180 (pi radians). Place above Kite in detection. Possibly above concave/convex?
- [ ] Show "Triangle?" in the shape name box.

**Comment by jessegreenberg** [comment]
OK, Triangle has been added as requested. A couple of questions.
- @BLFiedler What sound tracks in each sound design should play when a triangle is detected? For no sound plays when we have a triangle.
- @terracoda When you find a triangle and shape names are shown you will now hear the same shape detection context response "Found a triangle." Is that correct?
- @terracoda What should the context response be when shape names are hidden and you find a triangle? For now I have a placeholder response that should be easy to find
  - "Hello Taliesin! How would you like to describe finding a triangle when shape name is hidden?"

**Comment by terracoda** [comment]
I think I put my design ideas for the strings over in #236 . I'll see if I can update some of the strings.

**Comment by BLFiedler** [comment]
Remaining items pertaining to the Triangle and description are happening in #236. Closing this one.
