### ISSUE TITLE
Should vertex labels be translatable?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#218]
@BLFiedler do you have any thoughts on whether the vertex labels should be translatable?

![image](https://user-images.githubusercontent.com/6396244/190237750-7753c1bd-1dbb-452c-8b81-e2c02334671a.png)

I assumed they should be but it seems maybe this kind of marking should not be? I am not sure.

**Comment by terracoda** [comment]
How do variable letters work in Math sims?

**Comment by BLFiedler** [comment]
Reached out in Slack and received the following from Amy:

> Brett Fiedler
> We're currently using ABCD as labels for the vertices in Quadrilateral and are trying to determine if the labels should be translatable or if they are symbolic enough in nature. This would be relevant for non-Latin alphabets. I know that there isn't a direct translation for e.g., A into every other alphabet.
Have we handled this before in another sim? Is it best to leave it as symbolic and untranslatable or make them translatable and let the translators make the call?

> Amy Rouinfar
> There is precedent for allowing translation these sorts of labels. For example, the A, B, C atom labels in Molecule Polarity. It’s up to the translator whether or not to localize these labels, but it seems like many choose to keep A, B, C. (Including locales with non-Latin alphabets.) (edited)

**Comment by BLFiedler** [comment]
Based on that, I'd say we should go ahead and let them be translatable and let the translators decide for their locale.

Over to you, @jessegreenberg

**Comment by terracoda** [comment]
I would like to add one consideration. 
Would a translated A, B, C, or D automatically populate a dynamic string that is part of an object or context response, or a dynamic state description...once we figure out how to translate the descriptions?

Is it best to leave that question for the future?

**Comment by BLFiedler** [comment]
It does seem that there are a lot of open questions for availability of and translation of Description and Voicing in other locales/translations.

Happy to consider how we could optimize that now if reasonable, but if work needs to happen across sims we may leave it for that discussion. Sounds like this issue exists in several math sims or sims with equations. How does it work in Ohm's Law and Resistance in a Wire?

**Comment by terracoda** [comment]
Not sure about Ohm's Law and Resistance in a Wire, and CM reported on Slack that the strings are translatable in all math sims that he has worked on.

**Comment by jessegreenberg** [comment]
OK great, they are translatable currently so I think this can just be closed.
