### ISSUE TITLE
Comparative Size Parameters for Corners & Sides - changes to regions & ranges for regions 

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#219]
MEGA ISSUE ALERT! - @jessegreenberg you can proceed to the last few comments.

@jessegreenberg, I'd like to change the way we describe the comparative size of the corners, and sides, too, if this works.

The goal was to create 2 more landmarks (half the size of and twice the size of) that can provide a bit more orientation as to the actual size of the corners. And changed wording to the almost equal region, "smaller and similar to" and "wider and similar to" gives a little more context, too.

The scale is now based on percentages rather than a fixed linear scale describing smaller to wider.

Here's a screen shot from the design doc.

![image](https://user-images.githubusercontent.com/1902116/190639706-8ff5755b-5078-42ee-ab0b-069ef0d29a55.png)

Here's the table in markdown.

| Mappings | Comparative Angle Size Parameters for Corners |
| --------- | ------------------------------------------------- |
|   < 20%   |  far smaller than  |
|   < or = 20% & > 50% |  much much smaller than  |
|   = 50% |  half the size of  |
|   > 50% & < 60% |  much smaller than  |
|   > 60% & < 90% |  somewhat smaller than  |
|   > or = 90% & < 100% |  smaller and similar to  |
|   = 100% |  equal to  |
|   > 100% & < or = 110% |  wider and similar to  |
|   > 110 % & < 150% |  somewhat wider than  |
|   > or = 150% & < 200% |  much wider than  |
|   = 200% |  twice the size of  |
|   > 200% & < or = 250% |  much much wider than  |
|   > 250% |  far wider than  |

Edit: Fixed mistake in table and screenshot.

**Comment by terracoda** [comment]
Hopefully, I did the greater than and less than statements correctly.

**Comment by terracoda** [comment]
So, the above scale is the "full" scale. I can't think of how I could change the "simpler" scale used to describe a corner to its adjacent corners, so no changes that scale yet.

**Comment by terracoda** [comment]
@jessegreenberg, if the above works for corners, I think I would have to do the same to the sides.

**Comment by terracoda** [comment]
And here's the table for comparative side lengths
![image](https://user-images.githubusercontent.com/1902116/190639028-899126ef-5f30-4757-8861-7f647ee0d1d4.png)

| Mappings | Comparative Side Length Parameters |
| --------- | ---------------------------- |
|   < 20%   |  far shorter than  |
|   < or = 20% & > 50% |  much much shorter than  |
|   = 50% |  half as long as  |
|   > 50% & < 60% |  much shorter than  |
|   > 60% & < 90% |  somewhat shorter than  |
|   > or = 90% & < 100% |  shorter and similar to  |
|   = 100% |  equal to  |
|   > 100% & < or = 110% |  longer and similar to  |
|   > 110 % & < 150% |  somewhat longer than  |
|   > or = 150% & < 200% |  much longer than  |
|   = 200% |  twice as long as  |
|   > 200% & < or = 250% |  much much longer than  |
|   > 250% |  far longer than  |

**Comment by jessegreenberg** [comment]
To implement this we need to determine when one angle is twice/half/equal to another. @BLFiedler would you mind helping determine which angle tolerance interval to use for this? It should have similarly to the right angle indicators so I thought possibly `staticAngleToleranceInterval`. But we are not comparing the angle to a static value, we are comparing it to a value computed from another angle.

What about for length?

**Comment by jessegreenberg** [comment]
OK, this is done for angles in the above commit. It is really difficult to ever hear "half the size of" or "twice the size of" unless it is perfectly so like this:

![image](https://user-images.githubusercontent.com/6396244/190826264-4b6453e5-2dc9-433f-8b4d-f1abe8ea4ef3.png)

Otherwise each step will skip over twice/half angles.

Is that OK and should I continue to implement this for sides?

**Comment by terracoda** [comment]
I was hoping there might be situation like Corners B and D here, where D is approximately twice as wide as B.
@BLFiedler briefly discussed a range for the new regions, and thought we would just try it first without a range.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1902116/191035064-fdeeeda2-88c4-439e-ac00-3fe004f59ef1.png">

**Comment by terracoda** [comment]
Follow-up to previous comment regarding "half the size of" and "twice the size of". Here are other cases where I thought these 2 regions could be helpful, but with the default step size and the exact region range, I can't find or land on the new regions in these cases.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/1902116/191036821-351b58a8-ba94-469a-a1fe-f724072fae9a.png">

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1902116/191038366-4d5ecec2-39f9-4f91-82bf-346ed7297565.png">

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1902116/191038937-e11d1a45-f022-498c-9059-50c40e25ab97.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1902116/191039191-c3854288-a15d-4cdd-8def-0b1981909ee3.png">

Question: since we are dealing in qualitative described values, would it be better to have a small range for these 2 new regions or small regions around the half and twice regions, like how we defined regions on either side of equal to?

Better map ideas out in design doc first.

**Comment by BLFiedler** [comment]
We might stick to `interAngleToleranceInterval` since it is a comparison to another angle and looking for their relation to equal. This will be a larger tolerance interval than `staticAngleToleranceInterval` as well.

Testing appropriate tolerances to use with default "5-step-per-grid" (minorVertexInterval = 0.05) now. Might still need to consider ranges, but maybe we can find an acceptable tolerance.

**Comment by BLFiedler** [comment]
Just noting - not providing actionables. Moving corner C to find "half of" corner A.

**??QUESTION??:** Are we aiming for there to only be 1 position where it read half of and that we can just reliably find it for any set of opposite angles (as frequently as possible?)

A note on the above question - it will always be easier to find the benchmarks for larger shapes than smaller shapes (see issue #212 for examples of finer angle changes with larger shapes)

Tested:
`staticAngleToleranceInterval` = 0.02
`interAngleToleranceInterval` = 0.04
`parallelAngleToleranceInterval` = 0.02
`shapeLengthToleranceInterval` = 0.005

Query Params: `staticAngleToleranceInterval=0.02&interAngleToleranceInterval=0.04&parallelAngleToleranceInterval=0.02&shapeLengthToleranceInterval=0.005&showModelValues`

Parallel to grid
![image](https://user-images.githubusercontent.com/47331395/191076370-1dd9cb15-9e28-436c-84db-9903fa271871.png)

Tilted (translate C right until I heard 'half of'):
![image](https://user-images.githubusercontent.com/47331395/191076874-79e47093-57d4-4a1d-a7f6-af6c49e5d4e9.png)

And I found quite a few more.

@terracoda, let me know how this feels for the default grid size and if you can find more of the voiced regions. 

I'll experiment with the fine grid size some as well. Now that we have 4 tolerance parameters, we can safely (i think) change them with the input grid.

**Comment by terracoda** [comment]
@BLFiedler regarding

> ??QUESTION??: Are we aiming for there to only be 1 position where it read half of and that 
> we can just reliably find it for any set of opposite angles (as frequently as possible?)

**Answer:** 
Though, that is how it is implemented at the moment, the answer is no. Having single-value regions is not the goal. We briefly discussed having a range for these new regions that could indicate "almost half" and "almost twice". 

The goal is to be able to hear some descriptions that give better qualitative reference points about the size of your corners and sides which hopefully would give a learner a better idea of the shape overall - perhaps help figure out what they want to change next in order to find a particular shape.

I also had a question above...
> ??Question??: Since we are dealing in qualitative described values, would it be better to have  > a small range for these 2 new regions or small regions around the half and twice regions, like > how we defined regions on either side of equal to?

I mapped out some words in the design doc with some tweaks to the ranges

Mappings | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| < 20% | far smaller than |
| < or = 20% & > 45% | much much smaller than |
| < or = 45% & > 50% | about half as wide but smaller than |
| = 50% | half as wide as |
| > 50% & < 60% | about half as wide but wider than |
| > 60% & < 70% | much smaller than |
| > 70% & < 90% | somewhat smaller than |
| > or = 90% & < 100% | similar but smaller than |
| = 100% | equal to |
| > 100% & < or = 110% | similar but wider than |
| > 110 % & < 150% | somewhat wider than |
| > or = 150% & < 190% | much wider than |
| > 190% & < 200% | about twice as wide but smaller than
| = 200% | twice as wide as |
| > 200% & < or = 210% | about twice as wide but wider than |
| > 210% & < or = 250% | much much wider than |
| > 250% | far wider than |

If we add new regions, I think we should take away the much-much regions.

**Comment by jessegreenberg** [comment]
I was wondering if we should just use a range for "half as wide", like ~35%-65% or something. That seems to be what the goal is for these qualitative descriptions. Then we don't have to tie this feature to the tolerances.

**Comment by terracoda** [comment]
@jessegreenberg, I agree, lets try that.

Mappings | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| < 20% | far smaller than |
| **< or = 20% & > 40%** | much much smaller than |
| **= or > 40% & < or = 60%** | _about half as wide as_ |
| **> 60% & < 70%** | much smaller than |
| **> 70% & < 90%** | somewhat smaller than |
| > or = 90% & < 100% | _similar but smaller than_ |
| = 100% | equal to |
| **> 100% & < or = 120%** | _similar but wider than_ |
| **> 120 % & < 140%** | somewhat wider than |
| **> or = 140% & < 180%** | much wider than |
| **> or = 180% & < or = 220%** | _about twice as wide as_ |
| **> 220% & < or = 260%** | much much wider than |
| **> 260%** | far wider than |

Bolded ranges are different from before, and italicized strings are different from before.

**Comment by terracoda** [comment]
Over to you @jessegreenberg. Please try this scale. We may need to tweak the ranges for the regions, but this is my best guess.

**Comment by terracoda** [comment]
Oh, just noticed a little uneven-ness, so adjusted the ranges for 
- somewhat wider than
- much wider than

And **pasting in the table for the sides** which is the same as the corners...

Mappings | Comparative Side Length Parameters
| --------- | ----------------------------------------------- |
| < 20% | far shorter than |
| **< or = 20% & > 40%** | much much shorter than |
| **= or > 40% & < or = 60%** | _about half as long as_ |
| **> 60% & < 70%** | much shorter than |
| **> 70% & < 90%** | somewhat shorter than |
| > or = 90% & < 100% | _similar but shorter than_ |
| = 100% | equal to |
| **> 100% & < or = 120%** | _similar but longer than_ |
| **> 120 % & < 150%** | somewhat longer than |
| **> or = 150% & < 180%** | much longer than |
| **> or = 180% & < or = 220%** | _about twice as long as_ |
| **> 220% & < or = 260%** | much much longer than |
| **> 260%** | far longer than |

**Comment by terracoda** [comment]
Over to you @jessegreenberg.

**Comment by jessegreenberg** [comment]
OK, these mappings were added in the above commits. I think it sounds nice, I can easily find most of them and the "half as long/twice as long" descriptions though I had a hard time triggering the "similar..." ones.

@terracoda ready for you to test!

**Comment by terracoda** [comment]
This is just a comment.

For the first shape I tried (randomly), Corner A hit the "about half as wide" region for both the opposite corner and the adjacent corners.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1902116/192096906-da911630-4003-4ca4-b383-2035b370a801.png">

**Comment by terracoda** [comment]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/1902116/192099213-2acbfa0a-73ea-4791-b1a9-efb4fdb73665.png">

This Rhombus is nice:
- Corner A, equal to opposite corner, about half as wide as equal adjacent corners
- Corner B, equal to opposite corner, about twice as wide as equal adjacent corners
- Corner C, (same as corner A)
- Corner D, (same as corner B)

And here's a similar Rhombus with model values shown. The visual angle guides look pretty close to exact halves, but looking at the model values they are in actual numeric terms not exact halves.

Here's a Kite.
- Corner A, equal to opposite corner, wider than adjacent corners
- Corner B, about twice as wide as opposite corner, about half as wide as equal adjacent corners
- Corner C, (same as corner A)
- Corner D, about half as wide as opposite corner, much much smaller than equal adjacent corners

<img width="999" alt="image" src="https://user-images.githubusercontent.com/1902116/192099926-a043c832-4598-4915-a5cb-07726a080538.png">


I think this is better than before, and provides a bit more detail. I would still like to explore if proximity to 90 degrees might be helpful in some places. Will discuss with @BLFiedler.

Note: the descriptions of the sides in the above Kite is interesting emphasizing the approximate qualitative nature of the scale. 

- Side AB, about half as long as opposite side, equal to one adjacent side
- Side BC, about half as long as opposite side, equal to one adjacent side _(same as AB above)_
- Side CD, much longer than opposite side, equal to one adjacent side
- Side DA, much longer than opposite side, equal to one adjacent side _(same as CD above)_

@BLFiedler, mathematically, do you think it is weird that Sides CD and DA are not described as "about twice as opposite side"? The ranges I put in were a guess on my part and they are uneven and not mapped to anything mathematical.

**Comment by terracoda** [comment]
I get the "about half" and "about twice" regions often now. 
We might need to adjust the range for the regions in general.

Main design questions are: 
1. What level of mathematical accuracy/precision do the ranges need to have/represent?
2. Would  regions around "half" and "twice" that follow the pattern of the regions around "equal to" see in the table in https://github.com/phetsims/quadrilateral/issues/219#issuecomment-1251469978 offer a better experience?

Or perhaps just 2 approximate regions for each, like this:
Comparative Angle Size Parameters for Corners
| ----------------------------------------------- |
| far smaller than |
| much much smaller than |
| about half as wide but wider than |
| about half as wide but smaller than |
| much smaller than |
| somewhat smaller than |
| similar but smaller than |
| equal to |
| similar but wider than |
| somewhat wider than |
| much wider than |
| about twice as wide but smaller than |
| about twice as wide but wider than |
| much much wider than |
| far wider than |

Actually, I think the above list does not offer any more clarity and would likely be confusing.
 
I think a slightly smaller range for the "about half" and "about twice" regions (sides and corners) and discussion on what level of mathematical precision we are trying to achieve would be helpful for me and eventually the learners who will use quadrilateral.

**Comment by terracoda** [comment]
I would like to discuss with @BLFiedler , and I am wondering if these range adjustments might be helpful?
I'll change the label to design.

Mappings | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| < 20% | far smaller than |
| **< or = 20% & > 45%** | much much smaller than |
| **= or > 45% & < or = 55%** | _about half as wide as_ |
| **> 55% & < 70%** | much smaller than |
| **> 70% & < 90%** | somewhat smaller than |
| > or = 90% & < 100% | _similar but smaller than_ |
| = 100% | equal to |
| **> 100% & < or = 125%** | _similar but wider than_ |
| **> 125 % & < 155%** | somewhat wider than |
| **> or = 155% & < 190%** | much wider than |
| **> or = 190% & < or = 210%** | _about twice as wide as_ |
| **> 210% & < or = 250%** | much much wider than |
| **> 250%** | far wider than |

**Comment by BLFiedler** [comment]
I think that should work. I like keeping the interval for "half/twice" relatively narrow.

Do you think it'd be helpful to continue using "half" as a reference point and replace 'much much smaller/wider' with 'less than half' or 'much less than half' or something similar?

**Comment by terracoda** [comment]
There's an idea. I will review :-)

**Comment by terracoda** [comment]
I don't really like the "much much" region.

**Comment by terracoda** [comment]
Maybe we just need fewer regions. There is a lot of cognitive load here.
I was also thinking if some scale about being close to 90 degrees might be more helpful.

**Comment by terracoda** [comment]
I am having a lot of trouble with this - both in terms of the math and the words. Here's my latest attempt at the comparative size scale. The conflicts in mind are how best to describe the comparisons? 

Mappings | Iteration with half & twice & new mappings
| --------- | ------------------------------------------- |
| < 10% | far smaller than |
| < or = 10% & > 30% | much less than half of  |
| < or =30% & > 45% | a little less than half of |
| = or > 45% & < or = 55% | half as wide as (with a narrow range) |
| > 55% & < 70% | a little more than half of |
| > 70% & < 85% | somewhat smaller than |
| > or = 85% & < 100% | similar but smaller than |
| = 100% | equal to |
| > 100% & < or = 115% | similar but wider than |
| > 115 % & < 130% | somewhat wider than |
| > or = 130% & < 145% | almost twice as wide as OR a little less than twice as wide as |
| > or = 145% & < or = 155% | twice as wide as(with a narrow range) |
| > 155% & < or = 170% | a little more than twice as wide as |
| > 170% & < or = 200% | much more than twice as wide as |
| > 200% | far wider than |

Visually we have pie slices of 30 degrees each. Would it be better to describe the pie slices? For example, imagine how we currently describe the corners of this Dart:
- Corner A, far smaller than opposite corner, similar but wider than equal adjacent corners
- Corner B, equal to opposite corner, smaller than adjacent corners
- Corner C, far wider than opposite corner, far wider than adjacent corners
- Corner D, equal to opposite corner, smaller than adjacent corners

Does adding in the  number of pie slices add a sense of size to the corners that we are currently missing?
- Corner A, 1 pie slice, far smaller than opposite corner, similar but wider than equal adjacent corners
- Corner B,  less than 1 pie slice, equal to opposite corner, smaller than adjacent corners
- Corner C, about 9 pie slices, far wider than opposite corner, far wider than equal adjacent corners
- Corner D,  less than 1 pie slice, equal to opposite corner, smaller than adjacent corners

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1902116/193056584-09f43f62-b2c8-4191-8034-dd2ffd9131e2.png">

Note: I am not proposing we mention pie slices in object responses as they are changing (I haven't thought about that).

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1902116/193056584-09f43f62-b2c8-4191-8034-dd2ffd9131e2.png">

- Corner A, about 4 pie slices, somewhat wider than opposite corner, almost twice as wide as equal adjacent corners
- Corner B,  about 2 pie slices, equal to opposite corner, smaller than adjacent corners
- Corner C, right angle, somewhat smaller than opposite corner, somewhat smaller than equal adjacent corners
- Corner D,  about 2 pie slices, equal to opposite corner, smaller than adjacent corners

**Comment by terracoda** [comment]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/1902116/193070195-3269fafa-9fad-4811-b7e5-8de68ea30a41.png">

- Corner A, about 3 pie slices, equal to opposite corner, somewhat wider than equal adjacent corners
- Corner B,  almost 3 pie slices, equal to opposite corner, somewhat smaller than equal adjacent corners

**Comment by terracoda** [comment]
If learners know that a pie slice is 30 degrees, they might be able to think about the above parallelogram as pretty close to a rectangle.

**Comment by terracoda** [comment]
Ok, we have to go back to simple on these comparative scales. More words does not bring more clarity.
I have to work out the mappings with help from @BLFiedler or @jessegreenberg, and this scale for comparative descriptions
Mappings | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| ? | far smaller than |
| ? | much smaller than |
| ? | about half as wide as |
| ? | somewhat smaller than |
|  ? | similar but smaller than |
| = 100% | equal to |
| ? | similar but wider than |
| ? | somewhat wider than |
| ? | about twice as wide as |
| ? | much wider than |
| ? | far wider than |

**Comment by terracoda** [comment]
And I would like the same string changes for the Comparative length parameters. 

Mappings | Comparative Length Parameters for Sides
| --------- | ----------------------------------------------- |
| ? | somewhat shorter than |
| ? | much shorter than |
| ? | about half as long as |
| ? | somewhat shorter than |
|  ? | similar but shorter than |
| = 100% | equal to |
| ? | similar but longer than |
| ? | somewhat longer than |
| ? | about twice as long as |
| ? | much longer than |
| ? | far longer than |

**Comment by terracoda** [comment]
I am going to put the ideas for describing the pie slices and the side-length units in separate and related issue.

This issue should be about just finalizing the comparative size Parameters for corners and sides.

**Comment by terracoda** [comment]
@BLFiedler let me know if we need to work together on mapping out the above ranges.

**Comment by BLFiedler** [comment]
So, if we constrain the number of bins between between half and twice AND we want the "equal to" to match the shape model, then we're left needing to create uneven regions (which we have already recognized). If we're okay with that, then any reasonable region sizes will work. It just becomes increasingly large as we move away from equal (until functionally infinity), e.g,

Mappings, x is angle of comparison  | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| `-` x <= 100% | far smaller than |
| `-` 60 >= x > 100% | much smaller than |
| `-` 40 >= x > -60% | about half as wide as |
| `-` 20 >= x > 40% | somewhat smaller than |
| `-` (0-`iATI`) > x > 20%  | similar but smaller than |
| 0% | equal to [*has to match model, so within `interAngleToleranceInterval`]|
| `+` (0+`iATI`) < x < 35% | similar but wider than |
| `+` 35 <= x < 75% | somewhat wider than |
| `+` 75 <= x < 125% | about twice as wide as |
| `+` 125 <= x < 200% | much wider than |
| `+` x >= 200% | far wider than |

Or if you prefer set bracket notation, parenthesis is exclusive, bracket is inclusive.

Mappings, x is angle of comparison  | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| `-` [1x, inf*x] | far smaller than |
| `-` [0.6x, 1x) | much smaller than |
| `-` [0.4x, 0.6x) | about half as wide as |
| `-` [0.2x, 0.4x) | somewhat smaller than |
| `-` ((0-`iATI`)x, 0.2) | similar but smaller than |
| `=` [(0-`iATI`)x, (0+`iATI`)x] | equal to [*has to match model, so within `interAngleToleranceInterval`]|
| `+` ((0+`iATI`)x, 1.35x) | similar but wider than |
| `+` [1.35x, 1.75x) | somewhat wider than |
| `+` [1.75x, 1.25x) | about twice as wide as |
| `+` [1.25x, 2x) | much wider than |
| `+` [2x, inf*x] | far wider than |

**Comment by terracoda** [comment]
With the way the regions get bigger as one goes up the scale, I am wondering if "much wider than" should come before "about twice as wide as", and than any more than "twice as wide as" (which is a lot) is "far wider than".

**Comment by terracoda** [comment]
Moving "much wider than" above "about twice as wide as"

Mappings, x is angle of comparison  | Comparative Angle Size Parameters for Corners
| --------- | ----------------------------------------------- |
| `-` [0.1x, 0) | far smaller than |
| `-` [0.4x, 0.1x) | much smaller than |
| `-` [0.6x, 0.4x) | about half as wide as |
| `-` [0.8x, 0.6x) | somewhat smaller than |
| `-` ((1-`iATI`)x, 0.8x) | similar but smaller than |
| `=` [(1-`iATI`)x, (1+`iATI`)x] | equal to [*has to match model, so within `interAngleToleranceInterval`]|
| `+` ((1+`iATI`)x, 1.30x) | similar but wider than |
| `+` [1.30x, 1.60x) | somewhat wider than |
| `+` [1.60x, 190x) | much wider than |
| `+` [1.90x, 2.10x) | about twice as wide as |
| `+` [2.10x, inf*x] | far wider than |

**Comment by terracoda** [comment]
@jessegreenberg, @BLFiedler said we should discuss with you which representation works best for you. I'd like to start with the ranges in  https://github.com/phetsims/quadrilateral/issues/219#issuecomment-1263872113

**Comment by terracoda** [comment]
@jessegreenberg, once we discuss, this issue would be high priority.

**Comment by terracoda** [comment]
And for side lengths, assuming they would work in a similar way, I copied the same ranges into the design document.
![image](https://user-images.githubusercontent.com/1902116/193334389-bcf4750e-1c60-4d80-bdb2-e574aa91bdb4.png)

**Comment by terracoda** [comment]
After yesterday's design meeting, I think these adjustments to the scales are clear for @jessegreenberg.

If #210 relates to this issue, it should likely be done first.

**Comment by terracoda** [comment]
Ok, found some cases like this where the visual is looking very exact, so "**about** half as wide as opposite corner" is conflicting with my inner description designer.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/1902116/194158629-9777d3ee-3473-40af-b017-31e23023f01b.png">

I have added the exact "half" and exact "twice" regions back in, AND I am not differentiating the words in the "about" regions on either side of these exact regions. We do differentiate the regions on either side of the "equal to" region, but we won't for "half" and "twice". The language is too complicated.

![image](https://user-images.githubusercontent.com/1902116/194158558-1cce4b6b-7d2e-4842-b134-b03b40961b38.png)

**Comment by terracoda** [comment]
@jessegreenberg, I updated the text-based table in https://github.com/phetsims/quadrilateral/issues/219#issuecomment-1263872113

**Comment by jessegreenberg** [comment]
OK! This change has been made @terracoda, over to you to review.

**Comment by terracoda** [comment]
I think these regions are implemented as I have them designed.
Any tweaking of regions or region order will happen in new issues. No changes at this time.
