### ISSUE TITLE
Zoom out grid slightly to allow vertex to rest on a grid line at each boundary

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#220]
When making the maximum size shape, interviewees had tried to go to the top and bottom grid lines, but the vertex is halted by the boundary before reaching it. It'd be nice to have the grid lines indented enough so the vertex rests on a grid line at the boundary.

@jessegreenberg tested this after discussion in a meeting:

![Image](https://user-images.githubusercontent.com/47331395/190682395-78f2185e-e2c9-4d35-a1d5-7d448069d657.png)

with the comment:
> Model bounds dilated by 0.05 model units to produce this image

Follow-up in slack: 
**BF:** Looks fine I think. Really not too big of a change. Does the grid spacing need any adjusting? Are there still five spaces per grid square?

**JG:** 
>Does the grid spacing need any adjusting?
IMO nope!
>Are there still five spaces per grid square?
Yes

**Comment by BLFiedler** [comment]
Go ahead and commit!

**Comment by jessegreenberg** [comment]
Done in the above commit. Increasing the model bounds impacted the model-view transform and literally had the effect of zooming out a little. Note that means everything in the grid area got a little smaller including side widths, vertex radii, tick marks on each vertex...things that are sized relative to the model. Vertex labels are not dependent on model coordinates and are relatively larger now.

@BLFiedler can you confirm this is OK or is any pixel polishing necessary after this?

**Comment by BLFiedler** [comment]
Thanks!

First test it looks like either our current shape boundaries are getting in the way (getting stuck on a boundary?) or the bottom spacing is just too small to let C & D in the below picture reach the bottom. Two pictures below are the lowest I can bring C or D.

![image](https://user-images.githubusercontent.com/47331395/191034624-a17833a1-aa08-4f28-bb93-804c91bd28df.png)

![image](https://user-images.githubusercontent.com/47331395/191034672-35e51770-8b3a-438e-ba14-e7a65a67d5e3.png)

**Comment by jessegreenberg** [comment]
Thanks for catching! It should be symmetric so I am not sure why it is getting stuck here, Ill investigate.

**Comment by BLFiedler** [comment]
Just to note there is [still some funny business at the bottom](https://github.com/phetsims/quadrilateral/issues/220#issuecomment-1251058487). I'd also like to tweak the play area a bit after we made the label changes in #190.

- [ ] Investigate inability to bring vertices to the very bottom of the play area
- [ ] Shrink the left and right play area boundaries so that the "partial grid square" width matches the "partial grid square" height on the top and bottom

![image](https://user-images.githubusercontent.com/47331395/192312580-df3eeec6-f52a-49de-91b7-652619baef7c.png)

**Comment by BLFiedler** [comment]
Two TODOs remain two[ comments above](https://github.com/phetsims/quadrilateral/issues/220#issuecomment-1258178321)

**Comment by jessegreenberg** [comment]
We bailed on #41 but this part
> "Investigate inability to bring vertices to the very bottom of the play area"

was fixed by #180

**Comment by jessegreenberg** [comment]
OK, I think this was done well in the above commit. @BLFiedler would you like to review? Is it OK that the vertex can overlap the edge of the grid now?

**Comment by BLFiedler** [comment]
Good catch. It doesn't bother me, but it looks like we tend to avoid that in other sims with anything resembling a collision. 

If it doesn't complicate anything, can you inflate the bounds just enough to avoid overlap? I think making the bound slightly bigger is better here, without allowing any further movement by the vertices so they still center on the outermost grid lines

![image](https://user-images.githubusercontent.com/47331395/207083477-91781ab4-abf5-46ee-863d-85f92d72861c.png)

**Comment by BLFiedler** [comment]
Looks good! Closing.
