### ISSUE TITLE
Iteration 1: Object Responses

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#224]
Some feedback was listed in https://github.com/phetsims/quadrilateral/issues/182#issuecomment-1218319725

First thing I need changed, so I can listen and imagine better is to remove the strings that describe 
- "closer to" or "farther from" opposite corner, and
- "closer to" and "farther from" opposite side.

I think the the other strings "angle wider", "angle smaller", "adjacent sides longer", and "adjacent sides shorter" will serve well as progress responses.

I still have lots of changes to work out, but @jessegreenberg can you remove those strings from corner and side object responses?

**Comment by jessegreenberg** [comment]
Over slack @terracoda and I discussed:

> there is a case where the angle doesn't change and "closer to/farther from opposite corner" is the only object response. What would you like the object response to be in that case? Something like "No change in angle"?

> Like the sides, is it possible to just provide the directional string in those cases: up, leflt, down, or right?

> Yes, we could do that. So for #224, the object response for moving a vertex with a keyboard will be "angle smaller"/"angle wider" or if there is no change it will just be "left/right/up/down".

**Comment by terracoda** [comment]
As you can see in the screen shot in the previous comment, I am still working out the actual strings. I am thinking we will need to name the corners sometimes. I wanted to avoid that because it complicates things. 
I am still working on it.

**Comment by jessegreenberg** [comment]
Sounds good, thanks. 

> And how easy would it be to provide the current state in these situations?

Time to implement probably matches difficulty to design each of these options. Second row would take less than an hour, the rest of the rows might take 4-6 hours. (Very rough guesses of course).

**Comment by terracoda** [comment]
For now, @jessegreenberg  will put in the directional strings, so I can use the sim to help me through these response design challenges.

**Comment by jessegreenberg** [comment]
OK that much is done. Back to you @terracoda.  https://github.com/phetsims/quadrilateral/issues/224#issuecomment-1253863315 might happen in new issues, maybe this can be closed after review.

**Comment by terracoda** [comment]
Ok, pulling a fresh version :-)

**Comment by terracoda** [comment]
@BLFiedler discussed some ideas today for object responses. Rather than exact state information for object response, I will try some important events related to a moving object.

**Comment by terracoda** [comment]
Thanks for removing the distance strings and adding the directional string for the case where the angle doesn't change.

Closing this issue. More iterations will be posted in new issues.
