### ISSUE TITLE
Add support for switching locales

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#229]
PhET is adding this for all sims, we should probably add to Quadrilateral too. Very little text in this simulation means it should be very quick.

To be worked on as we get closer to publication or if other issues are complete. @BLFiedler fyi, in case you have concerns about this issue.

**Comment by jessegreenberg** [comment]
Removing my assignment until this is something we have time to work on.

**Comment by BLFiedler** [comment]
We are not going to be working on this for publication. Also appears to currently cause conflicts with Voicing in Ratio and Proportions testing. Possible lift that may require more significant effort.
