### ISSUE TITLE
Incorrect equality called out on context response describing corners

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#230]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1902116/191841563-42365850-55ac-4e35-8840-755d4da1611c.png">

Sorry, I don't have &showModelValues on, but I am hearing:
- angle wider, and
- Corner {{C}} points inward, Corner {{A}} and Corner {{C}} are equal and pairs of adjacent sides are equal.

I get the correct comparative description of corners C and A when I move focus away and then back to Corner C.

The above might just be a simple error.

**Comment by terracoda** [comment]
With showModeValues
<img width="814" alt="image" src="https://user-images.githubusercontent.com/1902116/191860598-8bcb8fe8-d694-44d5-a20e-b792477e369f.png">

**Comment by jessegreenberg** [comment]
Thanks @terracoda! Im guessing that something is wrong with the description for dart.

**Comment by jessegreenberg** [comment]
It looks like the string pattern is correct but it is just referring to the wrong vertices, it should say 

> Corner {{C}} points inward, Corner {{B}} and Corner {{D}} are equal and pairs of adjacent sides are equal.

**Comment by terracoda** [comment]
Fixed. Thanks.
