### ISSUE TITLE
Shape Sound check box does not re-check after Reset All

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#232]
Totally not sure, but might be related to #226.

When I uncheck the Shape Sound checkbox, and then press or activate the Reset All button, the checkbox does not become checked again. 

I am not sure if this is intentional or not.

Here's a after activating the Show Shape Name & unchecking both the Corner Labels & Shape Sound check boxes
<img width="964" alt="image" src="https://user-images.githubusercontent.com/1902116/193578126-4c1e1da0-5ca3-4c72-8e5d-cda32857cd0f.png">

After pressing/activating the Reset All - the Shape Sound check box does not currently reset.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/1902116/193578400-58b74d67-87ee-40c7-8761-52d6917fec61.png">

**Comment by jessegreenberg** [comment]
Thanks @terracoda, not intentional! Fixed.
