### ISSUE TITLE
Shape incorrectly named

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#234]
I found triangular quads can be named as kites incorrectly a couple of time.
Sorry, no model values, and I haven't figured out what triggers this. It happened on 3 different occasions.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1902116/194361239-6c4c90dd-dd76-4345-8073-8a242bf44667.png">

Oh, found one with model values shown.
I think I may have had fine input checked in both cases, and definitely using fine input below.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1902116/194363639-8845b764-8d01-42b5-87a2-0911abc65e01.png">

**Comment by terracoda** [comment]
Here's another example - not using fine input and do not have voicing enabled.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/1902116/194409238-8ce4d62a-a07d-4147-9a63-9545c3a41e89.png">

**Comment by terracoda** [comment]
I don't see the incorrect shape name any more.
Can I close this issue?

**Comment by jessegreenberg** [comment]
Thanks @terracoda, Ill take a look. I don't understand why this would be fixed yet.

**Comment by jessegreenberg** [comment]
I am still seeing this, it will happen when one of the bottom sides of the "triangle" has a length equal to an adjacent side like this:

![image](https://user-images.githubusercontent.com/6396244/195933139-70563cef-ce1c-433e-82f2-dcf9a56343c9.png)


In this case, there are two pairs of equal adjacent sides and one pair of equal opposite sides.

**Comment by terracoda** [comment]
A kite has to have two pairs of adjacent sides that are equal.

**Comment by terracoda** [comment]
And 1 pair of opposite angles.

Having opposite sides that are equal is not a requirement for a kite.

 Sorry @jessegreenberg, I am not sure what the question is.

**Comment by jessegreenberg** [comment]
@terracoda said:
> A kite has to have two pairs of adjacent sides that are equal.
> And 1 pair of opposite angles.

Right! Technically the shape you posted in https://github.com/phetsims/quadrilateral/issues/234#issuecomment-1280858511 has that.

Adjacent sides BC and CD are equal. AND adjacent sides CD and DA are equal.
Angle B equals angle D.

So the model categorizes this as a kite. So the question is - Is this a Kite or is there another condition for a Kite that we should be looking for like "A kite has to have two pairs of adjacent sides that are equal, where each side is unique". But maybe there is a more correct definition.

**Comment by BLFiedler** [comment]
I thought perhaps identity of the pairs may come up. I think we'll want to override the name of the shape to a Triangle per issue #215 and #236, so maybe this isn't an issue, unless we can come up with another case where kite appears.

**Comment by BLFiedler** [comment]
Triangle detection being implemented in issue #215.

We'll put that above detection of a Kite and this may be solved. Check back when that is done.
