### ISSUE TITLE
What about an Easter egg response questioning number of sides?

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#236]
Related to Shape Maintenance Responses in issue #198 there is a special case when the Quad can appear on screen looking like a triangle. 

This shape state is possible for both Convex Quads and Kites, but I think it can only be maintained (multiple key presses or continuous movement) when it is a Convex Quadrilateral. 

This triangle-like shape state might only be possible with certain input environments - like when using a discrete input method (e.g. keyboard) with the virtual sim. I am not sure if this kind of movement would be possible with the new TMQs or actuated TMQs, but it might be possible with other tangible inputs like the colored foam blocks. Regardless, it is possible with the virtual environment.

My math understanding is that the following shapes are not mathematically triangles because the shapes still have 4 vertices and 4 sides. That said, they appear like and feel like triangles (with tangible/haptic experiences), so I am wondering if a fun question would be appropriate for a context response here - a small Easter egg to quote @emily-phet.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1902116/194557914-143837d0-c25a-49a3-9e02-0d7b10e8bbb2.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/1902116/194557974-cc5c458b-fe14-492b-ace7-7e499f874894.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/1902116/194558100-e4f5ba87-eed9-403d-9535-6b20fcaea73d.png">

**Possible Context Response strings**
- Whoah! How many sides does this shape have? 
- Whoah! Does shape have 3 sides or 4?
- Whoah! Is this shape a quadrilateral?

I am imagining that this context response could either fire randomly when maintaining 180 angle, or it could fire as a convex quad maintenance context response while maintaining 180 degrees instead of a maintenance response about the the changing side lengths soon to be proposed in comment https://github.com/phetsims/quadrilateral/issues/198#issuecomment-1271634080

**Comment by terracoda** [comment]
Hey, Wow, Interesting?
Does shape have 3 sides or 4?

**Comment by terracoda** [comment]
I'll review #198 before updating this issue.

**Comment by terracoda** [comment]
"Wait" also works.

I think I like this response:
- "Wait? Does shape have 3 sides or 4?"

This question might encourage learners to click on the sides and come up with different reasoning to answer that question.

@jessegreenberg, can you use a method to randomly swap between the 2 responses?
- "{{CornerName}} {{flat}} as adjacent sides get change in length."
- "Wait? Does shape have 3 sides or 4?"

**Comment by terracoda** [comment]
That is, randomly swap between the 2 responses when a learner is maintaining a triangular shape.
- "{{CornerName}} {{flat}} as adjacent sides get change in length."
- "Wait? Does shape have 3 sides or 4?"

**Comment by jessegreenberg** [comment]
OK, added in the above commit. In this case, half of the time it will use the "Wait? Does shape..." and the other half it will use ""{{CornerName}} {{flat}} as adjacent sides get change in length.""

Back to @terracoda.

**Comment by terracoda** [comment]
I like the response, but 50% of the time is a bit too often.
We can discuss with @BLFiedler at Tomorrow's design meeting.

**Comment by terracoda** [comment]
This shape will playfully be called a triangle. Maybe "Wait? Found a Triangle?"
@terracoda with make sure all necessary responses communicate the same message.

**Comment by terracoda** [comment]
Ok, let's keep "Triangle?" with a question mark in the Shape Name box.

Toggling the Shape Name interaction to show shape name:
-  Change to: "You have {{a Triangle! Is that right?}}" instead of "You have a Triangle!"

**And for Context Responses:**
- Shape Name context response: 
    - Found {{a Triangle? Is that right?}}
- Shape Property Response:
    - Corner {{cornerLetter}} flat, adjacent sides look like one. 
- Two Shape Maintenance Responses:
    - When moving the 180-deree corner
        -  {{CornerName}} {{flat}} as adjacent sides change in length.
    - When moving a non-180 degree corner
        - Adjacent sides {{sideLetter}} and {{sideLetter}} in line as shape gets {{bigger/smaller}}.

**Comment by terracoda** [comment]
@jessegreenberg, I updated the 
- Found {{a Triangle? Is that right?}}
- and then changed it to: "Found {{a Triangle, is that right?}}"

It's unclear to me of we want to say, "is this right?" all the time.

We can get other strings in and see if I should change, "Found {{a Triangle, is that right?}}".

**Comment by terracoda** [comment]
Discussed at design meeting. We can keep the full string,"{{a Triangle, is that right?}}" wherever it currently shows up.

**Comment by terracoda** [comment]
@jessegreenberg, I need you to implement the 
- Shape Property Response, and 
- the two Shape Maintenance Responses

**Comment by jessegreenberg** [comment]
OK, this change has been made. I believe all triangle cases are now described.

The easter egg description that would change half of the time has been removed.

@terracoda over to you to review.

**Comment by terracoda** [comment]
This all sounds good @jessegreenberg. Thanks. Closing.
