### ISSUE TITLE
Object Reponses - Moving a Corner

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#237]
In addition to #219, we will need changing object responses.

Please see design document...[Table: Object Responses for Moving a Corner (ready for implementation)](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.9u49uu82mkhv)

I've tried to organize this info as best I can. Let's discuss if anything is unclear or way too complicated.
I worked really hard on this and am totally open to discuss.

![image](https://user-images.githubusercontent.com/1902116/194652143-c8eaa792-54ea-47ab-b81a-eb3d4f683199.png)
![image](https://user-images.githubusercontent.com/1902116/194652201-d6083386-77c1-4407-918d-aee7577a3d97.png)
![image](https://user-images.githubusercontent.com/1902116/194652249-41985747-92d3-41d1-aa6f-d16f5b817f9e.png)
![image](https://user-images.githubusercontent.com/1902116/194652312-6d566a14-6ba6-4a84-a97f-84041df300cf.png)

**Comment by jessegreenberg** [comment]
OK! I think this is implemented as requested with one exception:
![image](https://user-images.githubusercontent.com/6396244/196282179-64f47059-3894-47b7-a9ec-08196abadd23.png)


For these two cases I AM including angle change and landmark. The exclusion here was a little difficult to do and conflicts with the example in the first row of the "Landmark Angle States" table.

@terracoda I think this is ready for your review.

**Comment by jessegreenberg** [comment]
In the above commit, we added a special case check for when describing relative angles for a trapezoid. In this case, we make the angle tolerance interval 0 so that equality is only described when angles are exactly equal. That way it is impossible to hear that angles are equal when we leave the isosceles trapezoid.

**Comment by terracoda** [comment]
The object responses are sounding really good. 

Regarding your comment above, would this re-arrangement of the strings address the difficultly of implementation?

![image](https://user-images.githubusercontent.com/1902116/196738874-f401c00e-4143-4769-9914-1304ef34acc8.png)

realize now that we could put the responses about angle changes together a bit differently. Would it simplify matters, if we think about them as being 3 angle-progress parameters:
- angle {{smaller/ wider}}
- angle /equal to}} {{opposite corner}}/{{namedAdjace

And then when the angle is equal to an opposite or an adjacent, we don't need a comparative size statement added on to the response
    
There are a few open issues around tolerances, I will note one here, and copy it over to one of the open ones if needed.
1. "Adjacent corners equal" for a few steps on other side of 180 when maintaining Convex Quads and Concave Quads. This response is correct for Kites and Darts. And correct for Quads when maintaining a Triangle. I think we have a tolerance issue when the moving corner goes just above or just below 180 degrees, and the shape is neither a Kite nor a Dart. 
Here's one example
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1902116/196734107-1a2dc754-411e-4525-a2d4-4f60da696281.png">

**Comment by terracoda** [comment]
In addition, there are a few open issues around tolerances, I will note one here. It might need to be copied over to one of the other open issues.

I hear "adjacent corners equal" for a few steps on other side of 180 when maintaining Convex Quads and Concave Quads. This response is correct for Kites and Darts. And correct for Quads when maintaining a Triangle. 

But I don't think it is correct when maintaining a Convex or Concave quad.

This makes me think we have a tolerance issue when the moving corner goes just above or just below 180 degrees, and the shape is neither a Kite nor a Dart. 

Here's one example
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1902116/196734107-1a2dc754-411e-4525-a2d4-4f60da696281.png">

**Comment by terracoda** [comment]
Regarding tolerances, maybe we just don't describe anything about the angle change when the angle change is smaller than the angle tolerance. Would this work? 

I am thinking an angle change that is smaller than the angle tolerance is not a detectable angle change - at least it is a small enough difference that we decided to not show it visually.

For object response design, if there is no detectable angle change, we can describe direction of movement and prevent the description any other related corner details. That is in the first row of the table in https://github.com/phetsims/quadrilateral/issues/237#issue-1401666374.

**Comment by terracoda** [comment]
@jessegreenberg, I think you top priority is #41 so I am marking this for next weeks meeting in case it doesn't discussed beforehand.

**Comment by jessegreenberg** [comment]
> would this re-arrangement of the strings address the difficultly of implementation?
> Would it simplify matters, if we think about them as being 3 angle-progress parameters:

No I don't think so. Mostly I didn't implement this because I noticed an inconsistency in the design. If I understand correctly these two conflict:
![image](https://user-images.githubusercontent.com/6396244/196776144-74f7bfc7-f0fc-4d2f-9d7f-bcab0de386d8.png)
![image](https://user-images.githubusercontent.com/6396244/196776202-db34b0fc-76bd-49f6-b6d5-744e49456ad0.png)

So I went with the easier option at the time which was to hear the angle landmark in this case. But we could do either, would you rather hear it in this case or not?

@terracoda can you please make a new issue for the tolerance issues you found? I think that is going to be larger than this issue and will impact all Voicing responses.

**Comment by terracoda** [comment]
Ah, I see, I think I need to think through the priority of these.

**Comment by terracoda** [comment]
I'll work on this.

**Comment by terracoda** [comment]
Ok, this morning I reviewed and updated the design documentation moving corner object responses, re-ordering the table in order to be in order of priority. Hopefully this will help resolve some issues that I will post after posting the [Table: Object Responses for Moving a Corner (re-arranged to address design issues)](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.9u49uu82mkhv) from the design document.

**Comment by terracoda** [comment]
I will make a check list of what updates, I think would be great and which ones which are bugs that need to be fixed.

**Comment by terracoda** [comment]
Questions:
1. First, can we order the priority in the above manner? 
2. If yes, would that address the conflicts you found with the first implementation?
3. And if yes and yes, would this help eliminate some special cases?

If we can do the priority above easily, we can focus on the places where I marked object response in red.
- [ ] Make it so when we have Equality Events 1, we hear the parameters about equality with no added comparative size information
- [ ] Equality Events 2 - working well, but can we make "adjacent corners {{right angles}}" higher in priority than the size comparisons less high in priority? For example, can we make the first kite example work?
- [ ] Landmark Events (row 1 & 2) - can we re-arrange parameters so, we add "right angle" to Equality Events 1?
- [ ] Landmark Events (row 3) - right-angle events seem to be working differently for Darts. Can we make Darts work the same as Kites unless its against the model in some way. Not sure if the provided example is an isolated case, or not.

@jessegreenberg, the priority level makes sense to me, but if it does not to you, can we briefly discuss it?

**Comment by terracoda** [comment]
Ok, @jessegreenberg and I spoke. No changes I am asking for are difficult, but he showed me the logic in the code, and I am going to see if I can stick a little closer to that structure, and still achieve the design I want. 

During our discussion, we noted a ToDo in the code about the "All corners equal". Assigning back to me to clarifiy a few things.

**Comment by terracoda** [comment]
Ok, I made just a few adjustments. I think we are way closer than I though, @jessegreenberg.
Please use the table below as reference. Check list of change below.
![image](https://user-images.githubusercontent.com/1902116/197280996-d9f5f041-de66-45c3-acd9-470079e1d74f.png)
![image](https://user-images.githubusercontent.com/1902116/197281525-91b30129-8dc8-4391-819f-45b5714b519e.png)
![image](https://user-images.githubusercontent.com/1902116/197281568-0418e552-3328-4e23-8125-6ae7f1a49fc7.png)
![image](https://user-images.githubusercontent.com/1902116/197281631-7e35679f-c9b3-450c-876b-a45c5729e03f.png)
![image](https://user-images.githubusercontent.com/1902116/197281682-e71ed2bf-648d-451e-9fdf-b3d65e25bdfd.png)
![image](https://user-images.githubusercontent.com/1902116/197281721-fd2c9b62-c93a-443a-a780-fef99b20b0cf.png)
![image](https://user-images.githubusercontent.com/1902116/197281781-54efa7cd-7956-4659-9626-5f9f6c4077a6.png)
![image](https://user-images.githubusercontent.com/1902116/197281841-26bbd9a4-4dbc-4d6c-94a0-e2cfad40526a.png)
![image](https://user-images.githubusercontent.com/1902116/197281894-8057c89f-9890-4e3f-b5ef-fc7fd28e7855.png)

[ ] Equality Event 1: When moving corner becomes equal to another corner, do not provide progress phrase, "angle {{wider/ smaller}}".
[ ] Equality Event 2: When an angle change or progression makes moving corner wider or smaller & two adjacent corners become equal right angles, can we make sure we hear "angle {{wider/ smaller}}," + "adjacent corners {{right angles}}"?
[ ] Landmark Angle Events: When corner becomes 90 degrees and all corners become 90 degrees (squares & rectangles), please remove "All corners equal", and go back to standard phrase, "{{right}} angle," + "equal to {{opposite corner}}".
[ ] Landmark Angle Events (row 3) - I think this is a bug just for Darts. I thought I should hear the same for both Kites and Darts, when the moving corner becomes a right angle.
[ ] Triangle examples, Can we prioritize equality over size in both cases? Or will that mess things up?

Ok, when you are back working on Quad descriptions, hopefully this can be updated. I'll adjust the context responses accordingly. I might be able to do some of those myself.

**Comment by jessegreenberg** [comment]
OK, I made some changes for the requests in the above commits. 

> quality Event 2: When an angle change or progression makes moving

I don't understand how this would work, doesn't this conflict with "Quality Event 1"?

I hope I got the rest! Back to you @terracoda.

**Comment by BLFiedler** [comment]
Moving this TODO from #212 to here.

Length changes are mismatched for model and object responses, we would like object response for length to use the same tolerance as the model: `shapeLengthToleranceInterval` (eventually `interLengthToleranceInterval`). See closed #212 for discussion, though it is not summarized very well there.

- [ ] Update default shapeLengthToleranceInterval = 0.005
- [ ] Update the object response adjacent side tolerances to match shapeLengthToleranceInterval

**Comment by jessegreenberg** [comment]
@BLFiedler or @terracoda I **think** I made the right change for the above commit, but I am not really sure. The result is that it will require larger changes to hear side change responses like "adjacent sides longer". Hopefully that is right.

**Comment by terracoda** [comment]
**Design and Implementation Testing Notes for latest implementation.**

1. Making a square by moving a corner, I hear "equal to {{NamedAdjacentCorner}}". This was not my intention, so I may need to re-think the equality events.
Example case below moving Corner A, I hear, "Equal to {{Corner B}}" and then context response, "All right angles and all sides equal."
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1902116/203383997-b959028d-b19d-4d0f-87c8-aa47f6f298ea.png">
Discussed with JG and he will try the following:
![image](https://user-images.githubusercontent.com/1902116/203396394-ce4f684f-bb54-474f-9d60-0830e5172d16.png)

**Comment by terracoda** [comment]
2. We can have a 3-corner equality event.
This seems common in kites.
![image](https://user-images.githubusercontent.com/1902116/203420314-e3907c42-c73d-43df-afd6-c542e156c986.png)

I am hoping we can do the following when three corners become equal:
![image](https://user-images.githubusercontent.com/1902116/203420696-2e61ba9f-651d-4749-a783-f3f345ce2345.png)

I don't think this can happen with a convex quad or concave quad. If it did, I think we would have kite or dart.

**Comment by terracoda** [comment]
3. Maintaining a dart or concave quad - Can the object responses for maintaining a dart behave the same as a kite. Making "angle pointing inward" a landmark doesn't sounds good to me. 
![image](https://user-images.githubusercontent.com/1902116/203433995-8d3593a2-c809-47c3-b8d1-ca4cce47f0ac.png)

**Comment by terracoda** [comment]
4. I found a bug and noted that over in #261.

Back to you @jessegreenberg for my design fixes (1, 2, and 3) above.

Please comment if these changes do not =make sense to the shape model and current string design.

**Comment by terracoda** [comment]
- [ ] design issue 1 updated
- [ ] design issue 2 updated
- [ ] design issue 3 updated

Please assign back to me when ready. I think you may have already done design issue 1.

**Comment by jessegreenberg** [comment]
> Can the object responses for maintaining a dart behave the same as a kite. Making "angle pointing inward" a landmark doesn't sounds good to me.

Sorry, I don't understand what you are requesting. Would you like to remove the "angle pointing inward" progress response entirely?

**Comment by terracoda** [comment]
5. I have one more design issue aside from the tolerance problem which is in another issue...
In Equality Event 1, I am only hearing "equal to {{CornerName}}" and never hearing "equal to opposite corner".

I was hoping to hear "equal to opposite corner", when that property mattered to a shape. For example, when moving a corner transforms the shape into a rhombus, parallelogram, kite or dart. 

Is there a way to do this that doesn't mean making 4 more special cases? We already made a special case for squares and rectangles.

![image](https://user-images.githubusercontent.com/1902116/203621386-6d0bedd2-6290-4196-a2d0-64ac6720d08b.png)

**Comment by terracoda** [comment]
@jessegreenberg and I discussed issue 3 (angle pointing inward) on slack.
Summary:
> There isn't a concept of landmark in this sim.
> Let's not force a landmark idea onto an object state that has many values. Let's remove it from the object responses and see if it works okay in the Shape Property Response (it's already there as well). Additionally, on focus/click learners can get a description that the angle is greater than 6 slices which should indicate it is pointing inward (hopefully).

**Comment by jessegreenberg** [comment]
OK something that might work for https://github.com/phetsims/quadrilateral/issues/237#issuecomment-1325496186 was done in https://github.com/phetsims/quadrilateral/commit/d2d3b8f1dbef2a72f2c9bebd07f7b124bdb4a75a

"angle pointing inward" removed from the object response in https://github.com/phetsims/quadrilateral/commit/41f445a9589d40c6c114f16dc2690fc861361ec3/

Back to you @terracoda!

**Comment by terracoda** [comment]
Looks like design issues 3 & 5 are implemented.
I think we should close this issue.
Thanks @jessegreenberg. Nice work as always.
