### ISSUE TITLE
Updates for Show Shape Name Interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#238]
In #183, we added an interaction to show and hide the Shape Name.

In comment https://github.com/phetsims/quadrilateral/issues/183#issuecomment-1273710446 I mention I have a updates to the Voicing design which is the focus of this issue.

There are 2 tables in the design doc that capture the voicing design and voiced strings for this interaction. Screen shots of the tables included here.

- [Table: Show/Hide Shape Name (ready for implementation)](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit?pli=1#heading=h.4ca8rlve0nrx)
- [Table: Mouse-only Reading Block for Show/Hide Shape Name (ready for implementation)](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit?pli=1#heading=h.4n5tc1nbo6m7)

@jessegreenberg, of the three possibe Name Response (in read), I would like try, "Shape Name Hidden" both visually and for the voiced name response. I am not 100% sure, but I think @BLFiedler may have been hesitant about the idea of using "Shape Name?" with a question mark.

![image](https://user-images.githubusercontent.com/1902116/194937384-2d7b47f8-13da-4049-80ac-b806daf711ab.png)
![image](https://user-images.githubusercontent.com/1902116/194937420-9f684efc-1ca4-4f59-81d9-7a834b365a55.png)
![image](https://user-images.githubusercontent.com/1902116/194938763-3bc26ac9-adee-4db5-9905-914812e07e84.png)
![image](https://user-images.githubusercontent.com/1902116/194937662-63e3cc64-94e7-4167-9a34-e09569a3fb4a.png)

**Comment by jessegreenberg** [comment]
OK, I think what is described here has been implemented, @terracoda can you please review?

**Comment by terracoda** [comment]
You nailed it. It sounds good!

Thanks @jessegreenberg !

**Comment by terracoda** [comment]
@jessegreenberg, I missed one detail for the Shape Name reading block. It should not be available for focus-based input like keyboard and custom swipes. Learners who use focuse-based input (alt input) get the Name Response on focus, so they don't need another tab stop with the same information.

The purpose of the reading block is to make the on-screen text voice-able for mouse/touch users without having to toggle the show/hide button.

Re-assigning to you. Let me know if you have any questions.

We did something similar for the Distance Arrows and the Mass Control Grey Boxes in Gravity Force Lab:Basics. It would be nice if this was an option when implementing reading blocks.

**Comment by jessegreenberg** [comment]
Got it, done in the above commit.

> It would be nice if this was an option when implementing reading blocks.

We have an easy way to do this, but the API is a little clumsy. If we ever have an opportunity to open up Voicing infrastructure work this is something that could be enhanced.

@terracoda all good here?

**Comment by terracoda** [comment]
All good, and I liked you comment about the API, too. Glad this is easy for us, and we can improve it when we need to.
