### ISSUE TITLE
Update for Corner Guides Responses

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#239]
Soon we will have descriptions that roughly describe the number of 30 degree slices that are represented in the the corner guides, so I have a couple of tweaks to the the Corner Guides responses.

Change Context response that goes from unchecked to checked from "Angle guides added to corners."
To:
- Angle guides with 30 degree slices added to corners.
- No change to other context response.

Change Hint Response from " Explore shapes with or without visual angle guides."
To: 
-  Explore shapes with or without angle guides.
- Just remove the word "visual".

**Comment by jessegreenberg** [comment]
This update was done in the above commit, @terracoda would you like to confirm?

**Comment by terracoda** [comment]
Thanks @jessegreenberg. This is implemented as I requested, so closing. There might be a couple more tweaks once we discuss #240 today - the check boxes in general.

Closing this issue, though since it is complete.
