### ISSUE TITLE
Updates to Context & Hint Responses for the Visual Guide Checkboxes

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#240]
I have some design questions and tweaks for the Name, Hint, and Context Responses for the visual Guide check boxes.
Design Questions:
1. For Voicing can we or do we want to employ the same keyboard design patterns for activation of buttons and check boxes?
2. Can we align the visual name and the accessible names better for the check boxes?
3. How do we want to frame the Hint Response?
    - "Explore with or with"
    - "Explore shapes with or without"
    - "Create shapes with or without"
4. Do we want to mention "symmetry" anywhere?

![image](https://user-images.githubusercontent.com/1902116/195124101-2dddbdcb-ccb4-4cea-a692-92f78e29f526.png)
![image](https://user-images.githubusercontent.com/1902116/195132008-e81feaa6-dc26-4bea-a247-1da021ef0582.png)
![image](https://user-images.githubusercontent.com/1902116/195124325-927b85e0-ccf5-4c77-a6bc-39d8148b86e0.png)

These will be quick updates once we briefly discuss the wording.

**Comment by terracoda** [comment]
This issue relates to #239.

**Comment by terracoda** [comment]
@jessegreenberg, I have updated the [Table: Responses for Visual Guides](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit?pli=1#heading=h.285ytvclo42i) in the Voicing Design Doc. I removed all the extra-idea strings and crossed out the strings that are currently implemented. The updated strings that should be implemented for Name, Hint and Context Responses should all be noted in red text.

![image](https://user-images.githubusercontent.com/1902116/195186394-a17f08e7-87be-49b6-9edd-77e397b6b7a1.png)
![image](https://user-images.githubusercontent.com/1902116/195186481-2acd0adf-4ee5-4e06-a026-fdd746f62502.png)

**Comment by terracoda** [comment]
Over to you @jessegreenberg if you haven't already implemeted all of this :-)

**Comment by terracoda** [comment]
Note for the Corner Labels check box, please make the visual change as well to be "Angles" instead of "Corners".

**Comment by jessegreenberg** [comment]
OK, done in the above commit. @terracoda would you like to review?

**Comment by terracoda** [comment]
The new descriptions sound really good to me! Thanks @emily-phet and @jessegreenberg for the discussion yesterday and thinks @jessegreenberg for quick implementation.

Closing.

**Comment by terracoda** [comment]
@jessegreenberg, I missed one response.

When unchecking the Diagonals checkbox, the response should say:
- Diagonal guides hidden.
And not "- Diagonal guides removed."

Please close after update. Everything else is awesome.
