### ISSUE TITLE
Updates for Shape Sound Check Box Interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#241]
Design Questions
5. Wondering if we need to pluralize the name?
6. And I have some help text options:
    - Explore with or without sounds for shape changes.
    - Create shapes with or without the help of sounds.

![image](https://user-images.githubusercontent.com/1902116/195127501-a869dff1-a6b5-481d-8150-0c7d79ffc0cb.png)

**Comment by terracoda** [comment]
@jessegreenberg, please add an "s" to "Shape Sound" in the name response, and add the Hint Response.

Here's the a copy of [Shape Sounds Table](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.hvtbu8b4hevy) from the voicing design doc
![image](https://user-images.githubusercontent.com/1902116/195190871-efd2c673-1770-4ec9-9980-8a843358ff6f.png)

**Comment by jessegreenberg** [comment]
OK, changes made in the above commit. @terracoda would you like to review?

**Comment by terracoda** [comment]
All sounds great. Thanks @jessegreenberg for the quick turn around. Closing.
