### ISSUE TITLE
Sim is not responsive, or slow to respond and then crashes

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#242]
I was experiencing strange focus highlight behaviour earlier this morning and was wondering if my keyboard and/or mouse were not working.

Now the sim is just not working with alt input or mouse and it crashes. I just got the Safari warning that "This web page is using significant energy."

Before the total crash the Reset All button worked to reset the sim, but then soon after moving a side, the shape was stuck and the music was playing forever.

DevTools showed many errors happening
![image](https://user-images.githubusercontent.com/1902116/195396451-3abfa7b3-c79a-42a9-a2f1-b8c9d89e06f7.png)
![image](https://user-images.githubusercontent.com/1902116/195396499-683b77c6-d509-4ec6-b37a-f0a2b347760a.png)
![image](https://user-images.githubusercontent.com/1902116/195396544-846895a4-9078-488e-a266-d23dc39eb339.png)

After chatting with @jessegreenberg on Slack, the sim totally froze and the Reset All button no longer worked.

And here's DevTools after sim was completely unresponsive and I got the safari warning
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/1902116/195396349-c82f74a8-7558-43f0-b7d6-634946373697.png">

**Comment by terracoda** [comment]
The crash must have happened when I was chatting with @jessegreenberg as the number of messages is the same.

**Comment by terracoda** [comment]
While maintaining a Kite with mouse input this screen popped up in front of the sim:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1902116/195397771-c011dd0e-d8b4-4233-ae0a-50ab92d94cc3.png">

Here's the console tab
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/1902116/195397961-a82a6e63-1f42-49bb-9102-7ce592539554.png">

**Comment by terracoda** [comment]
Of course, sim was crashed at that point.

**Comment by terracoda** [comment]
OK, I have reloaded the sim and will track my key presses.

Ok, I made a few key presses moving sides and corners and then lined-up a similar kite - one aligned to the Y-axis. The sim crashed after moving Corner C up 2 steps. I think this can be repeated.

Align a kite so you can maintain it on the vertical axis and the sim will crash.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/1902116/195398915-d76b6743-4c00-4a53-922c-e90bfb2ef5d0.png">

**Comment by jessegreenberg** [comment]
Thank you @terracoda, thats it!! {{cornerLabel}} and {{flat}} are not getting filled in, throwing this assertion. Hopefully the `announcingUtteranceWrapper` problem is just downstream of this and if we fix the description the problem will resolve.

**Comment by jessegreenberg** [comment]
OK, this case should be fixed. There were two problems
- The string `{{cornerLabel}} flat as adjacent sides change in length testing` had extra braces around "flat" when it shouldn't
- The string pattern for kite/date was using the string pattern for maintaining the "flat" angle, and so `cornerLabel` was never getting filled in, throwing an error at this assertion.

This was ultimately a copy/paste error. Thanks for catching @terracoda, hopefully that is all but I wouldn't be too surprised if there are more of these now that we have found one.

**Comment by jessegreenberg** [comment]
Back to you to verify if you wish or close.

**Comment by terracoda** [comment]
Maintaining kites and darts seem fine - sim is behaving again :-)
