### ISSUE TITLE
Combine side units and angle slices into one checkbox

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#243]
**Design questions for side units and angle slices**

In #231, we added descriptions  that capture a semi-quantitative perspective of the corners and sides by roughly describing the number of slices in the corner angle guide and the the number of units on the sides. This information is available on keyboard focus and click and on-demand by hitting Space or Enter keys or re-clicking a side or corner. 

I think the information is good information (see https://github.com/phetsims/quadrilateral/issues/231#issuecomment-1277622133) and will be helpful for people with diverse visual impairments as well as others.

I have a couple of more general design questions which I putting in this issue to discuss with @BLFiedler, or for longer term consideration & impact.

1. We have no way to turn off units for sides. Is this okay for everyone? We like the units on the sides, but now that we describe them, do we want to add another checkbox or possibly combine the angle slices & side units into one checkbox, so both can be turned on and off together?
2. I personally, like keeping the comparative description for both modes, and being able to add on the quantitative component. We could consider the pros & cons of making this information an either/or situation. I have not considered this yet or how it would impact the experience. Likely, a bit late in the design process to think deeply about this for this sim.

Should we consider item number 1...
Here's a quick draft of a possible Voicing design for a Units checkbox:
- Name Response: Units (appropriate icon)
-  Context Responses: 
    - Evenly spaced side units added. 
    - Marks hidden.
- Hint Response: Create shapes with or without help of side units.

And here's a quick draft of Voicing design for a combined checkbox for both Side Units and Angle Slices:
- Name Response: Units & Slices (appropriate icons)
-  Context Responses: 
    -  Evenly spaced side units and angle guides showing 30 degree slices added.
    - Side units and angle guides hidden.
- Hint Response: Create shapes with or without help of side units and angle guides.

It's optional that we consider any of this.

**Comment by terracoda** [comment]
Discussed again at Description at October 25 design meeting.
Ideally, we need a good word that covers both or two small words?
We really would like to keep the Labels checkbox if at all possible.

Ideas for label name for a combined checkbox:
- Units & Slices
- Units/ Slices
- Units
- Segments
- Tick Marks
- Measurements
- Guides

It's important to think of all the pieces that support the visual label name together.

Personally, I like the way these sound together:
- Name Response: Measurements (+ appropriate icons)
- Context Responses:
    - Evenly spaced side units and 30-degree angle slices added.
    - Side units and angle slices hidden.
- Hint Response: Create shapes with or without help of rough measurements for sides and angles.

I am totally open to alternatives.

**Comment by BLFiedler** [comment]
A few to-do items will arise from this:

@jessegreenberg:
- [ ] By default, make sides appear visually smooth
- [ ] Side segments appear alongside corner markers when checked.
- [ ] Rename Angles checkbox to Shape Markers or just Markers if that doesn't fit.

@terracoda:
- [ ] Determine which descriptions should appear when side segments are hidden and when the box is checked.

We might break these out to separate checkboxes, but everyone was interested in trying this out. We'll go ahead with both side and angle "markers"/guides behind the same checkbox for now.

**Comment by terracoda** [comment]
@jessegreenberg, the side units and corner slices were implemented in #231. There is no change to the strings or the behaviour of the strings. 

This issue is adjusting the over all design, so that the side units can be turned off in the voicing and the description. Instead of having separate check boxes, one for side units and one for corner slices, we'll have one single Shape Markers checkbox that turns both on or off.

The new checkbox will affect both State Descriptions under the Details button, and the strings in the side and corner initial object response.

When checked we will always hear side units and angle slices under Details.

Note that Object Responses in Preferences has to be checked to hear any of the object response details. If the Shape Markers checkbox is not checked and Object Responses are check, the Object Responses will only contain the comparative descriptions of the sides and corners. This is how it already works for the Angle Slices, so we are just aligning the two semi-quantitative values.

**Comment by jessegreenberg** [comment]
I think the requests from this issue are complete. @terracoda and @BLFiedler can you please review?

**Comment by terracoda** [comment]
Since we took "Shape" out of the Name Response, I think it should go in the help text and context response.
Also I think I can shorten these phrases.
I'll see if I can make these adjustments.

- Name Response: "Markers" (+ appropriate icons)
- Context Responses:
    - Evenly spaced side units and 30-degree angle slices added.
    - Shape markers for sides and angles hidden.
- Hint Response: Create shapes with or without help of rough shape markers for side length and angle width.

**Comment by terracoda** [comment]
Ok, I updated the strings in https://github.com/phetsims/quadrilateral/commit/7b4401e1c70cfd8670084e4f3ab3320fad924939

**Comment by terracoda** [comment]
Ok, verified. The updated text.
I think it sounds fine., so closing.
I'll open a new issue for an icon change.
