### ISSUE TITLE
Options for chunking Details information

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#244]
What easy method could we use to have the option to break up the Details information?

Currently we have a heading "Quick Info" then 3 buttons, "Play Overview", "Play Details", and "Play Hint"
<img width="206" alt="image" src="https://user-images.githubusercontent.com/1902116/195878747-165fabc5-885a-49ef-92fa-572a68acd0d5.png">

Could we have an option to use an expand/collapse interaction (instead of a play-button) that could open and reveal a number of detail buttons? 

This would be super handy for sims (many sims) where there are too many details to create a succinct and understandable big-picture description. Even for GFLB, the details description is very long.

Details [+]
- Details expanded. (context response) 
- and a few buttons become available under Details [-]
These buttons are just an example based what we
    - Play Position Details?
    - Play Side Details?
    - Play Corner Details?

With Object Responses checked in Preferences, we can easily replay side and corner details right on the shape. With this sim option unchecked, having those details accessible from the tool bar might be nice.

 I will be re-looking at what details we need under the Play Details button.

This issue is just to ask if we have the ability and time to add more buttons to break up the details information. I think this option would be beneficial to many sims in the future.

**Comment by jessegreenberg** [comment]
There is no easy opt-in for this now. This would be a new development project in common code (joist). It wouldn't be a huge project but between design/implementation/code review/QA, it might take focus for a couple weeks? I can't speak to whether we have time for this, but it is something we could do!

**Comment by BLFiedler** [comment]
Let's rope @emily-phet into this discussion today in design meeting. It seems like this might be something to consider for the Future of Voicing (TM).

**Comment by terracoda** [comment]
We may not need more flexibility for the Details button for this sim, but in general it seems like a useful function.

**Comment by BLFiedler** [comment]
There may be space for implementing these changes in Joist depending on how things go for collision detection (#41), but this may end up being an issue better suited for the next sim.

**Comment by terracoda** [comment]
I will open a separate issue for a new design of the state descriptions that will be delivered under the Details button.

**Comment by terracoda** [comment]
If (big if) we have the option for drilling down into the details we could provide a list of quantitative details in the side bar like this
Play Details can provide a brief set of general details, and maybe a 
Play More Details button could provide the following:
**[>/||] Side Length Details **
- Side {{AB}} ,{{shortest}}, {{just under 2 units}}.
- Side {{BC}}, {{j2 and half units}}.
- Side {{CD}}, {{longest}}, {{just under 4 units}}.
- Side {{DA}}, {{just under 2 and half units}}.

**[>/||] Corner Angle Details**
- Corner {{A}}, {{just over S slices}}.
- Corner {{B}}, widest, {{just over S slices}}.
- Corner {{C}}, smallest, {{just over S slices}}.
- Corner {{D}}, {{just over S slices}}.

This would be most handy when Object Responses is not checked.

**Comment by terracoda** [comment]
If we decide to go with Play More Details, for this sim, we could put the Longest and Shortest side/s and the Widest and smallest corner/s details under a separate button, see #254. Note, for this sim, these details can be turned on and off. I don't think I would want the button to be appear and disappear. I think, it would make sense to just provide the access to the info regardless of the information is visually displayed with visual side units and visual corner slices.

That said, for this sim, I hoping the less technical descriptions will be easier to parse.

**Comment by BLFiedler** [comment]
Last meeting we considered the timeline for the change to Joist necessary to add additional buttons and determined it would not align with our goals for Quad's publication. This feature will be developed for another sim or on its own.
