### ISSUE TITLE
Updates for Reset Shape button

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#246]
The Reset Shape button behaves just like the Reset All button when using any input method. 

However, because it is a partial reset, I have provided a hint response. A hint response will help differentiate its function from the full reset button.

![image](https://user-images.githubusercontent.com/1902116/196231370-5db26a26-a5c1-4af0-a2e8-baddccd8dd04.png)

@jessegreenberg, If you have time, you can implement the Hint Response. 

I'd like to ask @BLFiedler at tomorrow's design meeting if he thinks slightly different context responses would be beneficial.

**Comment by jessegreenberg** [comment]
OK @terracoda I added this response.

**Comment by terracoda** [comment]
Thanks, @jessegreenberg . I think the period creates too long of a pause.
I'll see if I can find the string to update it to:
- Keep chosen guides on with reset shape.

**Comment by terracoda** [comment]
I made 2 iterations and like
- Keep guides visible with reset shape.

**Comment by terracoda** [comment]
Just need to discuss context responses with @BLFiedler.

**Comment by BLFiedler** [comment]
Despite the ubiquity of use of "home shape" in the studies, I'm a little uncertain on its use in the sim. I do like either of the sentences that follow.  Should we use one or the other depending on if the shape name is displayed or just opt for the "all right angles, all sides 2 units" to keep it simple?

**Comment by terracoda** [comment]
A single response is totally reasonable. I like that, and I was not super interested in "Home Shape" either, so glad we are in agreement there.

Let's go with:
- All right angles, all sides two units.

I'll see if I can find the string in the code :-)

**Comment by terracoda** [comment]
@jessegreenberg, I updated the context responses. Now we just have one single context response, so you have remove the duplicate.

**Comment by jessegreenberg** [comment]
Looks good @terracoda! I just removed the duplicate. Would you like to review or anything else for this issue?

**Comment by terracoda** [comment]
Nope, I'll go ahead and close.
