### ISSUE TITLE
Clean up Preferences Menu - first pass

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#248]
A few thoughts to tidy up the preferences menu, though we'll likely have more before publication:

### Simulation Tab
- [x] Remove Shape Identification Feedback checkbox. We'll keep the visual indicators that were previously associated with this as default behavior.
- [x] Let's hide the Synchronize Recording button behind a query parameter if possible as it will only be used for research purposes.

### Audio Tab
Since we only have two sound designs we want to focus on, let's 
- [x] Put the Sound Design selection menu on the next line
- [x] Remove all of the rest besides Tracks Build Up Simple and Volume Emphasis. 
- [x] Rename "Tracks Build Up Simple" to "Building (Default)"
- [x] Rename "Tracks Volume Emphasis" to "Shape Emphasis"

Should we change this to radio buttons instead as there are only two? @terracoda, any thoughts?

**Comment by jessegreenberg** [comment]
Front end changes for this request done in the above commits, ready for @BLFiedler  to review. I still have code related to old sound designs to hack and slash out.

**Comment by jessegreenberg** [comment]
OK lots of deletions in the above commits. I think that is enough cleanup for now, removing my assignment.

**Comment by terracoda** [comment]
I think the heading for the "Sound Design" should be either:
- Sound Design Options or
- Shape Sound Options

I'll think about the labels, context responses and help soon.
