### ISSUE TITLE
Keyboard Shortcuts Dialog

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#249]
I still need to create a keyboard shortcuts dialog.

This sim has custom interactions, and may have  hot keys to get to the check boxes.

**Comment by terracoda** [comment]
@jessegreenberg, can you put in a default Keyboard Shortcuts dialog? I'll work what needs to get added.

**Comment by terracoda** [comment]
That is, if there is a "default" Keyboard Shortcuts dialog.

**Comment by jessegreenberg** [comment]
There isn't really a default one but I added some boilerplate and a dialog with "basic actions" has been added. Ready for content whenever!

**Comment by terracoda** [comment]
Thanks @jessegreenberg. That's perfect for now.

**Comment by terracoda** [comment]
Here's an initial rough draft of the Keyboard shortcuts.
<img width="972" alt="kb-shortcuts-blank" src="https://user-images.githubusercontent.com/1902116/198705332-93b76115-f644-4c94-96bd-74ea23bd23bd.png">

I think Voicing shortcut keys will need to go somewhere else, but just noting them here as there is room in this dialog.

**Comment by terracoda** [comment]
Oh, I forgot the Space or Enter shortcut on the corners and sides.

**Comment by terracoda** [comment]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/1902116/198710738-afbfd241-deef-492a-a1ea-7c108ac492c2.png">

**Comment by terracoda** [comment]
This rough, and I'll post the accessible version of the content today.

**Comment by terracoda** [comment]
Oops, I didn't use a dialog with "Toggle checkboxes [Space]. This is a better draft here. I even added [Enter] key to buttons, which we really should add.

<img width="972" alt="kb-shortcuts-blank" src="https://user-images.githubusercontent.com/1902116/198840886-63c13f14-01a1-4617-9a79-1eec4b7fa040.png">

So, main question, what to do with the Voicing Shortcuts. Are the just for Voicing?

**Comment by terracoda** [comment]
@BLFiedler do you have any thoughts about whether the Check Shape, and Reset Shape shortcuts need to be Voicing specific? They should not conflict with screen reader software.And for pressing Space or Enter  on a focused corner or side. I think that's how it might work with screen reader software,though I would need to double check.

**Comment by terracoda** [comment]
I'll assign to @emily-phet and @BLFiedler for comment.

**Comment by emily-phet** [comment]
I think where possible, we should avoid having modality specific shortcuts. Since Voicing is enabling a display, it would be ideal if there were corresponding displays in the visual, etc. Of course, that likely won't work across the board...but an ideal good to aim for. 

I'm not sure what you're remaining questions are - or next steps for this issue. We discussed it prior to the POSE workshop and I can't recall if you still  had remaining questions or needs. Let me know if that's the case. :)

**Comment by BLFiedler** [comment]
I don't think Check Shape and Reset shape need to be Voicing specific.

I'm not certain about the "Enter or Space" for re-voicing the side/corner information. I don't think we have equivalent toggle-able display (it's "always-on" visually). Might be that remains as a sole Voicing specific control?

**Comment by terracoda** [comment]
I think the Space and Enter keys for repeating the object's current state information will be pretty intuitive to learners. I'm not sure we will need to document this. 

I agree that the Check Shape and Reset Shape shortcuts can be general shortcuts. 

I'll update the content.

**Comment by terracoda** [comment]
Ok, here's what I suggest for the accessible content:

H1: Keyboard Shortcuts
Tab to get started.

**H2: Move Sides or Corners**
- Move a side or corner up, left, down, or right with Arrow keys or with letter keys W, A, S, or D.
- With fine input enabled, move in smaller steps with Shift plus Arrow keys or Shift plus letter keys W, A, S, or D.

**H2: Shape Shortcuts**
- Check Shape with ALT plus C.
- Reset Shape with ALT plus Shift plus R. 

**H2: Basic Actions**
- Move to next item or group with Tab key.
- Move to previous item or group with Shift plus Tab key.
- Move between items in a group with Left and Right arrow keys or Up and Down arrow keys.
- Press buttons with Space key or Enter.
- Toggle checkboxes with Space key.
- Exit a dialog with Escape key.
- Reset All with ALT plus R.

**Comment by terracoda** [comment]
Rough visual of above content
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1902116/202000203-5bbcade8-c72a-4e0a-9c62-b3f99493d814.png">

**Comment by terracoda** [comment]
@terracoda to open a issue in scenery-phet for Press buttons and Reset All.

**Comment by terracoda** [comment]
As stated in scenery-pht#789, maybe the ESC key to exit exit a dialog should remain as the last item under Basic Shortcuts.
<img width="972" alt="image" src="https://user-images.githubusercontent.com/1902116/203372910-1b8e5854-028a-435d-bbe3-e7ae87367aae.png">

**Comment by jessegreenberg** [comment]
Lets check in on #283 before adding this.

**Comment by BLFiedler** [comment]
@jessegreenberg and I discussed related to the recent changes

1.) Fine input is being moved to a query parameter and shift modifier is becoming default enabled for mouse and keyboard. We should remove "with fine input enabled" for that item in the dialog.
2.) If we enable Shift+Mouse Drag, should we put that in the dialog as well? Mixed input, but does require keyboard. Would probably be [   Shift    ] + Mouse (icon + text)

**Comment by BLFiedler** [comment]
@terracoda , thoughts on above to implement?

**Comment by terracoda** [comment]
Ok, here's the latest:

H1: Keyboard Shortcuts
Tab to get started.

H2: Move Sides or Corners
- Move a side or corner up, left, down, or right with Arrow keys or with letter keys W, A, S, or D.
- Move side or corner in smaller steps with Shift plus Arrow keys or Shift plus letter keys W, A, S, or D.

H2: Shape Shortcuts
- Check Shape with ALT plus C.
- Reset Shape with ALT plus Shift plus R.

H2: Basic Actions
- Move to next item or group with Tab key.
- Move to previous item or group with Shift plus Tab key.
- Move between items in a group with Left and Right arrow keys or Up and Down arrow keys.
- Press buttons with Space or Enter keys.
- Toggle checkboxes with Space key.
- Reset All with ALT plus R.
- Exit a dialog with Escape key.

**Comment by terracoda** [comment]
How is this for a rough visual?
<img width="972" alt="image" src="https://user-images.githubusercontent.com/1902116/209372121-573cef16-f198-4296-ab79-c4cc459559fd.png">

**Comment by terracoda** [comment]
Or we can have the check Shape shortcut first which is what I originally mocked up.
<img width="972" alt="image" src="https://user-images.githubusercontent.com/1902116/209372597-8fa9bf3b-71c5-43fc-901d-8b3598dc3497.png">

Here's the PDOM text re-arranged.

H1: Keyboard Shortcuts
Tab to get started.

H2: Move Corners or Sides
- Move a corner or side up, left, down, or right with Arrow keys or with letter keys W, A, S, or D.
- To move in smaller steps add Shift key to movement keys or mouse.

H2: Shape Shortcuts
- Reset Shape with ALT plus Shift plus R.
- With Voicing enabled Check Current Shape with ALT plus C.

H2: Basic Actions
- Move to next item or group with Tab key.
- Move to previous item or group with Shift plus Tab key.
- Move between items in a group with Left and Right arrow keys or Up and Down arrow keys.
- Press buttons with Space or Enter keys.
- Toggle checkboxes with Space key.
- Reset All with ALT plus R.
- Exit a dialog with Escape key.

**Comment by terracoda** [comment]
I m not opposed to having a mouse icon instead of the words. I just do not have an icon handy.

**Comment by terracoda** [comment]
I think this unblocks the implementation of the dialog. 
I can always change the wording if people would rather have really explicit language around the smaller steps section. I think this version is nice and simple.

**Comment by jessegreenberg** [comment]
I think it looks great!

**Comment by jessegreenberg** [comment]
I am adding this to the blocks-dev-test because a couple of slightly tricky things need to be sorted out in code.
1) The "With Voicing enabled..." row should not be translatable, and it should only be visible when Voicing is supported (platform and locale checks according to PreferencesModel).
2) The hotkey for reset needs to be added to common code.

**Comment by terracoda** [comment]
@jessegreenberg, regarding the Voicing and translation issue, would this text feel better?

H2: Shape Shortcuts
   - English only, with Voicing enabled Check Current Shape with ALT plus C.
   -  Reset Shape with ALT plus Shift plus R.

**OR**

H2: Shape Shortcuts
   - With Voicing enabled (English only) Check Current Shape with ALT plus C.
   -  Reset Shape with ALT plus Shift plus R.

**Comment by jessegreenberg** [comment]
No need to change in my opinion @terracoda, this content will be totally invisible when not running in English (and when Voicing is not supported on your platform).

**Comment by terracoda** [comment]
Ok, we keep it simple, then :-)

**Comment by jessegreenberg** [comment]
I think this is ready, @terracoda can you please review the dialog now?

**Comment by jessegreenberg** [comment]
I noticed one of the strings was incorrect and missing `lineWrap` fixed above.

**Comment by jessegreenberg** [comment]
Also, these sections didn't have Voicing support. Added above.

**Comment by terracoda** [comment]
Reviewing.

**Comment by terracoda** [comment]
I hear longer pauses at the end of each line in the Basic Actions reading block. 
If possible, it would be nice to hear longer pauses, at the end of the lines for the other reading blocks. I am not sure why the pauses re shorter.

In addition, I need to adjust the strings for Move Corner and Sides. I think I need to spell it all out like we have done in previous sims.

H2: Move Corners and Sides
- Move corner or side up, left, down, or right with Arrow keys or with letter keys W, A, S, or D.
- Move in smaller steps with Shift plus Arrow keys, or Shift plus letter keys W, A, S, or D, or Shift plus Mouse.

I'll see if I ca make the text changes myself.

**Comment by terracoda** [comment]
Ok, I made all changes to visual text in KB dialog and the A11y text in the KB dialog.

I think the nice pause happens if the line ends in an actual word and a period, like "...Tab key." or "Arrow keys.", but if the line ends with a non-word, like a letter key description, "D.", "C." or "R." there is no nice natural pause. 

I'll see if an extra space after the period does anything.

**Comment by terracoda** [comment]
A space after the period does not add any extra pause from the web speech voice.

Neither Alex or Google US English voices added a pause at the end of sentences that end in a letter.

I'll remove the space.

**Comment by terracoda** [comment]
Assigning back to @jessegreenberg in case there is anything code clean-up needed.

I did change the content and order of words in the KB Shortcuts dialog. I am not sure how closely they need to match their corresponding code names.

**Comment by jessegreenberg** [comment]
Looks great! Commits were dd6ee60e79e1e3d0a277a726a005d41883e7930c 9eb68f17859270ce5f6fe6408e6d9ad2c8d0d77d 6f438b68c4a7d38c661af85015f558aa9b7c762a 0f87d2903d6e6c9eb0de8ca1c2eac4527345ae0e. I did update the key names in the json, but otherwise it sounds like this is good to close.
