### ISSUE TITLE
Inconsistencies with different tolerance intervals

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#250]
While testing object responses in #237 using https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.67/phet/quadrilateral_en_phet.html?showModelValues

I hear a tolerance issue here where as Corner C becomes a right angle, it is described as "similar but smaller than Corner B". However, if I click on Corner C, I get the correct description, "equal to one adjacent corner".
Maybe we just are not applying the tolerances in all the same cases?
<img width="905" alt="image" src="https://user-images.githubusercontent.com/1902116/196561466-ad9ad899-1899-4554-8fc8-26bb64a1d362.png">

_Originally posted by @terracoda in https://github.com/phetsims/quadrilateral/issues/247#issuecomment-1283113932_

**Comment by BLFiedler** [comment]
Hm. Noting here that I can move into a right angle with C and hear it as "just under 3 slices" from the above configuration.

https://user-images.githubusercontent.com/47331395/196719372-e5d53c3c-9989-4d1b-b606-8e7a7cad6dc2.mp4

We might need to do a pass and shore up where description is and is not using tolerances. There are a few benchmarks like 90 degrees and "equal" where matching the model will matter. I suspect C in this case is minimally off of 90 degrees but not exact so instead of right angle we get the nearly 3 slices. In this case it will likely need to use `staticAngleToleranceInterval` like we use for the right angle indicators.

**Comment by jessegreenberg** [comment]
> I hear a tolerance issue here where as Corner C becomes a right angle, it is described as "similar but smaller than Corner B".
> I cannot reproduce the above case today, so maybe I interpreted what I heard incorrectly :-)

I created the same shape configuration as https://github.com/phetsims/quadrilateral/issues/250#issue-1415015249 and I am also not hearing this problem, but I suspect it is still around...

> I can move into a right angle with C and hear it as "just under 3 slices" from the above configuration.

Similarly, I recreated this confiruation and was not able to hear this on master. I only hear "right angle".

<details><summary>My shape</summary>

![image](https://user-images.githubusercontent.com/6396244/196734962-7e76999a-dd65-497a-ac7d-3db0e486bf85.png)

</details>

> Noting that for this Trapezoid, we're still hearing that B and C are equal when they are 0.024 radians away from each other (outside of interATI).

I am not able to reproduce this either :(

I thought this issue was going to be about how there are problems because some descriptions about right angle are comparing two corners (using interAngleToleranceInterval) while other descriptions about right angle are comparing to 90 degrees (using staticAngleToleranceInterval). But I am not able to reproduce this yet. Tested on master locally and on phettest.

**Comment by jessegreenberg** [comment]
Wait, I just found a case where this happens - I think this is an input problem, not a tolerance problem. The Voicing response for the corner is always spoken on mouse down. It will speak to you the state of the corner at the start of a drag and may not get interrupted. It needs to voice the full response on mouse UP only if the position hasn't changed.

**Comment by jessegreenberg** [comment]
Done in the above commit. This behavior matches john-travoltage more closesly. @BLFiedler @terracoda can you please confirm this is fixed?

**Comment by terracoda** [comment]
@jessegreenberg, Do you have a dev version, or is it safe to pull from master?

**Comment by terracoda** [comment]
Copied from #237 
In addition, there are a few open issues around tolerances, I will note one here. It might need to be copied over to one of the other open issues.

I hear "adjacent corners equal" for a few steps on other side of 180 when maintaining Convex Quads and Concave Quads. This response is correct for Kites and Darts. And correct for Quads when maintaining a Triangle. 

But I don't think it is correct when maintaining a Convex or Concave quad.

This makes me think we have a tolerance issue when the moving corner goes just above or just below 180 degrees, and the shape is neither a Kite nor a Dart. 

Here's one example
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1902116/196734107-1a2dc754-411e-4525-a2d4-4f60da696281.png">

And more from #237 

> Regarding tolerances, maybe we just don't describe anything about the angle change when the angle change is smaller than the angle tolerance. Would this work?

> I am thinking an angle change that is smaller than the angle tolerance is not a detectable angle change - at least it is a small enough difference that we decided to not show it visually.

> For object response design, if there is no detectable angle change, we can describe direction of movement and prevent the description any other related corner details. That is in the first row of the table in https://github.com/phetsims/quadrilateral/issues/237#issue-1401666374.

And last one from #237 
> I think what I am trying to say is that the change itself has to be bigger than the tolerance.
> Maybe these aren't bugs for tolerances, but bugs for responses? We might just be calling the incorrect response, because according to the tolerances a change didn't happen?

**Comment by terracoda** [comment]
I was using https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.67/phet/quadrilateral_en_phet.html

**Comment by terracoda** [comment]
I've done a fresh pull, and will test.

**Comment by terracoda** [comment]
Today on Master, we found this is still an issue for keyboard... copying some slack discussion here

TS: When using shift key with fine input, heard "right angle, similar but smaller than corner B" instead of "right angle, equal to corner B". The corners are equal. I am not sure why the response changes after turning on fine input and why it sticks around when I turn it off.

JG: I wonder if it is not an issue of tolerance but when the response is triggered. I have a theory it is requested just before the angles become equal. That was fixed for mouse input in https://github.com/phetsims/quadrilateral/issues/250 but maybe not for keyboard. Can you please note in that issue that it is still an issue for keyboard input?

Example:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/1902116/196994270-122b79f0-158f-47b1-93d8-612fb4f5993d.png">

**Comment by terracoda** [comment]
I found this example when moving a corner. Corner C is described as "have as wide as Corner A", but Corner C is just over 90 degrees, so it doesn't have the right angle indicator. I can actually do 2 key presses in the "half as wide" region - that may need adjusting. 

![Image](https://user-images.githubusercontent.com/1902116/198092402-704c876c-fb7e-40f2-a53d-9a23fb61c37c.png)

**Comment by terracoda** [comment]
Here's a Square example
Model says all sides are equal, but the sims says sides DA and BC are just under 2 units whereas Sides AB and CD are 2 units.


![Image](https://user-images.githubusercontent.com/1902116/198159744-d0053978-daf7-4ece-b56f-b233ed0d9bb3.png)

**Comment by BLFiedler** [comment]
> I found this example when moving a corner. Corner C is described as "have as wide as Corner A", but Corner C is just over 90 degrees, so it doesn't have the right angle indicator. I can actually do 2 key presses in the "half as wide" region - that may need adjusting. Both the following values for Corner C are described as "half as wide as Corner A"

I believe the only way to address this is by shrinking the tolerance interval or by adjusting the description is indicate "about half". I'm not sure of another solution here. Can you think of any other cases? I know this is a a particularly potent set of reference points (180 degrees and 90 degrees), but it is also a triangle, which we're not intending to support pedagogically.

> Here's a Square example
> Model says all sides are equal, but the sims says sides DA and BC are just under 2 units whereas Sides AB and CD are 2 units.

Hmmm.. will have to dig in on that one. I know we have some boundary issues at the bottom (#220 ) that have not yet been sorted out. May be related.

**Comment by BLFiedler** [comment]
This will likely be solved by #41 OR is one of the issues that needs to be solved if collision is abandoned (**decision by December 6**)

**Comment by BLFiedler** [comment]
Let's try to reproduce this when #41 is resolved and the grid is resized in #220. Leaving myself assigned until then.

**Comment by BLFiedler** [comment]
Testing moving into and out of this position and to the boundaries for awhile. I don't think this will be reproducible given the adjustments and fixes to the bottom of the grid. Closing. Other tolerances issues bein worked on (all tied to #261)
