### ISSUE TITLE
Object Responses for Moving a Side

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#253]
@terracoda is working on this.

**Comment by terracoda** [comment]
The design of moving side object responses may be affected by https://github.com/phetsims/quadrilateral/issues/212#issuecomment-1290862267 so be mindful of tolerances changes that addressed maintaining a Rhombus and transitions between Square-Rhombus-Parallolelogram.

**Comment by terracoda** [comment]
@jessegreenberg, the design table outlining the [Object Response for Moving a Side](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.ah4lt3elqv06) is almost ready.

These are the progress responses:
- {{parallel}} adjacent sides {{longer/shorter}}
- {{equal}} adjacent sides {{longer/shorter}}
- adjacent sides {longer/shorter}}, (when sides are neither equal or parallel)
- adjacent sides {{change in length}} (replaces adjacent sides change unequally)
- left, right, up, down (already working - same as what we do in other case when there is no discernible change)

These are the state changes that I hope we can call out:
- adjacent sides {{equal}},
- adjacent sides {{parallel}},

And hopefully, these equality events, too:
- equal to {{one adjacent side}},
- two sides equal, (not adjacent to moving side)
- three sides equal, (any three sides)

**Comment by terracoda** [comment]
You can peruse the table, but I am still fixing up the examples, and trying to sort out the logic of the responses. There may be some conflicts at the moment.

**Comment by terracoda** [comment]
Keeping myself assigned to finish clean-up.

**Comment by terracoda** [comment]
The [design table with example Side Object Responses](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.wp80qp4f4ecl) is all cleaned up.

And here's a cleaned up summary of the responses:

### Side Progress Responses:

- {{parallel}} adjacent sides {{longer/shorter}} 
    - When attached sides are/remain parallel (or parallel and equal) as they change in the same way.
    - E.g., Always true for moving the side of a shape in the parallelogram family.
- {{equal}} adjacent sides {{longer/shorter}}
    - When attached sides are equal, but not parallel, and they change in the same way.
    - E.g., Moving one of the parallel sides of an Isosceles Trapezoid in a way that maintains the equality of its equal adjacent sides.
- adjacent sides {longer/shorter}}, 
    - When sides are neither equal nor parallel as they change in the same way.
    - E.g., Can be true when moving a side of a Convex Quadrilateral.
- adjacent sides {{change in length}} 
    - When attached sides change in length in different ways. 
    - **Note:** Same phrase as the Triangle maintenance. 
    - **Note:** This should replace "adjacent sides change unequally".
    - E.g., Can be true when moving a side of a Trapezoid or a Convex Quadrilateral.
- left, right, up, down
    - When side movement makes no discernible change in length to the adjacent sides.
    - **Note:** Already working - same as what we do in other cases when there is no discernible change in length (or angle for corners).
    - E.g., Can be true when moving a side of a Trapezoid or a Convex Quadrilateral.

### Side State Change Responses:
State changes that I think we need to call out. No progress needed here.

- adjacent sides {{equal}},
    - When unequal attached sides become equal.
    - E.g., A Trapezoid to Isosceles Trapezoid.
- adjacent sides {{parallel}}, 
    - When non-parallel attached sides become parallel
    - E.g., A Convex Quadrilateral to a Trapezoid.

### Side State-changing Equality Events
Hopefully, we can also call out these state-changing equality events, if it makes sense to the model:

- equal to {{one adjacent side}}, 
    - When the moving side becomes equal to one attached side.
    -  E.g., when a Kite is found when moving a side.
- two sides equal, 
    - When two random sides (not including the moving side) become equal. 
    - E.g., A right-angle Trapezoid to transition would be a common scenario.
- three sides equal, 
    - When any three sides become equal. 
    - E.g., A common scenario might be maintaining an Isosceles Trapezoid, but maybe Convex and Concave Quadrilaterals also find places where they have 3 equal sides.

**Comment by jessegreenberg** [comment]
Almost done in the above commit @terracoda, the only missing cases now are "two sides equal" and "three sides equal" of Side "State-changing Equality Events". Ill continue that next time, but feel free to try out what is there now.

**Comment by terracoda** [comment]
Just a note that the side object responses are sounding nice in the dev link you have me.

**Comment by jessegreenberg** [comment]
OK this is in place @terracoda, ready for you to review.

**Comment by jessegreenberg** [comment]
Sorry, I forgot to reassign you!

**Comment by terracoda** [comment]
Ok, I have my notes in the design doc. I will post more details here in the morning.
Some responses are not as I would expect, but do not sound incorrect. E.g., some equality events do not fire as I expected, but it doesn't sound incorrect.
Some progress responses are firing more often than I expect, e.g. "adjacent sides change in length".
Some directional progress responses are firing when I think we should hear a length change, e.g. Parallelogram to Rectangle, but it doesn't sound incorrect.

**Comment by terracoda** [comment]
Notes and examples from Design Doc. It's the cases with the responses in red where i have concerns.  
![image](https://user-images.githubusercontent.com/1902116/206482053-1e7443a1-5a65-472e-b0ab-6ebba07693db.png)
![image](https://user-images.githubusercontent.com/1902116/206482180-c886346d-5b91-48ab-a0d6-202ee85872f7.png)
![image](https://user-images.githubusercontent.com/1902116/206482285-ca534e28-8875-4438-bffb-d3c8d2fc5906.png)
![image](https://user-images.githubusercontent.com/1902116/206482412-5d3f27f2-ee4d-44f6-b9ad-c53ec616b1c3.png)
![image](https://user-images.githubusercontent.com/1902116/206482514-8c285a4f-ef89-49f3-9b80-1c5c93e4f999.png)
![image](https://user-images.githubusercontent.com/1902116/206482854-99df64fd-075c-4bb5-84da-2ac4c86fe30e.png)
The rest of the responses seem to be working fine, so didn't copy themintot he issue.

**Comment by jessegreenberg** [comment]
> Often hear direction which is not what is intended.

In order to hear "adjacent sides longer/shorter" the lengths have to have changed by the tolerance interval. We could reduce the length requirement for this alert. This will cause "adjacent sides change in length" to be heard much more frequently.

> Should hear length change but sometimes hear direction.

This should also be fixed if changing the length threshold for hearing about adjacent sides.

> According to model properties, it should be a rhombus but the shape is visually named a parallelogram.

This seems beyond this issue, can you make a new issue if this is still happening?

> For large-ish parallelograms, I often hear direction instead of length change.

Again, seems like the threshold for describing length changes needs to be adjusted.

> Hearing [[adjacent sides change in length]] too often, even when both adjacent sides get longer or shorter, but they are not the same length.

Thanks, I think this is fixed in the above commit. The code was saying "the adjacent sides have to change **by the same amount**", but I think your intent was "the adjacent sides have to change in the same direction (both longer/both smaller)"

**Comment by jessegreenberg** [comment]
OK I reduced the threshold for describing adjacent side length changes by a factor of 3. I am not hearing "parallel adjacent sides longer" when going from square -> rhombus.

@terracoda I think that covers all of your review comments. Back to you to try it out.

**Comment by terracoda** [comment]
Woo hoo. Found a Rhombus when using the keyboard.
![image](https://user-images.githubusercontent.com/1902116/208485656-50b71d82-b5cc-4cba-8ade-209e93513b70.png)

**Comment by terracoda** [comment]
Apologies for the delay on the details. I have cleaned up the design in the design document. They can be found under [Summary of Side Object Responses (Iteration 3) - Ready for Implementation](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.ah4lt3elqv06)

Here's a quick summary of the design change:

- We have one new response, "equal to {{adjacent sides}}". It has to be higher priority than "adjacent sides {{equal}}".
- We don't need the response "3 sides equal", and I am not hearing it in the latest implementation.
- The response, "two sides equal", though working well in latest implementation, it may not be needed. Please leave it in if it is not causing issues for the code.
- **Note:** All the progress responses seem to be working really well in latest implementation.

Examples can be found in [Table: Object Responses for Moving a Side (Examples & Testing Results)](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.wp80qp4f4ecl)

**Comment by terracoda** [comment]
Over to you @jessegreenberg.

**Comment by jessegreenberg** [comment]
I think I got it all in the above commit. 

> We don't need the response "3 sides equal"

Great, thanks! This one was going to be trickier to add.

@terracoda back to you for testing.

**Comment by terracoda** [comment]
Testing Notes Jan 6, 2023 (in progress)
Moving to the spot says "equal to adjacent sides"
I think it should be "equal to one adjacent side"?
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1902116/211099036-a30ab13b-12a0-482a-80d7-bb657b85224c.png">

**Comment by jessegreenberg** [comment]
Thanks for finding @terracoda, I think the above error fixes a problem where the "equal to adjacent sides" string was being used way too much. Can you confirm it is fixed?

**Comment by terracoda** [comment]
Correctly hearing, "equal to one adjacent side" when I find a kite, moving a side:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1902116/211106795-e585a381-8883-410e-9277-c617e0f54507.png">

And here, too:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1902116/211108490-4d8239ad-3a8a-4dbe-954c-24fc15450a7e.png">

I think you fixed it @jessegreenberg

**Comment by terracoda** [comment]
I think moving side object responses are implemented correctly, closing.

**Comment by terracoda** [comment]
I also correctly heard, "two sides equal" at some point before closing the issue.
