### ISSUE TITLE
State Descriptions for Details button 

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#254]
Somewhat related to #244, I am redesigning what we put under the Details button, so the information can be more digestible.

**Comment by terracoda** [comment]
#208 is not a duplicate issue.

In this issue, I am redesigning what we put under the Details button, so the information can be more digestible which is one way to make the details more useful and understandable.

**Comment by terracoda** [comment]
At today's design meeting, I presented the following re-design of the state descriptions that go under the Details button.
![image](https://user-images.githubusercontent.com/1902116/197871830-0c76f4e8-4af2-4427-92d1-3daf141baf9a.png)

@BLFiedler has some concern about "Diagonally opposite corners are equal." being part of all parallelogram descriptions.

Re-thinking and playing with my old design, I realized we have a "general corner description" and a "general side description" that is already implemented, so I am going to look at this again to see if I can keep using those as I try to make the detail briefer and more understandable.

**Comment by terracoda** [comment]
Ok, here's Iteration 2.
Here's the [Details Button table in the design doc](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.sk2kjp3m1xnj) in case I need to correct typos or strings.

![image](https://user-images.githubusercontent.com/1902116/198144039-308a618e-39c6-47c8-9be3-05223c349a55.png)
![image](https://user-images.githubusercontent.com/1902116/198143631-797d63f0-3875-41b5-9cc6-f8fe4a290389.png)
![image](https://user-images.githubusercontent.com/1902116/198143702-1c35b63b-9fc3-4e29-938b-47122625165c.png)
![image](https://user-images.githubusercontent.com/1902116/198143751-6ab26dd2-e8bf-4149-8450-d9f43443af4f.png)
![image](https://user-images.githubusercontent.com/1902116/198143798-2d0e8c61-c85c-4677-8ccd-a2bd800075fa.png)

**Comment by terracoda** [comment]
I still need to sort out the units for area. Here are the words I would like to use
![image](https://user-images.githubusercontent.com/1902116/198144895-c00403ab-b353-42e4-aca7-612ec04c7ae7.png)

**Comment by terracoda** [comment]
@jessegreenberg, I am not sure how to create the Shape Size scale. I will reach out to @BLFiedler in the morning.

**Comment by terracoda** [comment]
Once I have the mappings for the Shape Size we will need to do the following:
[ ] Create the pattern for the first bullets, You have a {{shapeSize}} {{shape/ shapeName}}.
[ ] Remove the corner and side details that come after Detail 1: general corner & side description.
[ ] Add the Shape Property pattern. 
     [ ] Note that in some cases I would like to remove duplicate information.
[ ] I would like to listen to it before we add the strings for units and slices.

**Comment by terracoda** [comment]
I'll move the Scale for Shape Size to separate issue. It could change.

**Comment by terracoda** [comment]
The scale for the shape size is in issue #256.

**Comment by terracoda** [comment]
Copy of table from design doc:
![image](https://user-images.githubusercontent.com/1902116/201975770-2c942d82-7c70-43ad-b190-937047fba237.png)
![image](https://user-images.githubusercontent.com/1902116/201975892-cadab1ab-20b2-4c75-9e21-7f96affe4192.png)
![image](https://user-images.githubusercontent.com/1902116/201975978-bc6b12d4-4c84-4c7e-8714-7e5e571db42b.png)
![image](https://user-images.githubusercontent.com/1902116/201976091-0f31f153-a05d-496a-a43e-23a141649cfe.png)
![image](https://user-images.githubusercontent.com/1902116/201976189-93d5adf1-40a7-4be5-9962-472e261fb446.png)

**Comment by terracoda** [comment]
Discussed {{diagonally}} at design meeting. Do not include this parameter.

**Comment by terracoda** [comment]
Adding updated table for the Details button


![Image](https://user-images.githubusercontent.com/1902116/203359661-9bf6c37c-f5f0-4a5d-a263-c351cbef9377.png)
![Image](https://user-images.githubusercontent.com/1902116/203360251-f915b01d-eb68-496b-a49c-c9f4fa8d029b.png)
![Image](https://user-images.githubusercontent.com/1902116/203360419-3c4b16d6-2106-4067-b20d-31818752d06e.png)
![Image](https://user-images.githubusercontent.com/1902116/203360536-0db6358a-ca48-4ac4-b53c-86d138953bef.png)

**Comment by jessegreenberg** [comment]
Alright, these descriptions have been added @terracoda! Ready for you to have a listen.

**Comment by terracoda** [comment]
The details are sounding great! I have a design update request. 
When the angle is flat (180 degree angle), it would be nice to be able to quantify that. We don't do that anywhere else.
Is it possible to add the slices, so the phrase would be like this:
- Widest corner {{flat and 6 slices}}, smallest corners {{just over 2 slices}}. 

![image](https://user-images.githubusercontent.com/1902116/203659793-89cc1036-df8d-4b6a-b052-b8f4e8b579aa.png)

**Comment by terracoda** [comment]
Actually, "flat" is in the Shape Property Response phrase.
I think we should just say "6 slices"
- Widest corner {{6 slices}}, smallest corners {{just over 2 slices}}.

**Comment by terracoda** [comment]
This was my original thought. Let's go with this if possible.
![image](https://user-images.githubusercontent.com/1902116/203661361-5fa4ffe7-a401-46cd-8d78-04bcb379ffa0.png)

**Comment by jessegreenberg** [comment]
OK, this special case for the details button has been added. Back to you @terracoda .

**Comment by terracoda** [comment]
Sounds good. Thank you @jessegreenberg.

**Comment by terracoda** [comment]
There's one more update for the Details descriptions. Since it was about Shape Size/Area, it's described over in issue #256.

Closing this issue.
