### ISSUE TITLE
Scale for Shape Size (shape area)

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#256]
Let's try something really simple for shape size:

- tiny (Likely, not available with TMQ)
    - < 1 unit squared or < 1 grid cell

- very small (Likely not available with TMQ)
    - = 1 unit squared or < 4 units squared

- small (smaller than a quadrant)
    - = 4 units squared or < 24 units squared

- medium-sized (larger than 1 quadrant and smaller than 2 quadrants)
    - = 24 units squared or < 48 units squared 

- large (larger than 2 quadrants)
    - = or > 48 units squared 

I explored a little with [visual screen shots in the design document here](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.xrm2ys76x6ac).

**Comment by terracoda** [comment]
These descriptions will be in the first phrase of the Details Button.

**Comment by terracoda** [comment]
@jessegreenberg, my ranges for each size are pretty roug, but the idea is:
1. tiny: shape are is smaller than a grid cell
2. very small: shape area is smaller than the starting square
3. small: shape area is smaller than a quadrant
4. medium-sized: smaller than two quadrants
5. large: shape area is larger than two quadrants

If we think of it that way, maybe it will naturally remain in synch, even if the Play Area changes?

**Comment by jessegreenberg** [comment]
Cool, this looks great! Is there another issue for the updates to the details button? Maybe we can track implementation there to see this change in context.

**Comment by terracoda** [comment]
Yes, the associated issue is #254 , State Descriptions for Details Button.

**Comment by jessegreenberg** [comment]
OK, this has been implemented as part of https://github.com/phetsims/quadrilateral/issues/254. Back to @terracoda to review this mapping.

**Comment by terracoda** [comment]
Nice job @jessegreenberg.

I'll have to discuss this with @BLFiedler.

**Comment by BLFiedler** [comment]
Discussed in meeting, @terracoda will add some language around Area as some shapes can have area sizes with contrasting length sizes.

**Comment by terracoda** [comment]
The mappings of the described scale itself are fine, but since size can be ambiguously interpreted (i.e., a long and skinny shape might appear big rather than small) we agreed to reword the first line of the Details to be about "area" rather than size.

We can also name the parameter "QualitativeShapeArea if it isn't already that already. 

**Depending on if shape name is hidden or shown, here are the phrases we need to update:**
- Your shape has a {{{QualitativeShapeArea}} area.
- Your {{ShapeName}} has a {{QualitativeShapeArea}} area.

**Changed from:**
- You have a {{QualitativeShapeSize}} shape.
- You have a {{QualitativeShapeSize}} {{ShapeName}}.

**Screenshot of change in the design document:**
![image](https://user-images.githubusercontent.com/1902116/204620971-fb0299e3-cbef-4aa0-8e27-c68fccc52021.png)

**Comment by terracoda** [comment]
@jessegreenberg, note that with this new wording, we no longer have the contrasting strings of "a small Isosceles Trapezoid " and "an Isosceles Trapezoid"!

I'm not sure you addressed that issue already.

**Comment by jessegreenberg** [comment]
> we no longer have the contrasting strings of

Great its removed from this case! But we still need both for the "You have an isosceles trapezoid response."

This is done in the above commit, can you please review?

**Comment by terracoda** [comment]
Sounds good. Thanks @jessegreenberg.

**Comment by terracoda** [comment]
It's pretty easy to change one's shape a lot, and never change the shape area from "small area", so I am adjusting the ranges.
![image](https://user-images.githubusercontent.com/1902116/208929010-cc6d7b3b-b89b-4497-b631-fdcc47a37f10.png)
![image](https://user-images.githubusercontent.com/1902116/208928479-9a2b1bc0-9d9a-4410-9ba6-c6794c48b626.png)
![image](https://user-images.githubusercontent.com/1902116/208928522-6127fa42-f89a-4c83-92cb-6f0b320e5165.png)

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-c622e6b1-7fff-4a6c-9c42-fd7a70a68b70">

Qualitative Shape Size | Range in Units Squared
-- | --
tiny | < 4 units squared. Note: The “tiny” range is not available with the TMQ, unless pushing the sides together gets smaller than the area of the starting shape (likely not).
very small | = or > 4 units square and < or = 12 units squared. Note: The “very small” range starts at the starting square.
small | > 12 units squared and < or = 24 units squared
medium-sized | > 24 units squared and < or = 48 units squared
large | > 48 units squared. Note: The Max area = 96 units squared.

</div>

**Comment by terracoda** [comment]
@jessegreenberg, I didn't change the number of regions, just the mappings. Over to you for implementation.

**Comment by jessegreenberg** [comment]
Scales changed in the above commit. But the asymmetric equality checks will need much more code that is less maintainable for this, can you confirm that is required before I implement?

After the above commit, the mapping is
tiny:  < 4 units squared
very small: >= 4 units squared && < 12 units squared
small: >= 12 units squared && < 24 units squared
medium sized: >= 24 units squared && < 48 units squared
large: >= 48 units squared

**Comment by terracoda** [comment]
I don't think asymmetric quality checks are required. I just wanted smaller ranges for the very small, small, and medium-sized regions.

**Comment by terracoda** [comment]
So...
- **tiny** should capture shapes with an area smaller than the starting square, that is less than 4 units squared.
- **very small** should capture shapes with an area smaller than or equal to 12 units squared
- **small** should capture shapes with an area smaller than or equal to 24 units squared
- **medium-sized** should capture shapes with an area smaller than or equal to 48 units squared
- **large** should capture shapes with an area greater than 48 units squared

Is that more symmetric?

**Comment by terracoda** [comment]
Is this more symmetric?

- tiny: < 4 units squared
- very small: >= 4 units squared && <= 12 units squared
- small: > 12 units squared && <= 24 units squared
- medium sized: > 24 units squared && <= 48 units squared
- large: > 48 units squared

**Comment by terracoda** [comment]
The ranges in https://github.com/phetsims/quadrilateral/issues/256#issuecomment-1362396197
will work just fine.

**Comment by terracoda** [comment]
Tiny area
<img width="585" alt="image" src="https://user-images.githubusercontent.com/1902116/209180490-1682e1f7-4567-4c8a-aad8-418099b5f597.png">

Very small area
<img width="577" alt="image" src="https://user-images.githubusercontent.com/1902116/209180575-d1115068-476e-4536-8cf9-034a06e25bb1.png">

Small area
<img width="573" alt="image" src="https://user-images.githubusercontent.com/1902116/209180669-0e3fbcb7-1859-4878-976c-107dc51f6ca5.png">

Medium area
<img width="577" alt="image" src="https://user-images.githubusercontent.com/1902116/209180821-9e9079e5-bc6c-4a1f-a0f6-4a44cdb47882.png">

Large area
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1902116/209180940-43bfaf3a-49d0-455d-abd2-ac76a8cbdffa.png">

I think this feels good.
Closing.

**Comment by terracoda** [comment]
I updated the design doc with ranges from https://github.com/phetsims/quadrilateral/issues/256#issuecomment-1362396197
