### ISSUE TITLE
State Descriptions for Hint Button

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#259]
I thought we had an open issue for the Hint button, but I can't seem to find it, so here's what I need changed in the Hint button content:
1. Move the "You have a {{Shape}}" to the the Details button, see #254 
2. Update the content to be: 
"Move sides and corners to change shape properties and explore what shapes you can make. If needed, check out keyboard shortcuts."

**Comment by terracoda** [comment]
@jessegreenberg, note that in Interactive Description we have a paragraph with, "If needed, check out keyboard shortcuts under Sim Resources." In Voicing, we do not have the heading "Sim Resources" read out, so I just left that off.

**Comment by jessegreenberg** [comment]
OK, this has been updated, @terracoda would you like to review?

**Comment by terracoda** [comment]
Verified. Thanks.
