### ISSUE TITLE
Reminder to update icon for Markers Checkbox

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#263]
Since we combined the side unit and angle slices into one checkbox in #243, we may need a new icon that includes side units.

This issue is kind of related related to #190

**Comment by BLFiedler** [comment]
Might need to zoom out a bit farther than one corner to get across the idea. Something that more simply captures something like this rhombus?

![image](https://user-images.githubusercontent.com/47331395/204582689-48fbcefe-1a9c-444a-ba17-ef2ffd97f8b4.png)

**Comment by BLFiedler** [comment]
Alternatively, we could go very simple with just a FontAwesome ruler:
https://fontawesome.com/v5/icons/ruler?s=regular&f=classic
![image](https://user-images.githubusercontent.com/47331395/204583645-9216d8c3-c4e3-44e9-aecc-77847368bf99.png)

Or riff on the idea with their combined ruler and add our corner slices:
https://fontawesome.com/v5/icons/ruler-combined?s=light&f=classic
![image](https://user-images.githubusercontent.com/47331395/204583816-da340b53-0597-4d83-a205-d9b930a515d5.png)

**Comment by terracoda** [comment]
I like the idea of a combined protractor/ruler theme. Are you suggesting we adjust it slightly so it looks like slices and units. This a very rough re-working of the former icon. It would be better it wasn't at 90 degrees.
![image](https://user-images.githubusercontent.com/1902116/204642986-ac17dd60-547f-45b2-92a5-dbb409a22f2c.png)

I can imagine a mix the protractor icon but at an angle between 90 and 180 with fewer tick marks on the rule part, and slices for the protractor part.

**Comment by terracoda** [comment]
Kind of like this, but with adjusted markers and added slices.
![image](https://user-images.githubusercontent.com/1902116/205699144-bfbcff4a-9972-49dc-b798-10e71f567586.png)

**Comment by terracoda** [comment]
Something like a mix of the above and this hand sketch
![protractor-sketch](https://user-images.githubusercontent.com/1902116/206716044-87614a29-f9f2-4139-9b07-7532e1f785b7.jpg)

**Comment by terracoda** [comment]
I think any representation of a protractor-ruler like icon that measures anyway from 180 degrees to about 100 degrees would be nice. I think we should avoid 90 degrees because we do not show the slices in the quad at 90 degrees.

**Comment by BLFiedler** [comment]
@jessegreenberg , would something like TS's sketch be easily done in code, or should I get something drawn up?

**Comment by jessegreenberg** [comment]
I should be able to draw this in code pretty quickly, but Ill report back if I get bogged down.

**Comment by terracoda** [comment]
@jessegreenberg, just an FYI, I would be fine with an angle less than 90 degrees instead of greater than 90 degrees if that works better for size.

**Comment by jessegreenberg** [comment]
OK, initial draw done in the above commit. It ended up being some pretty complicated drawing code! But nice to have without an asset file.

@terracoda @BLFiedler can you please review, any pixel polishes?

**Comment by jessegreenberg** [comment]
During meeting @BLFiedler and @terracoda mentioned that the new icon looks a bit pixelated. The `lineWidth` for the new icon wasn't set to match the others which may explain this. @BLFiedler @terracoda does this look any better?

**Comment by BLFiedler** [comment]
That sounds right @terracoda. I think the quality is fine. Even the edges of some of our panels have aliasing artifacts on my display.

One thing I notice now, we are greater than 90 degrees, but do not see more than 3 slices. Should be more like 3 and a 1/4 slices probably. Is that a simple fix @jessegreenberg ? Still alright asking for an SVG if it feels not worth the effort.

**Comment by terracoda** [comment]
I agree with @BLFiedler, it would be good to have the angle accurately represented.

Values of 105 degrees or 45 degrees might work well. I am open to other values.

**Comment by jessegreenberg** [comment]
Good catch. It looks like arcs are drawn relative to the wrong point, they are being drawn relative to the bottom left corner instead of the inner corner where the sides meet, so all arcs look a bit off center (and the wrong angles are shown).

**Comment by jessegreenberg** [comment]
OK, it is much better after the above commit. It is great to have it in code because it will be easy to tweak. In fact, @BLFiedler @terracoda if you want to play with the look of the icon now you can modify these values in your local copy:

https://github.com/phetsims/quadrilateral/blob/3a795f07f6ec6f5e98e5e5c83781e89d8005a8a4/js/quadrilateral/view/QuadrilateralIconFactory.ts#L47-L55

OK, over to you to review again.

**Comment by terracoda** [comment]
I think the icon looks great. Removing my assignment.

**Comment by terracoda** [comment]
@BLFiedler, I think this issue is ready to close.

**Comment by BLFiedler** [comment]
Agreed
