### ISSUE TITLE
Fix awkward wording one side-length region

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#267]
There is one description that is rather awkward.

It sounds like "Parallel to and similar but longer than" or something like that.

@terracoda to review.

**Comment by terracoda** [comment]
- Parallel to and similar but longer than opposite side, longer than adjacent sides.
I need to check the comparative length scale. in the design doc.

**Comment by terracoda** [comment]
I am not sure I can easily fix this awkwardness.

**Comment by terracoda** [comment]
I looked at this more carefully. I think the "to" after "parallel" is not supposed to be there. I didn't have it in the design doc. And I even have a note in there to make an issue. When I looked at this issue before I think I was just having cognitive overload.

The initial side object response examples in the design doc are like this:
**Without described Markers**
- Square: Side {{DA}}, {{parallel}} {{and}} {{equal to}} opposite side, {{equal to}} {{parallel}} adjacent sides
- Side {{DA}}, {{parallel}} {{and}} {{equal to}} opposite side, {{much shorter than}} {{parallel}} {{and}} {{equal}} adjacent sides
- Side {{DA}}, {{equal to}} opposite side, {{not equal to}} {{parallel}} adjacent sides

**With described Markers**
- Side {{DA}}, {{2 units}}, {{parallel}} {{and}} {{equal to}} opposite side, {{equal to}} {{parallel}} adjacent sides
- Side {{DA}}, {{2}} {{and a half}} units, {{parallel}} {{and}} {{equal to}} opposite side, {{much shorter than}} {{parallel}} {{and}} {{equal}} adjacent sides
- Side {{DA}}, {{just under}} {{4}} units, {{equal to}} opposite side, {{not equal to}} {{parallel}} adjacent sides

I think just removing the "to" after parallel should address this awkward wording.
I'll see if I can find it in the code.

**Comment by terracoda** [comment]
I removed "to" in https://github.com/phetsims/quadrilateral/commit/dc11247dc3a5ade342118ace18b81df623bd6f2e

Now, I have another problem - described parallel sides that are not equal (e.g. parallel sides on trapezoids) are grammatically incorrect. I did not include this example in my list above.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/1902116/221275176-6aff725b-477b-40c8-ab69-739aeaa980be.png">

- Side {{AB}}, {{3}} units, {{parallel}} {{and}} {{a little shorter than}} opposite side, {{similar but shorter than}} adjacent sides

**Ideally, this description should be:**
- Side {{AB}}, {{3}} units, {{parallel to}} {{and}} {{a little shorter than}} opposite side, {{similar but shorter than}} adjacent sides

Unfortunately, in the design doc, I only documented this difference in examples. I did not document it in a parameters table for describing the parallel state.

We only need 2 parameters. I think this can be accomplished in an if/else statement near wherever the "parallelSideObjectResponsePattern" (line 705 in strings file) is being applied.

**If side is parallel && equal to opposite side:**
Use this string pattern:
           "parallelAndEqualToSideObjectResponsePattern": {
        "value": "Parallel and equal to opposite side, {{adjacentSideDescription}}"
      },

**Else (i.e., if not equal to opposite parallel side)**
Use this string pattern:
      "parallelSideObjectResponsePattern": {
        "value": "Parallel to and {{oppositeComparison}} opposite side, {{adjacentSideDescription}}"
      },

@jessegreenberg, assigning to you for comment.
Hopefully, this is totally straightforward.

And not sure if the if statement would be better like this:
**If side is parallel && equal to opposite side:**
Use this string pattern:
           "parallelAndEqualToSideObjectResponsePattern": {
        "value": "Parallel and {{oppositeComparison}} opposite side, {{adjacentSideDescription}}"
      },

The only possible value, I would want in {{oppositeComparison}} would be "equal to" which is why I removed the parameter and the curly braces. Please do what makes the most sense.

**Comment by jessegreenberg** [comment]
Reviewed during check-in meeting today. Ill look into changing the string pattern conditionally.

**Comment by jessegreenberg** [comment]
@terracoda and I met to do this one together and added the new string pattern and logic for this. We reviewed many cases together and @terracoda confirmed it is working as expected. Closing.
