### ISSUE TITLE
Issue with length tolerance interval and description

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#269]
While working on #253 I noticed a case like this:
![image](https://user-images.githubusercontent.com/6396244/205768472-ea8de7bf-f5e8-4751-a4fc-8cf11e9d4e12.png)
 Moving side BC to the right describes "equal adjacent sides longer".

That is accurate within our tolerance intervals but is wrong for a trapezoid and visually. @BLFiedler @terracoda is this an issue or is this acceptable?

**Comment by terracoda** [comment]
To answer your question, I don't think calling the side equal when there are not is acceptable.

We would need "**almost** equal adjacent sides longer"

**Comment by terracoda** [comment]
Some how we need to narrow down when tolerances apply and when they do not.
I think we have struggled with this from the beginning, but I think we are getting much much closer to a solution.

**Comment by jessegreenberg** [comment]
I think you are correct @terracoda, the proposal in https://github.com/phetsims/quadrilateral/issues/261#issuecomment-1339606315 should fix this case.

**Comment by BLFiedler** [comment]
Folding this into #261, as they are at their core the same issue we hoped to solve with the recent step size and tolerance changes.
