### ISSUE TITLE
Should any query parameters be moved into constants?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#278]
@BLFiedler do you think it would be good to move some query parameters to constants as we move toward publication? In constants the values are more clear, stable, easier to find. It isn't a big deal though if you want to continue to modify them on the fly. Or maybe you envision users to be able to customize these in the wild?

**Comment by jessegreenberg** [comment]
Feel free to close if no changes needed, I am mostly interested in knowing what query parameters you intend to be public for teachers (if any).

**Comment by BLFiedler** [comment]
We want to keep `showModelValues` at least through QA, maybe forever.

**Comment by BLFiedler** [comment]
Review after next QA test

**Comment by jessegreenberg** [comment]
Over slack @BLFiedler provided 
![image (5)](https://user-images.githubusercontent.com/6396244/229168784-8b09d1ed-1558-4bce-b4b8-485230582fa3.png)

These are the only public query parameters. Others should be marked private.

**Comment by jessegreenberg** [comment]
OK, I marked those query parameters as `public` and added documentation that the others are intended to be private. This will make it clear that we should not change these in the future, and also adds a nice warning dialog if a teacher gets it incorrect

![image](https://user-images.githubusercontent.com/6396244/229599682-825d77fd-50b0-4503-a650-e4a3f7e34a7b.png)

**Comment by jessegreenberg** [comment]
Closing.
