### ISSUE TITLE
Corner is described as "eqaul to opposite corner", but it is not

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#281]
I am not sure this is a tolerance issue.
Here Corner D is described as equal to opposite corner in two consecutive locations. 

In this Convex Quadrilateral D is 1.601 radians and B is 1.613 and they are described as equal in the moving-a-corner object response, that is when D landed in this spot, the response said "equal to opposite corner"
<img width="842" alt="image" src="https://user-images.githubusercontent.com/1902116/206239490-6c4e641c-42f0-4627-ae8f-99a2da64f057.png">

Then, one more step right, it's still equal and the shape becomes a parallelogram. In this case, the corners are truly equal.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/1902116/206240488-6d24827f-e32f-4771-bfe7-9e8ef0a8ae4d.png">

**Question 1:** Is the first description of equality correct within tolerances? Or is it a bug, should we be hearing, "angle wider" instead of "equal to opposite corner"?

**Question 2:** Is the side lengths of the opposite sides of the Parallelogram are 0.93 and 0.96. All 4 are described as "just under 4 units". Is this okay? The shape is almost a rhombus.

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/207906708-09708dc9-b853-41c1-a91e-c6285e8bf702.png)

Out of context image placeholder

**Comment by BLFiedler** [comment]
Folding this into #261, as they are at their core the same issue we hoped to solve with the recent step size and tolerance changes.
