### ISSUE TITLE
Preferences Menu - Sound Design Section

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#282]
Related to https://github.com/phetsims/quadrilateral/issues/248, Cleaning up the Preferences Dialog, we need Voicing Design a for both the "Sound Design" section under Sounds in the Audio tab, and "Fine Input Spacing" under the Simulation tab.

I'll create 2 issues, this one is for the section "Sound Design" which currently has 2 radio buttons and a checkbox.
**_Iteration 1_**
I sketched out a [voicing design for iteration 1 in the design document](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.br62wujucwrm)
![image](https://user-images.githubusercontent.com/1902116/206747711-b5e8a0e8-cd4e-4fee-a620-72129822d237.png)

I suggest we discuss Iteration 2.

_**Iteration 2**_
**Section heading for radio buttons and checkbox:**
- I suggest "Shape Sound Options" instead of "Sound Design".

**Help text options for radio buttons:**
-  Choose how sound design represents different shapes as you interact.
-  Choose the sound design you hear as you create different shapes.

**Help text options for BOTH radio buttons AND checkbox:**
-  Choose how sound design **plays and** represents different shapes as you interact.
-  Choose the sound design you hear as you create different shapes.

**Names for radio buttons:**
- Layer sounds that emphasize shape properties.
- Play sounds that emphasize different shapes.

**Context responses for radio buttons:**
- Shape sounds increase and decrease with shape properties.
- Shape sounds different for each shape. 

**The checkbox for "Tracks play forever" is trickier.**
- Name for the checkbox:
    - Play Shape Sounds forever when checked in sim.
        - Context responses for checkbox:
            - When checked: Playing shape sounds forever.
            - When unchecked: Fading out shapes sounds.

I also considered a Shape Sound Duration (AB switch), but we do not have a design pattern for an A-B switch. It might be easy, but I have not thought about that aspect of an A-B switch. It might work as a toggle button with 2 names under the hood, not sure.

- Shape Sounds fade out. <--> Shape Sounds play forever.
    - Context responses for checkbox:
        - When toggled right: Playing shape sounds forever when checked in sim.
        - When toggled left: Fading out shapes sounds when checked in sim.

**Comment by BLFiedler** [comment]
Sounds great. Let's largely plan on implementing your Iteration 2, but let's chat about it briefly in Description meeting this week so I understand where each of those suggestions go and to refine our language around each sound design.

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/207687697-fe400cd7-1cfc-4424-9721-1726f05307a4.png)

@terracoda , what about something like this for the visuals?

**Comment by terracoda** [comment]
Yep that looks good and maybe the following Context Responses when things are toggled on and off:

**Context responses for radio buttons (we might not need these responses):**
-    Shape sounds increase and decrease with shape changes.
 -   Shape sounds different for each shape.

**Context responses for checkbox:**
        When checked: Playing shape sounds forever.
        When unchecked: Playing shapes sounds during active transformations.

**Comment by terracoda** [comment]
@BLFiedler, is this issue ready for @jessegreenberg (or you) for implementation?

**Comment by jessegreenberg** [comment]
I feel like the placeholder text will be a distraction for the QA team so I am going to do this quickly now.

**Comment by jessegreenberg** [comment]
This was done. @BLFiedler @terracoda can you please review the new visual text and layout?

@terracoda can you please review the Voicing for this content? I wasn't sure how to do the radio buttons, have we done Voicing for radio buttons before? If so, can you point me to an example? If not, when would you like name/object/context/hint responses be triggered from various input?

**Comment by terracoda** [comment]
- [ ] In first radio button, "(default)" doesn't sound right. I suggest changing "(default)" to "(recommended)", if that design is the preferred use case.
- [ ] Remove "the" in "Choose the sound design you hear as you create different shapes."


**Name Responses and Context Responses for radio buttons...**
- Would shorter names work better?
     - _Name Response:_ Layered shape sounds (recommended)
         - _Upon selection/activation name & context response:_ Layered shape sounds (recommended), Emphasizing shared shape qualities.
     - _Name Response:_ Unique shape sounds.
        - _Upon selection/activation name & context response:_ Unique shape sounds, Emphasizing each shape.

@BLFiedler. Maybe we may only need a Name Response for these radio buttons? The text on the screen can just identify the selected design. Radio buttons are activated on focus/click. Do you think of these names accurately communicate the selected sound design?:
- Layered sounds emphasize shared shape qualities (recommended).
- Unique sound combinations identify each shape.

The Play Forever check box...
- We need permanent context responses for checkboxes. This approach could evolve if there are general changes to how options are turned off and on in the Preferences menu.

Checkbox design:
- Name response: Play sounds forever when checked in sim.
- When checked: Playing sounds forever.
- When unchecked: Sounds fade with pauses in interaction.

Over to you @BLFiedler for some thoughts on polishing the visual text and the responses.

**Comment by BLFiedler** [comment]
I am not sure I have a true recommendation for a sound design. Teachers should pick their preference for their teaching goal. "Default" was just to indicate that Layered is what is (by default) enabled on sim load.

The rest of the suggested design looks/sounds good to me!

**Comment by BLFiedler** [comment]
Also, along with #328 , we'll simplify the implementation of the second sound design to play only one track at a time, which will truly act to differentiate each shape for shape's sake (no property mapping, no suggestion of relation to the rest of the shapes)

**Comment by terracoda** [comment]
Ok, I'll leave "(default)".

If we are only playing one sound for each shape in option 2 ( https://github.com/phetsims/quadrilateral/issues/328 ),

**I think the radio button names should be...**

  - Layered sounds emphasize shared shape qualities (default).
  - Unique sounds identify each shape.

**The Play Forever check box...**
- Name response on keyboard focus: Play shape sounds forever when checked in sim.
    - When checked with mouse or alt input: Shape sounds play forever.
    - When unchecked with mouse or alt input: Shape sounds fade out.

**Comment by terracoda** [comment]
@BLFiedler, we can see how the checkbox goes, but if it doesn't sound good, what do you think of two radio buttons?

In retrospect i think this checkbox needs help text. The names and context responses are too complicated because there is no help text for the checkbox.

- Help text before two radiobuttons: Choose how shape sounds play when checked in sim.
     - Shape sounds play forever.
     - Shape sounds fade out.

**Comment by terracoda** [comment]
I'll mock this up visually and re-post. The changes are getting confusing. Keeping my assignment.

**Comment by terracoda** [comment]
Sorry, Preferences Menu UI components are difficult to get my head around.
<img width="404" alt="soundDesignOptions-radiobuttons" src="https://user-images.githubusercontent.com/1902116/213576477-52bf1fa6-9dde-4832-b251-3ce9884418e8.png">
<img width="404" alt="soundDesignOptions-checkbox" src="https://user-images.githubusercontent.com/1902116/213576493-c2b1edd3-06ef-4917-9b26-c29893d8973d.png">

**Comment by BLFiedler** [comment]
During meeting:

We can borrow from RaP for voiced radio buttons if we want. But maybe it's not worth it.

BF indicated preference for updated label from first mockup in prior comment on first sound design: "Sounds layer to emphasize..."

Over to @terracoda for any Voicing adjustments.

**Comment by terracoda** [comment]
@jessegreenberg, I think this graphic captures the preferred visual design. In the meeting, I think we also decided that "(default)" was not necessary.

<img width="404" alt="soundDesignOptions-checkbox" src="https://user-images.githubusercontent.com/1902116/215098034-e7ae5359-3f88-459c-91ea-4f6d0fb8ba57.png">

As for how the radio buttons should voice, as the above post mentions, please just try using the current name responses. I should work as Focus/Click/Touch events all activate the radio button in Voicing. 

**Note**: I might have to do something slightly different for Interactive Description, but maybe not as in that case, we have web interaction semantics that indicate if something is selected or not. For Interactive Description it is possible for a learner to use the cursor keys and not activate the radio button (i.e., just reading its label). We do not have the cursor key case in Voicing.

**Comment by terracoda** [comment]
@jessegreenberg, also to note, the radio buttons in RaP have context responses, but their actual name responses are very short. Let's see if these Preferences radio buttons will sound ok with only name responses.

**Comment by jessegreenberg** [comment]
These changes were made in the above commits. @terracoda can you please review? A couple of questions, which we started to discuss over slack.

1) Should "Shape Sound Options" be a reading block? Other headings in preferences are not, but they only have 1 item below them. In those cases, the reading block content for the heading is put in some text below it. The reasoning for this was to reduce the number of items in the traversal order. But that might not work as well for "Shape Sound Options" because there is more than one control below the heading.
2) The default Voicing pattern for checkbox is to speak the name response + context response upon selection. Is the default behavior what you intended in this case or does the name response need to be suppressed?

**Comment by terracoda** [comment]
Great Questions Jesse.

**Re Q2 - default voicing pattern for checkboxes**
The checkboxes in the Preferences Menu are atypical. They do not follow the common-code pattern. Where do I document this? This question has come up before. Mouse users cannot get the name response for the Preferences Menu's checkboxes (which tend to have long names) because they toggle the checkbox when they click on it. They will only get the context response that matches the checked state. Keyboard users get the name response on focus, and the context response upon toggling - the name response is suppressed on toggle (i.e., not repeated).

Using an on-off switch for "Play shape sounds forever" would make this entire UI way simpler.

I am thinking people would more more likely to want to play sounds forever before potentially changing the sound design. I am going to propose something different and simpler.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1902116/227221076-8b583325-83ab-401e-afe0-e97191b99960.png">

With this design, "Shape Sound Options" can follow the Preferences Menu reading-block pattern.

And the context responses for the on-off switch would be:
- Play shape sounds forever on. (when toggled on)
- Play shape sounds forever off. (when toggled)

We can leave it to the leaner to figure out that Shape Sounds has to be checked in the sim for this to take effect.

**Comment by terracoda** [comment]
And the sound options should be indented for consistency.
<img width="1021" alt="Preferences-Sound-Options" src="https://user-images.githubusercontent.com/1902116/227231144-50865035-ae4b-4e50-9ebc-1224fb0ce16b.png">

**Comment by jessegreenberg** [comment]
> They do not follow the common-code pattern. Where do I document this?

Sorry, I am not sure. I really like this proposed design though! It was done in the above commits. Can you please review?

**Comment by terracoda** [comment]
Seems like this is working nicely.

**Comment by jessegreenberg** [comment]
Great, thanks! @terracoda will continue to review but this is no longer blocking test.

**Comment by terracoda** [comment]
I found a navigation glitch with the Shape Sound Options radio buttons. The sim crashed.
I'll open a separate issue. This issue is just wrapping up the voicing design and visual design.

I have to re-load to check on those :-)
