### ISSUE TITLE
Preferences Menu - Fine Input Spacing

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#283]
Related to issues #282 and #248 
Here's Iteration 1 of how to turn on Fine Input Spacing.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1902116/206748692-9cc7f30c-fb36-4593-b2ce-4f8b6b1d45c8.png">

Issues I see are that it does say exactly what it does, and it does not explain to keyboard users that they have to use the shift key, although that is proposed to mentioned in the Keyboard Shortcuts dialog like this:
![image](https://user-images.githubusercontent.com/1902116/206749417-5696fbac-1105-4ddd-9fa0-070f3f652155.png)

With those issues in mind I came up with the following 2 options. I am open to other ideas or leaving it as is already designed.

**Same section heading**
- Fine Input Spacing

**Two options for the description paragraph:**
1. Decrease step size for all inputs. Shift key required when using keyboard. Fine input creates more continuous movement and makes it easier to find some shapes.
2.  Increase number of steps between visual grid lines from 5 to 20 for all inputs to create more continuous movement. **Note:** Shift key required when using keyboard, and finer input can make it harder to find some shapes.

**Suggested Context response for toggling on/off switch:**
- Toggled on: Fine input on for mouse, touch and Shift key with keyboard.
- Toggled off: Fine input off for all inputs.

**Comment by BLFiedler** [comment]
Happy to adjust the paragraph - suggesting a hybrid of your suggestions.

- [ ] Change find input spacing description: "Decrease step size for all input devices allowing more continuous vertex and side movement. Note: Shift key required when using keyboard. Fine Input can make it harder to find some shapes."
- [ ] Implement context responses:
   - Toggled on: "Fine input on for mouse, touch and Shift key with keyboard."
   - Toggled off: "Fine input off for all inputs."

**Comment by jessegreenberg** [comment]
Done in the above commits. I also added a line wrap so the description isn't as wide.

However, I wanted to ask if this should be a query parameter? Would a teacher/student need to frequently change this during runtime? We could potentially remove this tab of Preferences if it isn't needed, and also simplify keyboard help dialog. The need to call out complexity of particular input methods adds a lot of words to the sim, maybe this could be moved to teacher tips?

**Comment by BLFiedler** [comment]
Hey, that's a really good point. I'm not sure, having just sort of started to conceptualize the difference in utility between the menu and query parameters as teacher tools.

I would probably ask @terracoda whether it feels valuable to have smaller step size. If so, I would want to make sure it was readily available.. 

My concern with it in the Pref menu currently is that I think you can run into some funky situations if quickly flipping between them (more so from Fine Input to Default, not so much the other way). However, we can maybe smooth that over based on the behavior in #146.

Let's chat about this quickly tomorrow.

**Comment by BLFiedler** [comment]
@jessegreenberg,

Go ahead and toss this into query parameters. We won't advertise, but it should be helpful for our own use and we can point toward it if teachers ask for it.

-[ ] Remove the Preferences Menu Simulation tab, including the Fine Input Spacing toggle.
-[ ] Rename query parameter to `?smallerStepSize` (does this need a =true or does it trigger to true just by invoking it?)

**Comment by terracoda** [comment]
The major and minor steps that we discussed in today's design meeting are good. Fine input spacing is different than the small grid that will be implemented and available without the query parameter.

**Comment by jessegreenberg** [comment]
Done in the above commit. A new flag query parameter was added `smallerStepSize` (no =true necessary). A couple of follow up questions:
1) Are we done with the ClapperBoardButton now? It is still in the simulation tab behind a query parameter. If we are done with it, it would be nice to delete QuadrilateralSimulationPreferencesNode.
2) Should I go through and rename all "fine input spacing" references to "smaller step size"? Including query param `?fineInputSpacingToleranceIntervalScaleFactor`/`majorFineVertexInterval`/`minorFineVertexInterval`?

**Comment by BLFiedler** [comment]
> 1. Are we done with the ClapperBoardButton now? It is still in the simulation tab behind a query parameter. If we are done with it, it would be nice to delete QuadrilateralSimulationPreferencesNode.

Answered in Slack:
BF: Yeah. We can add it back in for any study we do in the future.

@jessegreenberg ,
- [ ] Remove the clapperboard from the sim and delete the Simulation tab in the Pref menu.

> 2. Should I go through and rename all "fine input spacing" references to "smaller step size"? Including query param `?fineInputSpacingToleranceIntervalScaleFactor`/`majorFineVertexInterval`/`minorFineVertexInterval`?

We'll probably want to get rid of these query parameters and just set them as the default behavior for the query. Let me toy with things and make sure the values are what they should be and then we can just integrate them.

@BLFiedler ,
- [ ] Find best values for `?fineInputSpacingToleranceIntervalScaleFactor`/`majorFineVertexInterval`/`minorFineVertexInterval` and assign JG to bake into the `smallerStepSize` query.

**Comment by jessegreenberg** [comment]
Thanks! Removed in the above commits.

**Comment by BLFiedler** [comment]
updated query parameter defaults for smallerStepSize step sizes and tolerance adjustment in above commit

@jessegreenberg, go ahead and
- [ ] Remove `fineInputSpacingToleranceIntervalScaleFactor`/`majorFineVertexInterval`/`minorFineVertexInterval` query parameters and bake them into the default values of the `smallerStepSize` query parameter.

**Comment by jessegreenberg** [comment]
I realized we have ?smallerStepSize and "Small steps" now in this sim which are two different features. Over slack we discussed renaming ?smallerStepSize (which was previously "fine input spacing") to "reduced step size".

**Comment by jessegreenberg** [comment]
There is more to clean up here but it can be done later, I think.

**Comment by jessegreenberg** [comment]
Hmm...Ive lost what I still wanted to do here. I searched two-word and camel case combinations of "fine input" and "smaller step" and everything is now correctly referred to as "reducedStepSize". 

Hopefully the cleanup I wanted to do was done in other issues during code review.

I think this can be closed.
