### ISSUE TITLE
Bug when activating Voicing

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#288]
While showing a demo, @terracoda pressed the control key and clicked on the Voicing toggle switch. The Voicing toggled between enabled/disabled state rapidly. This was in Safari. What happened?

**Comment by jessegreenberg** [comment]
Cannot reproduce on Windows 10 Chrome.

**Comment by terracoda** [comment]
I was using Safari

**Comment by terracoda** [comment]
Oops. Did not mean to close.

MacOS 12.2.1 and Safari 
More importantly I was using Quad dev version 71.
I was also sharing my screen.
I was trying to Silence Voicing while demoing the Voicing section of the Audio Tab. 

I held down the Control Key and then clicked a few random things, not sure which ones, but I think it was the Voicing on/off switch.

The Voicing feature starting toggling on and off on its own. I think it did this 3 or 4 times.

**Comment by jessegreenberg** [comment]
@terracoda and I investigated. It seems to be a problem with the right click context menu. A ctrl + left click is equivalent to a right click in macOS. https://www.macrumors.com/how-to/right-click-on-a-mac/#:~:text=The%20Control%2DClick&text=Holding%20down%20the%20Control%20(Ctrl,on%20a%20two%2Dbutton%20mouse.&text=The%20Control%20key%20performs%20the,while%20holding%20the%20key%20down.

When that happens the browser does not provide an 'up' event and so the switch gets stuck pressed. It moves with drag events without the mouse being down.

**Comment by jessegreenberg** [comment]
This is a larger scenery issue for all mouse presses in macOS with the control key, this is going to be tracked in 
https://github.com/phetsims/scenery/issues/1511
