### ISSUE TITLE
Tab Order Change - Start with Corner A

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#289]
Interview feedback from participant with low vision.

It was confusing to land on Side DA first. The letter themselves a re somewhat difficult to process., so getting the letters in order should make these shape details a little easier to grasp.

The new tab order should go back to starting with Corner A, so:
1. Corner A
2. Side AB
3. Corner B
4. Side BC
5. Corner C
6. Side CD
7. Corner D
8. Side DA

Our initial reasoning to change to starting with a Side was to limit how much the shape changes on initial movement to support non-visual learners. There have been many changes to the description and sound design since that decision, so we feel very comfortable with going back to starting at Corner A.

**Comment by jessegreenberg** [comment]
@terracoda this was done. Closing.
