### ISSUE TITLE
Implement shift modified mouse drag and set default mouse drag to majorVertexInterval value

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#291]
While aiming to focus on larger step sizes for scaffolding and reducing tolerances to ease description mismatch, we would like to keep with the shift modifier for keyboard.

We plan on discussing possibly implementing a "sticky" UI toggle for smaller steps (useful for touch), but decided it would be nice for mouse to mimic keyboard.

@jessegreenberg indicated it should be possible in Slack.

- [x] Investigate and implement shift+mousedrag to switch to `minorVertexInterval` when pressed.

**Comment by jessegreenberg** [comment]
It would be ideal if KeyboardListener behaved a little differently so that it fired on both key down and key up instead of either/or. Currently I need to use two KeyboardListeners to support this, Ill take a look at KeyboardListener to see if it can better support this kind of thing.

**Comment by jessegreenberg** [comment]
OK, done - @BLFiedler can you give it a try?

**Comment by BLFiedler** [comment]
Wooo! Look goods. Some behavior related to #292 that @terracoda brought up that I'll bring up there related to mouse input.
