### ISSUE TITLE
Vertices/Slide can jump when I click to check side length

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#297]
From #296

> **I found 1 bug when I use mouse clicks to check the side length.** 
> If I click on a side to get the length, and the side is slightly off the grid, the side's vertices sometimes jump to the grid line, changing the shape with a click.
> 
> Example: I had this quadrilateral
> <img width="585" alt="image" src="https://user-images.githubusercontent.com/1902116/209153239-824c3289-297a-4ecb-88f4-79ee528d1978.png">
> 
> And I then did a mouse clicks on on Sides BC and CD, and then DA to check the lengths. Sides BC and CD did not move, but then when I clicked on Side DA corners D and A simultaneously jumped onto the grid.
> <img width="583" alt="image" src="https://user-images.githubusercontent.com/1902116/209153423-80da8415-43cc-44a8-a5c4-b97143ef106f.png">
> 
> The jumping does not happen all the time. I am going back forth with shift key modifier for mouse and keyboard. It might be connected to that.

**Comment by terracoda** [comment]
Maybe the above is intended behavior? Or slightly misplaced intended behavior?

I think the intent to that if I am not pressing the shift key and I try to move a side with mouse, the vertices are going to jump to align with the nearest grid lines.

Can we make sure there is a noticeable change in position before we jump the vertices?  If I am just clicking the side length and not actually dragging the side, the side's vertices should not jump.

**Comment by BLFiedler** [comment]
Closing this and referencing in the original issue (#291) which hasn't been fully reviewed and closed yet.
