### ISSUE TITLE
Toggle for sticky small steps and UI rearrangement

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#298]
For convenience for mouse/keyboard and to allow for small steps on touch, we'd like to add a toggle that sets majorVertexInterval = minorVertexInterval. 

Notes:
- Default off
- Shift key will not do anything when this is toggled on.
- The "snap to" major grid behaviour present for the default keypress should not happen. Only small steps should occur.
- Toggling off the stick small steps should not automatically jump to the major grid. We still want input to do that as designed in #292 
- Let's use the 'rocker' toggle component like the pref menu for now as a first pass for testing
- We'll need description for the toggle.

@jessegreenberg ,
- [x] Implement the toggle described above with the name "Lock to small grid" for now (open to shorter or more descriptive names)
- [x] Place it below the checkboxes, replacing the shape sound checkbox. Move the Shape Reset button just to the right of the Shape Name display. Move the shape sound checkbox just to the right of that. You can distribute so the edge of the shape sound icon aligns with the right edge of the play area.

@terracoda ,
- [x] Design the name, context, & object responses for this button.

**Comment by BLFiedler** [comment]
I made a rough mockup here just to see. It's likely going to be a little crowded. 
![image](https://user-images.githubusercontent.com/47331395/209202051-cbec0a57-d580-4eeb-9bd0-a2ed3424bf70.png)


Perhaps we should shave a little bit of the shape name display if possible to make some more space?

![image](https://user-images.githubusercontent.com/47331395/209202002-19274035-e6a7-48e5-be12-fad6f8ef5d56.png)

**Comment by jessegreenberg** [comment]
Done in the above commits. Ready for further design.

For the ToggleSwitch, I went with the size that we use in the Preferences dialog. But with default colors. The track fill for left/right values can be changed, as well as other things if you want to change the look. Layout of the label is custom for this sim, we can change that too however you see fit.

**Comment by terracoda** [comment]
In Ratio Proportion we have a checkbox that toggles a lock for the ratio between the hands.
Here's the Voicing design (for reference only). 

- Name: Ratio Lock
- Help text: Move hands as a single unit with ratio locked.
    - Note this particular lock becomes/is disabled when the hands are knocked out of ratio or are not in ratio to begin with on focus. With Interactive Description there is special help text when the checkbox is disabled: "Enabled when hands are at challenge ratio."
- When checked/locked: Hands locked at challenge ratio. Move hands and observe.
- <img width="109" alt="image" src="https://user-images.githubusercontent.com/1902116/210429077-d8add3ef-b025-43a8-a9e3-d98aa570709a.png">
- When unchecked/unlocked: Hands no longer locked.
- <img width="111" alt="image" src="https://user-images.githubusercontent.com/1902116/210429008-530e6bc7-e787-44e6-8e5c-6a56697b4761.png">


The interaction for locking access to movement on the small grid should be more straightforward in Quad.

**Comment by terracoda** [comment]
In Area Model Algebra, there is a Grid check box and then 2 radio buttons that toggle the representation of the grid
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1902116/210592761-64f43d67-08fa-4a7c-b597-35b310dd75c6.png">

In Ratio and Proportion, we have a combobox for choosing the number of tick marks. I wonder if either of these interactions would simplify the idea of choosing the grid size?
<img width="199" alt="image" src="https://user-images.githubusercontent.com/1902116/210593755-65202656-d9fb-48ed-9c83-3457e9ef85fd.png">

**Comment by terracoda** [comment]
Ok, I brainstormed several idea in this google doc, [What to do with Grid - Large and Small?](https://docs.google.com/document/d/1Nez_i22dUb_T1193UGg5VQE66CDS7gU0Tl5DNcwuSF8/edit#) and I think maybe that a combobox might work well.

The Voicing Design pattern is the same as the one for the Range combobox in RAP.

**Comment by terracoda** [comment]
Assigning to @BLFiedler for comment and assistance.

**Comment by terracoda** [comment]
I'll add a lock-adorned checkbox to the google doc, too.

**Comment by terracoda** [comment]
I added a lock button interaction to the google doc. It could be changed to a checkbox if necessary. Buttons, however are more flexible as they are activated by both Enter and Space keys.

**Comment by terracoda** [comment]
From slack: 
I added a Lock interaction - a button with a dynamic name. I think this will work.
@jessegreenberg is this type of button straightforward to implement. To me it would be the same type of interaction as BASE's Add/Remove Wall button.

@jessegreenberg: Should not be a problem.

**Comment by terracoda** [comment]
Let's go with something like this:
<img width="249" alt="small-steps-unlocked copy" src="https://user-images.githubusercontent.com/1902116/210664276-5ec880db-4049-4fd3-a634-69a45bbd84a4.png">
<img width="249" alt="small-steps-locked copy" src="https://user-images.githubusercontent.com/1902116/210664266-ee880cc3-7036-4ba9-8f24-bcc6ce0c2180.png">

Voicing Responses are as follows:
Dynamic Name Responses:
- Small Steps Unlocked
- Small Steps Locked

No Object Responses

Dynamic Context Responses:
- Upon locking: Corner and side movement locked to small steps.
- Upon unlocking: Small steps no longer locked. Add Shift key to make small steps.

Static Hint Response (only on focus of button)
- When locked, move corners and sides in small steps with or without visual grid.

This [Table: Small Steps, button with dynamic label](https://docs.google.com/document/d/1Nez_i22dUb_T1193UGg5VQE66CDS7gU0Tl5DNcwuSF8/edit#heading=h.g677lhghuijk) lays out the responses by input if the above is not clear.

**Comment by terracoda** [comment]
@jessegreenberg, let me know if you have any questions. I think this button interaction will work better and is more simple to voice (and describe) than the ON/Off switch which is currently implemented visually.

**Comment by terracoda** [comment]
- [ ] Implement new type of toggle button with dynamic lock icon
- [ ] Change tab order, so this interaction come right before the Reset All button
- [ ] Implement Voicing responses as described above

**Comment by jessegreenberg** [comment]
I can do this, but I can't help but think this is a checkbox with extra steps/more complexity. Why does it need to be a button? Why does it need a dynamic name response, could the object response handle that? Could we use the same component as RaP?

**Comment by jessegreenberg** [comment]
In the above commit I added a Checkbox with a lock icon using the same Voicing strings you have but organized into the Voicing design for a checkbox. The Voicing output is the same.

I used: 
Name Response - "Locked"
Object Response - "Locked"/"Unlocked"
Context Response - "Corner and side movement..."/"Small steps no longer..."
Hint Response - "When locked, move..."

Implementing this, it made me wonder why we are using "Locked" terminology for this and maybe that is what is making the Voicing design harder? We are letting the user choose between big steps and small steps. We are not really locking to anything. Should we get rid of the lock icon and words?

@terracoda @BLFiedler  can you please try master and review comments? If if you still think it is best to use a new UI component, let me know and Ill proceed with the original design.

**Comment by BLFiedler** [comment]
I think the idea of "locking" is perhaps only helpful if you're aware you can access the small steps without pressing that checkbox/toggle/button. I see the confusion potential without that being explicit (like the idea archived in #307). I'm okay doing away with the lock icon and vocab.

However, I'm still not very excited about a checkbox, since it does something quite different than the other checkboxes in the sim (changes how you interact with the sim, not just adjusting the information provided). I'm alright with a simple "on/off" toggle as it was, but I don't see that being used like that in any other sim...

Maybe we do just go the big radio button route a la RaP and a lot of the other math sims and use these two:

### Shape Step Size
(Default large steps) https://fontawesome.com/icons/table-cells-large?f=sharp&s=solid
![image](https://user-images.githubusercontent.com/47331395/211041659-4a561c08-f0ec-4398-affc-90bb514a2169.png)

(Small steps) https://fontawesome.com/icons/table-cells?s=solid&f=sharp
![image](https://user-images.githubusercontent.com/47331395/211041684-821e488c-a69a-4b62-822f-f1fc59ef7241.png)

@terracoda ?

**Comment by jessegreenberg** [comment]
> With Voicing no interaction semantics are communicated, and this blurs the experience for keyboard users and blind learners.

IMO, this is a non-issue because Voicing was not meant to be used by blind learners.

But I understand a lot of thought has gone into this, and I am happy to proceed with the original design. I don't think I agree with it, but I feel like my feedback has been heard.

**Comment by jessegreenberg** [comment]
After some slack discussion we are going to go ahead with the original design. Back to me.

**Comment by jessegreenberg** [comment]
OK, a new toggle button was added that implements the design in https://github.com/phetsims/quadrilateral/issues/298#issuecomment-1371521512. When pressed, we voice the name and context response. @terracoda can you please review this?

**Comment by terracoda** [comment]
I love the name-changing button

<img width="159" alt="image" src="https://user-images.githubusercontent.com/1902116/211119344-73e826fa-09d8-4207-bc51-ad55aa22035a.png">
<img width="161" alt="image" src="https://user-images.githubusercontent.com/1902116/211119459-a9fc9b17-5893-40d6-a97b-8eb92b391fec.png">

It's distinct form the checkboxes, is operable with Space and Enter keys, Voices well, and should work with screen reader if we ever turn on Interactive Description.

I think I can shorten one context response:
- From: Small steps no longer locked. Add Shift key to make small steps.
- To: Shift key needed to make small steps.

And change the hint response:
- From: When locked, move corners and sides in small steps with or without visual grid.
- To: When locked, corners and sides move in small steps.

Hopefully, I can do this myself.

**Comment by terracoda** [comment]
Ok, with Jesse's help I was able to commit my updated responses.

I think this issue can be closed.
