### ISSUE TITLE
Visual quarter and half ticks for the quadrilateral

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#299]
The description indicates the side lengths in quarters (#296) . Let's do the same visually.

Let's do a ruler style ticks along the outer edge of the shape at each quarter for each side length. Let's also differentiate the quarter / three-quarter from the half by making it longer as you often find on measurement tools. For simplicity the tick mark for 1/4 & 3/4 can be one-quarter of the width and 1/2 can be one-half of the length, since we're trying this only on one side of the shape (rather than both inner and outer).

Over to you @jessegreenberg ,

- [x] Implement the previously described visuals when Markers is checked.

**Comment by jessegreenberg** [comment]
Done in the above commit. Ready for review and/or polishing.
