### ISSUE TITLE
Implement Voicing Responses for Transformations

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#30]
Initial responses have been drafted for simple transformations from a side-focused interaction perspective.

More details can be found under [Voicing in the Tangible Space ](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.tobh0kd0keks) section of the Voicing Design Doc.

### Initial Implementation Plan:
- What is the Max - min range for the quad device?
- Can we divide that range of “proximity to parallel” by 7? I have eight described regions, but “in parallel” is a single-value region, or at least a tiny range.

### Parameters for Object Responses
Example phrases: 
- Moving both sides: “tilting {{opposite}} side{{s}} {{right}} {{in}} parallel”
- Moving a single side: tilting {{right}} side {{right}}, {{opposite}} side{{s}} {{not so close to}} parallel

**Side Name Parameters:**
- opposite
- right
- left 
- upper
- lower 

**Direction Parameter:**
- up
- left  
- down
- Right

**Side Plural/Singular Parameter:**
- sides
- side

**Proximity to Parallel Sides Parameter (8-point scale)**
Please evenly distribute regions across the range (hope this is possible), and make “in parallel” match whatever is currently determining that state for the sound design.
- extremely far from
- very far from
- far from
- not so close to
- somewhat close to
- very close to
- extremely close to
- in

### Parameters for Context Responses
The parallel state context responses seem like full-phrase parameters.
**Parallelogram State Parameters:**
- Keeping a parallelogram. (movement that maintains a parallelogram)
- You lost your parallelogram. (movement that loses a parallelogram)
- You made a parallelogram. (movement that creates a parallelogram)

There are two simple progress phrases  - tracking progress towards a parallelogram
Example phases:
- {{Closer to}} a parallelogram. (movement that results in moving closer towards a possible parallelogram state)
- {{Farther from}} a parallelogram.  (movement that results in moving further away from a possible parallelogram state)
-  **Progress parameters:**
    - Closer to 
    - Farther from

**Comment by jessegreenberg** [comment]
@terracoda I think the only question I have so far is at what interval should we hear "Keeping a parallelogram" when interacting with the quadrilateral? Is it repeated for as long as the shape is changing, or once every amount of change in the model, once every amount of time?

**Comment by BLFiedler** [comment]
Not sure if we arrived at a concrete answer here, but I think I like the latter ("once every amount of time"), starting at a pretty long time (Maybe 5ish seconds?) and seeing how it feels. Something that is an occasional reminder of what else you're hearing if you're using the sound, but often enough that you're not left out in the dark if you're not?

How does that sound to you @terracoda?

**Comment by terracoda** [comment]
I agree, we can't keep saying descriptions like we are playing sonification.

For keeping a parallelogram we could try every 2 seconds.

And when not a parallelogram, we have proximity-to-parallel regions on the object responses, so the situation is a bit more nuanced. I don't know how big the regions will be, but in previous work, at least in Interactive Description I have tried to find a balance between  number of keypresses and repeating the same region. 

Once the parallelogram is lost, we'll have region-based object responses and the other progress-oriented context responses. 

We could use the same strategy (every 2 seconds) with mouse, but with key presses it will probably need some tweeking once we can feel our way through the regions.

**Comment by terracoda** [comment]
@jessegreenberg, is that enough to go on? Don't spend too much time at it. Having any words thrown at me will help me check what needs to change.

**Comment by terracoda** [comment]
I am totally not sure how the regions will work.

**Comment by terracoda** [comment]
@jessegreenberg, can you have a look at the table marked Iteration 2!
https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.2rsp6zqlvmqf

The phrases are very similar to Iteration 1, but I moved the information about the changing sides over to the context response column. This feels better to me, and the object responses become much simpler.

**Comment by terracoda** [comment]
In today's Quad Description meeting, we discussed that it might be hard to do determine "Closer to" and "Farther from" a parallelogram. So let's leave that off for now.

**Comment by jessegreenberg** [comment]
Collecting questions as I implement:
- How do we describe "up" vs "down" when tilting top and bottom sides? Thought about describing clockwise/counterclockwise change instead.

**Comment by terracoda** [comment]
The tolerances are messing with these kinds of state descriptions.
For example, I can start with a rhombus/parallelogram and then move a side to make the shape smaller and then have a trapezoid and not a parallelogram.

I don't know what to do about this.

**Comment by BLFiedler** [comment]
See if things are a bit better setting `?angleToleranceInterval=0.05`. I found that alright with Cursor input and few problem areas with keyboard input.

**Comment by jessegreenberg** [comment]
I implemented table 1 in the design doc, @terracoda has a second iteration that should be implemented. Ill change what is in place to the organization of that table then build a dev version. @terracoda is going to think about a design where we have "tilt" in the context response. The table has a few options for each response, @terracoda said I should use the first one for each for now.

**Comment by terracoda** [comment]
@jessegreenberg and I met after today's description design meeting.

While @jessegreenberg  is implementing the iteration 2 above, I am going to try to think about the object response as moving a thing, and maybe that is not needed when using the Tangible device. And then I am going to think about the full context of what's happening with the shape - maybe that the shape  is leaning/tilting/straightening, and the key details you need to about the change that is happening to the shape.

**Comment by jessegreenberg** [comment]
Here is a new dev version with these: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.14/phet/quadrilateral_en_phet.html?showPointerAreas

A couple of things:
1) I went ahead and implemented the proximity to parallel descriptions.
2) I made the in parallel/out of parallel utterances higher priority so they are always heard/never interrupted.

I think it sounds really good, your design really came together @terracoda! Assigning to you to review.

**Comment by BLFiedler** [comment]
It does sound nice! Love having some voicing in place. I agree with your assessment in slack @terracoda 

> Even if the context responses, it not always clear which pair of opposite sides is "close", "far", etc from parallel, but is clear something is wonky and needs exploration.

That seems to be the biggest missing piece to me with all checkboxes checked. To me, what we're hearing feels good as context responses knowing what I'm moving visually, but if I didn't have that quick check of the pairs of sides I'd feel a bit confused. (I've only tried cursor input so far)

**Comment by terracoda** [comment]
There will be significant changes to these context responses. @jessegreenberg is it ok to work in the same issue?

**Comment by terracoda** [comment]
I'll close this issue as the design work for context responses is complete and being implemented in #143, #144, #146, #154.
