### ISSUE TITLE
Change Grid to display both minor and major grid (like our showVertexGrid query)

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#300]
During our last meeting, we thought the appearance of a thickness differentiated grid looked pretty good and integrates well with the step size changes  / shift modifier defaults.

Let's make that default when Grid is checked.

@jessegreenberg,

- [x] Change grid to display minor grid as well as major grid whenever Grid is checked.
- [x] Remove showVertexGrid query parameter and cleanup related code as you see fit

Edit: Forgot these details. This looked pretty good on my setup for linewidths playing with the query parameter.

![Image](https://user-images.githubusercontent.com/47331395/209181559-c61861f9-fc03-4dae-992b-e1487e0a36ba.png)

**Comment by jessegreenberg** [comment]
Ready for review, @BLFiedler how does this look?

**Comment by BLFiedler** [comment]
Works for me! I noticed the Grid became default on at startup. Can we return it to off by default?

Good to close after that.

**Comment by jessegreenberg** [comment]
Thanks, sorry about that. It is off by default again. Happy 300 issues, closing.
