### ISSUE TITLE
Possibly change "angle flat" to "6 wedges"

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#309]
Related to #295, describing the angles as "wedges" sounds really good.

I might want to change the stative object response for the value of 180 degrees from "angle flat" to "6 wedges".

Reasoning copied from other issue:
> 
> There is one object value/state, the 180 degree "angle flat" state that is described as "angle flat". Since the wedges are showing (not like in the right-angle state), I think it would be good to describe this state as "6 wedges".
> 
> I'll create a new issue for this and see if I can make the change myself. I don't want the change to affect the context response that says, "angle flat, two side look like one". I think that's a context response.

**Comment by terracoda** [comment]
@jessegreenberg, where are the text-based parameters defined? 
Is this textual change easy for me to try out?

**Comment by jessegreenberg** [comment]
Sure! "angle flat" is used in two places:
1) Whenever "wedges" are described.
2) In the vertex change object response.

You can change both at the same time changing this string value
https://github.com/phetsims/quadrilateral/blob/61f80797ec24fa9f172acec2d86307ce0a766800/quadrilateral-strings_en.json#L538-L540

to
```js
      "angleFlat": {
        "value": "6 wedges"
      },
```

**Comment by terracoda** [comment]
@jessegreenberg, I made the change so that only the object responses use "6 wedges". I think this sounds good. The context responses still "flat" descriptions.

Assigning back to you in case there is code clean-up to do.

**Comment by jessegreenberg** [comment]
OK, great!  Commits were 0a1d9de5975717c4d7d7a04b706a399c486592d2 and ff18d3d717d1b51d5049ccf7764ae962a58bbacd and they look good.

@terracoda when you make commits, would you mind linking them to the issue? You can do that by pasting the issue URL in your commit message.

**Comment by jessegreenberg** [comment]
Closing.
