### ISSUE TITLE
(Voicing) Implement content for read me buttons

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#31]
I have drafted some possible descriptions for the three read-me buttons. More details and versions in the [Read-Me Button](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.vj0ds4r6fj6y) section of the Voicing design doc.

Let's go with  these as a starting point:

### Play Overview Button (static content):
- A quadrilateral is a closed four-sided shape. This quadrilateral is an interactive sim. It changes as you play with it. There are four grabbable sides and four grabbable corners. You have the power to change the shape and explore what makes a parallelogram. You can also reset the sim.

### **Play Details Button {{dynamic content}}:
1. Currently, your shape is {{a parallelogram}}, and {{a rhombus}}}}.  

**Parameters for named quads that are parallelograms:**
    - square
    - rectangle
    - rhombus

2. Currently, your shape is {{a trapezoid}}, and {{not}} {{a parallelogram}}.
- Iteration: Currently, your shape is {{not}} {{a parallelogram}}. It is {{a trapezoid}}.

**Parameters for named quads that are not parallelograms:**
- kite
- isosceles trapezoid
- trapezoid
- con-caved shape??

### Play Hint Button (static for now)
- Play with sides and corners and explore what makes a parallelogram.

**Comment by jessegreenberg** [comment]
Looks good @terracoda Ill get started on this and the voicing. The part that we have not discussed yet for the virtual model is detecting the named shapes. Most seem easy enough to detect with existing model Properties except for kite.

@terracoda and @BLFiedler is this the best way to determine if a quad is a kite? https://socratic.org/questions/how-do-you-prove-that-a-shape-is-a-kite? Do we need to calculate the bisectors/angles at the bisector? Do we need new tolerance intervals for this?

**Comment by jessegreenberg** [comment]
In that example, is it sufficient to check the sides like this?
![image](https://user-images.githubusercontent.com/6396244/141510416-011b159b-dfb2-4709-bf35-a844703f7659.png)

**Comment by terracoda** [comment]
The definition of kite above seems good, and I'd prefer @BLFiedler way in on this.

**Comment by BLFiedler** [comment]
I think this is optional information, so I'd like to avoid any special circumstance variables being introduced (like new tolerance intervals).

On that note - I think you can get away with calling something a Kite if any two opposite angles are congruent, but not the other pair. This angle requirement forces the length requirement of two adjacent sides and I think is simpler. Which would allow us to stick with only using the angleToleranceInterval for this.

It'd look something like:
KITE: [angle1 == angle3 (in angleToleranceInterval) AND angle2 =/= angle4 (outside angleToleranceInterval)] OR [[angle2 == angle4 (in angleToleranceInterval) AND angle1 =/= angle3 (outside angleToleranceInterval)]

**Comment by jessegreenberg** [comment]
> I think this is optional information,

Adding to meeting to check on this, is it something that we would like to implement now?

**Comment by BLFiedler** [comment]
Sorry, I meant it's optional in that the shape identification is not pertinent to scaffolding in the sim. I'll let @terracoda decide priority of implementing particular pieces of the voicing :)

**Comment by terracoda** [comment]
Well, I think it provides useful secondary information, and Emily has agreed that providing shape information under the details button would be fine.

The actual shape of kite may not be needed for initial interviews, but the easy shapes to calculate would be great. I think it would be interesting to get feedback from learners on the information under the read me buttons.

I would suggest getting everything else ready for interviews and then if there is time add in detection for a kite.

**Comment by jessegreenberg** [comment]
OK sounds good. Ill go ahead with this and try the kite detection approach that @BLFiedler suggested in https://github.com/phetsims/quadrilateral/issues/31#issuecomment-970413140.

**Comment by jessegreenberg** [comment]
In the above commit I implemented named shape detection for everything except kite.

**Comment by jessegreenberg** [comment]
An initial pass at this has been done. Overall I hope it works well! Of course, the named shapes were the most challenging to implement and there are still some quirks do discuss with the team. Mostly they involve cases where our tolerance has allowed the shape to be a parallelogram, but it also looks like a trapezoid. But a trapezoid can never be a parallelogram. So in these cases it is being described as a rectangle or a rhombus. 

For example, our tolerance allows this to be a parallelogram:
![image](https://user-images.githubusercontent.com/6396244/143958678-3f383489-0802-4ee4-b119-cb10538cb94a.png)


And so it is described as a "rhombus" even though it is more like a trapezoid.

In this case, the angles are within tolerance and it is described as a rectangle. It is more like a trapezoid, but the tolerance forces us to describe this as a parallelogram.
![image](https://user-images.githubusercontent.com/6396244/143958859-124cef27-936a-48be-8c7a-d3d2e77d2058.png)

**Comment by jessegreenberg** [comment]
@BLFiedler and @terracoda mentioned that a rhombus should have equal sides, currently all parallelograms are described as a rhombus.

**Comment by jessegreenberg** [comment]
For the issue described in https://github.com/phetsims/quadrilateral/issues/31#issuecomment-982128299, we determined that the behavior was better when the tolerance was much lower. During meeting we noticed that `angleToleranceInterval=0.05` looked pretty good. We will make this the default. This was committed as the new default in https://github.com/phetsims/quadrilateral/commit/e594ebffc1404cada0cc1fd2fa826073acf57d86

**Comment by jessegreenberg** [comment]
> Currently, your shape is {{a parallelogram}}, and {{a rhombus}}}}.
> Currently, your shape is {{a trapezoid}}, and {{not}} {{a parallelogram}}.

During meeting @terracoda said that these will change so the "parallelogram" statement always comes first. A new phrase for the "not" case will be made.

**Comment by terracoda** [comment]
**Play Details Button {{dynamic content}}:

1. Currently, your shape is {{a parallelogram}}, and {{a rhombus}}}}.
Parameters for named quads that are parallelograms:
- a square
- a rectangle
- a rhombus

2.  (iteration 2) Currently, your shape is {{not}} {{a parallelogram}}. You have {{a trapezoid}}.
Parameters for named quads that are NOT parallelograms:
- a kite
- a isosceles trapezoid
- a trapezoid
- a right-angled trapezoid
- a con-caved shape

@jessegreenberg, I added "right-angled trapezoid"

**Comment by terracoda** [comment]
I can hear all shape names except "right-angled trapezoid", but not sure we want that one.

**Comment by terracoda** [comment]
The order when the shape is a parallelogram needs to be flipped around.

Currently, your shape is {{a parallelogram}}, and {{a rhombus}}}}.

**Comment by terracoda** [comment]
We do not need "right-angled trapezoid" until we know otherwise. All other named shapes are working.

**Comment by terracoda** [comment]
Actually, the order in both parallelogram states (parallelogram and not a parallelogram) need to be updated.

**Play Details Button {{dynamic content}}:

1. Currently, your shape is {{a parallelogram}}, and {{a rhombus}}}}.
    Parameters for named quads that are parallelograms:

    - a square
    - a rectangle
    - a rhombus

2. Currently, your shape is {{not}} {{a parallelogram}}. You have {{a trapezoid}}.
    Parameters for named quads that are NOT parallelograms:

    - a kite
    - a isosceles trapezoid
   -  a trapezoid
   - a con-caved shape

**Comment by jessegreenberg** [comment]
I used https://www.wikidata.org/wiki/Q19420771 to detect a right-angled trapezoid it was pretty easy to add in the existing shape-detection function so I went for it.

**Comment by jessegreenberg** [comment]
The pattern has been updated but I am noticing a bug in the shape detection code because of changes for #25 - now that the angle tolerance for shape angles is infinite when dragging a side, it is messing with this code.

**Comment by jessegreenberg** [comment]
Alright, it is working as I would expect again after the above commit. There is now a different tolerance for detecting shapes than there is for detecting a parallelogram. @terracoda can you please review this?

**Comment by terracoda** [comment]
This is awesome @jessegreenberg. Apologies for taking so long to verify it.
The only difference I noticed in the implementation is:
- "concave shape" is spoken as "concave quadrilateral"

And I think "concave quadrilateral" is better, so I will update the design document with that wording.
