### ISSUE TITLE
Problem with global shift key listener

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#311]
- Make sure sim is in the foreground
- Press shift
- Click outside of the browser window
- release shift

The global KeyboardListener does not get inerrupted and so from then on the shift key is "stuck" down.

**Comment by jessegreenberg** [comment]
Also happens if you shift tab out of the sim. That makes sense, it is effectively the same reason.

**Comment by jessegreenberg** [comment]
Couldn't find a good way to interrupt the listener or detect when the tab has lost focus in ~20 minutes of trying. Will have to come back later.

**Comment by jessegreenberg** [comment]
A workaround is applied above. We need support for that in scenery/joist so that listeners will interrupt but this is sufficient for now.

**Comment by zepumph** [comment]
Could we make a scenery issue for this? Would it be helpful to try to spend a bit of time pairing on a general solution?

**Comment by jessegreenberg** [comment]
This is now built in to KeyboardListener, TODO removed. Closing.
