### ISSUE TITLE
When to show tangible controls in Preferences

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#315]
Sorry if this issue is a duplicate, but I didn't see another related to this.

It seems like the "Input" tab of preferences should probably only be shown when there is a device connection.

I think it will be distracting to QA so I am going to go ahead with hiding the Input tab unless `?deviceConnection` is present. 

@BLFiedler do you agree with this or did you have something else in mind?

**Comment by jessegreenberg** [comment]
It will only be shown with ?deviceConnection with the above commit.

**Comment by BLFiedler** [comment]
I believe we off-hand mentioned this, yes. This should be the correct behavior. If it's helpful to have, we may consider activating for camera input hands, but not relevant currently.

**Comment by BLFiedler** [comment]
Just to note, the `deviceGridSpacing` parameter present when `deviceConnection` is enabled does affect the spacing for `cameraInput=hands`. I took advantage of this when making a link to share before any action was taken on #258

**Comment by BLFiedler** [comment]
@BLFiedler, check the Input tab for clarity to teacher audience. In conjunction with #301 .

We'll need to make sure this tab is accessible to. I'll tag in TS when that's ready.

**Comment by BLFiedler** [comment]
Similar action has to be done for #258 changes that will pull in Input tab for Camera Input Hands. It needs updating for this sim and Voicing strings.

**Comment by terracoda** [comment]
@BLFiedler these slider controls a re pretty cryptic. When we tackle #258, we'll update this part of the Preferences dialog as well.

**Comment by terracoda** [comment]
I do not understand what these controls do, so I am not sure how to describe them.

Here are start:

**Tangible Input** 
Use slider controls to adjust the behavior of the sim object the tangible device controls.

Position Interval? [0.0125 - 0.2500]
Make the sim respond to smaller or larger tangible device changes.

Smoothing length? [1 - 10]
Reduce sim object jitter by increase by decreasing or increasing smoothing value?

Update interval [0 - 1]
Adjust how often you hear voiced updates about changes?

**Comment by terracoda** [comment]
If possible, it would be good if the displayed ranges were all the same or all ranges with whole numbers.

**Comment by jessegreenberg** [comment]
Over slack @terracoda said that Voicing is important. @terracoda can you please let me know what the Voicing responses for the sliders should be? Should the text still be visible?

**Comment by terracoda** [comment]
### Suggested Design Changes
- Visual Sliders: If possible, 
    - make tick marks darker
    - add min & max values
    - lay sliders out more like the sliders in GFL regular.
- Title: Change “Tangible Input” to “Device Input.” BF mentioned this in the last meeting.
- Help text paragraph: Remove “controls” after slider. 
    - “Use sliders to adjust the mapping and communication parameters between the simulation and the BLE-enabled device to reduce noise-related jitter.”
    - “Use sliders to adjust the mapping and communication parameters between the simulation and the BLE-enabled device to optimize performance.”
- Slider 1: “Step Interval Mapping” - “Adjust amount of movement the input device needs to make to make a step-change in the simulation.” 
    - Value is in centimeters?, if so maybe we can adjust to millimeters to remove decimal points.
    - Range: [0.0125 - 0.2500] 
- Slider 2: “Smoothing Average” - “Adjust number of values used to smooth noise in incoming sensor values from input device.”
    - Value is number of data point values
    - Range: [1 - 10]
- Slider 3:  - “Sim Update Interval” - “Adjust length of time before a new value from input device is accepted and updated in simulation.”
    - Value in seconds 
    - Range: [0 - 1]

### Voicing Design 
**Tab stop 1:** 
- Highlight first paragraph starting with “Use slider”
- Voice: [Heading] + [Paragraph ] = “Device Input.” + “Use sliders to ]

**Tab stop 2:**
- Highlight: Pink focus highlight on slider thumb
- Voice: [Name Response] + [Object Response]
    - “Step Interval Mapping”, “0.2500 centimeters” ?? Units ??

**Tab stop 3:**
- Highlight help text slider 1 
- Voice slider 1 help text

**Tab stop 4:**
- Highlight: Pink focus highlight on slider 2’s thumb
- Voice: [Name Response] + [Object Response]
    - “Smoothing Average” , “10” or “10 values” or “10 data points”

**Tab stop 5:**
- Highlight help text slider 2 
- Voice slider 2 help text

**Tab stop 6:**
- Highlight: Pink focus highlight on slider 3’s thumb
- Voice: [Name Response] + [Object Response]
    - “Sim Update Interval” , “1 second”
    - If less than 1 -> “Sim Update Interval” , “0.25  seconds”

**Tab stop 7:**
- Highlight help text slider 3 
- Voice slider 3 help text

**Comment by terracoda** [comment]
@jessegreenberg and @BLFiedler, what do you think of the above? Especially, the voicing of help text on a separate tab stop.

**Comment by terracoda** [comment]
I'm wondering if we can ditch the help text, if I have a cleaver context response to slider changes?

**Comment by terracoda** [comment]
For screen reader accessibility, the initial value, name and role should all fire on focus. 
- New values should fire with each discrete step.
- Default large steps (range divided by 10) should fire with Page Up and Down keys.
- Min and Max values should fire with the Home and End keys.
- For the help text, the paragraphs of help text, they should be accessible with the down arrow (cursor keys).

I think all this comes for free if we use our typical PDOM structures. 

Four pointer-based input, is it safe to assume these are snappy sliders?

**Comment by BLFiedler** [comment]
> Alternative wording: “Use sliders to adjust the mapping and communication parameters between the simulation and the BLE-enabled device to optimize performance.” or "optimize device control."

It's best I think not to be vague here. The only thing we're trying to solve is the noise from the device crossing the step thresholds, which causes the sim shape to jump without interaction. I'm not sure if jitter is jargony, so if there is a better word there, we can sub out. 

> Slider 1: “Step Interval Mapping” - “Adjust amount of input-device movement needed to make a step-change in the simulation.”
> Is value is in centimeters?, if so maybe we can adjust to millimeters to remove decimal points?
> Range: [0.0125 - 0.2500]

There is no unit here. It is a relative dimension to the normalized play area.

Good with everything else!

**Comment by BLFiedler** [comment]
@terracoda, any further review here or should it go to JG to implement?

**Comment by terracoda** [comment]
Ok, over to @jessegreenberg to implement information in https://github.com/phetsims/quadrilateral/issues/315#issuecomment-1579102776

Regarding slider 1, we'll have to leave the raw values as is. Hopefully, it works ok. 

For a published version we should look into a qualitative range or a context response that describes the relative change required for a step change in the sim. Just off the top of my head - NOT for implementation - something like this might work "{{Very small, Small, Big, Very Big}} device movements make sim change".

**Comment by jessegreenberg** [comment]
@terracoda I realized that I didn't make the units dynamic for the update interval control. That logic was added in the above commit.

**Comment by terracoda** [comment]
Hey @jessegreenberg, I know I said it doesn't have to be perfect, but if the following things are relatively simple, can you address them?

**With Voicing on:**
- When I activate step arrows on the ends of the sliders with a mouse, I don't hear the update. It works fine with the keyboard. Can you make it voice the same thing (Name Response + Object  Response) with mouse input? The buttons do not need individual unique names. They are not accessible to the keyboard, and HOPEFULLY, that keeps them hidden from screen readers.

- For "Smoothing Average" on value "1", I hear, "Smoothing Average 1 values"
    - If easy, I'd love to hear, "Smoothing Average 1 value".

@brettfiedler, the slider name repeats with each step, so I want to shorten the 3-word names to 2 words. I think the help text explains the function of the sliders nicely, so the shorter names feel good to me. 

Please check if you agree with renaming:
- [ ] Step Mapping <- from "Step Interval Mapping"
- [ ] Update Interval <- from "Update Interval"

**Comment by terracoda** [comment]
"1 values" should be "1 value", too.

**Comment by jessegreenberg** [comment]
@terracoda and I met to discuss. We went ahead with the wording changes, though they can be modified if @brettfiedler has recommendations.

I also added Voicing responses to the NumberControl arrow buttons. Back to @terracoda for review and @brettfiedler for the comment in https://github.com/phetsims/quadrilateral/issues/315#issuecomment-1591831541.

**Comment by brettfiedler** [comment]
Fine with all changes. Descriptions are long, but there isn't and may not be proper documentation for it for some time. Over to TS to review and close.

**Comment by terracoda** [comment]
@jessegreenberg, I am hearing responses when I press the arrow buttons, now. Thanks!

Just so, I understand your comment from https://github.com/phetsims/quadrilateral/issues/315#issuecomment-1591429975

> These controls ignore voicing response options so object responses are always spoken regardless of Preferences settings.

By "These controls", do you mean all controls in the Preferences menu?

**Comment by terracoda** [comment]
This issue can be closed. The controls are Voicing as expected and everything is screen reader accessible.

I just have a question for @jessegreenberg in previous https://github.com/phetsims/quadrilateral/issues/315#issuecomment-1593571406

**Comment by jessegreenberg** [comment]
I meant the controls that we added for this issue. It has to be done manually and I was just noting that it was considered.

**Comment by terracoda** [comment]
Thanks @jessegreenberg, closing.
