### ISSUE TITLE
How should we fill in credits for this sim?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#316]
Here are the fields. We can fill in the QA portion after the final RC. Opening this issue in case it deserves some thought and discussion because of our collaboration with other teams and institutions.

```
  credits: {
    leadDesign: '',
    softwareDevelopment: '',
    team: '',
    qualityAssurance: '',
    graphicArts: '',
    soundDesign: '',
    thanks: ''
  },
```

**Comment by terracoda** [comment]
Maybe something like this? @BLFiedler, if we want to name a lead designer, I think it should be you.

- leadDesign: ??
- softwareDevelopment: Jesse Greenberg
- team: Brett Fiedler, Emily B. Moore, Taliesin Smith
- qualityAssurance: TBA
- graphicArts: ??
- soundDesign: Ashton Morris
- thanks: ??

We had "Contributors" listed in RaP, so is that the best way to list our collaborators?

**Comment by BLFiedler** [comment]
If we are acknowledging visual and sound design, I believe it's probably about time to add in a description designer acknowledgment... :) 

I'm fine with removing lead designer and being listed as the first non-developer team member, as was done in RaP.

re: Graphics, I'd either put Jesse or remove it altogether.

### Collaborations/Contributors:

This is what we did for RaP:
> Dor Abrahamson and the Embodied Design Research Lab (UC Berkeley)
> Clement Zheng, Peter Gyory, and Ellen Do from the ACME Lab (CU Boulder ATLAS Institute)

So for Quad:
Sofia Tancredi, Dor Abrahamson, and the Embodied Design Research Lab (UC Berkeley)
Scott Lambert, Jenna Gorlewicz, and the CHROME Lab (St. Louis University)

**Comment by terracoda** [comment]
So looks like this is what you need @jessegreenberg:

  credits: {
    softwareDevelopment: 'Jesse Greenberg',
    team: 'Brett Fiedler, Emily B. Moore, Taliesin Smith',
    collaborators: 'Sofia Tancredi, Dor Abrahamson, and the Embodied Design Research Lab (UC Berkeley), Scott Lambert, Jenna Gorlewicz, and the CHROME Lab (St. Louis University)',
    qualityAssurance: 'TBA',
    soundDesign: 'Ashton Morris',
  },

**Comment by jessegreenberg** [comment]
OK, thank you! I alphabetized the contributors because credits are are intended to be alphabetized. I think a code reviewer might flag that. But if that order was important I don't think it really matters too much and I can change it. @BLFiedler @terracoda does master look OK? QA will be filled in later.

**Comment by terracoda** [comment]
Ok looks good to me
<img width="608" alt="image" src="https://user-images.githubusercontent.com/1902116/213487993-50e330b1-4c8b-4a58-b0e7-7d6d62b261de.png">

**Comment by BLFiedler** [comment]
Calling @emily-phet to see if there is any nuance missed due to the complexity and far reach of this sim design

**Comment by emily-phet** [comment]
@BLFiedler Can you bring this up as a topic to discuss in the Wednesday Quad meeting?

**Comment by BLFiedler** [comment]
Discussed with contributors, we'll update the credits as follows:

credits: {
softwareDevelopment: 'Jesse Greenberg',
team: 'Brett Fiedler, Emily B. Moore, Taliesin Smith',
collaborators: 'Sofia Tancredi, Dor Abrahamson (Embodied Design Research Lab, UC Berkeley), Scott Lambert, Jenna Gorlewicz (CHROME Lab, St. Louis University)',
qualityAssurance: 'TBA',
soundDesign: 'Ashton Morris',
},

**Comment by jessegreenberg** [comment]
QA credits have been filled in for master and 1.0! Closing.
