### ISSUE TITLE
Voicing doesn't read Shape Sound radio buttons with mouse

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#321]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari 16.1 and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/879, Voicing will not read the Shape Sound Options when clicked on with the mouse. It only reads them with keyboard nav.

**Steps to reproduce**
1. Turn on Voicing 
2. Click on the Shape Sound Options radio buttons

**Visuals**

https://user-images.githubusercontent.com/87318828/211605934-b1f23181-936e-48f9-967c-d70504fab9a9.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Language: en-US
Window: 1399x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Great, thanks @Nancy-Salpepi! Related to #249, the Voicing content for these buttons was meant to be filled in there.

**Comment by BLFiedler** [comment]
Assigning @terracoda to review and close when #282 is complete

**Comment by jessegreenberg** [comment]
This is a subset of #282 now, the Voicing for these buttons will be reviewed by @terracoda there. Closing.
