### ISSUE TITLE
"Mouse" in Keyboard Shortcuts dialog should be translatable 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#323]
For https://github.com/phetsims/qa/issues/879, with string tests, the word "mouse" in the Keyboard Shortcuts dialog never changes.
<img width="487" alt="Screenshot 2023-01-10 at 1 13 33 PM" src="https://user-images.githubusercontent.com/87318828/211631086-f36229ac-d7ce-4837-bc86-08d5ed2dbaba.png">

Confirmed with @jessegreenberg on Slack that "mouse" should indeed by translatable.

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi! Here is the dialog now:
![image](https://user-images.githubusercontent.com/6396244/211674882-80238f0c-80de-4bd0-862f-88fb98fd3223.png)

OK to close?

**Comment by jessegreenberg** [comment]
Yes exactly. When running in a non-English language or where Voicing isn't supported that row in the dialog won't be shown at all. (Can see with `?supportsVoicing=false`.

**Comment by Nancy-Salpepi** [comment]
Ok thanks! I like that parameter! 
Closing this
