### ISSUE TITLE
Lock is not centered on button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#325]
For https://github.com/phetsims/qa/issues/879, the lock is off-center:

<img width="113" alt="Screenshot 2023-01-10 at 2 22 29 PM" src="https://user-images.githubusercontent.com/87318828/211642705-1cd6e8d0-c053-4ab2-b2a3-2055e2bddcf0.png">

**Comment by Nancy-Salpepi** [comment]
I see that it looks centered when opened. 
<img width="113" alt="Screenshot 2023-01-10 at 2 25 22 PM" src="https://user-images.githubusercontent.com/87318828/211643226-4eac6f9a-ef7a-4d6e-8e18-0c103cd23a19.png">

**Comment by jessegreenberg** [comment]
Good eye, we fixed this recently in https://github.com/phetsims/scenery-phet/issues/794. It should be centered when closed and not move when opened.  Can you confirm it is OK on master?

**Comment by jessegreenberg** [comment]
Thank you! Ill go ahead and close.
