### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#326]
For https://github.com/phetsims/qa/issues/879. Seen on Win 11 Chrome.
When running a fuzz test on the debug version of the sim, these assertion failed errors occurred.
<img width="350" alt="bug" src="https://user-images.githubusercontent.com/41024075/211684802-2908fd73-54f8-4c85-8165-5e7ff92cb1ea.png">

**Comment by jessegreenberg** [comment]
Uh oh...thanks @KatieWoe. This probably isn't sim specific, Ill take a look.

**Comment by jessegreenberg** [comment]
I have been fuzzing master and 1.0.0-dev.73 debug build for about 10 minutes and haven't seen this yet. @KatieWoe is this issue rare for you or does it happen quickly on your platform?

**Comment by jessegreenberg** [comment]
I let master and https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet_debug.html fuzz with `?brand=phet&ea&debugger&fuzz` for ~3 hours this evening and did not see this issue.

I expected this error to show up before https://github.com/phetsims/utterance-queue/issues/97 (changes made last week) but don't understand how it could show up now.

@KatieWoe are you able to see this consistently? Any extra query parameters?

**Comment by KatieWoe** [comment]
This is the link I used: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet_debug.html?fuzz. I was able to reproduce the assertion withing 10 minutes, but I'm not sure what's causing it. The only thing I can think of was that I did enable sound by clicking on the sim as it was loading.

**Comment by jessegreenberg** [comment]
Ill try again and think on race conditions that might cause this assertion to appear again...

**Comment by BLFiedler** [comment]
Just a data point - let that link above run for 20+ minutes and no crashing (Chrome, win10)

**Comment by KatieWoe** [comment]
Clarification, the sim didn't seem to crash. It kept going after these errors popped up in the console

**Comment by jessegreenberg** [comment]
Thats good to know @KatieWoe, thanks. I was also running with the console open and did not see any assertions come thorugh.

**Comment by BLFiedler** [comment]
> Clarification, the sim didn't seem to crash. It kept going after these errors popped up in the console

Gotcha, thanks. Trying again.

**Comment by BLFiedler** [comment]
Again, just a single data point update, over an hour and no assertion raised in console.

**Comment by jessegreenberg** [comment]
Over slack @KatieWoe said that she was not able to replicate on Win 10. Then she tested the same test with a recent build of RaP on Win 11 and was NOT able to see it in ~10 minutes of fuzzing.

**Comment by jessegreenberg** [comment]
@KatieWoe can you please try on win 11 quad master with assertions enabled and the console open? If it happens can you please paste an image of the error from the console? Hopefully with the console open the sim will freeze the first time it happens.

**Comment by jessegreenberg** [comment]
@KatieWoe was able to see this on master in an unbuilt sim wiht ?ea and found this ouput which is not too helpful unfortunately:
![image](https://user-images.githubusercontent.com/6396244/211896613-8f87354f-5460-408d-a073-c1c20b4557ff.png)

I am not sure what else to try at this time so its back to be to think through why this would happen in utterance-queue code.

**Comment by Nancy-Salpepi** [comment]
I was able to get the same assertion error this morning with mac + chrome while running a fuzz test. I went back and recorded my screen and slowed it down as much as I could. It seems to involve the About dialog, but I haven't been able to replicate the error on my own (without ?fuzz). 

https://user-images.githubusercontent.com/87318828/212086508-517d9a22-ab75-4ccc-8a3c-a18c499dff1e.mp4

**Comment by jessegreenberg** [comment]
After the above comment and finding https://github.com/phetsims/joist/issues/898, I am curious if this is actually related to Chrome 109 and that joist issue.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/joist/issues/898 has been fixed and I believe that change will fix this problem as well.

I let the sim fuzz for ~40 minutes in Chrome 109 and I am not seeing this issue. @KatieWoe would you mind trying again on master?

**Comment by KatieWoe** [comment]
Things are ok for me now.

**Comment by jessegreenberg** [comment]
That is great news, thanks. Closing.
