### ISSUE TITLE
When continuous sounds are heard with checkbox is inconsistent

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#327]
**Test device**
iPad 9th generation and mac

**Operating System**
iOS 16.1.1 and macOS 13.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/879, with 'Play Shapes Sounds forever....' checked in the preferences menu, if I uncheck and then recheck the sounds checkbox in the sim, sometimes I hear sound and sometimes I don't. 

**Steps to reproduce**
1. Check the Play Shape Sounds forever checkbox in the Audio tab of the Preferences menu
2. Move side BC to the right
3. Uncheck the Sounds checkbox in the sim
4. Move side BC to the right again
5. Check the Sounds checkbox --you will hear sound
6. Uncheck and then recheck the Sounds checkbox--you will not hear sound

**Visuals**

https://user-images.githubusercontent.com/87318828/211877166-073a9809-bc4d-44b4-8ea2-2456645738ee.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Language: en-US
Window: 1388x714
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Interesting, thanks @Nancy-Salpepi. I think the correct behavior is that sounds should NOT play when you check the checkbox, until you change the shape again. Ill go ahead with that.

**Comment by BLFiedler** [comment]
I agree. Even with the Tracks Play Forever enabled, if you check and uncheck that checkbox, sound should only play again when you move the shape.

**Comment by jessegreenberg** [comment]
Over slack @Nancy-Salpepi thought of a good point to think through. 

> if I have the sounds checked in the sim and the continuous sounds checked as well-- then I shut off Sounds or All Audio and turn them back on — I hear sound. So if you make the change you proposed above, would you have to change those as well?

@BLFiedler with this thought do you think anything should change?

**Comment by jessegreenberg** [comment]
Thinking about it a bit, I am OK with the difference. I think it is good that general Audio and Sound controls in preferences don't start/stop ambient sounds. But it is best that shape music should only play after changing the shape.

**Comment by BLFiedler** [comment]
We are all okay with this. The checkbox serves to "turn off" the sonification ("shapes changes" in Voicing). Whereas, the Audio off (or pref menu) is more like muting the sounds, resuming when you've turned it back on.

**Comment by BLFiedler** [comment]
WAIT. Actually, checkbox is inconsitent, which is what NS was pointing out. Let's make sure the checkbox just stops the sonification (or prevents it if not enabled) every time. Shape sound should not play unless you move the shape when Shape Sound checkbox enabled.

Over to JG to fix

- [ ] Fix :)

**Comment by jessegreenberg** [comment]
The above is a potential simple fix for this. Now we strop all tracks and reset the player when shape sounds are disabled OR enabled so that in order to hear sounds again the shape must be moved.

Closing.

**Comment by Nancy-Salpepi** [comment]
>The above is a potential simple fix for this. Now we strop all tracks and reset the player when shape sounds are disabled OR enabled so that in order to hear sounds again the shape must be moved.

@jessegreenberg does that also refer to when the Shape Sound Options are changed?

**Comment by jessegreenberg** [comment]
Yes, it should behave the smae for "Shape Sound Options". Is that what you are seeing?

**Comment by Nancy-Salpepi** [comment]
Yes. I have to move the shape again for sound to resume.

**Comment by jessegreenberg** [comment]
OK, great. I think this can be closed, please reopen if thats not the case.
