### ISSUE TITLE
Is it intentional that the "Voice helpful hints" box is read as "extra help" in voicing?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#330]
Is it intentional that the "Voice helpful hints" box is read as "extra help" in voicing?

_Originally posted by @KatieWoe in https://github.com/phetsims/qa/issues/879#issuecomment-1380861624_

**Comment by jessegreenberg** [comment]
@terracoda can you please review and comment?

**Comment by terracoda** [comment]
The words in the context response that are delivered on activation and deactivation of the checkbox are intentionally different. 

When you move focus to the checkbox you should hear the voicing of what is written on the page. This is a State Description, i.e., the name or label of the checkbox.

When you check or uncheck the checkbox, you have changed the state of the checkbox (not the name of it) and as a result your action has adjusted/affected the context - the sim will now voice helpful hints (i.e. extra help). I intentionally changed the words in the context response so things don't just repeat the same thing all the time.

With mouse activation, you will only hear the context response - not the name of the checkbox.

Does that make sense? Is that how the Voicing is working?

**Comment by terracoda** [comment]
Assigning back to @KatieWoe :-)

**Comment by KatieWoe** [comment]
It is. Closing
