### ISSUE TITLE
Sides may read out as words instead of letters

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#331]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/879
When voicing a side of the quadrilateral, if the letter a is in it, it is read out like a word instead of two letters. "Ahb" and "Dah" instead of "A.B." and "D.A.". The other two sides sound fine.

**Visuals**

https://user-images.githubusercontent.com/41024075/212160112-3a6ff621-9476-443d-8828-d087295faee1.MOV

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. I think we were aware of this, but would be good to check. The speech synthesizer controls this. In the past we haven't modified the strings as a workaround to force it to pronounce things a certain way. @terracoda can you confirm that is best or if you want to explore something else for this case?

**Comment by Nancy-Salpepi** [comment]
I noticed that too with the Google voice, but once I changed voices to Samantha it was fine.

**Comment by terracoda** [comment]
Yep, some Voices handle these strings better than others.
I think we have to live with this until screen reader technology and speech synthesizers are better.
