### ISSUE TITLE
Sparse alt+c voicing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#333]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/879
>Kathryn Woessner
  [1:01 PM]
When using alt+c it only seems to read out if any sides are in parallel. Should it be reading out more, like angles and lengths?
Jesse Greenberg
  [2:09 PM]
Hmm, I think it depends on the shape. Let me check
[2:10]
Yes, there is a custom string for every shape. As long as the description is accurate, I think that is most important.
Kathryn Woessner
  [2:10 PM]
Ok. It seemed a bit sparse to me
Jesse Greenberg
  [2:11 PM]
For all of them or a particular shape?
Kathryn Woessner
  [2:12 PM]
All that I saw at least.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
It sounds like all the content was accurate, but the feedback is that it felt sparse. @terracoda assigning to you to review and comment if anything should be done.

**Comment by Nancy-Salpepi** [comment]
Similar to my comment in https://github.com/phetsims/quadrilateral/issues/322#issuecomment-1377624798

**Comment by terracoda** [comment]
Let, me explain about the two Responses you can hear with the Check Shape function:
- When Shape Name is Shown, and you use Alt + C, you get:
    - "You have a {{ShapeName}}."

- When Shape Name is Hidden, and you use Alt + C, you get the same string we use for the Context Response when a shape transformation happens. This is essentially the defining properties of the shape - not all the properties of the shape. The Alt + C shortcut allows a learner to be able to re-play that shape's unique defining properties without leaving the shape.

You both bring up a good point that we could say more about the shape with that shortcut. 

Did you notice that you can directly click on (or move focus to) each corner and side to hear a description of each corner and side? Do you think using Alt + C together with corner and side "object responses" makes the information less sparse?

What kind of information would you expect to hear when shape name is hidden and you use ALT + C?

**Comment by terracoda** [comment]
For example, I could have used the strings we designed for the Details button, which have more detail. Compare the following bullet points for each shape. The first one is the Shape-Property Context Response which is currently implemented and the second is the essential part of the Details button.

Square:
- ALT + C: All right angles. All sides equal.
- Details button: [..] all corners are right angles, and all sides are equal.

Rectangle:
- All right angles.
- [..] all corners are right angles, and opposite sides are equal.

Parallelogram: 
- Opposite sides in parallel.
- [...] opposite corners are equal, and opposite sides are equal. Opposite sides in parallel.

Rhombus:
- All sides equal.
- [...] opposite corners are equal, and all sides are equal. 

Kite:
- Corners {{A}} and {{C}} are equal and pairs of adjacent sides are equal.
- [...] one pair of opposite corners are equal, and pairs of adjacent sides are equal. Corners {{A}} and {{C}} are equal.

Dart:
- Corner {{B}} points inward, corners {{A}} and {{C}} are equal, and pairs of adjacent sides are equal.
- [...] one pair of opposite corners are equal, and pairs of adjacent sides are equal. Corner {{B}} points inward, corners {{A}} and {{C}} are equal.

Concave Quadrilateral:
- Corner {{B}} points inward, no sides in parallel.
- Details for this shape can vary a little, here's two examples:
    - [...] no corners are equal, and one pair of adjacent sides are equal. Corner {{B}} points inward, no sides in parallel.
    - [...] no corners are equal, and no sides are equal. Corner {{B}} points inward, no sides in parallel.

Convex Quadrilateral:
- No sides in parallel.
- Details for this shape can vary a little, here's a few examples:
    - [...] no corners are equal, and one pair of adjacent sides are equal. No sides in parallel.
    - [...] no corners are equal, and no sides are equal. No sides in parallel.
    - [...] no corners are equal, and pairs of adjacent sides are equal. No sides in parallel.

One has to balance implicit scaffolding with learning goals, and with the Voicing feature. one has to deeply consider what is essential for learning. If a learner wants more information they generally have options for getting more info (e.g., play details, click on a corner or side). I have to decide weather to provide more information, or let them decide to turn on more information and access it themselves.

Given this background, do you still feel the information is sparse?

**Comment by Nancy-Salpepi** [comment]
While testing, I easily discovered that I could click on or tab to a side or corner to hear information about it. Yes, I can see that using the shortcut + that information gives a more complete picture. 

I guess, in my mind, the point of  'shortcut' keys, is to allow me to reach a goal, like printing a document or taking a screenshot, faster. In this case, I was thinking I could get the same information given about the shape when pressing the details button without having to tab there to get it, if that makes sense. But, I completely understand what you are saying @terracoda. I wasn't thinking about it in terms of learning goals and scaffolding. What you are saying makes perfect sense to me.

**Comment by KatieWoe** [comment]
I was thinking the same thing as @Nancy-Salpepi. If this is as designed, I think we can close this issue.

**Comment by terracoda** [comment]
It is working as designed, and also nice to hear your thoughts about the design. You two have more experience than me when it comes to teaching.

Thanks for your questions. I'll close the issue.
