### ISSUE TITLE
Bluetooth connection buttons need to be moved

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#334]
Noticed while working with Scott today on actuated quad, the device connection buttons overlap the current UI.

![image](https://user-images.githubusercontent.com/6396244/213525876-db4ce393-d078-4b02-8fcd-f8f478aecb35.png)

**Comment by BLFiedler** [comment]
Should these exist in the Input tab of the Pref menu? If not, let's just translate them to the upper right empty space above the checkboxes.

- [ ] While we're at it, let's also change the button to **Pair Bluetooth Device**

**Comment by jessegreenberg** [comment]
> Should these exist in the Input tab of the Pref menu?

Sure! That is a good idea.

**Comment by jessegreenberg** [comment]
Darn, it won't be trivial to move them into the dialog. The bluetooth button needs a reference to the model so bluetooth can control shape Properties and the model is not available from the dialog.

Can definitely work on this, but would be best to confirm they should be in the dialog and what the layout will look like in the end before tinkering with code.

**Comment by BLFiedler** [comment]
@jessegreenberg 
- [ ] Move the buttons evenly spaced into the top right of the sim above the checkboxes, left aligned to checkboxes.
- [ ] Change button colors to the same as the grid icon
- [ ] Put Bluetooth button first in tab order if there, Calibrate second

@BLFiedler , revisit how accessible this process should be given not for formal "publication"

**Comment by jessegreenberg** [comment]
OK, requested updates are done. @BLFiedler back to you.

**Comment by jessegreenberg** [comment]
In we added another device connection control that is also part of these buttons. Can be seen with `?serial`.

**Comment by BLFiedler** [comment]
I think this is complete. Layout changes as a result of this move and some code cleanup are happening in #364
