### ISSUE TITLE
Remove unused sound files

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#335]
While working with @jbphet we noticed that the sounds are taking up a huge amount of space (relative for a PhET sim). We should be able to get rid of several.  There is also a process for making sound files smaller, @jbphet noted there is documentation for this, Ill take a look.

**Comment by BLFiedler** [comment]
Sound design is complete. Go ahead and remove anything not in use and shrink as needed!

**Comment by jessegreenberg** [comment]
Unused sounds have been removed in #344. Ill make a new issue for reducing file sizes of remaining files.
