### ISSUE TITLE
Please make a dev version with the latest changes

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#340]
It would be nice to have a new dev version to share with collaborators. @jessegreenberg, please make one when you get a chance.

**Comment by jessegreenberg** [comment]
New dev version: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.74/phet/quadrilateral_all_phet_debug.html

Delevered to @terracoda over slack as well. Closing.
