### ISSUE TITLE
BLE button goes out of dev bounds

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#356]
Just noticed it was cut off.

![image](https://user-images.githubusercontent.com/6396244/217031096-6d490951-7641-4bac-b124-3e26a5f7b19c.png)

@BLFiedler are you OK renaming this button, maybe to "Pair BLE Device"? Or would you like to solve this another way?

**Comment by BLFiedler** [comment]
BLE works for me! (heh, rhymes)
