### ISSUE TITLE
Review minor layout changes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#364]
In #351 and https://github.com/phetsims/quadrilateral/issues/361 I changed the ModelViewTransform slightly and also some of the layout code.

The result is slightly different layout compared to the build that recently went through dev test. @BLFiedler can you please review master and comment on if it looks OK or if you would like any pixel polishing?

**Comment by jessegreenberg** [comment]
Specifically, you might notice there is a little less space between the quad grid area and view edges/controls.

**Comment by BLFiedler** [comment]
Sounds good. This did give me a moment to notice things are spaced a little unevenly, and we could try to center either the entire sim or just the controls.

![image](https://user-images.githubusercontent.com/47331395/218512568-9fa27c50-044f-4e75-abd1-d4539d7d2d69.png)

Perhaps we try to shift the whole sim a little more to the center? Add some padding to the left to distribute the space on the left and right sides?

**Comment by jessegreenberg** [comment]
The right thing to do would be to change the layout code to make sure that all ScreenView contents are centered in the layout bounds. But that would be a much more time consuming task at this point (everything in the ScreenView is free-floating and positioned relative to the grid).

Instead, I just eyeballed it by shifting the grid over a little. Then I reduced the `maxWidth` of visibility controls text a bit so it still looks right with translated strings.

@BLFiedler can you review? If you want to play with it you can modify `QuadrilateralConstants.SCREEN_VIEW_X_MARGIN` and test with and without `?stringTest=doube`.

**Comment by BLFiedler** [comment]
I think that will work! I'm not sure what to expect from the stringTest. Lengthening things by 2x shrinks everything (not totally incomprehensible, but we kept the English words short here intentionally. Is there a strategy to invoke if translations shrink the text significantly?

**Comment by BLFiedler** [comment]
Roger. Okay. I think will do as is. I am not too concerned with the grow to the right if the play area is still a little more central that it was.
