### ISSUE TITLE
Check on soundDesign query parameter for publication

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#370]
We want to keep the `soundDesign` query parameter. Let's check to make sure the names we use for it make sense to publish to teachers.

**Comment by jessegreenberg** [comment]
One of the code review comments was about how the capitalized strings for these (matching the EnumerationValue) are unconventional. If this is public and needs to stick around we should user lowercase or camelCase and map back to the EnumerationValue.

**Comment by BLFiedler** [comment]
For reference:

https://github.com/phetsims/quadrilateral/blob/master/js/quadrilateral/QuadrilateralQueryParameters.ts#L108-L114

**Comment by BLFiedler** [comment]
Perhaps we just separate like:
- shapeLayer
- shapeUnique

To use the language in the pref menu

**Comment by jessegreenberg** [comment]
Great! How is that?

**Comment by BLFiedler** [comment]
👍
