### ISSUE TITLE
Side.interactiveProperty may not be necessary

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#377]
Side.interactiveProperty may not need to be in the model, this and related code could be moved to the ScreenView, and that would also remove some code from QuadrilateralShapeModel (for #367).

**Comment by terracoda** [comment]
Without it can we still track the length of the side for diverse input?

**Comment by jessegreenberg** [comment]
Yes. To clarify, this was code added for https://github.com/phetsims/quadrilateral/issues/93. Behavior should be the same but instead of a model Property for the interactive state of the side, it is going to be managed by the view.

**Comment by jessegreenberg** [comment]
OK, this was done in wip-2-22-23 branch, closing.
