### ISSUE TITLE
Avoid duplicated checks for valid shape in TangibleConnectionModel

### ISSUE THREAD

**Issue by samreid** [phetsims/quadrilateral#401]
Discovered in #398, @jessegreenberg and @matthew-blackman and I were looking at https://github.com/phetsims/quadrilateral/blob/7a012e768b3ffd480af1651536119b4650cbb14b/js/quadrilateral/model/prototype/TangibleConnectionModel.ts#L165-L185 and wondering if it would be better to create a scratch `QuadrilateralShapeModel` then ask if it is a valid shape? We think there may be duplicated logic here.

**Comment by jessegreenberg** [comment]
The code referenced here is totally removed, and its using `QuadrilateralShapeModel.isQuadrilateralShapeAllowed( testShapeModel );` instead. So much nicer!

I was able to test it with `?cameraInput=hands`, and it is working well, maybe even better - before the change I was seeing what looked like incorrect shapes sometimes. Closing.
