### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by samreid** [phetsims/quadrilateral#404]
From https://github.com/phetsims/quadrilateral/issues/403, we would like to add unit tests for the QuadrilateralShapeDetection in particular.

**Comment by jessegreenberg** [comment]
I added unit tests for shape detection, and it has been nice to have them while making changes for #398. While not exhaustive it covers one of each shape and the sim is now set up to add more unit tests if we want.

@samreid would you like to see anything else here or any other tests?
