### ISSUE TITLE
Change default grid interval for tangible

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#408]
From meeting with @BLFiedler @terracoda and Scott Lambert, default interval should be 0.625 (to match the smallest grid size).

**Comment by jessegreenberg** [comment]
I believe that is a typo, we want the default interval to be 0.0625.

**Comment by jessegreenberg** [comment]
The default value for query parameter `deviceGridSpacing` now matches the default query paramter value of `minorVertexInterval`. Is there anything else to do here @BLFiedler?

**Comment by BLFiedler** [comment]
Cannot currently test, but the slider matches, so I think we can take this as it is!
