### ISSUE TITLE
Bug with shape detector

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#410]
In a meeting with @BLFiedler and @terracoda today we found that Rhombus is not getting detected when we expect. We should figure out why. Changes in #403 are most likely the cause but I am not sure.

**Comment by jessegreenberg** [comment]
OK, @BLFiedler identified a bug form #403 where rhombus should be inheriting from parallelogram properties instead of rectangle. That was fixed in the above commit. However, after fixing that I still cannot get the sim to produce a rhombus (also with ?reducedStepSize).

These two conditions are both failing:
  TWO_EQUAL_ADJACENT_SIDE_PAIR,
  ALL_EQUAL_SIDE

**Comment by jessegreenberg** [comment]
OK, I found another bug where the wrong value was being used for `interLengthToleranceInterval`. But it still isn't working.

I forgot that `interLengthToleranceInterval` is reduced with `reducedStepSize`. So in those conditions we have these values:
![image](https://user-images.githubusercontent.com/6396244/225469755-dbf95216-f572-42a7-9ec5-bc81890c7c1f.png)

But even without `reducedStepSize` we have
![image](https://user-images.githubusercontent.com/6396244/225469562-73cfb782-3110-4177-af92-2339f602a1b3.png)

@BLFiedler is it possible the new `interLengthToleranceInterval` is too small?  When I revert to 0.001 I can find a rhombus with typical conditions. However I still cannot find a rhombus with `reducedStepSize`.

**Comment by BLFiedler** [comment]
I'll try to give it a whirl. The reduction was because, with the largest square, I could still get a rhombus with a small step side drag. I'll have to see if there's a happy middle ground. Looks like we did probably hit a limit, though. Interesting!

**Comment by BLFiedler** [comment]
I widened this as much as possible without getting a rhombus on side drag for the largest square. Works for `?reduceStepSize' as well. 

The best way to get a rhombus in the sim remains: 

1.) anchoring two points on the same vertical axis and moving the other two points to make equal sides 
![image](https://user-images.githubusercontent.com/47331395/225695307-98579d6d-db73-4ce4-b7cf-bca42b177e7c.png)

OR 2.) making a kite from the starting square (move a corner diagonally) and repeat on the opposite corner
![image](https://user-images.githubusercontent.com/47331395/225695497-62c0d46b-3917-4730-8d8b-14eb75ff0b57.png)

I don't think there is a way around this. It's going to remain difficult to find one by side dragging a square or try to arbitrarily make the side lengths equal.

**Comment by BLFiedler** [comment]
Feel free to re-open if this is still a problem while working on other issues.
