### ISSUE TITLE
Performance testing and sign-off

### ISSUE THREAD

**Issue by samreid** [phetsims/quadrilateral#411]
For code review https://github.com/phetsims/quadrilateral/issues/398, This should be done by QA on a dev test, to check the performance on our slower supported devices.

**Comment by jessegreenberg** [comment]
Thanks @samreid. I believe this was done. In a dev test before the code review I requested
> Hey QA team, sorry I forgot to note in the original issue. Could you do a check for any performance problems on the slowest device that PhET supports if you have time?

And @KatieWoe and @Nancy-Salpepi responded with 
> I didn't notice any major performance issues with the Chromebook. I believe the rest of the QA team is also going to take a look.

> I tested an iPadOS 14 device and it was running smoothly.

Closing.
