### ISSUE TITLE
Email announcement language

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/quadrilateral#419]
We need an e-mail announcement draft to give to Oliver to announce to the PhET list that Quadrilateral is ready!

**Comment by BLFiedler** [comment]
Calling @emily-phet here. We have some uncertainties about the timing and language to use around a general Voicing announcement, since Quadrilateral makes for a good number of Voicing sims. 

Related issue: https://github.com/phetsims/a11y-research/issues/168

**Comment by emily-phet** [comment]
I think we should send out a Quad specific email, so it gets it time to shine on its own. 

We could also use some screen capture from the interview footage Sarah captured to include, and have a brief blurb about this sim being a collaborative project. 

Re inclusive features / voicing specific emails, I think we should plan a short series of emails specifically on inclusive features linking to the new videos (once they're done) starting in August. Fall is the best time for that kind of info as people are in planning / prep mode. Now they're in "survive the end of the school year" mode.

**Comment by terracoda** [comment]
Just an FYI, I composed a Voicing announcement a long time ago, and it has been waiting for comment and approval.

**Comment by terracoda** [comment]
Here's a link to the "general" Voicing feature announcement I drafted a while back:
https://docs.google.com/document/d/1BfnncnWElNjcNPDGWVtdRr0oJFXum2FGZ5fzSQ8jebA/edit#heading=h.ae9x9dndha8y

 @emily-phet, you wanted to wait to announce the Voicing feature until we had more than just a couple published. With Quadrilateral, we will have 5 simulations with the Voicing feature.

I don't understand why we can't do a nice Voicing announcement in addition to announcing Quadrilateral. Our audience has not yet been introduced to the Voicing feature.

**Comment by terracoda** [comment]
We can add Quad to the general announcement or leave it separate. I don't think it hurts to put Quad in the Voicing announcement as well as posting a proper announcement for this amazing new simulation.

**Comment by terracoda** [comment]
I started a Quad announcement email document here
https://docs.google.com/document/d/1L--tFSaqrHQtmyoEWwUYDb7z3tYK7Lnofu2BbVKhHMM/edit#

Adding video should be able to shorten the text.

For now, I have included the interaction summary (from sim page), list of inclusive features tweaked to encourage exploration, and learning goals (taken directly from sim page).

What is challenging for this announcement is what to include to capture the embodied aspect?
- use with tangible quad
- use with other forms of input, e.g. camera input which will still be on the prototypes page

**Comment by terracoda** [comment]
@emily-phet, @brettfiedler and I re-organized and greatly shortened the Quad email announcement. Would you like to have a look?

**Comment by brettfiedler** [comment]
Made another pass. Just one final question, @emily-phet, then it's good to go. I saw you mentioned wanting more info about CI:H. While I suppose we can't plant it on the main webpage, we do have the Camera Input: Hands video ready to go. We could link it here in the page or find a way to quickly link it in the Quadrilateral CI:H prototype on the prototypes page?

**Comment by brettfiedler** [comment]
Email was sent out!
