### ISSUE TITLE
Sim crashes on Shape Sound Options adio buttons (Preferences menu)

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#421]
I found this while wrapping up #282.

The sim has crashed twice now, so reproducible.

I move keyboard focus to radio buttons, and then hit the down arrow key to move to the 2nd radio button. The focus highlight moves, and the sim becomes unresponsive, requiring a full reload. 

Maybe you forgot something simple on the radio buttons? I haven't seen this behaviour before?

It might be a bigger issue. Just re-loading the sim again.

**Comment by jessegreenberg** [comment]
I just tried in Windows 10 Chrome, Firefox and Edge with both master and the latest dev version and I am not seeing this yet. @terracoda are you seeing this in https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.76/phet/quadrilateral_all_phet.html?

Can you please confirm you have the sim and all common code pulled to latest?

**Comment by terracoda** [comment]
No, I was using master.

**Comment by terracoda** [comment]
I pulled on phettest.

**Comment by terracoda** [comment]
I'll try again, and clear my cache.

**Comment by terracoda** [comment]
It's working fine - closing. I must have been missing some code :-)
