### ISSUE TITLE
Voicing reads description for last part of shape that you tab through before moving to other controls

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#422]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.2.1

**Browser**
Safari 16.3

**Problem description**
For https://github.com/phetsims/qa/issues/923, with Voicing on, if I quickly tab through all of the corners/sides of the shape to reach the other controls, Voicing will always read out the description for Side DA. Likewise, if I Shift + Tab through all the angles/sides, to get to the Voicing Toolbar, it will read the description for Corner A. 

**Steps to reproduce**
1. Turn on Voicing and select all Voicing Options. 
2. Exit the Preferences menu
3. Shift + Tab through all controls and all areas of the shape to reach the Voicing Toolbar -- you will hear the description for Corner A.
4. Tab through all corners/sides to reach the top controls -- you will hear the description for Side DA.

**Visuals**

https://user-images.githubusercontent.com/87318828/228376153-507fda89-efe5-438d-9863-9c06d10eb60f.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.76/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.76 2023-03-28 17:13:45 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1342x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by terracoda** [comment]
Hmm, there is a bit of lag there. We can probably improve that.

**Comment by jessegreenberg** [comment]
Ahh, thanks @Nancy-Salpepi - this was actually introduced recently in #270.  Priority for the Utterances for all quadrilateral components was raised and that is causing this. I guess we need to be a little more sophisticated in how we solve that issue.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi can you please try on master, is that better?

**Comment by Nancy-Salpepi** [comment]
Yes! I don't hear anything about side DA or corner A when I am tabbing through. 🙂

**Comment by jessegreenberg** [comment]
Hooray! OK thank you for finding and checking. Closing.
