### ISSUE TITLE
Voicing isn't interrupted when pressing other controls

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#424]
**Test device**
MacBook Air and iPad

**Operating System**
macOS 13.2.1 and iOS 16.3.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/923, pressing other parts of the shape will interrupt what is being voiced, but pressing any other control, including Reset All, will not interrupt the utterance. I looked back at other dev versions and the utterance was interrupted when pressing other controls, but maybe this change was intentional?

**Steps to reproduce**
1. Enable Voicing and select all Voicing options
2. Press a side or corner
3. Press Reset All or any other control along the top or side of the play area

**Visuals**

https://user-images.githubusercontent.com/87318828/228566410-7a54a57f-a118-42b1-a472-6f1e620e35cb.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.76/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.76 2023-03-28 17:13:45 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1342x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi - I think this is caused by the same issue as #422, can you please confirm this is fixed in master?

**Comment by Nancy-Salpepi** [comment]
You're right @jessegreenberg. The little voice inside my head was telling me to check master. I don't know why I never listen to it!
Closing!
