### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#428]
We will need screenshots for 1.0!

@BLFiedler are you familiar with making these? I am not sure how it is done.

Once ready We need to check them into master and then cherry-pick them into 1.0 branch.

**Comment by BLFiedler** [comment]
Found this in the QA book for guidance

https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots

**Comment by BLFiedler** [comment]
Followed QA book instructions. They are there now! Closing.
