### ISSUE TITLE
Keyboard Nav dialog should include checkboxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#431]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/926.
Discussed with @terracoda over zoom. The keyboard nav dialog says that to press a button you should use enter or space. However, to press a checkbox you must use space. There are a number of checkboxes, but this instruction is not included.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-rc.2/phet/quadrilateral_all_phet.html
Version: 1.0.0-rc.2 2023-04-04 16:04:39 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe and @terracoda, added to master and cherry-picked into the 1.0 branch. dependencies.json was updated. To be verified in next RC.

**Comment by KatieWoe** [comment]
Looks good in rc.3
