### ISSUE TITLE
Layered sounds can become off beat in macOS Safari

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#435]
While investigating https://github.com/phetsims/scenery/issues/1555 I noticed that layered sounds get out of sync on macOS 11.7.2 Safari.

To reproduce
1) Create a rectangle
2) After a short delay, return to square

The layered square sounds are a bit off beat.

Will need to patch for https://github.com/phetsims/qa/issues/926.

**Comment by jessegreenberg** [comment]
Did not happen in macOS Chrome, so this is Safari specific.

**Comment by jessegreenberg** [comment]
This does not happen in dev.73, so I think this is related to https://github.com/phetsims/quadrilateral/issues/345.

@Ashton-Morris can you think of a reason why sounds_quadMelodyTracks004 from [this folder ](https://drive.google.com/drive/folders/1g-wUm7l5cKQfIlUsj2VJ0rUR9egjfWqG)would work well but the same sound file from [this folder ](https://drive.google.com/drive/folders/1dEa7U9d2vjiTu9UtTp92Z4e1Jq7Ov5wo)would get off-beat? This only seems to happen in macOS Safari.

**Comment by Ashton-Morris** [comment]
@jessegreenberg I pulled these into my DAW and into a spectrogram application, they are identical except for one being stereo. I don't think its the files that are causing an issue.

I tried this in safari and I am getting the same off-time behavior that you are getting.

**Comment by jessegreenberg** [comment]
OK thanks so much for looking into it @Ashton-Morris. Ill try to put the old sound file into the current version of the sim and see if that fixes the problem. If it is fixed, that will indicate its a problem with the way Safari is reading the file - otherwise it will tell us its a problem with the code.

**Comment by jessegreenberg** [comment]
OK, I just confirmed that this is fixed on master by reverting to the lower quality sound file. So something about the higher quality file is changing behavior in macOS Safari.

**Comment by jessegreenberg** [comment]
I found an online waveform viewer called audiomass.co and it might be showing the issue. On Chrome, it shows that the high quality audio file is 1.992 seconds long. In Safari, it shows the audio file as 2.016 seconds long.

**Comment by jessegreenberg** [comment]
I downloaded the file, re-exported it with Clip Champ, and now safari reports it is the same length in time as Chrome. However, Clip Champ inflated the file to 59 kb (because it is mp4 instead of mp3).

I tried the same process using audiomass.co but audiomass made it even longer in all browsers (probably adding extra silence)

**Comment by Ashton-Morris** [comment]
I have uploaded these sounds to[ this folder](https://drive.google.com/drive/u/1/folders/1dEa7U9d2vjiTu9UtTp92Z4e1Jq7Ov5wo). Hopefully one of them does not cause the issue


- sounds_quadMelodyTracks004_160kbps.mp3
- sounds_quadMelodyTracks004_56kbps.mp3
- sounds_quadMelodyTracks004_80kbps.mp3
- sounds_quadMelodyTracks004_112kbps.mp3
- sounds_quadMelodyTracks004_128kbps.mp3

**Comment by jessegreenberg** [comment]
Thanks @Ashton-Morris! I tried 160kbps and 80kbps. 80kbps still sounded off in Safari, but 160kbps aligns well with the other tracks. Ill commit that one. The size of the sounds directory is still small IMO (3.8MB, down from 10MB in https://github.com/phetsims/quadrilateral/issues/345) and its worth the slightly larger size.

Ready to cherry-pick into the RC branch.

**Comment by jessegreenberg** [comment]
Hey QA team - to verify this, you should be able to do the following in macOS Safari.
1) Make a rectangle.
2) Go back to a square.

When broken, one of the sounds will be off-beat. You should be able to hear it broken in rc.2. It should sound right in rc.3.

**Comment by Nancy-Salpepi** [comment]
This is fixed in rc.3.
