### ISSUE TITLE
Prepare a shareable version with prototypes and other improvements

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#443]
We have been making some improvements to the prototype content so that it is nicely shareable. That includes
1) Adding media pipe controls and making their content specific to this sim (#258)
2) Improving controls for BLE connection (#315)
3) Adding support for Voicing of the BLE controls (#315)
4) Adding screen reader support for tangible and BLE controls (#441)
5) Following up from #441, maybe we want to make the localization tab screen reader accessible as well. (not done yet)

How should we share a version with these changes? Should all of these improvements be included in the version we share? Some options:

- We could publish a dev version with almost no effort but none of these improvements will be in the live 1.0 release. It might be nice to show off prototype features with a query param from the latest version on the website.
- We could patch these fixes into a maintenance release - A little more time consuming up front but less likely to introduce bugs and therefore would have lower QA and bug fixing cost. We could select which changes we want to include in the release.
- We could publish a 1.1 version, starting a new RC process from the beginning. Much more QA time required, but less time spent cherry-picking changes into the 1.0 branch.
- Other?

**Comment by terracoda** [comment]
@brettfiedler, do you agree with going through QA for a 1.1 release? I figure we need to do screen reader testing on the changes to the Preferences menu, so that's why I think that is a good option.

It seems https://github.com/phetsims/joist/issues/930 might get addressed soon, so we might not need to wait too long for that.

**Comment by brettfiedler** [comment]
We discussed and decided it might be cleanest to go 1.1. More QA time, but less dev time. QA queue seems light at the moment. Will vet out recent common code changes. We have a little bit of time before prime announcement time (which we need to finalize).

1. Need https://github.com/phetsims/joist/issues/930 complete - TS reviewing, one final dev task for JG, then review and close.
2. Dev-lite test (including screen reader on preferences menu only)
3. Respond to issues
4. RC testing
5. Publish 1.1

Timeline: Between 2-4 weeks

Other items: 
- BF: [Upload teacher tips when finished (minor task)](https://github.com/phetsims/quadrilateral/issues/258)

**Comment by jessegreenberg** [comment]
Quadrilateral 1.1 has been published to production! https://phet.colorado.edu/sims/html/quadrilateral/latest/quadrilateral_all.html
