### ISSUE TITLE
Voicing Keyboard Shortcut should be invisible when in locales other than English

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#444]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/958, in the Keyboard Shortcuts Dialog, the Shape Shortcut involving Voicing should be invisible when in locales other than English. 
See https://github.com/phetsims/quadrilateral/issues/249#issuecomment-1370207090. 

**Visuals**
<img width="396" alt="Screenshot 2023-06-26 at 9 34 13 AM" src="https://github.com/phetsims/quadrilateral/assets/87318828/4288d78c-5a64-4178-8f7d-6f86afea1668">

**Comment by jessegreenberg** [comment]
Thanks for finding this @Nancy-Salpepi, you are right. I think the intention from https://github.com/phetsims/quadrilateral/issues/249#issuecomment-1370207090 was that this would never be displayed if Voicing is not available. It is correctly hidden for other languages on startup but not at runtime for dynamic locales.

I am looking into this now but was surprised to see that the help content does not support making rows of content invisible during runtime. Ill keep looking.

**Comment by jessegreenberg** [comment]
In the above commit a row of keyboard help content can be hidden. The check shape row is hidden if voicing is not supported for the current locale.  It should be hidden when the language changes and when running the sim in a different language (not all file).

@Nancy-Salpepi can you please confirm?

**Comment by Nancy-Salpepi** [comment]
This looks good in master.

**Comment by jessegreenberg** [comment]
Great, thank you! Closing.
