### ISSUE TITLE
Interactive highlight flashes when moving mouse between button and text

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#445]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/958, with interactive highlights on, if I move my mouse back and forth between the lock button and the text "Small Steps" the interactive highlight flashes. I don't see this happen when I move between a checkbox/radio button and text. 

This also happens in published. 

**Steps to reproduce**
1. Turn on interactive highlights
2. Move mouse between the lock button and the text. 

**Visuals**

https://github.com/phetsims/quadrilateral/assets/87318828/928fcb6f-6050-407a-ad60-680d03f89935

**Comment by Nancy-Salpepi** [comment]
Actually, if I place the mouse between the 2, the highlight disappears. 
Looking at the pointer areas, there is nothing around the text, even though pressing the text presses the button. 
<img width="194" alt="Screenshot 2023-06-26 at 2 25 51 PM" src="https://github.com/phetsims/quadrilateral/assets/87318828/8d9eddcd-c8bd-489f-ad82-c8b8f7c9fcd5">

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, that makes sense. The pointer area for the button is set in its implementation but the listener and interactive highlight work for the text because it was added as a child of the button.

The easiest thing to do is to make the text not clickable and to remove the interactive highlight around it.  @brettfiedler what do you think of that, is that acceptable? Otherwise we can change the composition of the button and text so this problem goes away.

**Comment by brettfiedler** [comment]
There's some similarity with a checkbox here in terms of disabled and enabled state - even though we chose to use a button. I think I would be okay removing the highlight from the text and making it not clickable, but I want to check with @terracoda to see if there's a reason pressing the text should behave more like a checkbox/radio button.

**Comment by jessegreenberg** [comment]
During standup meeting today @terracoda mentioned that it would be ideal for the flickering to be fixed while the text is still clickable so I am going to start working on that as a fix.

**Comment by terracoda** [comment]
Yes, @jessegreenberg, there should be no "touch-area gap" between the button and the supporting button label. The entire area should be a touch area, like the entire area is highlighted on keyboard focus.

**Comment by terracoda** [comment]
We have the same problem in Ratio and Proportion.

**Comment by terracoda** [comment]
Is this lock button with a supporting label a common code component?

**Comment by Nancy-Salpepi** [comment]
Ratio and Proportion uses a checkbox not a button. I don't see any flashing there.

**Comment by terracoda** [comment]
It did originally, but this is on master.
<img width="1062" alt="Screen Shot 2023-06-28 at 4 05 39 PM" src="https://github.com/phetsims/quadrilateral/assets/1902116/47cd7b75-4ede-41e8-adca-70d8d50e72c9">

**Comment by terracoda** [comment]
This is published version, but a maintenance release will turn the Ratio Lock into a "text-supported button".
![Screen Shot 2023-06-28 at 4 07 42 PM](https://github.com/phetsims/quadrilateral/assets/1902116/b3b33411-07a8-4b62-aaa9-9ce00abbf2ba)

**Comment by Nancy-Salpepi** [comment]
ahhhhh! Got it! Thanks Taliesin!

**Comment by terracoda** [comment]
I think if we remove any padding or margin on the right side of the button and the left side of the text, we won't any flickering. Visually, these two pieces are 1 thing. And in the code they are nested together as one thing, so the flicker is just a presentational mishap that seems simple to fix.

**Comment by terracoda** [comment]
@jessegreenberg, will look into making the fix in common code. 

I think this sort of "text-support-iconic toggle button" is a really useful component.

It emerged through 2 design challenges - 1 voicing and 1 visual.

I could figure out a way to gracefully voice the "Lock Ratio" checkbox, so we came up with the iconic Ratio Lock checkbox. 

The for Quad, Brett and I didn't want another checkbox for locking the small steps, so we merged the idea of a "text-support-iconic toggle button" into Quad and RaP.

**Comment by jessegreenberg** [comment]
OK, should be fixed for quadrilateral. The pointer areas are adjusted so that the highlight doesn't flicker. They also update with dynamic locales.

> remove any padding or margin on the right side of the button

True, but that would impact the layout. so I went with adjusting the pointer areas.

> will look into making the fix in common code.

I can't take this on at the moment but the next time we need this kind of UI combination we should generalize it.

**Comment by jessegreenberg** [comment]
Behavior after the fix:

![rts2](https://github.com/phetsims/quadrilateral/assets/6396244/734f2bde-de1f-4c58-8a39-96c7f5f6579d)

Closing.

**Comment by terracoda** [comment]
Thank you @jessegreenberg and @Nancy-Salpepi.
