### ISSUE TITLE
Screen readers do not correctly read radio button under "Shape Sound Options"

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#446]
For https://github.com/phetsims/qa/issues/958, with NVDA and with VO, the "Unique sounds identify each shape" radio button is read the same as the first selection.
<img width="1440" alt="Screenshot 2023-06-27 at 12 53 35 PM" src="https://github.com/phetsims/quadrilateral/assets/87318828/442287ac-3118-4d79-ab54-e00adab7cfb0">

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi! The string is just incorrect, fixed in the above commit.
