### ISSUE TITLE
Reading labels when there are none

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#449]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/961
When labels are turned off, if you listen to voicing descriptions of the shape it will still refer to the labels. Saying things like "side c-d" or "corner b" etc. Should this be reworded when such labels aren't there?

**Steps to reproduce**
1. Make a shape such as a trapezoid
2. Uncheck the labels box
3. Turn on voicing
4. Listen to the description of the shape
5. Click on the shape edges and corner

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.1.0-rc.1/phet/quadrilateral_all_phet.html
Version: 1.1.0-rc.1 2023-06-28 19:27:03 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - I don't think this is a bug, even though "Labels" are hidden visually we still need a way to identify each Vertex/Side in the speech interface.

@terracoda do you agree?

**Comment by brettfiedler** [comment]
Yeah, this was explicitly discussed during implementation. It is an atypical case, but unavoidable without inventing new names for the sides or implementing a system to denote each side by their orientation which was deemed too complex for dev time.

**Comment by terracoda** [comment]
That is correct. The labels are visually hidden to reduce screen clutter, and to meet other pedagogically scenarios in the visual design, but for the Voicing they cannot be hidden or removed. They are essential for the descriptions.
