### ISSUE TITLE
Change vertex 1,2,3,4 to be  "corner 1,2,3,4"

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#45]
Currently, we use "corners" in Overview, and "vertex" on vertices.

Need to make vertex names be corner 1, corner 2, corner 3, corner 4.

**Comment by jessegreenberg** [comment]
Voicing name responses updated from vertex -> corner in the above commit. @terracoda can you please review?

**Comment by terracoda** [comment]
The corners sound great thanks.
