### ISSUE TITLE
Non-translatable string

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#450]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/961
Keyboard nav dialog has a string that does not seem to be translatable.

**Visuals**
![nottranslated](https://github.com/phetsims/quadrilateral/assets/41024075/b5d618d1-c7af-4f41-b50d-f72e02e3b014)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.1.0-rc.1/phet/quadrilateral_all_phet.html?stringTest=long
Version: 1.1.0-rc.1 2023-06-28 19:27:03 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Nancy-Salpepi** [comment]
@KatieWoe the string isn't translated because it only visible when the locale is English. 
See https://github.com/phetsims/quadrilateral/issues/444

**Comment by KatieWoe** [comment]
Whoops. Sorry about that
