### ISSUE TITLE
Query parameters in Tips have bad URLS

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/quadrilateral#451]
@brettfiedler (I think you were in charge of the tips?)

The query parameter links found in the tips are invalid (missing "_all"). Ex:
soundDesign=shapeUnique links to:
https://phet.colorado.edu/sims/html/quadrilateral/latest/quadrilateral.html?soundDesign=shapeUnique
should link to:
https://phet.colorado.edu/sims/html/quadrilateral/latest/quadrilateral_all.html?soundDesign=shapeUnique

**Comment by brettfiedler** [comment]
Thanks. Timing for locale support and when I first made these I believe caused an oversight. My bad. Fixed in the uploaded version.
