### ISSUE TITLE
In NVDA with Win 11 + Firefox it is possible to get stuck on the word "Preferences"

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#452]
In NVDA with Win 11 + Firefox I noticed that it was possible to get "stuck" on the word Preferences in the preferences menu. The up and down arrow keys didn't let you leave it and you needed to use tab. Not sure if this is an issue or an NVDA oddity.

_Originally posted by @KatieWoe in https://github.com/phetsims/qa/issues/961#issuecomment-1623971007_

**Comment by jessegreenberg** [comment]
I said: 

> I just tried on Windows 10 + Firefox with NVDA. The only time it got stuck was when I manually put it in "Forms" mode. By pressing "Insert + Spacebar" to get out of forms mode, I could read like normal again. @KatieWoe do you know if maybe it switched to Forms mode? It usually plays a harsh beep when it switches.

@KatieWoe said

> I don't think so.

So promoting to a new issue.

I will try upgrading my NVDA version to see if that is related.

**Comment by jessegreenberg** [comment]
No, I have the latest NVDA and Firefox for Windows 10 - Firefox 115.0, NVDA 2023.1.

@KatieWoe would it be possible to make a screen recording of this I can gather any other info?

**Comment by KatieWoe** [comment]
It seems to happen if you use tab or shift+tab to reach that area.

https://github.com/phetsims/quadrilateral/assets/41024075/ad736f95-39ee-4dff-b915-f9a2d274da35

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - looks like totally normal reading... Ill try again and take a brief look at the markup.

**Comment by jessegreenberg** [comment]
The markup looks like

```html
<div>
  <button>Close</button>
  <h1>Preferences</h1>
  <ul>...tabs...</ul>
  <>...tab contents...</>
</div>
```

The "Preferences" heading is not wrapped in another element (just a thought I had that might have explained this).

**Comment by jessegreenberg** [comment]
I was able to get this to happen in two different ways:
First way:
1) Tab to the close button.
2) Read with NVDA to an unselected tab. Activate the tab (in browse mode).
3) NVDA gets stuck on "Preferences".

OR
1) Tab to the close button
2) Read to the "Preferences" h1.
3) Press the "Enter" key. 
4) NVDA is now "stuck" on Preferences.

**Comment by jessegreenberg** [comment]
I created a basic HTML page that looks like this with no JavaScript and no complex styling. I can reproduce BOTH of the above bugs in that context.

![image](https://github.com/phetsims/quadrilateral/assets/6396244/755aae9c-2ce1-40a6-8ef4-2117cf6ff726)

**Comment by jessegreenberg** [comment]
OK, I found two things

1) The behavior goes away when I remove "role=dialog" attribute.
2) The behavior changes when I remove the aria-labelledby attribute. We have an "aria-labelledby" attribute on the dialog element pointing to the "Preferences" h1. When "aria-labelledby" is removed, virtual cursor behavior is the same, but instead of getting stuck on "Preferences", it gets stuck on "blank".

So... @KatieWoe I think you found an NVDA bug. It might be a feature to read the aria-labelledby content of the dialog in this case. But it seems very buggy that the virtual cursor gets stuck. I am going to submit a bug report to NVDA and add this to the list of known screen reader quirks.

**Comment by terracoda** [comment]
Just wondering if there is a way out of the stuck spot, or is it a keyboard trap?

**Comment by KatieWoe** [comment]
Tab or shift+tab gets you to a different section

**Comment by jessegreenberg** [comment]
OK, closing - to be tracked long term in https://github.com/phetsims/a11y-research/issues/190.
