### ISSUE TITLE
Description + Voicing warning suggestion

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#453]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox + NVDA
**Problem description**
For https://github.com/phetsims/qa/issues/961. This is mostly a suggestion for any sim that has screen reader support of the preferences menu and a voicing option. As of now, screen reader use and voicing are not supported simultaneously. I think some indication of this would be a good idea. Even if it is only read when using a screen reader. 

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.1.0-rc.1/phet/quadrilateral_all_phet.html
Version: 1.1.0-rc.1 2023-06-28 19:27:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment]
@KatieWoe, thanks for this comment. I do hear your concern. I have been reluctant to add a warning, but I think it would be easy to add some extra help text to the Voicing feature if the rest f the team agrees.

I don't remember explicitly asking screen readers users if they thought they would need an explicit warning before turning on the Voicing feature, so I don't have data on this.

Once the feature is turned on, it becomes very clear that if using a screen reader you need to decide to either not use Voicing or turn off your screen reader.

We could add to the help text in the Preferences Menu something like:

**Voicing**
Voice and highlight content as you interact. (Warning: Voicing is an alternative interactive described experience that may be helpful for many learners and learning contexts. Screen reader users need to turn off their screen reader to use Voicing).

**Comment by terracoda** [comment]
Tagging @emily-phet, @brettfiedler for comment.

The drafted "System Requirements" will capture this warning, once the Inclusive Features section is live on the website:

> - The Voicing feature is not meant to be used simultaneously with screen reader software. When a screen reader is in use, once a learner enables Voicing they should temporarily turn off their screen reader software.

**My Questions for you:**
1. Is it enough to communicate this information through the feature's "System Requirements"?

If not:

2. Do you think a warning is needed in the Preferences Menu? 
3. Do you think the warning should be hidden?

**Comment by emily-phet** [comment]
1. Yes.

I think the auditory overlap will make it quickly apparent that it's intended that only one system be used at a time, Voicing or Interactive Description. So if someone doesn't know, they will soon find out in the process of using the features. So I don't think we need to include this information in the preferences menu. I think doing so will potentially cause more harm than help, as many using Voicing will not know what a screen reader is, and those that do may balk at being told they should turn it off. That's different than a situation where the first recognize that Voicing provides a lot of information and they choose to turn it themselves.

**Comment by emily-phet** [comment]
Re-reading this thread, I think the key thing here is that it's not that Voicing + Interactive Description are not supported, it's that they are not designed to be used together. You can use them together, it will just likely be excessively verbose. But also, maybe not. The default setting for Voicing provides access to the Voicing Toolbar, object names and reading blocks. This might not be too verbose for use with a screen reader, and there may be cases where someone is using a screen reader and someone else is not, and having both may provide some benefit. 

As I mentioned above, I don't think there is a significant benefit to adding info on this in the preferences menu, and there could be potential harm.

**Comment by terracoda** [comment]
@emily-phet, that is a very interesting scenario you mentioned. I just tried it out.

And while there is repetition of state descriptions, the responsive descriptions are not duplicated, and the screen reader adds the web interaction semantics that Voicing does not contain.

Indeed they can be used together, it just depends on what kind of described experience you are looking for.

We will leave any necessary warnings in the Systems Requirements for the feature.

**Comment by terracoda** [comment]
Thanks @emily-phet. Closing issue.
