### ISSUE TITLE
Investigate Bluetooth as a device communication method

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#52]
Here is an example of using Bluetooth with electron: https://www.electronjs.org/docs/latest/tutorial/devices

Info about using HTML5 bluetooth:  https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API

Bluetooth is still very experimental for HTML5 and requires enabling in chrome://flags. It has relatively poor support in HTML5:
![image](https://user-images.githubusercontent.com/6396244/151035855-767c3cae-bdd9-4f37-90a2-d0d095e5f329.png)

**Comment by jessegreenberg** [comment]
This issue is to document thoughts and resources, but we are not going to dedicate time to this just yet. Waiting for assignment.

**Comment by jessegreenberg** [comment]
We would like to explore this now. I am going to start with electron communication because browser based communication looks so experimental. There is a node library for BLE that I am goin to try. https://www.npmjs.com/package/node-bluetooth

**Comment by jessegreenberg** [comment]
It seems that project isn't really maintained and fails to build on Windows.

**Comment by jessegreenberg** [comment]
I found another library called noble, but it seems very hacky and I have to override my bluetooth drivers to get it to work: https://github.com/noble/noble

**Comment by jessegreenberg** [comment]
It seems like using Zadig to override Windows bluetooth drivers is common practice for all Node.js BLE libraries. Here is another that requires it: https://github.com/noble/bleno

**Comment by jessegreenberg** [comment]
Ah, electron may have some direct bluetooth support: https://www.electronjs.org/docs/latest/tutorial/devices OR it might just be going through Chromium. Since it is a chromium process you presumably don't need to enable any special settings.

**Comment by jessegreenberg** [comment]
I got a basic bluetooth connection working in Electron. I am able to query my bluetooth headphones and read battery level. Examples here are super helpful: https://web.dev/bluetooth/

**Comment by jessegreenberg** [comment]
OK, I have had good luck setting up BLE in the electron app. Electron just uses Web bluetooth but it is supported out of the box because it is running a customized instance of Chromium with bluetooth enabled. If we want to switch to using bluetooth directly from the browser running the sim, we should be able to do that easily.

I wasn't able to test receiving stream of data over bluetooth because none of the devices I own (phone/watch/TV) offer bluetooth services that broadcast real-time updates. But it seems like we will be able to since I got basic queries working.

Questions for Scott/Chris:
 - What will the BLE device "look" like? Will it have unique filters/services/name so we can find it when we `requestDevices()`? Are those set by the chip or do you configure that?
 - Will the changing values broadcasted over bluetooth be listed as a unique "service" like "heart_rate" at the https://web.dev/bluetooth/#notifications example?

Questions for the team:
- This should work directly in the Chrome/Edge as long as `#enable-experimental-web-platform-features` is set. Then we wouldn't need the Electron app at all. But using the electron app means we can know that communication will work without requiring the user to set a flag. Which one is better?
- If we opt for directly in the browser, we will have to get around the limitation that bluetooth only works on https (making it difficult to test in development environments)

@BLFiedler I think I have explored all that I can without the device! I think we are ready to try Bluetooth with collaborators in the electron app or sim when we are ready.

Patch with bluetooth in the Electron app:

<details>

Index: index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/index.html b/index.html
--- a/index.html	(revision 0d630c4a5c6c8520fbc9d27c7910354b8acb6144)
+++ b/index.html	(date 1643941658670)
@@ -59,6 +59,10 @@
     <label for="debug-values-checkbox">Show model values</label>
     <input id="debug-values-checkbox" type="checkbox">
 
+    <h2>Bluetooth Controls</h2>
+    <button id="bluetooth-test-button">Test Bluetooth</button>
+    <p>Currently selected bluetooth device: <strong id="device-name"></strong></p>
+
   </div>
 </div>
 
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/package.json b/package.json
--- a/package.json	(revision 0d630c4a5c6c8520fbc9d27c7910354b8acb6144)
+++ b/package.json	(date 1643935840295)
@@ -26,7 +26,8 @@
     "lodash": "^4.17.21",
     "serialport": "^9.2.7",
     "socket.io": "^4.4.0",
-    "socket.io-client": "^4.4.0"
+    "socket.io-client": "^4.4.0",
+    "webbluetooth": "^2.1.0"
   },
   "config": {
     "forge": {
Index: renderer.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/renderer.js b/renderer.js
--- a/renderer.js	(revision 0d630c4a5c6c8520fbc9d27c7910354b8acb6144)
+++ b/renderer.js	(date 1643947567768)
@@ -233,4 +233,29 @@
     messageType: ServerMessages.DEVICE_SELECTED,
     messageContent: selectedPath
   } );
-} );
\ No newline at end of file
+} );
+
+// Bluetooth testing
+async function bluetoothTest() {
+
+  // Accessing any bluetooth devices that will provide a battery level
+  const device = await navigator.bluetooth.requestDevice( {
+    filters: [ { services: [ 'battery_service'] } ]
+  } );
+  document.getElementById( 'device-name' ).innerHTML = device.name || `ID: ${device.id}`;
+
+  // connect to the device
+  const server = await device.gatt.connect();
+  console.log( 'connected' );
+
+  const batteryService = await server.getPrimaryService( 'battery_service' );
+  console.log( 'service established' );
+
+  const batteryCharacteristic = await batteryService.getCharacteristic( 'battery_level' );
+  console.log( 'characteristic received' );
+
+  const value = await batteryCharacteristic.readValue();
+  console.log( `battery value: ${value.getUint8(0)}`);
+}
+
+document.getElementById( 'bluetooth-test-button' ).addEventListener( 'click', bluetoothTest );
\ No newline at end of file
Index: main.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main.js b/main.js
--- a/main.js	(revision 0d630c4a5c6c8520fbc9d27c7910354b8acb6144)
+++ b/main.js	(date 1643942005340)
@@ -37,7 +37,7 @@
   mainWindow.loadFile( 'index.html' )
 
   // Open the DevTools for debugging
-  // mainWindow.webContents.openDevTools();
+  mainWindow.webContents.openDevTools();
 
   // Handle messages that we receive from the child process
   addServerMessageListener( message => {
@@ -82,6 +82,15 @@
       messageContent: true
     } )
   } );
+
+  // bluetooth testing
+  mainWindow.webContents.on( 'select-bluetooth-device', ( event, deviceList, callback ) => {
+    event.preventDefault();
+    if ( deviceList && deviceList.length > 0 ) {
+      callback( deviceList[ 0 ].deviceId );
+      console.log( deviceList );
+    }
+  } );
 }
 
 // This method will be called when Electron has finished
Index: bluetooth.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bluetooth.js b/bluetooth.js
new file mode 100644
--- /dev/null	(date 1643935980130)
+++ b/bluetooth.js	(date 1643935980130)
@@ -0,0 +1,39 @@
+const bluetooth = require("webbluetooth").bluetooth;
+
+
+const messageListeners = [];
+
+/**
+ * Adds a listener to be called when the bluetooth.js sends a message to be handled by main.js.
+ * @param listener
+ */
+const addBluetoothMessageListener = listener => {
+  messageListeners.push( listener );
+}
+
+/**
+ * Removes a listener that was added by addBluetoothMessageListener.
+ * @param listener
+ */
+const removeBluetoothMessageListener = listener => {
+  const index = messageListeners.indexOf( listener );
+  if ( index >= 0 ) {
+    messageListeners.splice( index, 1 );
+  }
+}
+
+/**
+ * Send a message to the parent Node.js process.
+ * @param {string} messageType, determines how the parent process should handle.
+ * @param {*} messageContent
+ */
+const sendMessageToMain = ( messageType, messageContent ) => {
+  messageListeners.forEach( listener => {
+    listener( {
+      messageType: messageType,
+      messageContent: messageContent
+    } );
+  } );
+};
+
+module.exports = { addBluetoothMessageListener, removeBluetoothMessageListener }
\ No newline at end of file


</details>

**Comment by BLFiedler** [comment]
Waiting on information from folks making the devices for specific implementation of this into the simulation.

**Comment by jessegreenberg** [comment]
Scott and I met today and got BLE messages sent from his chip to an electron app. He is going to work on getting all Quad data moving through the chip. Then we will pair again to either receive BLE messages within the sim directly or within the electron app.

**Comment by jessegreenberg** [comment]
The above commit sets up way to connect to a bluetooth device in the sim, Scott and I will meet tomorrow to try it out.
![image](https://user-images.githubusercontent.com/6396244/162367818-60b918f1-3e5f-42ce-ada2-7767e7a8a335.png)

**Comment by jessegreenberg** [comment]
Shockingly, this sim code worked with Scott's bluetooth chip out of the box! Scott will continue to get the data from the device ready for bluetooth sending but we are ready to respond to it sim-side.

**Comment by BLFiedler** [comment]
We have successfully implemented this in the Tangible Device to Sim direction! The communication itself works quite well and we have a number of variables to tweak to smooth it out for a given device.

![Image](https://user-images.githubusercontent.com/47331395/183091407-5da6608e-df33-43af-ad7f-a7c53116544d.png)

We may wish to find a way to keep this in the preferences menu at publication.

The scope of this issue is likely to expand one to two notches. Scott is working on an actuated Quad that can be controlled by the simulation (the tangible device reads values from the sim and an actuated linear potentiometer updates the shape (lengths?) accordingly.

We'll want to investigate how to support communication in this direction over Bluetooth when Scott is ready. Trickier will be supporting priority during full bidirectional communication (does the sim decide the tangible device shape or does the tangible device decide the shape on the sim).

A farther-reaching goal and outside the scope of this issue is a web intermediary that connects two simulation instances on one to two computer devices with one tangible device on either end.

**Comment by BLFiedler** [comment]
Tagging @emily-phet for future discussions and prioritization on this topic.

**Comment by emily-phet** [comment]
I'd love to hear more details. Let's talk about this on Wednesday if there's time - I know @jessegreenberg has been working recently on updates to the Preferences menu for other project needs.

**Comment by BLFiedler** [comment]
Goals of this issue have been accomplished. We'll open up other issues to refine Preferences menu/query parameters for publication, as well as investigation into bidirectional communication when Scott has finished working on the actuated quad.
