### ISSUE TITLE
Should the model bounds be changeable?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#55]
I think it used to be that the simulation space would expand outside of the dev bounds on larger screens. That is no longer happening. The rectangle that draws available model space is the same size, no matter how large the screen is. I think we lost it when we made it so that the bounds can't overlap the ResetAllButton (or other controls in the future). So the bounds can't extend to the right.

But the bounds could extend further to the left here:
![image](https://user-images.githubusercontent.com/6396244/152450243-0080fbf2-3e56-42b4-961a-07b16211fe35.png)

@BLFiedler is this something that should happen?

**Comment by BLFiedler** [comment]
For later discussion
![iPadaspect](https://user-images.githubusercontent.com/47331395/154098427-e2732e13-23b1-4578-8581-25fb1ba2c775.png)
:

**Comment by BLFiedler** [comment]
Ideally, we want to have the play area expand to fill any usable space in the window. (left and right side in landscape aspect ratios, top and bottom in portrait aspect ratios)

**Comment by BLFiedler** [comment]
I suspect issue #80 will impact the solution to this, so temporarily deferring it.

**Comment by BLFiedler** [comment]
I do not believe it is worth handling the portrait case for publication. The play area is not amenable to wide/tall aspect ratios given the symmetry of the shapes we're scaffolding, the precise grid spacing, and the description areas.

Closing.
