### ISSUE TITLE
Implement sound design

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#6]
An issue to commit against for the sound implementation in quadrilateral. Created as requested in https://github.com/phetsims/quadrilateral/issues/5. The first designs are being discussed in https://github.com/phetsims/quadrilateral/issues/4.

**Comment by BLFiedler** [comment]
Sound design is being finalized and polished in other issues 
Boundary sounds: #127 
Shape pick up sounds: #128 
Shape sonification iterations past initial sound design: #175 
Sound ducking during Voicing: #185 

Considering this issue stale. Closing.
