### ISSUE TITLE
Replace and test out new sound for "quad-out-of-parallel" condition

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/quadrilateral#66]
[I have updated a sound and would like to test these changes.](https://drive.google.com/drive/u/0/folders/1YNrthgUqZXTQw-gA8ch6XIwBZ_RhsIKW)

Replace: **quad-out-of-parallel-001.mp3**

With : **quad-out-of-parallel-001-v2.mp3**

**Comment by jessegreenberg** [comment]
Alright, I have updated this sound. @BLFiedler @Ashton-Morris can you please review?

**Comment by jessegreenberg** [comment]
This was reassigned to me but there are no review comments, is there anything you would like to change @BLFiedler?
