### ISSUE TITLE
Kite is detected for a shape that is not a kite

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#72]
![image](https://user-images.githubusercontent.com/47331395/154747565-7245d7c2-1646-46ef-80c6-7b5f0530fd38.png)

I think it is perhaps taking any two sides being equal? A kite needs to enforce that two adjacent sides are equal length. Or we decided on a different kite metric.

**Comment by jessegreenberg** [comment]
OK I think this is fixed. I changed the check to compare side lengths instead of side angles. Now two pairs of adjacent sides must be the same length for it to be a kite.

@BLFiedler can you please confirm?

**Comment by BLFiedler** [comment]
Not seeing any rogue kites :) Closing.
