### ISSUE TITLE
Add small overshoots to vertex to help visualize external angles

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#73]
After discussion with Dor, it was noted that the presentation of the angle guides

1.) Is difficult to anchor a reference since the angle guides themselves begin in the middle of the sides, which is not where folks are visualizing the shape (either internally or externally along the sides).
2.) May bias individuals to only consider the internal angles and prevent reasoning that can leads to misconceptions for real math problems (like walking the path of an equilateral triangle resulting in a hexagon by attempting to turn the angle of the interior 60 degrees of the triangle)

I'd like to address both of these by adding short dash lines that run through the middle of the sides and outside of the shape to provide references to determine exterior angles. This is inspired and suggested by Dor's "chopstick" quadrilateral he made with rubber bands and had overhangs by the nature of its construction.

![image](https://user-images.githubusercontent.com/47331395/155007637-0dd8dd0c-54f9-4824-b06f-ef79ac0fe532.png)

Let's make them fixed length and coming out equal on the interior and exterior side. I think the appropriate behavior is for them to disappear under a vertex when the side is made small enough that a vertex overlaps and not have them emerge from the other side. These should only appear when the Angle Guides are checked.

With that, let's also bring the language used for angles in line with the current description and rename Angle Guide to "Corner Guide"

- [x] Add guide interior and exterior reference lines
- [x] Rename Angle Guide to Corner Guide

**Comment by BLFiedler** [comment]
The alternative to this is to go with our initial thought of putting the corner guides inside of the shape, but that seemed more problematic for intermediate and small shapes than our current solution for overlap/usability.

**Comment by jessegreenberg** [comment]
OK this has been added in the above commits. @BLFiedler can you please review?

In particular, want to make sure that it looks correct when it is a concave shape.

**Comment by BLFiedler** [comment]
@terracoda made the point that the Corner Guide should be Guides since there are more than 1 corner :) 

- [ ] Change Corner Guide to Corner Guides

**Comment by jessegreenberg** [comment]
OK, done - back to you @BLFiedler

**Comment by BLFiedler** [comment]
(quick change, not reopening) With the added visual markers on the shape, there are a lot of dashed lines of similar appearance. Adjust the dash interval and shortened the crosshairs. I think it helps look a touch less busy.
