### ISSUE TITLE
Updates to Read-Me Button Content (Overview & Hint)

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#75]
I have a some small changes to the Overview button content which is static:

**Overview (latest):**
A quadrilateral is a closed four-sided shape. This quadrilateral is an interactive sim. It changes as you play with it. 
Four grabbable corners and four grabbable sides allow you to create different shapes, and explore what makes a parallelogram. In addition, checkboxes add labels and guides to support your exploration, and a button resets the sim.

Note that the hint button now has dynamic content.

**Comment by terracoda** [comment]
Assigning back to me . I need to recheck because of decision on Tuesday to include shape names in the hint instead of in the details.

**Comment by terracoda** [comment]
Will re-assign shortly.

**Comment by terracoda** [comment]
I am going to make a second issue for the Hint button content as that content is now dynamic.

**Comment by terracoda** [comment]
Oh maybe, one issue is fine. Here's the final design for the hint button content. It's pretty straight forward. Here's a link to the [Hint Button Phrases and Parameters](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.2geae9lmgmz1)
![image](https://user-images.githubusercontent.com/1902116/156606933-af98cc8a-af36-4eac-b278-0f5e282b3592.png)

We will use the same static and dynamic phrases for the Interactive Description. Order might have to change, but I think it can stay exactly as it is here for now.

**Comment by terracoda** [comment]
No changes to the Read-me button hints in last 17 days, ready to implement.

**Comment by jessegreenberg** [comment]
Done, back to you for review @terracoda. The details button will no longer sound correct, that will be handled elsewhere.

**Comment by terracoda** [comment]
I think the shapes are all good, except for when it is just a general parallelogram. Currently, you have:
- You have a parallelogram, and a general quadrilateral.s Explore what makes parallelograms.

But I only want "parallelogram" in this case, like this:
- You have a parallelogram. Explore what makes parallelograms.

![image](https://user-images.githubusercontent.com/1902116/159038575-298bd3d2-3892-4391-a2e0-ac9a8828908f.png)

We might need a different hint in the parallelogram case, but for now, can you remove ", and a general parallelogram"?

**Comment by jessegreenberg** [comment]
Good catch @terracoda, thanks. Fixed in the above commit. Can you please review?

**Comment by terracoda** [comment]
The overview and hint are all good. Each shape is named correctly in the Hint button content.
