### ISSUE TITLE
Create PDOM, add Headings for Navigable Sign Posts & Tab Order for Interaction Points

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#76]
Related to checklist #74 and from the design document...

**Heading Outline for Navigable Sign Posts:**
- H1: Quadrilateral
- H2: Play Area
- H3: My Shape’s Corners
- H3: My Shape’s Sides
- H2: Control Area
- H2: Sim Resources

**Tab Order of Interaction Points:**

- (Under H3: My Shape’s Corners)
    - Corner A, movable
    - Corner B, movable
    - Corner C, movable
    - Corner D, movable 
- (Under H3: My Shape’s Sides)
    - Side AB, movable
    - Side BC, movable
    - Side CD, movable
    - Side DA, movable
- (Under H2: Control Area)
    - Corner Labels, checkbox
    - Corner Guides, checkbox
    - Reset All, button 
- (Under H2: Sim Resources)
    - Preferences, button
    - All Audio, toggle button
    - Keyboard Shortcuts, button
    - PhET Menu, pop-up button

**Comment by terracoda** [comment]
Nothing above has changed in the last 17 days. Still ready to implement the headings and interactive object names (and Tab Order).

**Comment by jessegreenberg** [comment]
Headings and PDOM traversal order have been set as described here. @terracoda would you like to review?

**Comment by terracoda** [comment]
The headings and object names sound good in VoiceOver and iOS VoiceOver.
