### ISSUE TITLE
Create Static Overview and Dynamic Hint in the Scene Summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#77]
Related to checklist #74, and from the [State Descriptions section](https://docs.google.com/document/d/1oikq9CFhZ6ajEIkLLNcXDXCXDp9q2aThqcD69THMTqI/edit#heading=h.gqilslbgkhfy) of the design doc please add the static part of the scene summary:

**Static Intro**
P: {{Quadrilateral}} is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area. 

P: In the Play Area you find your closed four-sided shape. Four grabbable sides and four grabbable corners allow you to create different shapes, and explore what makes a parallelogram.

P: The Control Area has checkboxes to add labels and guides, and a button to reset the sim.

---Dynamic part of the scene summary will go here (separate issue coming)---
**Note:** The phrases are the same as in Voicing, but in the PDOM might have a un-ordered list instead of a paragraph.

**Dynamic sim-specific interaction hint**
**Note:** Ideally, this paragraph has two separate phrases, the dynamic part, and the static part.
You have {{a parallelogram}}, {{and}} {{a square}}. Explore what makes parallelograms. 

**Static keyboard shortcuts hint:**
P: If needed, check out the Keyboard Shortcuts under Sim Resources.

More details about the parameters in the dynamic hint are mapped out in the Voicing Design Doc in [Hint Button Phrases & Parameters](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.qhavd2fyqk80).

**Comment by terracoda** [comment]
@jessegreenberg, I updated the content above to match the design document.

I included the dynamic part of the scene summary, but that also is part of issue, so the exact strings above for the shape properties could change.

**Comment by terracoda** [comment]
Copying images from the Voicing Design doc's [Hint Button Phrases and Parameters](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.fu635z2hs0cr) in case you need more details:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1902116/158031869-895f5ac9-98a2-4d52-ad1d-e09298c51705.png">

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1902116/158031895-294c5bfb-1aee-4c98-a26d-fba9a4cc63a7.png">

<img width="894" alt="image" src="https://user-images.githubusercontent.com/1902116/158031934-f3accaab-aca5-46e8-ae27-1591c7d23db7.png">

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1902116/158031950-b4237d5c-72d8-4fa2-9ebd-1f60426b704d.png">

**Comment by terracoda** [comment]
Related to Voicing issue #75

**Comment by terracoda** [comment]
Ready for initial implementation.

**Comment by jessegreenberg** [comment]
I added the static parts of the scene summary in the above commit. If I understand correctly I think that is all for this issue for now? The dynamic part is still being worked on and the tables related to Voicing in https://github.com/phetsims/quadrilateral/issues/77#issuecomment-1065947800 will be added in #75. Is that correct @terracoda?

**Comment by terracoda** [comment]
Oh yes, you are correct @jessegreenberg . This issue is just for the static parts. The interaction hint is now dynamic.

**Comment by terracoda** [comment]
The static parts of the scene summary are implemented nicely. Thanks.
