### ISSUE TITLE
Update Details read-me button content

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#78]
The content for the dynamic part of the scene summary and the Details button in Voicing are currently exactly the same, and we hope to keep it that way.

Still updating the table in the design doc.
This issue is also related to checklist issue #74.

**Comment by terracoda** [comment]
Ok, the tables in the design document is ready, I have copied images here as a record of the design. Please do no include the rows with the grey background. They are just there as edge cases for now.

@jessegreenberg, I tried to make it easier for you to break up the phrases & parameters by only having unique phrases in each cell. The ditto marks mean the string from the cell above applies. And "n/a" means there is no described property for this shape. I hope it is all clear. Note that in the second table, the only difference in the trapezoids' parallel-ness phrase is punctuation - a period for trapezoid and a comma for isosceles trapezoid.

### [Table: Details & PDOM Summary when Named Shape IS a Parallelogram](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.g9gru02za5r7)
**Examples:**
- Right now, your shape is {{a parallelogram}}. {{Opposite sides}} are parallel and {{have the same length}}, and {{opposite corners}} are {{equal}}. 
- Right now, your shape is {{a parallelogram}}, and {{a square}}. {{Opposite sides}} are parallel, {{all sides}} {{have the same length}}}}, and {{all corners}} are {{right angles}}.  

![image](https://user-images.githubusercontent.com/1902116/155544491-2a88de57-c008-4a5c-9c0d-0fafbb723f26.png)

### [Table: Details & PDOM Summary when Named Shape IS NOT a Parallelogram](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.nibhrnon14lw)
**Examples:**
- Right now, your shape is {{not}} {{a parallelogram}}. You have {{a kite}}. {{Pairs of adjacent sides}} {{have the same length}}. 
- Right now, your shape is {{not}} {{a parallelogram}}. You have {{a trapezoid}}. {{One}} {{pair of}} {{opposite sides}} is parallel.
- Right now, your shape is {{not}} {{a parallelogram}}. You have {{an isosceles trapezoid}}. {{One}} {{pair of}} {{opposite sides}} is parallel, and {{the other}} {{pair of}} {{opposite sides}} {{have the same length}}.
![image](https://user-images.githubusercontent.com/1902116/155544617-a61c7957-2251-490a-a8b3-a4620f4b015a.png)

**Comment by terracoda** [comment]
The above definitions were based on minimal definitions, so I need to iterate to include a full definition of paralell-ness, side length and corners for each and any shape.

**Comment by terracoda** [comment]
I have iterated. The new approach of focusing solely on corner and side length properties works well for shapes that are parallelograms, but is much more difficult for shapes that are not like kites, trapezoids, general quads.

I still have design questions: 

- When to describe opposites or pairs of opposites?
- When to describe adjacent properties?
- When to describe amount of actual degrees?

![image](https://user-images.githubusercontent.com/1902116/156014508-694ec446-ffea-4502-86bc-b9aad7c046f6.png)
**Kites**
![image](https://user-images.githubusercontent.com/1902116/156014653-a29000b7-79df-48ee-94d8-7a0258f301fa.png)
**Trapezoids**
![image](https://user-images.githubusercontent.com/1902116/156015464-3498d447-4de6-47e6-8b55-e27412b37c6e.png)
**Isosceles Trapezoids**
![image](https://user-images.githubusercontent.com/1902116/156015102-861f1b44-c7a3-4b23-81a5-563bd2922534.png)
**General and Concave Quads**
![image](https://user-images.githubusercontent.com/1902116/156015297-8a88930d-d7ed-4333-a917-f6f019646c12.png)

**Comment by terracoda** [comment]
Ok, at last meeting we discussed having 2 buttons for the shape details, but this not simple at this time because it would involve changes to the Preferences Menu. As a work around which is a good fit for this sim, we will move shape names to the hint button, and keep shape details for the details button. This might mean the arrangement of Strings in the PDOM might be slightly different. I'll open a separate issue for this if needed.

Here's my iteration on the Details button (and PDOM dynamic summary) that includes only corner and side property descriptions. 
![image](https://user-images.githubusercontent.com/1902116/156457882-8450203c-e186-420e-9749-526408c783f9.png)
![image](https://user-images.githubusercontent.com/1902116/156457965-760b6ae6-b680-4895-af3c-461b977c5df3.png)
![image](https://user-images.githubusercontent.com/1902116/156458042-a3de58a4-0155-4c93-8146-b58f0b57dcec.png)

THE ABOVE STRINGS may still need some tweaking, so not re-assigning yet.

**Comment by terracoda** [comment]
Ok, I think I have a solid draft of phrases and defined parameters. I would like to discuss this latest version with @BLFiedler before assigning over to @jessegreenberg 

[Shape Properties: Phrases & Parameters for Details & PDOM Summary](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.jw6i1lijfde1)
![image](https://user-images.githubusercontent.com/1902116/156608957-e0aa9e65-a9e9-48a3-9911-ac67f6be68a7.png)
![image](https://user-images.githubusercontent.com/1902116/156609150-9d9abd7c-076d-4503-ab71-5441f6027179.png)
![image](https://user-images.githubusercontent.com/1902116/156609224-cb8b0bba-0489-4e07-a469-275808b3b4e5.png)

**Comment by BLFiedler** [comment]
I do see the need for specific information when the resolution of the side length or angle differences is not enough. Especially with the Trapezoid case, where the 1 set of parallel lines is not quite obvious from the description there. Definitely worth a deeper discussion, but it's looking really good!

**Comment by terracoda** [comment]
@jessegreenberg, in the design doc I have updated the tables posted in previous comments. I am still working on the rules for non-parallelogram shapes. Everything is ready for parallelogram shapes. Everything, that is, except how best to determine the starting vertex and side.

Will assign to you when rules for non-parallelograms are documented.

**Comment by terracoda** [comment]
@BLFiedler suggested a different structure for the ordering logic:

 Within a sentence or between sentences, when ordering sets of corners or sides:
  -  Parallel (sides only)* > Equal (sides or corners)* > Remaining corners/sides*

 *When ordering within the above sets:
-  Bottom (-Y) > Left (-X). 
    - Choose the bottom-most (-Y) vertex or side (that has not been described). In the case of a tie, choose the leftmost (-X).

_Assumptions:_
- Sides are defined by their originating vertex (e.g., Side BC is ordered based on the position of vertex B)

**Comment by terracoda** [comment]
@jessegreenberg, the design doc has the latest iteration of the above table screen shots. Here are screen shots of Detail 1 and Details 1 & 2 just for a few parallelogram. There should not be any changes to the phrasing of the 3 main Details of the Shape Properties, but I am still trying to add some details that might be helpful to you for actual phrases, so i don't want to copy that big table in yet. That said, I don't think the phrase details should hold up implementation.

Just let me know if you have any questions.

**Detail 1: General description of shape’s corners and sides.** 

- The general description is always present.
- One sentence works for all shapes

**Detail 2: Shape-specific corner descriptions.** 

- The presence of the corner descriptions depends on the shape.
- If all corners are equal (squares and rectangles), the corner description is not included.

**Detail 3: Shape-specific side descriptions.** 

- The presence of side descriptions depends on the shape. 
- If all sides are equal (squares and rhombuses), the side description is not included.

![image](https://user-images.githubusercontent.com/1902116/158474225-462f89ec-3718-4c44-a2b9-9a5d84afe7fa.png)

![image](https://user-images.githubusercontent.com/1902116/158473859-016c97df-2ffb-47b7-a495-1587aa7e26f3.png)
![image](https://user-images.githubusercontent.com/1902116/158474349-36bcf14c-26ac-4e28-b493-abd03e6338c6.png)

**Comment by terracoda** [comment]
The ordering logic is in https://github.com/phetsims/quadrilateral/issues/78#issuecomment-1066994121

**Comment by terracoda** [comment]
The priority is to implement the Details button for Voicing. Add the dynamic big-picture summary to the PDOM if that makes sense and saves time. The design goal is that these descriptions will remain in synch.

**Comment by BLFiedler** [comment]
As @terracoda thought it might be helpful, I'm placing this shape hierarchy figure in this issue

![image](https://user-images.githubusercontent.com/47331395/158615918-c447df91-86ca-4f0b-a6da-e1c835e85bfa.png)

**Comment by jessegreenberg** [comment]
It seems like we need this kind of info in the model to support these descriptions
```
    - Whether all corners are equal
    - Whether all corners are right angles

    - Whether any adjacent corners are equal
    - Whether any opposite corners are equal

    - Whether any adjacent sides are equal in length
    - Whether any opposite sides are equal in length
    - Whether both pairs of adjacent sides are equal in length
    - Whether all sides are equal in length

    - What are the lowest two vertices
    - Each vertex needs to know its adjacent vertices and opposite vertex
 ```

Much of this is already calculated, but not available on the model. I think Ill refactor and add all of this to the model as reusable fields.

**Comment by jessegreenberg** [comment]
In the above commit I added the proposed model Properties and they seem to be updating successfully and correctly. Ready to work on some descriptions 🔧

**Comment by jessegreenberg** [comment]
Questions for next meeting:
-  "Corner {{B}} points toward Corner {{D}}." has note "not sure if this is required. Is it?

**Comment by jessegreenberg** [comment]
About the tolerance issue.


For the trapezoid detection issue:
 - We are adding angles and then using the same tolerance interval. For addition we could double the tolerance interval so that it is more lenient in this case.
 - We could double the `shapeAngleToleranceInterval`.
   - Note that this wouldn't quite fix it. 
 
In the end we identified that it might not be a problem! I was confused about the trapezoid definition and thought that there would be two pairs of adjacent vertices with equal angles. That is only true for an isosceles trapezoid, so I may have brought up a non-issue.

**Comment by jessegreenberg** [comment]
The above commits complete details 2, ready to start details 3.

**Comment by jessegreenberg** [comment]
OK the "details" button is done and ready for review.  There is still some cleanup to do but the Voicing is working.

The only thing I had a little trouble with was ordering the side descriptions according to the priority described in the doc (parallel >equal >vertical >horizontal order). I believe it is correct but there were a few examples in the design doc that did not match the output currently in the sim.

@terracoda this is ready for you to review.

**Comment by jessegreenberg** [comment]
In 4/5/22 meeting, we discussed that I didn't get the ordering of the sides quite right. It should always be relative to the first vertex of the side (instead of determining which side is lowest).

Back to me to make this change.

**Comment by terracoda** [comment]
The description implementation is really good, though I know you are still working on ordering of corner and side names.

One thing I noticed while listening is that there is very little space between Detail 2 and Detail 3. Can you make sure there is a period there (a full stop) and a space. This is quite pronounced in the Parallelogram descriptions.

Is there any way to view the Voiced text on the screen, like in show model values, or something similar. 

Text on the screen might be a future feature, so it would be nice to have regardless :-). I'll make an issue, so you can work on it separately.

**Comment by terracoda** [comment]
@jessegreenberg, I'll create a separate issue to implement the dynamic scene summary since Voicing is the priority.

**Comment by jessegreenberg** [comment]
Great!

> Is there any way to view the Voiced text on the screen, like in show model values, or something similar.

You can run the sim with query param `?printVoicingResponses` and it will put the output of Voicing in the dev tools console of your browser.

> One thing I noticed while listening is that there is very little space between Detail 2 and Detail 3. Can you make sure there is a period there (a full stop) and a space. This is quite pronounced in the Parallelogram descriptions.

I hear this too, but when I use `?printVoicingResponses` it looks like
"Right now, opposite corners are equal, and opposite sides are equal. Equal Corners C and A are a little smaller than equal Corners D and B. Parallel Sides CD and AB are a little longer than parallel Sides BC and DA."

But I hear almost no space between sentences 2 and 3.

**Comment by jessegreenberg** [comment]
OK, the ordering of sides has been adjusted to match the prioritization in the design doc. @terracoda back to you to review and to review my comment in https://github.com/phetsims/quadrilateral/issues/78#issuecomment-1089210649.

**Comment by terracoda** [comment]
I'll open a separate issue about making the Voiced text available...maybe @zepumph already has a solution for that in the console?

**Comment by terracoda** [comment]
I thought we were missing a case, but we are not :-)
