### ISSUE TITLE
Rename sides to use corner labels instead of positional names

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#79]
Rename sides
- Top Side - > Side AB
- Right Side - > Side BC
- Bottom Side - > Side CD
- Left Side - > Side DA

The same side names are noted in the Interactive Description design doc. 
Names across Voicing and Interactive Description ideally will remain in synch.

**Comment by terracoda** [comment]
@jessegreenberg, the corners have been renamed, but the sides still need to be re-named.

For description orientation accuracy, the model will need a way of determining what corner and side to start with the state descriptions. I will open a separate issue for that.

**Comment by terracoda** [comment]
The names of the objects will be the same in Interactive description, see issue #76 and checklist issue #74.

**Comment by jessegreenberg** [comment]
This is done in the strings but I haven't updated the model yet. One interesting thing to consider is the pronunciation of the side letters with screen readers and SpeechSynthesis. 

For me Chrome reads out "Side DA" as "Side Dah". @terracoda do we need to do anything about this?

**Comment by terracoda** [comment]
Actually, I'll test with VO, first.

**Comment by terracoda** [comment]
I have changed my mind. Don't change it. 

The pronunciation will vary between Voices and platforms. I hear Side DA as separate letters D A in Safari with WebSpeech and with VoiceOver.

Let's leave it with no space, unless of course, you already added a space and I am hearing D A because you added a space.

**Comment by terracoda** [comment]
@jessegreenberg please close update the names in the model and close this issue.

**Comment by jessegreenberg** [comment]
Sounds good. No, I had not made any changes here yet.

**Comment by terracoda** [comment]
The sides have been renamed. Thanks @jessegreenberg. Closing.
