### ISSUE TITLE
Synchronize minimum step size for cursor, touch, tangible, marker, and keyboard

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#80]
@terracoda  and I had a long discussion about the interaction between inputs and tolerance and the inconsistencies/reproducibility between inputs with respect to the tolerance values.

To coordinate between keyboard, mouse, and touch we believe a "grid" broken between minimum and major step sizes is necessary, and that the minimum step size match cursor. This is not a "snap to parallelogram" and may not solve the possibility of "skipping over" a parallelogram/other shapes, but will disallow every possible position on the play area. We do not plan to display a visual grid at this time.

Likewise, we recognize that a "minimal" movement for a tangible device (with data jitter) and detection window jitter for markers may benefit from such a feature assuming the step size is small enough to feel approximately continuous.

For an example, please see the [Geogebra Classic tool](https://www.geogebra.org/classic?lang=en). There are issues with the visually presented grid with their "Pan and Zoom" in this tool, but there is consistency in model step size.

**Comment by BLFiedler** [comment]
We hope to be able to set the step sizes as some even factor of the tolerance intervals, though I suspect this may be difficult given the nonlinear calculations that abstract the tolerance intervals from the pixel positions of the vertices.

**Comment by BLFiedler** [comment]
What I am unsure of at the moment is the impact a change such as this has on dynamic feedback such as the side length maintenance.

**Comment by jessegreenberg** [comment]
@BLFiedler discussed this with me today, we are going to try this out.

**Comment by jessegreenberg** [comment]
Working on this has identified two really weird bugs with alternative input. First, the amount of motion in the y direction is not the same as the x direction. Second, the amount of movement per step while pressing/holding seems dependent on the time elapsed in the animation frame. The second bug I think is an issue in KeyboardDragListener. The first issue is a problem with the model view transformation, it is not isometric!

**Comment by jessegreenberg** [comment]
The above commit adds the basics for this. I added a query parameter called ?showGrid as a guide to see the allowable vertex positions.

Its only working while dragging a side. The "drag by deltas" approach when dragging a side is causing a problem here. We need to fix https://github.com/phetsims/quadrilateral/issues/42 to get this working with sides.

**Comment by jessegreenberg** [comment]
OK this is in place. When using a mouse or finger vertices are constrained to the nearest 0.025 in model coordinates, this was the smallest keyboard step used from keyboard dragging.

@BLFiedler can you please review?

**Comment by BLFiedler** [comment]
Let's reduce the minor (shift-key) grid to 4 steps per major grid. The major grid size is fine for now.

**Comment by jessegreenberg** [comment]
Adjustment made in the above commit, back to @BLFiedler to review.
