### ISSUE TITLE
Inconsistencies between Serial and Model Values

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#91]
![jitter](https://user-images.githubusercontent.com/47331395/156409190-a172a5f4-fe08-406a-94d1-b22d04f1cd91.gif)

![image](https://user-images.githubusercontent.com/47331395/156407910-b0cd7313-f0c1-41c8-b1ee-bbb35959cb45.png)
![image](https://user-images.githubusercontent.com/47331395/156407993-7ce892b5-c08d-4715-a203-e421a6fa5c0f.png)

**Comment by jessegreenberg** [comment]
If I try to recreate the shape from the angle data exclusively:

<details>

![image](https://user-images.githubusercontent.com/6396244/156434900-8fa5922a-3a24-4078-b7f3-c64dcfdb1bab.png)


</details>

But if I try to create the shape from the side length data (dividing each model value by 10) I get something that looks like this:

<details>

![image](https://user-images.githubusercontent.com/6396244/156433198-b9194a1b-21f3-4533-864e-c2b6eb42bc45.png)

</details>

To recreate the quadrilateral we use the data from the top length, right length, left length, vertexA angle and vertexB angle. Others aren't used. My guess is that values from one of those sensors is not quite right.

**Comment by BLFiedler** [comment]
Yeah, it's quite likely there are just some sensor issues exclusive to my device, but I think it may also be worth some time to overlap with Scott and ensure that calculations on both sides are as synchronized as possible.

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/157112890-eded13aa-78f3-4bf6-aa37-4733c523d1cc.png)

**Comment by jessegreenberg** [comment]
@BLFiedler @jessegreenberg and Scott met to discuss this issue. We think there are two potential issues.

1) The values being sent from the devices are not hard coded or consistently mapped by the time that they reach the electron app. We are seeing some mirroring or cases where moving one side of the tangible affects a different side in the sim. Scott and I reviewed the electron app and the order that sides/angles are getting sent from the device and passed to the sim. He is going to change the device to send the values in the order assumed by the electron app. If that works out we should think of a way to enforce this so it doesn't get mismatched again.
2) It is possible one of the sensors used isn't providing the right values.

**Comment by jessegreenberg** [comment]
This was discussed during meeting today.

We identified that the device could provide length and angle values that don't actually form a legitimate quadrilateral. We discussed today how that is possible and what we should do about it. We brainstormed some things but didn't come up with a concrete solution.

**Comment by scottlambertSLU** [comment]
Hello, I fixed one of the issues from screenshot above - RT and LB angles were swapped. I had down that angle 1 is TL, 4 is TR, 3 is BR, 2 is BL, but I found (at least arduino side) that 1 is TL, 2 is TR, 3 is BR, 4 is BL (2 and 4 swapped). Behaves better now: 

https://user-images.githubusercontent.com/94307965/157700692-8e407262-18ab-4897-ac23-cfe965ca0691.mp4
