### ISSUE TITLE
Crash and freeze during side interaction

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#92]
While dragging the right side with a large shape that was a parallelogram, I encountered this crash. Was able to reproduce once. It seemed to happen when the bottom right vertex hit the bottom boundary, but I haven't found the consistent way to make it happen.

![image](https://user-images.githubusercontent.com/47331395/156581615-c0526931-d6de-437a-974e-7fabc35308fa.png)

Possibly related is another "freeze" that does not generate an error in the console log when playing with a shape that is NOT a parallelogram

![image](https://user-images.githubusercontent.com/47331395/156582132-a468b70d-70a3-41a9-bcf9-a4ce8a5632f0.png)

I cannot drag a side or vertex, but I can press the reset button and resume play, BUT the shape does not reset to a parallelogram

![image](https://user-images.githubusercontent.com/47331395/156582217-26d36abf-dc0e-4e86-ac72-fa01352c9acf.png)

(AFTER RESET)

![image](https://user-images.githubusercontent.com/47331395/156582352-6eca6c5d-0cc0-49f9-b43e-28326758fa21.png)

**Comment by jessegreenberg** [comment]
I was able to hit this assertion once, but haven't found the consistent case. It is caused by the side drawing code here
https://github.com/phetsims/quadrilateral/blob/d93b6d40acd283be00a85111d118b02ec01cc99f/js/quadrilateral/view/SideNode.ts#L77-L86
