### ISSUE TITLE
Shape jitter and vertex position uncertainty when moving two sides simultaneously

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#93]
I'm not sure if this is related to the recent crashes, but when attempting to drag two sides simultaneously using a touchscreen, there is jitter and the sides appear to warp around a bit (as though it's not certain which finger to prioritize..?) Will try to get a video.

**Comment by jessegreenberg** [comment]
Confirmed. It kind of feels like a performance issue to me. When dragging one side or multiple vertices the framerate is ~55 fps but when dragging two sides the framerate goes down to ~15 fps with `?profiler`.

**Comment by jessegreenberg** [comment]
@BLFiedler I saw this issue the first time I loaded the sim on my touchscreen device but after clearing the cache I am not seeing this anymore. Is this still an issue for you?

**Comment by BLFiedler** [comment]
I don't see an intuitive behavior here worth building out for adjacent sides simultaneously being dragged. Let's pass control to the first side that is pressed when an adjacent side is dragged. The second "multitouched" side drag does nothing.

- [ ] Implement multitouch behavior for two adjacent side dragging that gives control to the first side interaction

@jessegreenberg, if this ends up sounding like more than a few lines of code, then we'll just leave it as an acceptable bug.

**Comment by jessegreenberg** [comment]
OK, done in the above commit. When a side is pressed, its adjacent sides basically have input disabled. I think that supports this.

@BLFiedler can you please test this and multitouch cases now?

**Comment by BLFiedler** [comment]
Works as advertised. 2-4 vertex control, opposite side control, but no adjacent side simultaneous control!
