### ISSUE TITLE
Set new default tolerance interval values

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#95]
When issue #86 is complete, can we have a full list of all toleranceIntervals (including scaleFactors)?

I'd like to assign a few new default values to them, including changing the scaleFactors to be larger to accommodate greater difficulty in multitouch when the toleranceIntervals for parallelogram and shape maintenance become smaller.

**Comment by BLFiedler** [comment]
Wahoo! Thanks Jesse. This is very helpful. Also tagging @terracoda for awareness.

Let's go to the more extreme end for most of these. For very small shapes, there is still a bit of inconsistency and it reveals that area where you can drag laterally but retain "same lengths", but I think that will likely be unavoidable (just like small values of RaP, but I don't feel it's necessary to work around it as we did there).

`angleToleranceInterval`=0.01
`angleToleranceIntervalScaleFactor`= 10
`shapeAngleToleranceInterval`=0.01
`shapeLengthToleranceInterval`=0.01
`lengthToleranceIntervalScaleFactor`=0.05 (no change)

Another repercussion of this is that when you release a parallelogram (e.g., using two vertices), it will drop out of being a parallelogram as the angleToleranceInterval reverts to 0.01 from 1. I think this will have to be acceptable for now and that is likely to be limited to multitouch interaction.

**Comment by jessegreenberg** [comment]
Testing recently I find it very challenging to find a quadrilateral when using a mouse with these values. Not necessarily a problem but it is my experience, it has to be placed pretty exactly.

**Comment by BLFiedler** [comment]
> Testing recently I find it very challenging to find a quadrilateral when using a mouse with these values. Not necessarily a problem but it is my experience, it has to be placed pretty exactly.

We added a "symmetry grid" to assist with this. For now, we will look at other modal feedback to help with finding shapes. We can return to tolerance adjustment if that does not ease the search.
