### ISSUE TITLE
Performance is terrible on iPad Air 2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#98]
Noticed while debugging an unrelated issue. Performance on my Android phone is much better. Just noting because it is a platform we currently support. 

Drawing code and code related to determining drag areas with kite is super inefficient. Thats probably where I would start to optimize.

**Comment by jessegreenberg** [comment]
@BLFiedler just wanted to ping you about this, in case it needs some effort before June targets.

**Comment by BLFiedler** [comment]
Hm. Is it equally bad on vertex or side movement? I see some degradation in performance on a 6th gen iPad when dragging multiple sides, but otherwise seems okay on both Chrome and Safari (iOS 15.3.1).

**Comment by jessegreenberg** [comment]
Lets reassess performance in the upcoming dev test, closing this one.
