### ISSUE TITLE
Update Tab Order for Voicing to Match PDOM

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#99]
Once the PDOM headings and objects are implemented, the Tab order for Voicing should match. The PDOM Tab order is defined in issue #76 which is ready for implementation.

**Comment by jessegreenberg** [comment]
This should be done now, traversal order for Voicing should automatically match PDOM. Can you confirm @terracoda?

**Comment by terracoda** [comment]
Sounds great @jessegreenberg. I tested on VoiceOver and iOS VoiceOver.
